// IW5 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool

main()
{
    _id_47D9();
    _id_6A11();
    _id_5004();
    _id_47DE();
    _id_4CAC();
    _id_7711();
    level thread _id_6A12();
    _id_6A13();
}
#using_animtree("player");

_id_47D9()
{
    level._id_1245["player_rig"] = #animtree;
    level._id_1F90["player_rig"] = level._id_1F5D;
    level._id_0C59["player_rig"]["escape_player_deploy_chute"] = %castle_truck_escape_player_deploy_chute;
    level._id_0C59["player_parachute"]["landing"] = %o_castle_3_3_player_chute_landing;
    level._id_0C59["player_rig"]["landing"] = %int_castle_3_3_player_landing;
    maps\_anim::_id_1264( "player_rig", "player_hits_ground", maps\castle_parachute::_id_8152, "landing" );
    level._id_0C59["player_rig"]["stealth_melee"] = %castle_6_2_spotlight_kill_player;
    level._id_0C59["player_rig"]["bomb_plant"] = %castle_player_platformcrawl_bombplant_alt;
    maps\_anim::_id_1264( "player_rig", "detach", maps\castle_courtyard_stealth::_id_80CA, "bomb_plant" );
    level._id_0C59["player_rig"]["bridge_bomb_plant"] = %int_castle_9_2_player_shimmy_bombplant;
    level._id_0C59["player_rig"]["bridge_jump"] = %int_castle_14_4_player_jump;
    maps\_anim::_id_1264( "player_rig", "gun_up", maps\castle_courtyard_battle::_id_81BC, "bridge_jump" );
    level._id_0C59["player_rig"]["wall_climb_start"] = %castle_player_wetwall_climb_get_in;
    maps\_anim::_id_1264( "player_rig", "left_hand_on", maps\castle_into_wet_wall::_id_81F9, "wall_climb_start" );
    maps\_anim::_id_1264( "player_rig", "right_hand_on", maps\castle_into_wet_wall::_id_81F8, "wall_climb_start" );
    level._id_0C59["player_rig"]["wall_climb_full"] = %castle_player_wetwall_climb_full;
    level._id_0C59["player_rig"]["wall_climb_peek_start"] = %castle_player_wetwall_climb_hole_peek_get_in;
    level._id_0C59["player_rig"]["wall_climb_peek_idle"][0] = %castle_player_wetwall_climb_hole_peek_idle;
    level._id_0C59["player_rig"]["wall_climb_peek_slip"] = %castle_player_wetwall_climb_hole_peek_slip;
    level._id_0C59["player_rig"]["wall_climb_peek_fall"] = %castle_player_wetwall_climb_hole_peek_fall;
    maps\_anim::_id_1267( "player_rig", "wallbreak", "kitchen_start", "wall_climb_peek_fall" );
    maps\_anim::_id_125D( "player_rig", "slatbreak", "wall_climb_peek_slip", "scn_castle_wetwall_wood_slat_break" );
    level._id_0C59["player_rig"]["cliffjump_glide"] = %castle_truck_escape_glide_player;
    level._id_0C59["player_rig"]["truck_enter"] = %castle_truck_escape_mount_player;
    level._id_0C59["player_rig"]["cliffjump_new"] = %castle_truck_escape_player;
    level._id_0C59["escape_chute_player"]["cliffjump_glide"] = %castle_truck_escape_glide_chute;
    level._id_1245["escape_chute_player"] = #animtree;
    level._id_1F90["escape_chute_player"] = "ctl_parachute_player";
}
#using_animtree("generic_human");

_id_6A11()
{
    level._id_0C59["price"]["intro"] = %ch_castle_1_1_price_chute_intro;
    level._id_0C59["price"]["chute_idle"][0] = %ch_castle_1_1_price_chute_idl;
    level._id_0C59["price"]["chute_left2right"] = %ch_castle_1_1_price_chute_left2right;
    level._id_0C59["price"]["chute_right2left"] = %ch_castle_1_1_price_chute_right2left;
    level._id_0C59["price"]["landing"] = %ch_castle_3_3_price_landing;
    level._id_0C59["price"]["chute_loop"] = %ch_castle_1_1_price_chute_idl_new;
    level._id_0C59["price"]["chute_right"] = %ch_castle_1_1_price_chute_rightturn_new;
    level._id_0C59["price"]["chute_left"] = %ch_castle_1_1_price_chute_leftturn_new;
    level._id_0C59["price"]["chute_up"] = %ch_castle_1_1_price_chute_updraft_new;
    maps\_anim::_id_1264( "price", "gun_in_hand", maps\castle_parachute::_id_814C, "landing" );
    maps\_anim::_id_1264( "price", "fire", maps\castle_parachute::_id_8153, "landing" );
    level._id_0C59["price"]["ruins_start"] = %ch_castle_4_1_price_startmove;
    level._id_0C59["price"]["ruins_talk"] = %ch_castle_4_1_price_speech;
    level._id_0C59["price"]["ruins_run_to_cover"] = %ch_castle_4_1_price_run2cover2;
    level._id_0C59["price"]["ruins_cover_wait"][0] = %ch_castle_4_1_price_cover2_wait;
    level._id_0C59["price"]["ruins_cover_hide"] = %ch_castle_4_1_price_cover2idl;
    level._id_0C59["price"]["ruins_run_to_patrol"] = %ch_castle_4_1_price_run2patrol;
    maps\_anim::_id_1264( "price", "hide_pistol", maps\castle_ruins::_id_8121, "ruins_talk" );
    maps\_anim::_id_1264( "price", "start_patrol", maps\castle_ruins::_id_8131, "lightning_flash" );
    level._id_0C59["price"]["do_not_engage"][0] = %ch_castle_5_1_price_do_not_engage;
    level._id_0C59["price"]["approach_overlook"] = %castle_overlook_run_to_idle_price;
    level._id_0C59["price"]["security_office_talk"] = %ch_castle_6_1_security_office_price_talk;
    level._id_0C59["price"]["jump_down"] = %ch_castle_6_1_price_jump_down;
    maps\_anim::_id_1264( "price", "dialog11", ::_id_63E9, "security_office_talk" );
    maps\_anim::_id_1264( "price", "dialog12", ::_id_63EA, "jump_down" );
    maps\_anim::_id_1267( "price", "dialog11", "start_stealth_guard_patroll", "security_office_talk" );
    level._id_0C59["price"]["move_to_stealth"] = %ch_castle_6_2_price_move2stealth;
    level._id_0C59["price"]["stealth_intro_wait"][0] = %ch_castle_6_2_price_wait_stealth_intro;
    level._id_0C59["price"]["stealth_intro"] = %ch_castle_6_2_price_stealth_intro;
    level._id_0C59["price"]["stealth_idle"][0] = %ch_castle_6_2_price_stealth_idl_truck;
    level._id_0C59["price"]["move_to_crawltruck"] = %ch_castle_6_2_price_stealth_move2_crawltruck;
    level._id_0C59["price"]["crawltruck_idle"][0] = %ch_castle_6_2_price_stealth_crawltruck_idl;
    level._id_0C59["price"]["crawltruck_crawl"] = %ch_castle_6_2_price_stealth_crawltruck_crawl;
    maps\_anim::_id_1264( "price", "price_is_prone", ::_id_6A15, "crawltruck_crawl" );
    level._id_0C59["price"]["crawltruck_under_idle"][0] = %ch_castle_6_2_price_stealth_crawltruck_prone_idl;
    level._id_0C59["price"]["crawltruck_to_run"] = %ch_castle_6_2_price_stealth_crawltruck_crawl2run;
    maps\_anim::_id_1264( "price", "price_is_not_prone", ::_id_6A16, "crawltruck_to_run" );
    level._id_0C59["price"]["melee_idle"][0] = %ch_castle_6_2_price_truck_idl;
    level._id_0C59["price"]["place_charge"] = %ch_castle_6_2_price_sets_charge;
    maps\_anim::_id_1264( "price", "bomb_appear", maps\castle_courtyard_stealth::_id_80CB, "place_charge" );
    maps\_anim::_id_1264( "price", "bomb_plant", maps\castle_courtyard_stealth::_id_80CC, "place_charge" );
    level._id_0C59["price"]["indicate_guard"] = %ch_castle_6_2_price_indicates_guard;
    level._id_0C59["price"]["stealth_catch"] = %ch_castle_6_2_price_catch;
    level._id_0C59["price"]["stealth_melee"] = %castle_6_2_spotlight_kill_price;
    level._id_0C59["price"]["road_sprint_into"] = %ch_castle_6_2_price_sprint_setup_crouch2idl;
    level._id_0C59["price"]["road_sprint_wait_loop"][0] = %ch_castle_6_2_price_sprint_setup_start_idl;
    level._id_0C59["price"]["road_sprint"] = %ch_castle_6_2_price_sprint;
    level._id_0C59["price"]["road_sprint_end_loop"][0] = %ch_castle_6_2_price_sprint_end_idl;
    level._id_0C59["price"]["road_sprint_exit"] = %ch_castle_6_2_price_exit_sprint_end;
    level._id_0C59["price"]["wait_before_backcrawl"][0] = %ch_castle_6_3_price_crawl_intro_start_idl;
    level._id_0C59["price"]["move_to_backcrawl"] = %ch_castle_6_3_price_crawl_intro_move2crawl;
    level._id_0C59["price"]["get_into_backcrawl"] = %ch_castle_6_3_price_crawl_intro_ready2crawl;
    maps\_anim::_id_1264( "price", "price_is_prone", ::_id_6A15, "get_into_backcrawl" );
    level._id_0C59["price"]["price_shoot_guard"] = %ch_castle_6_2_price_shoot_melee;
    maps\_anim::_id_1264( "price", "start_guard_anim", ::_id_6A14, "price_shoot_guard" );
    level._id_0C59["price"]["backcrawl_gap"] = %ch_castle_6_3_price_backward_crawl_b;
    maps\_anim::_id_1267( "price", "price_says_wait", "price_says_wait", "backcrawl_gap" );
    level._id_0C59["price"]["backcrawl_gap_idle"][0] = %ch_castle_6_3_price_backward_crawl_b_wait;
    level._id_0C59["price"]["backcrawl_bomb"] = %ch_castle_6_3_price_backward_crawl_c;
    level._id_0C59["price"]["backcrawl_stoptalk"] = %ch_castle_6_3_price_backward_crawl_c_stoptalk;
    level._id_0C59["price"]["backcrawl_bomb_idle"][0] = %ch_castle_6_3_price_backward_crawl_c_wait;
    level._id_0C59["price"]["backcrawl"] = %ch_castle_6_3_price_backward_crawl;
    level._id_0C59["price"]["backcrawl_idle"][0] = %ch_castle_6_3_price_backward_crawl_wait;
    level._id_0C59["price"]["backcrawl_exit1"] = %ch_castle_6_3_price_crawl_exit;
    maps\_anim::_id_1264( "price", "price_is_not_prone", ::_id_6A16, "backcrawl_exit1" );
    level._id_0C59["price"]["backcrawl_exit_wait1"][0] = %ch_castle_6_3_price_hide1_idl;
    level._id_0C59["price"]["backcrawl_exit2"] = %ch_castle_6_3_price_move2hide2;
    level._id_0C59["price"]["backcrawl_exit_wait2"][0] = %ch_castle_6_3_price_crawl_exit_hide_idl;
    level._id_0C59["price"]["start_into_idle"] = %ch_castle_6_3_price_into_start_idl;
    level._id_0C59["price"]["bomb_plant_platform"] = %ch_castle_6_3_price_crawl_plant_bomb;
    maps\_anim::_id_1264( "price", "bomb_appear", maps\castle_courtyard_stealth::_id_80CB, "bomb_plant_platform" );
    maps\_anim::_id_1264( "price", "bomb_disappear", maps\castle_courtyard_stealth::_id_80CC, "bomb_plant_platform" );
    level._id_0C59["price"]["security_office_run_up"] = %ch_castle_7_1_price_entry_run_up_steps;
    level._id_0C59["price"]["security_office_entry_idle"][0] = %ch_castle_7_1_price_entry_cover_idl;
    level._id_0C59["price"]["security_office_entry"] = %castle_comm_office_entry_price;
    maps\_anim::_id_1264( "price", "grab_pistol", maps\castle_prison_battle::_id_820D, "security_office_entry" );
    maps\_anim::_id_1264( "price", "knock1", maps\castle_prison_battle::_id_820F, "security_office_entry" );
    maps\_anim::_id_1264( "price", "knock2", maps\castle_prison_battle::_id_8210, "security_office_entry" );
    maps\_anim::_id_1264( "price", "kill_right", maps\castle_prison_battle::_id_8211, "security_office_entry" );
    maps\_anim::_id_1264( "price", "kill_left", maps\castle_prison_battle::_id_8212, "security_office_entry" );
    maps\_anim::_id_1264( "price", "kill_mid", maps\castle_prison_battle::_id_8214, "security_office_entry" );
    maps\_anim::_id_1264( "price", "hide_pistol", maps\castle_prison_battle::_id_8121, "security_office_entry" );
    maps\_anim::_id_1264( "price", "hide_knife", maps\castle_prison_battle::_id_8216, "security_office_entry" );
    maps\_anim::_id_1264( "price", "grab_rifle", maps\castle_prison_battle::_id_8217, "security_office_entry" );
    level._id_0C59["price"]["security_office_drag"] = %ch_castle_7_5_price_drag_guard_price;
    maps\_anim::_id_1264( "price", "door2_trigger", maps\castle_prison_battle::_id_7DD2, "security_office_drag" );
    maps\_anim::_id_1264( "price", "monitor_trigger", maps\castle_prison_battle::_id_7DD3, "security_office_drag" );
    maps\_anim::_id_1264( "price", "door_trigger", maps\castle_prison_battle::_id_7DD1, "security_office_drag" );
    maps\_anim::_id_1264( "price", "dialogue01", maps\castle_prison_battle::_id_7DD4, "security_office_drag" );
    maps\_anim::_id_1264( "price", "dialogue02", maps\castle_prison_battle::_id_7DD5, "security_office_drag" );
    maps\_anim::_id_1264( "price", "dialogue03", maps\castle_prison_battle::_id_7DD6, "security_office_drag" );
    level._id_0C59["price"]["goto_power_switch"] = %ch_castle_7_6_price_run_stairs;
    level._id_0C59["price"]["power_switch_wait"][0] = %ch_castle_7_6_price_light_switch_idl;
    level._id_0C59["price"]["power_switch_off"] = %ch_castle_7_6_price_lights_off;
    maps\_anim::_id_1264( "price", "lights_off", maps\castle_prison_battle::_id_2ABA, "power_switch_off" );
    level._id_0C59["price"]["prison_exit_briefing_open"] = %ch_castle_8_7_price_door_briefing;
    level._id_0C59["price"]["prison_exit_briefing_open_idle"][0] = %ch_castle_8_7_price_door_briefing_idl;
    level._id_0C59["price"]["prison_exit_briefing_close"] = %ch_castle_8_7_price_door_briefing_close;
    level._id_0C59["price"]["bridge_instruct_bombplant"] = %ch_castle_9_2_price_instructs_bombplant;
    level._id_0C59["price"]["bridge_instruct_idle"][0] = %ch_castle_9_2_price_instructs_idl;
    level._id_0C59["price"]["bridge_shimmy"] = %ch_castle_9_2_price_shimmy;
    level._id_0C59["price"]["bridge_mantle"] = %ch_castle_9_2_price_mantle_scaffold;
    level._id_0C59["price"]["wet_wall_investigate"] = %ch_castle_10_1_price_kneel_down;
    level._id_0C59["price"]["wet_wall_place_detcord"] = %ch_castle_10_2_price_set_det_chord;
    level._id_0C59["price"]["wet_wall_signal_move_to_window"] = %ch_castle_10_2_price_signal_run_to_window;
    level._id_0C59["price"]["wet_wall_signal_idle"][0] = %ch_castle_10_2_price_signal_idl;
    level._id_0C59["price"]["wet_wall_signal_flash"] = %ch_castle_10_2_price_signals_detonate;
    level._id_0C59["price"]["spiderclimb_enter"] = %ch_castle_10_3_wall_enter_price;
    level._id_0C59["price"]["spiderclimb_wait_idle"][0] = %ch_castle_10_4_looking_down_price;
    level._id_0C59["price"]["spiderclimb_climb_up"] = %ch_castle_10_4_spider_walk_price;
    level._id_0C59["price"]["peep_show_wait_idle"][0] = %ch_castle_10_5_wait_idle_price;
    level._id_0C59["price"]["peep_show"] = %ch_castle_10_5_peep_show_price;
    maps\_anim::_id_1264( "price", "dialogue15", maps\castle_into_wet_wall::_id_0151, "peep_show" );
    maps\_anim::_id_1264( "price", "dialogue16", maps\castle_into_wet_wall::_id_0152, "peep_show" );
    maps\_anim::_id_1264( "price", "dialogue18", maps\castle_into_wet_wall::_id_0153, "peep_show" );
    maps\_anim::_id_1264( "price", "dialogue20", maps\castle_into_wet_wall::_id_0154, "peep_show" );
    maps\_anim::_id_1264( "price", "grenade_pullout", maps\castle_into_wet_wall::_id_8228, "peep_show" );
    level._id_0C59["price"]["peep_show_fall"] = %ch_castle_10_9_wall_fall_price;
    level._id_0C59["price"]["stair_start"][0] = %ch_castle_12_1_price_pacing_startidl;
    level._id_0C59["price"]["stair_move"] = %ch_castle_12_1_price_pacing_move;
    level._id_0C59["price"]["stair_wait"][0] = %ch_castle_12_1_price_pacing_waitidl;
    level._id_0C59["price"]["stair_finish"] = %ch_castle_12_1_price_pacing_exit;
    level._id_0C59["price"]["flash_react"] = %ch_castle_12_3_price_flash_react;
    level._id_0C59["price"]["flash_effect"] = %exposed_flashbang_v1;
    level._id_0C59["price"]["table_slide"] = %ch_castle_12_1_price_table_mantle;
    level._id_0C59["price"]["overlook_intro"] = %ch_castle_14_2_move2idl;
    level._id_0C59["price"]["overlook_idle"][0] = %ch_castle_14_2_detonate_charge_price_idl;
    level._id_0C59["price"]["overlook_talk"] = %ch_castle_14_2_detonate_charge_price_talk;
    level._id_0C59["price"]["overlook_nag"] = %ch_castle_14_2_detonate_charge_price_nag;
    level._id_0C59["price"]["overlook_exit"] = %ch_castle_14_2_detonate_charge_price_exit;
    level._id_0C59["price"]["bridge_idle"][0] = %ch_castle_14_5_price_shoots_guard_price_idl;
    level._id_0C59["price"]["truck_idle"][0] = %castle_truck_escape_wait_idle_price;
    level._id_0C59["price"]["truck_start_drive"] = %castle_truck_escape_drive_start_price;
    level._id_0C59["price"]["truck_turn_left"] = %castle_truck_escape_turn_left_price;
    level._id_0C59["price"]["truck_turn_right"] = %castle_truck_escape_turn_right_price;
    level._id_0C59["price"]["truck_hit_react"] = %castle_truck_escape_crash_reaction_price;
    level._id_0C59["price"]["cliffjump_new"] = %castle_truck_escape_price;
}

_id_5004()
{
    level._id_1245["security_guard_chair"] = #animtree;
    level._id_0C59["generic"]["kitchen_death"] = %dying_back_death_v1;
    level._id_0C59["landing_guard1"]["landing"] = %ch_castle_3_3_price_landing_guard_1;
    level._id_0C59["landing_guard2"]["react_to_parachute"] = %patrol_bored_react_walkstop;
    level._id_0C59["ruins_patroller1"]["ruins_patrol"] = %ch_castle_4_2_patrol_guard_1;
    level._id_0C59["ruins_patroller2"]["ruins_patrol"] = %ch_castle_4_2_patrol_guard_2;
    level._id_0C59["ruins_patroller3"]["ruins_patrol"] = %ch_castle_4_2_patrol_guard_3_walk;
    level._id_0C59["ruins_patroller4"]["ruins_patrol"] = %ch_castle_4_2_patrol_guard_4_walk;
    level._id_0C59["activity_initial_group2_guard1"]["courtyard_activity"] = %ch_castle_5_3_heavy_activity_2_guard1_initial;
    level._id_0C59["activity_initial_group2_guard2"]["courtyard_activity"] = %ch_castle_5_3_heavy_activity_2_guard2_initial;
    level._id_0C59["activity_initial_group2_guard3"]["courtyard_activity"] = %ch_castle_5_3_heavy_activity_2_guard3_initial;
    level._id_0C59["activity_group2_guard1"]["courtyard_activity"] = %ch_castle_5_3_heavy_activity_2_guard1;
    level._id_0C59["activity_group2_guard2"]["courtyard_activity"] = %ch_castle_5_3_heavy_activity_2_guard2;
    level._id_0C59["activity_group2_guard2"]["courtyard_activity_idle"][0] = %ch_castle_5_3_heavy_activity_2_guard2_idl;
    level._id_0C59["activity_group2_guard3"]["courtyard_activity"] = %ch_castle_5_3_heavy_activity_2_guard3;
    level._id_0C59["activity_group2_guard3"]["courtyard_activity_idle"][0] = %ch_castle_5_3_heavy_activity_2_guard3_idl;
    level._id_0C59["activity_group3_guard1"]["courtyard_activity"] = %ch_castle_5_3_heavy_activity_3_guard1;
    level._id_0C59["activity_group3_guard1"]["courtyard_activity_idle"][0] = %ch_castle_5_3_heavy_activity_3_guard1_idl;
    level._id_0C59["activity_group3_guard2"]["courtyard_activity"] = %ch_castle_5_3_heavy_activity_3_guard2;
    level._id_0C59["activity_group3_guard2"]["courtyard_activity_idle"][0] = %ch_castle_5_3_heavy_activity_3_guard2_idl;
    level._id_0C59["btr_lift_guard1"]["courtyard_activity_runup"] = %ch_castle_5_4_btr_lift_guard1_runup;
    level._id_0C59["btr_lift_guard2"]["courtyard_activity_runup"] = %ch_castle_5_4_btr_lift_guard2_runup;
    level._id_0C59["btr_lift_guard3"]["courtyard_activity_runup"] = %ch_castle_5_4_btr_lift_guard3_runup;
    level._id_0C59["btr_lift_guard4"]["courtyard_activity_runup"] = %ch_castle_5_4_btr_lift_guard4_runup;
    level._id_0C59["btr_lift_guard5"]["courtyard_activity_runup"] = %ch_castle_5_4_btr_lift_guard5_runup;
    level._id_0C59["btr_lift_guard1"]["courtyard_activity"] = %ch_castle_5_4_btr_lift_guard1;
    level._id_0C59["btr_lift_guard1"]["courtyard_activity_idle"][0] = %ch_castle_5_4_btr_lift_guard1_endidl;
    level._id_0C59["btr_lift_guard2"]["courtyard_activity"] = %ch_castle_5_4_btr_lift_guard2;
    level._id_0C59["btr_lift_guard2"]["courtyard_activity_idle"][0] = %ch_castle_5_4_btr_lift_guard2_endidl;
    level._id_0C59["btr_lift_guard3"]["courtyard_activity"] = %ch_castle_5_4_btr_lift_guard3;
    level._id_0C59["btr_lift_guard3"]["courtyard_activity_idle"][0] = %ch_castle_5_4_btr_lift_guard3_endidl;
    level._id_0C59["btr_lift_guard4"]["courtyard_activity"] = %ch_castle_5_4_btr_lift_guard4;
    level._id_0C59["btr_lift_guard4"]["courtyard_activity_idle"][0] = %ch_castle_5_4_btr_lift_guard4_endidl;
    level._id_0C59["btr_lift_guard5"]["courtyard_activity"] = %ch_castle_5_4_btr_lift_guard5;
    level._id_0C59["activity_group2_guard_walker1"]["pairguards_idle"][0] = %ch_castle_6_2_pairguard1_idl;
    level._id_0C59["activity_group2_guard_walker2"]["pairguards_idle"][0] = %ch_castle_6_2_pairguard2_idl;
    level._id_0C59["activity_group2_guard3"]["truckguard_idle"][0] = %ch_castle_6_2_truckguard;
    level._id_0C59["activity_group2_guard1"]["pairguards_idle"][0] = %ch_castle_6_2_pairguard1_idl;
    level._id_0C59["activity_group2_guard1"]["pairguards_walk"] = %ch_castle_6_2_pairguard1_walk;
    level._id_0C59["activity_group2_guard2"]["pairguards_idle"][0] = %ch_castle_6_2_pairguard2_idl;
    level._id_0C59["activity_group2_guard2"]["pairguards_walk"] = %ch_castle_6_2_pairguard2_walk;
    level._id_0C59["melee_victim"]["stealth_melee"] = %castle_6_2_spotlight_kill_guard;
    level._id_0C59["melee_victim"]["stealth_catch"] = %ch_castle_6_2_price_catch_guard;
    level._id_0C59["melee_victim"]["stealth_catch_loop"][0] = %ch_castle_6_2_price_catch_guard_deadloop;
    level._id_0C59["melee_victim"]["price_shoot_melee"] = %ch_castle_6_2_price_shoot_melee_guard;
    level._id_0C59["melee_victim"]["price_shoot_melee_dead"][0] = %ch_castle_6_2_price_shoot_melee_guard_deadloop;
    level._id_0C59["platformguard1"]["platform_idle"][0] = %ch_castle_6_3_crawl_guards_guard1_startidl;
    level._id_0C59["platformguard1"]["platform_walk"] = %ch_castle_6_3_crawl_guards_guard1_walk;
    level._id_0C59["platformguard1"]["platform_idle_end"][0] = %ch_castle_6_3_jumping_guard_startidl;
    level._id_0C59["platformguard1"]["jump_down"] = %ch_castle_6_3_jumping_guard;
    level._id_0C59["platformguard2"]["platform_idle"][0] = %ch_castle_6_3_crawl_guards_guard2_startidl;
    level._id_0C59["platformguard2"]["platform_walk"] = %ch_castle_6_3_crawl_guards_guard2_walk;
    level._id_0C59["platformguard2"]["platform_idle_end"][0] = %ch_castle_6_3_crawl_guards_guard2_endidl;
    level._id_0C59["platformguard3"]["platform_idle"][0] = %ch_castle_6_3_crawl_guards_guard3_startidl;
    level._id_0C59["platformguard3"]["platform_walk"] = %ch_castle_6_3_crawl_guards_guard3_walk;
    level._id_0C59["platformguard3"]["platform_idle_end"][0] = %ch_castle_6_3_crawl_guards_guard3_endidl;
    level._id_0C59["platformguard4"]["platform_idle"][0] = %ch_castle_6_3_crawl_guards_guard4_startidl;
    level._id_0C59["platformguard4"]["platform_walk"] = %ch_castle_6_3_crawl_guards_guard4_walk;
    level._id_0C59["platformguard4"]["platform_idle_end"][0] = %ch_castle_6_3_crawl_guards_guard4_endidl;
    level._id_0C59["platformguard5"]["platform_idle"][0] = %ch_castle_6_3_crawl_guards_guard5_startidl;
    level._id_0C59["platformguard5"]["platform_walk"] = %ch_castle_6_3_crawl_guards_guard5_walk;
    level._id_0C59["platformguard5"]["platform_idle_end"][0] = %ch_castle_6_3_crawl_guards_guard5_endidl;
    level._id_0C59["generic"]["patrol_bored_idle"][0] = %patrol_bored_idle;
    level._id_0C59["security_guard_1"]["security_office_idle"][0] = %ch_castle_7_3_guard1_idle;
    level._id_0C59["security_guard_1"]["security_office_react"] = %ch_castle_7_3_guard1;
    level._id_0C59["security_guard_2"]["security_office_react"] = %exposed_idle_reactb;
    level._id_0C59["security_guard_2"]["generic_death"] = %exposed_death_falltoknees;
    level._id_0C59["security_guard_3"]["security_office_entry_guard"] = %castle_comm_office_entry_guard;
    maps\_anim::_id_1264( "security_guard_3", "stab_enter", maps\castle_prison_battle::_id_8221, "security_office_entry_guard" );
    maps\_anim::_id_1264( "security_guard_3", "throat_cut", maps\castle_prison_battle::_id_8222, "security_office_entry_guard" );
    maps\_anim::_id_1264( "security_guard_3", "land", maps\castle_prison_battle::_id_7DC8, "security_office_entry_guard" );
    maps\_anim::_id_1264( "security_guard_3", "kill_dude", maps\castle_prison_battle::_id_7DC9, "security_office_entry_guard" );
    level._id_0C59["security_guard_chair"]["security_office_guard_chair_idle"][0] = %ch_castle_7_2_guard_chair_idl;
    level._id_0C59["security_guard_chair"]["security_office_react"] = %ch_castle_7_2_guard_chair;
    level._id_0C59["security_guard_chair"]["security_office_react_stand"] = %ch_castle_7_2_guard_chair_to_stand;
    level._id_0C59["security_guard_chair"]["security_office_react_death"] = %ch_castle_7_2_guard_chair_death_fall;
    level._id_0C59["security_guard_chair"]["security_office_guard_chair_death_idle"][0] = %ch_castle_7_2_guard_chair_death_idl;
    level._id_0C59["security_guard_chair"]["security_office_drag"] = %ch_castle_7_5_price_drag_guard_guard;
    level._id_0C59["security_guard_chair"]["security_office_guard_drag_end"][0] = %ch_castle_7_5_price_drag_guard_guard_end_idle;
    level._id_0C59["prisoner1"]["harass_loop"][0] = %ch_castle_7_1_guard_taunting_prisoner_loop;
    level._id_0C59["prisoner1"]["harass_react"] = %ch_castle_7_1_guard_taunting_prisoner_react;
    level._id_0C59["prisoner1"]["harass_end_loop"][0] = %ch_castle_7_1_guard_taunting_prisoner_end_idl;
    level._id_0C59["prisoner3"]["harass_loop"][0] = %ch_castle_7_1_guard_taunting_prisoner3_loop;
    level._id_0C59["prisoner3"]["harass_react"] = %ch_castle_7_1_guard_taunting_prisoner3_react;
    level._id_0C59["prisoner3"]["harass_end_loop"][0] = %ch_castle_7_1_guard_taunting_prisoner3_end_idl;
    level._id_0C59["guard3"]["harass_loop"][0] = %ch_castle_7_1_guard3_taunting_loop;
    level._id_0C59["guard3"]["harass_react"] = %ch_castle_7_1_guard3_taunting_react;
    level._id_0C59["guard3"]["blinded_react_loop"][0] = %castle_dungeon_blind_idle_guard;
    level._id_0C59["generic"]["payback_pmc_sandstorm_stumble_1_single"] = %payback_pmc_sandstorm_stumble_1;
    level._id_0C59["generic"]["payback_pmc_sandstorm_stumble_1"][0] = %payback_pmc_sandstorm_stumble_1;
    level._id_0C59["generic"]["castle_dungeon_blind_idle_guard_single"] = %castle_dungeon_blind_idle_guard;
    level._id_0C59["generic"]["castle_dungeon_blind_idle_guard"][0] = %castle_dungeon_blind_idle_guard;
    level._id_0C59["generic"]["find_wall_guard"] = %castle_dungeon_find_wall_guard;
    level._id_0C59["generic"]["stair_stumble_back_guard"] = %castle_dungeon_stair_stumble_back_guard;
    level._id_0C59["generic"]["stair_stumble_forward_guard"] = %castle_dungeon_stair_stumble_forward_guard;
    level._id_0C59["generic"]["corner_standR_alert_idle"][0] = %corner_standr_alert_idle;
    level._id_0C59["generic"]["covercrouch_blindfire_1"] = %covercrouch_blindfire_1;
    level._id_0C59["generic"]["covercrouch_hide_idle"][0] = %covercrouch_hide_idle;
    level._id_0C59["generic"]["cover_twitch_01"] = %covercrouch_twitch_1;
    level._id_0C59["generic"]["cover_twitch_02"] = %covercrouch_blindfire_1;
    level._id_0C59["generic"]["prisoner_cower2"][0] = %ch_castle_8_5_prisoner_cower_2;
    level._id_0C59["generic"]["prisoner_shake1"][0] = %ch_castle_8_5_prisoner_shake_cage_1;
    level._id_0C59["generic"]["prisoner_pace_lean"][0] = %ch_castle_8_8_cell_1_guy1;
    level._id_0C59["generic"]["prisoner_sitting"][0] = %ch_castle_8_8_cell_1_guy2;
    level._id_0C59["generic"]["prisoner_arms_crossed"][0] = %ch_castle_8_8_cell_1_guy4;
    level._id_0C59["generic"]["prisoner_cowering_floor"][0] = %ch_castle_8_8_cell_2_guy2;
    level._id_0C59["generic"]["prisoner_shifting_looking"][0] = %ch_castle_8_8_cell_2_guy7;
    level._id_0C59["generic"]["prisoner_shifting_looking2"][0] = %ch_castle_8_8_cell_3_guy3;
    level._id_0C59["generic"]["prisoner_shaking_bars1"][0] = %ch_castle_8_8_cell_6_guy5;
    level._id_0C59["generic"]["prisoner_shaking_bars2"][0] = %ch_castle_8_8_cell_3_guy5;
    level._id_0C59["generic"]["prisoner_pacing_gesturing"][0] = %ch_castle_8_8_cell_6_guy1;
    level._id_0C59["generic"]["prisoner_crouch_cower"][0] = %ch_castle_8_8_cell_4_guy2;
    level._id_0C59["generic"]["guard_flare_toss"] = %ch_castle_8_3_guard_flare;
    level._id_0C59["meatshield_guard"]["meatshield_start"] = %ch_castle_8_5_prisoner_hostage_guard;
    level._id_0C59["meatshield_prisoner"]["meatshield_start"] = %ch_castle_8_5_prisoner_hostage_prisoner;
    level._id_0C59["meatshield_guard"]["meatshield_idle"][0] = %ch_castle_8_5_prisoner_hostage_guard_idl;
    level._id_0C59["meatshield_prisoner"]["meatshield_idle"][0] = %ch_castle_8_5_prisoner_hostage_prisoner_idl;
    level._id_0C59["meatshield_prisoner"]["meatshield_dies"] = %ch_castle_8_5_prisoner_hostage_death;
    level._id_0C59["meatshield_prisoner"]["meatshield_dies_idle"][0] = %ch_castle_8_5_prisoner_hostage_death_idle;
    level._id_0C59["meatshield_prisoner"]["meatshield_survives"] = %ch_castle_8_5_prisoner_hostage_prisoner_to_cover;
    level._id_0C59["meatshield_prisoner"]["meatshield_survives_idle"][0] = %ch_castle_8_5_prisoner_hostage_prisoner_to_cover_idl;
    level._id_0C59["meatshield_guard"]["meatshield_double_kill"] = %ch_castle_8_5_guard_double_kill;
    level._id_0C59["meatshield_prisoner"]["meatshield_double_kill"] = %ch_castle_8_5_prisoner_double_kill;
    level._id_0C59["alexi"]["peep_show"] = %ch_castle_10_6_peep_show_alexei;
    maps\_anim::_id_1264( "alexi", "dialogue12", maps\castle_into_wet_wall::_id_822D, "peep_show" );
    maps\_anim::_id_1264( "alexi", "dialogue14", maps\castle_into_wet_wall::_id_822E, "peep_show" );
    maps\_anim::_id_1264( "alexi", "dialogue16", maps\castle_into_wet_wall::_id_822F, "peep_show" );
    maps\_anim::_id_1264( "alexi", "alarm_start", maps\castle_into_wet_wall::_id_8226, "peep_show" );
    level._id_0C59["tv_room_guy1"]["peep_show"] = %ch_castle_10_6_peep_show_henchman_01;
    level._id_0C59["tv_room_guy2"]["peep_show"] = %ch_castle_10_6_peep_show_henchman_02;
    level._id_0C59["tv_room_guy3"]["peep_show"] = %ch_castle_10_6_peep_show_henchman_03;
    maps\_anim::_id_1264( "tv_room_guy3", "dialog01", maps\castle_into_wet_wall::_id_022E, "peep_show" );
    level._id_0C59["tv_room_guy4"]["peep_show"] = %ch_castle_10_6_peep_show_henchman_04;
    level._id_0C59["makarov"]["tv_scene"] = %ch_castle_10_7_tv_monitor_makarov_cheap;
    maps\_anim::_id_125A( "makarov", "dialogue08", "tv_scene", "castle_mkv_isee" );
    maps\_anim::_id_125A( "makarov", "dialogue09", "tv_scene", "castle_mkv_thisiswhat" );
    maps\_anim::_id_125A( "makarov", "dialogue10", "tv_scene", "castle_mkv_oldman" );
    maps\_anim::_id_125A( "makarov", "dialogue11", "tv_scene", "castle_mkv_youtoo" );
    maps\_anim::_id_125A( "makarov", "dialogue13", "tv_scene", "castle_mkv_confirmed" );
    maps\_anim::_id_125A( "makarov", "dialogue15", "tv_scene", "castle_mkv_listening" );
    maps\_anim::_id_125A( "makarov", "dialogue17", "tv_scene", "castle_mkv_updated" );
    level._id_0C59["president"]["tv_scene"] = %ch_castle_10_7_tv_monitor_president_cheap;
    maps\_anim::_id_125A( "president", "dialogue04", "tv_scene", "castle_prs_forthelast" );
    maps\_anim::_id_125A( "president", "dialogue06", "tv_scene", "castle_prs_notbow" );
    maps\_anim::_id_125A( "president", "dialogue07", "tv_scene", "castle_prs_iwilldie" );
    level._id_0C59["alexi"]["peep_show_react"] = %ch_castle_10_8_discovered_alexei;
    maps\_anim::_id_1264( "alexi", "dialogue17", maps\castle_into_wet_wall::_id_022D, "peep_show_react" );
    maps\_anim::_id_1264( "alexi", "startshooting", maps\castle_into_wet_wall::_id_8224, "peep_show_react" );
    maps\_anim::_id_1264( "alexi", "slipstart", maps\castle_into_wet_wall::_id_8207, "peep_show_react" );
    level._id_0C59["tv_room_guy1"]["peep_show_react"] = %ch_castle_10_8_discovered_henchman_01;
    maps\_anim::_id_1264( "tv_room_guy1", "dialogue01", maps\castle_into_wet_wall::_id_022F, "peep_show_react" );
    level._id_0C59["tv_room_guy2"]["peep_show_react"] = %ch_castle_10_8_discovered_henchman_02;
    level._id_0C59["tv_room_guy3"]["peep_show_react"] = %ch_castle_10_8_discovered_henchman_03;
    level._id_0C59["kitchen_guy1"]["wall_break_react"] = %ch_castle_11_1_guard_entry_dive;
    level._id_0C59["kitchen_guy2"]["wall_break_react"] = %ch_castle_11_1_guard_entry_shotgun;
    level._id_0C59["kitchen_guy3"]["wall_break_react"] = %ch_castle_11_1_guard_entry_slide;
    level._id_0C59["kitchen_guy4"]["wall_break_react"] = %ch_castle_11_1_guard_run_out;
    level._id_0C59["kitchen_guy5"]["wall_break_react"] = %ch_castle_11_1_guard_cooking_grab_gun;
    level._id_0C59["generic"]["catch_fire"] = %ch_castle_11_1_guard_on_fire;
    level._id_0C59["generic"]["guard_stumble"] = %ch_castle_12_1_guard_stumble;
    level._id_0C59["generic"]["guard_double_take"] = %ch_castle_12_5_guard_double_take;
    level._id_0C59["guarda"]["foyer_door_kick"] = %ch_castle_guard_doorkick_a;
    level._id_0C59["guardb"]["foyer_door_kick"] = %ch_castle_guard_doorkick_b;
    maps\_anim::_id_1264( "guarda", "doorkick_A", maps\castle_interior::_id_6A0E, "foyer_door_kick" );
    maps\_anim::_id_1264( "guardb", "doorkick_B", maps\castle_interior::_id_6A0D, "foyer_door_kick" );
    level._id_0C59["generic"]["inner_courtyard_roof_fall"] = %ch_castle_13_1_guard_roof_fall;
    level._id_0C59["guard0"]["bridge_entrance"] = %ch_castle_14_1_btr_escort_guard1;
    level._id_0C59["guard1"]["bridge_entrance"] = %ch_castle_14_1_btr_escort_guard2;
    level._id_0C59["guard2"]["bridge_entrance"] = %ch_castle_14_1_btr_escort_guard3;
    level._id_0C59["guard3"]["bridge_entrance"] = %ch_castle_14_1_btr_escort_guard4;
    level._id_0C59["guard4"]["bridge_entrance"] = %ch_castle_14_1_btr_escort_guard5;
    level._id_0C59["guard5"]["bridge_entrance"] = %ch_castle_14_1_btr_escort_guard6;
    level._id_0C59["guard6"]["bridge_entrance"] = %ch_castle_14_1_btr_escort_guard7;
    level._id_0C59["guard7"]["bridge_entrance"] = %ch_castle_14_1_btr_escort_guard8;
    level._id_0C59["guard8"]["bridge_entrance"] = %ch_castle_14_1_btr_escort_guard9;
    level._id_0C59["guard9"]["bridge_entrance"] = %ch_castle_14_1_btr_escort_guard10;
    level._id_0C59["guard0"]["bridge_idle"][0] = %ch_castle_14_1_btr_escort_guard1_idl;
    level._id_0C59["guard1"]["bridge_idle"][0] = %ch_castle_14_1_btr_escort_guard2_idl;
    level._id_0C59["guard2"]["bridge_idle"][0] = %ch_castle_14_1_btr_escort_guard3_idl;
    level._id_0C59["guard3"]["bridge_idle"][0] = %ch_castle_14_1_btr_escort_guard4_idl;
    level._id_0C59["guard4"]["bridge_idle"][0] = %ch_castle_14_1_btr_escort_guard5_idl;
    level._id_0C59["guard5"]["bridge_idle"][0] = %ch_castle_14_1_btr_escort_guard6_idl;
    level._id_0C59["guard6"]["bridge_idle"][0] = %ch_castle_14_1_btr_escort_guard7_idl;
    level._id_0C59["guard7"]["bridge_idle"][0] = %ch_castle_14_1_btr_escort_guard8_idl;
    level._id_0C59["guard8"]["bridge_idle"][0] = %ch_castle_14_1_btr_escort_guard9_idl;
    level._id_0C59["guard9"]["bridge_idle"][0] = %ch_castle_14_1_btr_escort_guard10_idl;
    level._id_0C59["guard0"]["bridge_alert"] = %ch_castle_14_1_btr_escort_guard1_idl2fire;
    level._id_0C59["guard1"]["bridge_alert"] = %ch_castle_14_1_btr_escort_guard2_idl2fire;
    level._id_0C59["guard2"]["bridge_alert"] = %ch_castle_14_1_btr_escort_guard3_idl2fire;
    level._id_0C59["guard3"]["bridge_alert"] = %ch_castle_14_1_btr_escort_guard4_idl2fire;
    level._id_0C59["guard4"]["bridge_alert"] = %ch_castle_14_1_btr_escort_guard5_idl2fire;
    level._id_0C59["guard5"]["bridge_alert"] = %ch_castle_14_1_btr_escort_guard6_idl2fire;
    level._id_0C59["guard6"]["bridge_alert"] = %ch_castle_14_1_btr_escort_guard7_idl2fire;
    level._id_0C59["guard7"]["bridge_alert"] = %ch_castle_14_1_btr_escort_guard8_idl2fire;
    level._id_0C59["guard8"]["bridge_alert"] = %ch_castle_14_1_btr_escort_guard9_idl2fire;
    level._id_0C59["guard9"]["bridge_alert"] = %ch_castle_14_1_btr_escort_guard10_idl2fire;
    level._id_0C59["guard0"]["bridge_explode"] = %ch_castle_14_3_flung_guard1;
    level._id_0C59["guard1"]["bridge_explode"] = %ch_castle_14_3_flung_guard2;
    level._id_0C59["guard2"]["bridge_explode"] = %ch_castle_14_3_flung_guard3;
    level._id_0C59["guard3"]["bridge_explode"] = %ch_castle_14_3_flung_guard4;
    level._id_0C59["guard4"]["bridge_explode"] = %ch_castle_14_3_flung_guard5;
    level._id_0C59["guard5"]["bridge_explode"] = %ch_castle_14_3_flung_guard6;
    level._id_0C59["guard6"]["bridge_explode"] = %ch_castle_14_3_flung_guard7;
    level._id_0C59["guard7"]["bridge_explode"] = %ch_castle_14_3_flung_guard8;
    level._id_0C59["guard8"]["bridge_explode"] = %ch_castle_14_3_flung_guard9;
    level._id_0C59["guard9"]["bridge_explode"] = %ch_castle_14_3_flung_guard10;
    level._id_0C59["guard0"]["bridge_dying"][0] = %ch_castle_14_5_guard1_dying;
    level._id_0C59["guard1"]["bridge_deadloop"] = %ch_castle_14_5_guard2_deadloop;
    level._id_0C59["guard2"]["bridge_deadloop"] = %ch_castle_14_5_guard3_deadloop;
    level._id_0C59["guard3"]["bridge_dying"][0] = %ch_castle_14_5_guard4_dying;
    level._id_0C59["guard7"]["bridge_deadloop"] = %ch_castle_14_5_guard8_deadloop;
    level._id_0C59["guard8"]["bridge_dying"][0] = %ch_castle_14_5_guard9_dying;
    level._id_0C59["guard0"]["bridge_death"] = %ch_castle_14_5_price_shoots_guard_guard1;
    level._id_0C59["guard0"]["bridge_deadloop"] = %ch_castle_14_5_price_shoots_guard_guard1dead;
    level._id_0C59["guard3"]["bridge_shot"] = %ch_castle_14_5_guard4_shot;
    level._id_0C59["guard3"]["bridge_deadloop"] = %ch_castle_14_5_guard4_deadloop;
    level._id_0C59["guard8"]["bridge_shot"] = %ch_castle_14_5_guard9_shot;
    level._id_0C59["guard8"]["bridge_deadloop"] = %ch_castle_14_5_guard9_deadloop;
}
#using_animtree("vehicles");

_id_47DE()
{
    level._id_0C59["ai_parachute"]["intro"] = %o_castle_1_1_parachute_intro;
    level._id_0C59["price_parachute"]["landing"] = %o_castle_3_3_price_chute_landing;
    level._id_0C59["player_parachute"]["chute_deploy"] = %castle_player_escape_chutepull_chute;
    level._id_0C59["player_parachute"]["chute_release"] = %castle_player_escape_chuterelease_chute;
    level._id_0C59["price_parachute"]["escape_parachute"] = %o_castle_15_6_parachute_chute;
    level._id_0C59["btr"]["btr_lift"] = %v_castle_5_4_btr_lift_btr;
    level._id_0C59["btr_helicopter"]["btr_lift"] = %v_castle_5_4_btr_lift_heli;
    level._id_0C59["btr"]["bridge_entrance"] = %v_castle_14_1_btr;
    level._id_0C59["btr"]["bridge_death"] = %fxanim_castle_bridge_btr_anim;
    maps\_anim::_id_1267( "btr", "btr_explode", "bridge_btr_kill", "bridge_death" );
    level._id_0C59["escape_truck_real"]["hit_gate"] = %castle_truck_escape_player_view_adjust_at_cliff;
}
#using_animtree("animated_props");

_id_7711()
{
    level._id_1245["peep_hole_grenade"] = #animtree;
    level._id_1F90["peep_hole_grenade"] = "generic_prop_raven";
    level._id_0C59["peep_hole_grenade"]["wall_climb_grenade_toss"] = %o_castle_10_8_grenade_toss;
    level._id_0C59["escape_truck"]["cliffjump_new"] = %castle_truck_escape_truck;
    level._id_1245["escape_truck"] = #animtree;
    level._id_1F90["escape_truck"] = "vehicle_uaz_open_player_ride";
    level._id_0C59["escape_chute_price"]["cliffjump_new"] = %castle_truck_escape_prices_parachute;
    level._id_1245["escape_chute_price"] = #animtree;
    level._id_1F90["escape_chute_price"] = "ctl_parachute_deployable";
    level._id_0C59["escape_chute_price_2"]["cliffjump_new"] = %castle_truck_escape_prices_parachute2;
    level._id_1245["escape_chute_price_2"] = #animtree;
    level._id_1F90["escape_chute_price_2"] = "ctl_parachute_ai";
    level._id_1245["player_rig_ripcord"] = #animtree;
    level._id_1F90["player_rig_ripcord"] = "viewmodel_parachute_ripcord";
    level._id_0C59["player_rig_ripcord"]["escape_player_deploy_chute"] = %castle_truck_escape_player_deploy_chute_ripcord;
}
#using_animtree("script_model");

_id_4CAC()
{
    level._id_1245["price_pistol"] = #animtree;
    level._id_1F90["price_pistol"] = "ctl_weapon_usp_silencer_animated";
    level._id_0C59["price_pistol"]["ruins_start"] = %o_castle_4_1_price_pistol_startmove;
    level._id_0C59["price_pistol"]["ruins_talk"] = %o_castle_4_1_price_pistol_speech;
    level._id_1245["btr_rope"] = #animtree;
    level._id_1F90["btr_rope"] = "fxanim_castle_btr_rope_mod";
    level._id_0C59["btr_rope"]["btr_lift"] = %o_castle_5_4_btr_lift_rope;
    level._id_1245["fxanim"] = #animtree;
    level._id_0C59["fxanim"]["fxanim_gp_chain_arch_sm"][0] = %fxanim_gp_chain_arch_sm_anim;
    level._id_0C59["fxanim"]["fxanim_gp_chain_short"][0] = %fxanim_gp_chain_short_anim;
    level._id_0C59["fxanim"]["fxanim_gp_chain_arch_sm_mod"][0] = %fxanim_gp_chain_arch_sm_anim;
    level._id_0C59["fxanim"]["fxanim_gp_chain_short_mod"][0] = %fxanim_gp_chain_short_anim;
    level._id_0C59["fxanim"]["fxanim_gp_chain_med_hook_mod"][0] = %fxanim_gp_chain_med_hook_anim;
    level._id_0C59["fxanim"]["fxanim_gp_chain_med_pulley_mod"][0] = %fxanim_gp_chain_med_pulley_anim;
    level._id_0C59["fxanim"]["fxanim_castle_generator_mod"][0] = %fxanim_castle_generator_anim;
    level._id_1245["cigarette"] = #animtree;
    level._id_1F90["cigarette"] = "bo_p_glo_cigarette01_animated";
    level._id_0C59["cigarette"]["platform_idle_end"][0] = %o_castle_6_3_jumping_guard_cigarette_startidl;
    level._id_0C59["cigarette"]["jump_down"] = %o_castle_6_3_jumping_guard_cigarette;
    level._id_1245["chair"] = #animtree;
    level._id_0C59["chair"]["security_office_guard_chair_idle"][0] = %o_castle_7_2_guard_chair_idl_chair;
    level._id_0C59["chair"]["security_office_guard_chair_move"] = %o_castle_7_2_guard_chair_death_chair;
    level._id_0C59["chair"]["security_office_guard_chair_death_idle"][0] = %o_castle_7_2_guard_chair_death_chair_idl;
    level._id_1245["door"] = #animtree;
    level._id_1F90["door"] = "paris_catacombs_door_pry_kick_rigged";
    level._id_0C59["door"]["security_office_entry_door_close"] = %o_castle_7_2_entry_door_close;
    level._id_0C59["door"]["security_office_entry"] = %castle_comm_office_entry_door;
    level._id_1245["airlock_door"] = #animtree;
    level._id_0C59["airlock_door"]["security_office_door_close"] = %o_castle_7_5_price_door_close_door;
    level._id_0C59["airlock_door"]["security_office_drag"] = %o_castle_7_5_price_drag_guard_door_open;
    level._id_1245["baton"] = #animtree;
    level._id_1F90["baton"] = "ctl_baton_wood_animated";
    level._id_0C59["baton"]["harass_loop"][0] = %o_castle_7_1_baton_loop;
    level._id_0C59["baton"]["harass_drop"] = %o_castle_7_1_baton_drop;
    level._id_0C59["baton"]["harass_drop_idle"][0] = %o_castle_7_1_baton_end_idl;
    level._id_0C59["door"]["prison_exit_briefing_open"] = %o_castle_8_7_price_door_briefing_door;
    level._id_0C59["door"]["prison_exit_briefing_open_idle"][0] = %o_castle_8_7_price_door_briefing_door_open_idl;
    level._id_0C59["door"]["prison_exit_briefing_close"] = %o_castle_8_7_price_door_briefing_door_close;
    level._id_1245["flare"] = #animtree;
    level._id_1F90["flare"] = "ctl_emergency_flare_animated";
    level._id_0C59["flare"]["guard_flare_toss"] = %o_castle_8_3_guard_flare;
    level._id_0C59["flare"]["guard_flare_toss2"] = %o_castle_8_3_guard_flare2;
    level._id_0C59["flare"]["guard_flare_toss3"] = %o_castle_8_3_guard_flare3;
    level._id_1245["bridge_tarp"] = #animtree;
    level._id_0C59["bridge_tarp"]["gone_with_the_wind"] = %fxanim_castle_bridge_tarp06_anim;
    level._id_1245["camera"] = #animtree;
    level._id_1F90["camera"] = "ctl_fiber_optic_cam_animated";
    level._id_0C59["camera"]["wet_wall_investigate"] = %o_castle_10_2_set_det_chord_optic_cam;
    level._id_1245["detcord"] = #animtree;
    level._id_1F90["detcord"] = "ctl_detcord_animated";
    level._id_0C59["detcord"]["wet_wall_place_detcord"] = %o_castle_10_2_set_det_chord_det_chord;
    level._id_1245["wet_wall"] = #animtree;
    level._id_1F90["wet_wall"] = "fxanim_castle_enter_wall_mod";
    level._id_0C59["wet_wall"]["detonate"] = %fxanim_castle_enter_wall_anim;
    level._id_1245["peep_hole_piece"] = #animtree;
    level._id_1F90["peep_hole_piece"] = "ctl_peep_hole_piece";
    level._id_0C59["peep_hole_piece"]["wall_climb_peek_slip"] = %castle_player_wetwall_climb_hole_peek_slip_slatbreak;
    level._id_1245["peep_hole_fx"] = #animtree;
    level._id_1F90["peep_hole_fx"] = "fxanim_castle_peep_hole_boards_mod";
    level._id_0C59["peep_hole_fx"]["wall_climb_peek_slip"] = %fxanim_castle_peep_hole_boards_anim;
    level._id_1245["kitchen_wall"] = #animtree;
    level._id_1F90["kitchen_wall"] = "fxanim_castle_kitchen_wall_mod";
    level._id_0C59["kitchen_wall"]["crash_thru"] = %fxanim_castle_kitchen_wall_anim;
    level._id_1245["meat"] = #animtree;
    level._id_1F90["meat"] = "fxanim_castle_meat_large_mod";
    level._id_0C59["meat"]["swing"][0] = %fxanim_castle_meat_large_anim;
    level._id_1245["secondary_chute"] = #animtree;
    level._id_1F90["secondary_chute"] = "ctl_parachute_handle_backup";
    level._id_0C59["secondary_chute"]["release"] = %castle_player_escape_chuterelease_chutestrap;
    level._id_1245["bridge_scaffolding_large"] = #animtree;
    level._id_1F90["bridge_scaffolding_large"] = "fxanim_castle_scaff_lrg_x_mod";
    level._id_0C59["bridge_scaffolding_large"]["shake"][0] = %fxanim_castle_scaff_lrg_x_anim;
    level._id_1245["bridge_scaffolding_small"] = #animtree;
    level._id_1F90["bridge_scaffolding_small"] = "fxanim_castle_scaff_sm_mod";
    level._id_0C59["bridge_scaffolding_small"]["shake"][0] = %fxanim_castle_scaff_sm_anim;
    level._id_1245["tree_large"] = #animtree;
    level._id_1F90["tree_large"] = "fxanim_castle_tree_large_sway_mod";
    level._id_0C59["tree_large"]["sway"][0] = %fxanim_castle_tree_large_sway_anim;
    level._id_0C59["tree_large"]["stop"] = %fxanim_castle_tree_large_sway_stop_anim;
    level._id_1245["tree_small"] = #animtree;
    level._id_1F90["tree_small"] = "fxanim_castle_tree_small_sway_mod";
    level._id_0C59["tree_small"]["sway"][0] = %fxanim_castle_tree_small_sway_anim;
    level._id_0C59["tree_small"]["stop"] = %fxanim_castle_tree_small_sway_stop_anim;
    level._id_1245["power_switch"] = #animtree;
    level._id_1F90["power_switch"] = "ctl_light_switch_panel_arm_animated";
    level._id_0C59["power_switch"]["power_off"] = %o_castle_7_6_price_lights_off;
}

_id_6A12()
{
    wait 1;
    var_0 = getentarray( "fxanim_gp_chain_arch_sm", "targetname" );

    foreach ( var_2 in var_0 )
    {
        var_2._id_1032 = "fxanim";
        var_2 maps\_utility::_id_2629();
        var_2 thread maps\_anim::_id_124E( var_2, "fxanim_gp_chain_arch_sm" );
        wait(randomfloatrange( 0.1, 1 ));
    }

    var_4 = getentarray( "fxanim_gp_chain_short", "targetname" );

    foreach ( var_2 in var_4 )
    {
        var_2._id_1032 = "fxanim";
        var_2 maps\_utility::_id_2629();
        var_2 thread maps\_anim::_id_124E( var_2, "fxanim_gp_chain_short" );
        wait(randomfloatrange( 0.1, 1 ));
    }

    common_scripts\utility::flag_wait( "entered_security_office_cage" );
    var_7 = getentarray( "fxanim_prison", "script_noteworthy" );

    foreach ( var_9 in var_7 )
    {
        var_9._id_1032 = "fxanim";
        var_9 maps\_utility::_id_2629();
        var_9 thread maps\_anim::_id_124E( var_9, var_9.targetname, "stop_fxanim" );
        wait(randomfloatrange( 0.1, 1 ));
    }

    var_11 = getentarray( "fxanim_castle_generator_mod", "targetname" );

    foreach ( var_13 in var_11 )
    {
        var_13._id_1032 = "fxanim";
        var_13 useanimtree( #animtree );
        var_13 thread maps\_anim::_id_124E( var_13, "fxanim_castle_generator_mod" );
        wait(randomfloatrange( 0.1, 3 ));
    }
}
#using_animtree("generic_human");

_id_6A13()
{
    level.scr_sound["price"]["castle_pri_coverourbacks"] = "castle_pri_coverourbacks";
    level.scr_sound["price"]["castle_pri_behindus"] = "castle_pri_behindus";
    level.scr_sound["price"]["castle_pri_keepup"] = "castle_pri_keepup";
    level.scr_sound["price"]["castle_pri_getdown"] = "castle_pri_getdown";
    level.scr_sound["price"]["castle_pri_beforestarted"] = "castle_pri_beforestarted";
    level.scr_sound["price"]["castle_pri_move3"] = "castle_pri_move3";
    level.scr_sound["price"]["castle_pri_wait3"] = "castle_pri_wait3";
    level.scr_sound["price"]["castle_pri_thisway3"] = "castle_pri_thisway3";
    level.scr_sound["price"]["castle_pri_laggingbehind"] = "castle_pri_laggingbehind";
    level.scr_sound["price"]["castle_pri_slowingme"] = "castle_pri_slowingme";
    level.scr_sound["price"]["castle_pri_onyourown"] = "castle_pri_onyourown";
    level.scr_sound["price"]["castle_pri_nexttime"] = "castle_pri_nexttime";
    level.scr_sound["price"]["castle_pri_mistakes"] = "castle_pri_mistakes";
    level.scr_sound["price"]["castle_pri_moveasimove"] = "castle_pri_moveasimove";
    level._id_11B7["price"]["castle_pri_moveasimove"] = %castle_1_12n_price_face;
    level.scr_sound["price"]["castle_pri_letsgo2"] = "castle_pri_letsgo2";
    level._id_11B7["price"]["castle_pri_letsgo2"] = %castle_1_13n_price_face;
    level.scr_sound["price"]["castle_pri_spotted"] = "castle_pri_beenspotted";
    level.scr_sound["price"]["castle_pri_lightemup"] = "castle_pri_lightemup";
    level.scr_sound["price"]["castle_pri_compromised"] = "castle_pri_compromised";
    level.scr_sound["price"]["castle_pri_dothatagain"] = "castle_pri_dothatagain";
    level.scr_sound["price"]["castle_pri_pitiful"] = "castle_pri_pitiful";
    level.scr_sound["price"]["castle_pri_dobetter"] = "castle_pri_dobetter";
    level.scr_sound["price"]["castle_pri_hold2"] = "castle_pri_hold2";
    level.scr_sound["price"]["castle_pri_whatyoukill"] = "castle_pri_whatyoukill";
    level.scr_sound["price"]["castle_pri_go2"] = "castle_pri_go";
    level.scr_sound["price"]["castle_pri_undertrucks2"] = "castle_pri_undertrucks2";
    level.scr_sound["price"]["castle_pri_getunder"] = "castle_pri_getunder";
    level.scr_sound["price"]["castle_pri_donthavetime"] = "castle_pri_donthavetime";
    level.scr_sound["price"]["castle_pri_cmon"] = "castle_pri_cmon";
    level.scr_sound["price"]["castle_pri_wait"] = "castle_pri_wait4";
    level.scr_sound["price"]["castle_pri_plantc4"] = "castle_pri_plantc4cover";
    level.scr_sound["price"]["castle_pri_burnthisplace"] = "castle_pri_burnthisplace";
    level.scr_sound["price"]["castle_pri_takehimout"] = "castle_pri_takehimout";
    level._id_11B7["price"]["castle_pri_takehimout"] = %castle_2_7n_price_face;
    level.scr_sound["price"]["castle_pri_useknife2"] = "castle_pri_useknife2";
    level.scr_sound["price"]["castle_pri_lostyouredge"] = "castle_pri_lostyouredge";
    level.scr_sound["price"]["castle_pri_waitforit"] = "castle_pri_waitforit";
    level._id_11B7["price"]["castle_pri_waitforit"] = %castle_2_10n_price_face;
    level.scr_sound["price"]["castle_pri_now2"] = "castle_pri_now2";
    level.scr_sound["price"]["castle_pri_screwthisup2"] = "castle_pri_screwthisup2";
    level.scr_sound["price"]["castle_pri_overhere"] = "castle_pri_overhere";
    level.scr_sound["price"]["castle_pri_stopdontmove"] = "castle_pri_stopdontmove";
    level.scr_sound["price"]["castle_pri_weregood2"] = "castle_pri_alrightcmon";
    level.scr_sound["price"]["castle_pri_c4platform"] = "castle_pri_c4platform";
    level.scr_sound["price"]["castle_pri_plantthec4"] = "castle_pri_plantthec4";
    level.scr_sound["price"]["castle_pri_daft"] = "castle_pri_daft";
    level.scr_sound["price"]["castle_pri_nevermind2"] = "castle_pri_nevermind2";
    level.scr_sound["price"]["castle_pri_easy"] = "castle_pri_easy";
    level.scr_sound["price"]["castle_pri_cleargo"] = "castle_pri_cleargo";
    level.scr_sound["price"]["castle_pri_weregood3"] = "castle_pri_weregood3";
    level._id_11B7["price"]["castle_pri_weregood3"] = %castle_3_11r_price_face;
    level.scr_sound["price"]["castle_pri_securityoffice2"] = "castle_pri_securityoffice2";
    level.scr_sound["price"]["castle_pri_illhandle"] = "castle_pri_illhandle";
    level.scr_sound["price"]["castle_pri_clear"] = "castle_pri_clear";
    level.scr_sound["price"]["castle_pri_camerasout"] = "castle_pri_camerasout";
    level._id_11B7["price"]["castle_pri_camerasout"] = %ch_castle_7_5_price_drag_guard_face_camerasout;
    level.scr_sound["price"]["castle_pri_knock"] = "castle_pri_knock";
    level._id_11B7["price"]["castle_pri_knock"] = %ch_castle_7_5_price_drag_guard_face_knockdoor;
    level.scr_sound["price"]["castle_pri_cheers"] = "castle_pri_cheers";
    level._id_11B7["price"]["castle_pri_cheers"] = %ch_castle_7_5_price_drag_guard_face_cheers;
    level.scr_sound["price"]["castle_pri_quiet"] = "castle_pri_quiet";
    level.scr_sound["price"]["castle_pri_nightvisionon"] = "castle_pri_nightvisionon";
    level.scr_sound["price"]["castle_pri_takecare"] = "castle_pri_takecare";
    level.scr_sound["price"]["castle_pri_ready"] = "castle_pri_ready";
    level.scr_sound["price"]["castle_pri_weaponsfree"] = "castle_pri_weaponsfree";
    level.scr_sound["price"]["castle_pri_sweepthrough"] = "castle_pri_sweepthrough";
    level.scr_sound["price"]["castle_pri_howfew"] = "castle_pri_howfew";
    level.scr_sound["price"]["castle_pri_usingflares"] = "castle_pri_usingflares";
    level.scr_sound["price"]["castle_pri_oldway"] = "castle_pri_oldway";
    level.scr_sound["price"]["castle_pri_reinforcements2"] = "castle_pri_reinforcements2";
    level.scr_sound["price"]["castle_pri_onpoint"] = "castle_pri_onpoint";
    level.scr_sound["price"]["castle_pri_startmoving"] = "castle_pri_startmoving";
    level.scr_sound["price"]["castle_pri_getoutofhere2"] = "castle_pri_getoutofhere2";
    level.scr_sound["price"]["castle_pri_nevermind"] = "castle_pri_nevermind";
    level.scr_sound["price"]["castle_pri_tenminutes"] = "castle_pri_tenminutes";
    level._id_11B7["price"]["castle_pri_tenminutes"] = %castle_6_5_price_face;
    level.scr_sound["price"]["castle_pri_fallbehind"] = "castle_pri_fallbehind";
    level.scr_sound["price"]["castle_pri_thisbridge2"] = "castle_pri_thisbridge2";
    level.scr_sound["price"]["castle_pri_c4oncolumn"] = "castle_pri_c4oncolumn";
    level.scr_sound["price"]["castle_pri_plantc4hurry"] = "castle_pri_plantc4hurry";
    level.scr_sound["price"]["castle_pri_goodfornothing"] = "castle_pri_goodfornothing";
    level.scr_sound["price"]["castle_pri_abouttocollapse"] = "castle_pri_abouttocollapse";
    level.scr_sound["price"]["castle_pri_sotakeitslow"] = "castle_pri_sotakeitslow";
    level.scr_sound["price"]["castle_pri_alittletooslow"] = "castle_pri_alittletooslow";
    level.scr_sound["price"]["castle_pri_holdon"] = "castle_pri_holdon";
    level.scr_sound["price"]["castle_pri_changeofplan"] = "castle_pri_changeofplan";
    level.scr_sound["price"]["castle_pri_justaboveus"] = "castle_pri_justaboveus";
    level.scr_sound["price"]["castle_pri_shootourway"] = "castle_pri_shootourway";
    level.scr_sound["price"]["castle_pri_waitformysignal2"] = "castle_pri_waitformysignal2";
    level.scr_sound["price"]["castle_pri_now3"] = "castle_pri_now3";
    level.scr_sound["price"]["castle_pri_areyoudim"] = "castle_pri_areyoudim";
    level.scr_sound["price"]["castle_pri_pisspoor"] = "castle_pri_pisspoor";
    level.scr_sound["price"]["castle_pri_go3"] = "castle_pri_go3";
    level.scr_sound["price"]["castle_pri_blowit"] = "castle_pri_blowit";
    level.scr_sound["price"]["castle_pri_doit2"] = "castle_pri_doit2";
    level.scr_sound["price"]["castle_pri_payattention"] = "castle_pri_pisspoor";
    level.scr_sound["price"]["castle_pri_focusyuri"] = "castle_pri_focusyuri";
    level.scr_sound["price"]["castle_pri_climbuphere"] = "castle_pri_climbuphere";
    level.scr_sound["president"]["castle_prs_forthelast"] = "castle_prs_forthelast";
    level.scr_sound["president"]["castle_prs_notbow"] = "castle_prs_notbow";
    level.scr_sound["president"]["castle_prs_iwilldie"] = "castle_prs_iwilldie";
    level.scr_sound["price"]["castle_pri_makarov"] = "castle_pri_makarov";
    level._id_11B7["price"]["castle_pri_makarov"] = %castle_wetwall_price_facial_8_4;
    level.scr_sound["makarov"]["castle_mkv_isee"] = "castle_mkv_isee";
    level.scr_sound["makarov"]["castle_mkv_thisiswhat"] = "castle_mkv_thisiswhat";
    level.scr_sound["makarov"]["castle_mkv_oldman"] = "castle_mkv_oldman";
    level.scr_sound["makarov"]["castle_mkv_youtoo"] = "castle_mkv_youtoo";
    level.scr_sound["tv_room_guy3"]["castle_ru1_noresponse"] = "castle_ru1_noresponse";
    level.scr_sound["alexi"]["castle_alx_checkwith"] = "castle_alx_checkwith";
    level.scr_sound["makarov"]["castle_mkv_confirmed"] = "castle_mkv_confirmed";
    level.scr_sound["alexi"]["castle_alx_yessir"] = "castle_alx_yessir";
    level.scr_sound["makarov"]["castle_mkv_listening"] = "castle_mkv_listening";
    level.scr_sound["alexi"]["castle_alx_thedaughter"] = "castle_alx_thedaughter";
    level._id_11B7["alexi"]["castle_alx_thedaughter"] = %ch_castle_10_6_peep_show_alexei_hours_face;
    level.scr_sound["makarov"]["castle_mkv_updated"] = "castle_mkv_updated";
    level.scr_sound["alexi"]["castle_alx_whatgoingon"] = "castle_alx_whatgoingon";
    level.scr_sound["price"]["castle_pri_wrong"] = "castle_pri_wrong";
    level.scr_sound["price"]["castle_pri_timetogo"] = "castle_pri_timetogo";
    level._id_11B7["price"]["castle_pri_timetogo"] = %castle_wetwall_price_facial_4_35;
    level.scr_sound["price"]["castle_pri_withthis"] = "castle_pri_withthis";
    level._id_11B7["price"]["castle_pri_withthis"] = %castle_wetwall_price_facial_8_15_4;
    level.scr_sound["price"]["castle_pri_thebodies"] = "castle_pri_thebodies";
    level._id_11B7["price"]["castle_pri_thebodies"] = %castle_wetwall_price_facial_8_15_3;
    level.scr_sound["tv_room_guy1"]["castle_ru1_grenade"] = "castle_ru1_grenade";
    level.scr_sound["price"]["castle_pri_downnow"] = "castle_pri_downnow";
    level.scr_sound["price"]["castle_pri_onyourfeet"] = "castle_pri_onyourfeet";
    level.scr_sound["price"]["castle_pri_inberlin"] = "castle_pri_inberlin";
    level._id_11BB["castle_nik_contact"] = "castle_nik_contact";
    level.scr_sound["price"]["castle_pri_willbreak"] = "castle_pri_willbreak";
    level._id_11BB["castle_nik_letyoudown"] = "castle_nik_letyoudown";
    level.scr_sound["price"]["castle_pri_leftside2"] = "castle_pri_leftside2";
    level.scr_sound["price"]["castle_pri_keepmoving2"] = "castle_pri_keepmoving2";
    level.scr_sound["price"]["castle_pri_dontslowdown"] = "castle_pri_dontslowdown";
    level.scr_sound["price"]["castle_pri_sortemout"] = "castle_pri_sortemout";
    level.scr_sound["price"]["castle_pri_throughhere"] = "castle_pri_throughhere";
    level.scr_sound["price"]["castle_pri_flashbang"] = "castle_pri_flashbang";
    level.scr_sound["price"]["castle_pri_rpgs"] = "castle_pri_rpgs";
    level.scr_sound["price"]["castle_pri_throughere"] = "castle_pri_throughere";
    level.scr_sound["price"]["castle_pri_onme2"] = "castle_pri_onme2";
    level.scr_sound["price"]["castle_pri_overehere"] = "castle_pri_overehere";
    level.scr_sound["price"]["castle_pri_staywithmeyuri"] = "castle_pri_staywithmeyuri";
    level.scr_sound["price"]["castle_pri_justintime"] = "castle_pri_justintime";
    level.scr_sound["price"]["castle_pri_doit"] = "castle_pri_doit";
    level.scr_sound["price"]["castle_pri_detonate"] = "castle_pri_detonate";
    level.scr_sound["price"]["castle_pri_move4"] = "castle_pri_move4";
    level.scr_sound["price"]["castle_pri_illdoit"] = "castle_pri_illdoit";
    level.scr_sound["price"]["castle_pri_sloppybastard"] = "castle_pri_sloppybastard";
    level.scr_sound["price"]["castle_pri_jumpgo"] = "castle_pri_jumpgo2";
    level.scr_sound["price"]["castle_pri_wholebase"] = "castle_pri_wholebase";
    level.scr_sound["price"]["castle_pri_btrblocking"] = "castle_pri_btrblocking";
    level.scr_sound["price"]["castle_pri_getin"] = "castle_pri_getin";
    level.scr_sound["price"]["castle_pri_detonating"] = "castle_pri_detonating";
    level.scr_sound["price"]["castle_pri_holdon2"] = "castle_pri_holdon2";
    level.scr_sound["price"]["castle_pri_reserve"] = "castle_pri_reserve";
    level.scr_sound["price"]["castle_pri_BTRs"] = "castle_pri_BTRs";
    level.scr_sound["price"]["castle_pri_chuteready"] = "castle_pri_chuteready";
    level.scr_sound["price"]["castle_pri_jump"] = "castle_pri_jump";
    level.scr_sound["price"]["castle_pri_getusout"] = "castle_pri_getusout";
    level._id_11BB["castle_nik_onmyway"] = "castle_nik_onmyway";
    level.scr_sound["guard1"]["castle_ru1_noresponse"] = "castle_ru1_noresponse";
    level.scr_sound["guard1"]["castle_ru1_everyoneoff"] = "castle_ru1_everyoneoff";
    level.scr_sound["guard1"]["castle_ru1_inorout"] = "castle_ru1_inorout";
    level.scr_sound["guard1"]["castle_ru1_killintruders"] = "castle_ru1_killintruders";
    level.scr_sound["guard2"]["castle_ru2_securitydetail"] = "castle_ru2_securitydetail";
    level.scr_sound["guard3"]["castle_ru3_dontaskme"] = "castle_ru3_dontaskme";
    level.scr_sound["guard2"]["castle_ru2_gettingsoaked"] = "castle_ru2_gettingsoaked";
    level.scr_sound["guard1"]["castle_ru1_enough"] = "castle_ru1_enough";
    level.scr_sound["guard1"]["castle_ru1_watchingyou"] = "castle_ru1_watchingyou";
    level.scr_sound["ruins_patroller4"]["castle_ru1_howslife"] = "castle_ru1_howslife";
    level.scr_sound["ruins_patroller3"]["castle_ru2_colddark"] = "castle_ru2_colddark";
    level.scr_sound["ruins_patroller4"]["castle_ru1_lovelife"] = "castle_ru1_lovelife";
    level.scr_sound["ruins_patroller3"]["castle_ru2_veryfunny"] = "castle_ru2_veryfunny";
    level.scr_sound["platformguard1"]["castle_ru3_lookbusy"] = "castle_ru3_lookbusy";
    level.scr_sound["platformguard2"]["castle_ru4_nothingtodo"] = "castle_ru4_nothingtodo";
    level.scr_sound["platformguard1"]["castle_ru3_someaction"] = "castle_ru3_someaction";
    level.scr_sound["platformguard2"]["castle_ru4_dieofboredom"] = "castle_ru4_dieofboredom";
    level.scr_sound["road_patroller_1"]["castle_ru3_crazy"] = "castle_ru3_crazy";
    level.scr_sound["road_patroller_2"]["castle_ru4_andtellhimwhat"] = "castle_ru4_andtellhimwhat";
    level.scr_sound["road_patroller_1"]["castle_ru3_thetruth"] = "castle_ru3_thetruth";
    level.scr_sound["road_patroller_2"]["castle_ru4_submitsreport"] = "castle_ru4_submitsreport";
    level.scr_sound["road_patroller_1"]["castle_ru3_betterthat"] = "castle_ru3_betterthat";
    level.scr_sound["road_patroller_2"]["castle_ru4_notanymore"] = "castle_ru4_notanymore";
    level.scr_sound["road_patroller_1"]["castle_ru3_gettingbetter"] = "castle_ru3_gettingbetter";
    level.scr_sound["road_patroller_2"]["castle_ru4_thanks"] = "castle_ru4_thanks";
    level.scr_sound["road_patroller_1"]["castle_ru3_justfalloff"] = "castle_ru3_justfalloff";
    level.scr_sound["generic"]["castle_ru1_intruders"] = "castle_ru1_intruders";
    level.scr_sound["generic"]["castle_ru1_soundalarm"] = "castle_ru1_soundalarm";
    level.scr_sound["generic"]["castle_ru2_goodfornothing"] = "castle_ru2_goodfornothing";
    level.scr_sound["generic"]["castle_ru2_tillwesay"] = "castle_ru2_tillwesay";
    level.scr_sound["generic"]["castle_ru2_sitdown"] = "castle_ru2_sitdown";
    level.scr_sound["guard3"]["castle_ru2_whatthehell"] = "castle_ru2_whatthehell";
    level.scr_sound["generic"]["castle_ru2_onthestairs"] = "castle_ru2_onthestairs";
    level.scr_sound["generic"]["castle_cop1_whatshappening"] = "castle_cop1_whatshappening";
    level.scr_sound["generic"]["castle_cop1_whoarethose"] = "castle_cop1_whoarethose";
    level.scr_sound["generic"]["castle_cop1_setusfree"] = "castle_cop1_setusfree";
    level.scr_sound["generic"]["castle_cop1_getusout"] = "castle_cop1_getusout";
    level.scr_sound["generic"]["castle_cop1_abouttime"] = "castle_cop1_abouttime";
    level.scr_sound["generic"]["castle_cop1_hurray"] = "castle_cop1_hurray";
    level.scr_sound["generic"]["castle_cop1_yeah"] = "castle_cop1_yeah";
    level.scr_sound["generic"]["castle_cop1_shootthe"] = "castle_cop1_shootthe";
    level.scr_sound["generic"]["castle_rup1_help"] = "castle_rup1_help";
    level.scr_sound["generic"]["castle_rup2_letusout"] = "castle_rup2_letusout";
    level.scr_sound["generic"]["castle_rup3_innocents"] = "castle_rup3_innocents";
    level.scr_sound["generic"]["castle_rup1_hereforus"] = "castle_rup1_hereforus";
    level.scr_sound["generic"]["castle_rup2_wecanhelp"] = "castle_rup2_wecanhelp";
    level.scr_sound["generic"]["castle_rup3_deathtomakarov"] = "castle_rup3_deathtomakarov";
    level.scr_sound["generic"]["castle_rup1_overhere"] = "castle_rup1_overhere";
    level.scr_sound["generic"]["castle_rup2_doctor"] = "castle_rup2_doctor";
    level.scr_sound["generic"]["castle_rup3_helpusplease"] = "castle_rup3_helpusplease";
    level.scr_sound["generic"]["castle_rup1_whatsgoingon"] = "castle_rup1_whatsgoingon";
    level.scr_sound["generic"]["castle_rup2_outthere"] = "castle_rup2_outthere";
    level.scr_sound["generic"]["castle_rup3_openthedoors"] = "castle_rup3_openthedoors";
    level.scr_sound["generic"]["castle_rup1_yes"] = "castle_rup1_yes";
    level.scr_sound["generic"]["castle_rup2_killthem"] = "castle_rup2_killthem";
    level.scr_sound["generic"]["castle_ru1_gunfire"] = "castle_ru1_gunfire";
    level.scr_sound["generic"]["castle_ru2_spreadout"] = "castle_ru2_spreadout";
    level.scr_sound["generic"]["castle_ru3_alertcommander"] = "castle_ru3_alertcommander";
    level.scr_sound["generic"]["castle_ru1_lockdown"] = "castle_ru1_lockdown";
    level.scr_sound["generic"]["castle_ru2_powerback"] = "castle_ru2_powerback";
    level.scr_sound["generic"]["castle_ru3_wherearethey"] = "castle_ru3_wherearethey";
    level.scr_sound["generic"]["castle_ru1_findthem"] = "castle_ru1_findthem";
    level.scr_sound["generic"]["castle_ru2_unidentified"] = "castle_ru2_unidentified";
}

_id_7DCC()
{
    level._id_7DCD = spawn( "script_model", ( 0.0, 0.0, 0.0 ) );
    level._id_7DCD hide();
    level._id_7DCD setmodel( self.model );
    level._id_7DCD attach( self.headmodel, "", 1 );
    level._id_7DCD._id_1032 = "security_guard_chair";
    level._id_7DCD maps\_anim::_id_1244();
}

_id_6A14( var_0 )
{
    var_0 notify( "start_melee_guard_anim" );
}

_id_6A15( var_0 )
{
    var_0._id_0EC6 = 1;
    var_0 allowedstances( "prone" );
}

_id_6A16( var_0 )
{
    var_0._id_0EC6 = 0;
    var_0 allowedstances( "stand", "crouch", "prone" );
}

_id_63E9( var_0 )
{
    var_0 maps\_utility::_id_168C( "castle_pri_moveasimove" );
}

_id_63EA( var_0 )
{
    var_0 maps\_utility::_id_168C( "castle_pri_letsgo2" );
}
