// IW5 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool

_id_7453()
{
    maps\_credits::_id_7455( &"CREDIT_DESIGNED_AND_DEVELOPED_BY_INFINI" );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( &"CREDIT_AARON_EADY", undefined, &"CREDIT_GUY_BEAHM", undefined, &"CREDIT_MICHAEL_VANCE", undefined );
    maps\_credits::_id_000C( &"CREDIT_AARON_HALON", undefined, &"CREDIT_HOUGANT_CHEN", undefined, &"CREDIT_MICHAEL_ZIPKIN", undefined );
    maps\_credits::_id_000C( &"CREDIT_AARON_MCLERAN", undefined, &"CREDIT_JAKE_ROWELL", undefined, &"CREDIT_MIKE_DENNY", undefined );
    maps\_credits::_id_000C( &"CREDIT_ADAM_SMITH", undefined, &"CREDIT_JANICE_LOHR_TURNER", undefined, &"CREDIT_MILTON_TREY_SHARP", undefined );
    maps\_credits::_id_000C( &"CREDIT_ADDISON_DEBOLT", undefined, &"CREDIT_JASON_BELL", undefined, &"CREDIT_MITCH_SANBORN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ADRIAN_LONGLAND", undefined, &"CREDIT_JASON_CHANG", undefined, &"CREDIT_NAKIA_HARRIS", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALBERTO_CONTRERAS", undefined, &"CREDIT_JASON_GAVAZZA", undefined, &"CREDIT_NATHAN_KINNEY", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALEJANDRO_GIL", undefined, &"CREDIT_JASON_HALL", undefined, &"CREDIT_NATHAN_SILVERS", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALESSANDRO_BARTOLUCCI", undefined, &"CREDIT_JASON_HAZELROTH", undefined, &"CREDIT_NEEL_KAR", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALEX_HAWORTH", undefined, &"CREDIT_JAY_MENCONI", undefined, &"CREDIT_NGHIA_LAM", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALLISON_WRIGHT", undefined, &"CREDIT_JEFF_CURLEY", undefined, &"CREDIT_NICKLAS_PAVLICH", undefined );
    maps\_credits::_id_000C( &"CREDIT_AMANDA_SULLIVAN_LEE", undefined, &"CREDIT_JEFF_HEATH", undefined, &"CREDIT_NORBERT_NACU", undefined );
    maps\_credits::_id_000C( &"CREDIT_AMBER_PEACHER", undefined, &"CREDIT_JEFF_ZARING", undefined, &"CREDIT_OSCAR_LOPEZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANDREW_AYE", undefined, &"CREDIT_JENNY_RYU", undefined, &"CREDIT_PAT_GRIFFITH", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANDY_DOHR", undefined, &"CREDIT_JEREMY_GRIFFITH", undefined, &"CREDIT_PAUL_KERBY", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANGIE_LAI", undefined, &"CREDIT_JEREMY_LUYTIES", undefined, &"CREDIT_PAUL_SANDLER", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANTHONY_RUBIN", undefined, &"CREDIT_JESSE_BUCHANAN", undefined, &"CREDIT_PAUL_STOUGHTON", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANTHONY_SCHMILL", undefined, &"CREDIT_JESSE_LEE", undefined, &"CREDIT_PETE_BLUMEL", undefined );
    maps\_credits::_id_000C( &"CREDIT_BHARATHWAJ_NANDAKUMAR", undefined, &"CREDIT_JESSICA_HOOK", undefined, &"CREDIT_PETER_CHEN", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRET_ROBBINS", undefined, &"CREDIT_JOCELYN_CHEW", undefined, &"CREDIT_PRASHAN_GUNASINGAM", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_BAKER", undefined, &"CREDIT_JOE_ARCOVITCH", undefined, &"CREDIT_RICHARD_KRIEGLER", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_WEST", undefined, &"CREDIT_JOE_CECOT", undefined, &"CREDIT_RICK_ALVAREZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRYAN_KUHN", undefined, &"CREDIT_JOE_SALUD", undefined, &"CREDIT_ROBERT_A_DYE", undefined );
    maps\_credits::_id_000C( &"CREDIT_CALEB_SCHNEIDER", undefined, &"CREDIT_JOHN_BOJORQUEZ", undefined, &"CREDIT_ROBERT_BOWLING", undefined );
    maps\_credits::_id_000C( &"CREDIT_CANDICE_CAPEN", undefined, &"CREDIT_JOHN_DOBBIE", undefined, &"CREDIT_ROBERT_FIELD", undefined );
    maps\_credits::_id_000C( &"CREDIT_CARLOS_PINEDA", undefined, &"CREDIT_JOHN_DOLAN", undefined, &"CREDIT_ROBERT_PITTS", undefined );
    maps\_credits::_id_000C( &"CREDIT_CATHERINE_SHEU", undefined, &"CREDIT_JOHN_GOLDSWORTHY", undefined, &"CREDIT_RODRIGO_SUAREZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHANCE_GLASCO", undefined, &"CREDIT_JOHN_HARRIES", undefined, &"CREDIT_RON_ANDAYA", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHELSY_BERRY", undefined, &"CREDIT_JOHN_SAHAS", undefined, &"CREDIT_ROSIE_WREDE", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHENG_LOR", undefined, &"CREDIT_JOHN_WASILCZYK", undefined, &"CREDIT_ROXANA_BRACAMONTES", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHETAN_BEDI", undefined, &"CREDIT_JOLYON_MYERS", undefined, &"CREDIT_RYAN_BROOKS", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHING_HUNG_CHU", undefined, &"CREDIT_JON_PORTER", undefined, &"CREDIT_SAMI_ONUR", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRIS_LAI", undefined, &"CREDIT_JONATHAN_KEISER", undefined, &"CREDIT_SAN_VUONG", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRIS_PENNYA", undefined, &"CREDIT_JONATHAN_SIMAS", undefined, &"CREDIT_SANDY_LIN", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRIS_SHEPHERD", undefined, &"CREDIT_JORDAN_ABELES", undefined, &"CREDIT_SARAH_SPERRY", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRIS_STAPLES", undefined, &"CREDIT_JORDAN_HIRSH", undefined, &"CREDIT_SCOT_BOYD", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRIS_WEBB", undefined, &"CREDIT_JORGE_E_RUIZ_CANO", undefined, &"CREDIT_SCOTT_WHITNEY", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISSY_ARYA", undefined, &"CREDIT_JOSH_KATZ", undefined, &"CREDIT_SEAN_SOUCY", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTOPHER_STONE", undefined, &"CREDIT_JULIAN_LUO", undefined, &"CREDIT_SERGIO_PACHECO", undefined );
    maps\_credits::_id_000C( &"CREDIT_COLIN_MUNSON", undefined, &"CREDIT_JULIE_COUCOULES", undefined, &"CREDIT_SEROZH_SARKISYAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_COLIN_OCONNOR", undefined, &"CREDIT_JUSTIN_HARRIS", undefined, &"CREDIT_SHANE_DALEY", undefined );
    maps\_credits::_id_000C( &"CREDIT_CONANT_FONG", undefined, &"CREDIT_JUSTIN_LAMPERSKI", undefined, &"CREDIT_SHIVA_DEONARINE", undefined );
    maps\_credits::_id_000C( &"CREDIT_COOPER_DRINKWARD", undefined, &"CREDIT_KACPER_CENTKOWSKI", undefined, &"CREDIT_SIMON_COURNOYER", undefined );
    maps\_credits::_id_000C( &"CREDIT_CRAIG_BROWN", undefined, &"CREDIT_KAREN_KWAK", undefined, &"CREDIT_SKYLER_CLARK", undefined );
    maps\_credits::_id_000C( &"CREDIT_CRAIG_LOUIE", undefined, &"CREDIT_KAREN_SIDEY", undefined, &"CREDIT_STAVROS_LEE", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAISUKE_IMAI", undefined, &"CREDIT_KEITH_NED_BELL", undefined, &"CREDIT_STEPHEN_MILLER", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANIEL_WAPNER", undefined, &"CREDIT_KELLY_MERMELSTEIN", undefined, &"CREDIT_STEPHEN_TANG", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANNY_CHAN", undefined, &"CREDIT_KRIS_DEMARTINI", undefined, &"CREDIT_STEVE_ACKRICH", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_BLIZARD", undefined, &"CREDIT_KYLE_AUDICK", undefined, &"CREDIT_STEVE_HOLMES", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_JOHNSON", undefined, &"CREDIT_LAWRENCE_MAI", undefined, &"CREDIT_STEVE_PEARCE", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_KELVIN", undefined, &"CREDIT_LEI_YANG", undefined, &"CREDIT_STEVEN_GIESLER", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_KUO", undefined, &"CREDIT_LISA_LIANG", undefined, &"CREDIT_SUZANNE_WHELPLEY", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_MICKNER", undefined, &"CREDIT_LISA_STONE", undefined, &"CREDIT_TABARI_JEFFRIES", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_SWENSON", undefined, &"CREDIT_LUKE_VERNON", undefined, &"CREDIT_TAEHOON_OH", undefined );
    maps\_credits::_id_000C( &"CREDIT_DEMETRIUS_LEAL", undefined, &"CREDIT_MARC_DAVID", undefined, &"CREDIT_TAM_LY", undefined );
    maps\_credits::_id_000C( &"CREDIT_DERRIC_EADY", undefined, &"CREDIT_MARK_DERIDDER", undefined, &"CREDIT_TAV_SHANDE", undefined );
    maps\_credits::_id_000C( &"CREDIT_DON_VECA", undefined, &"CREDIT_MARK_GANUS", undefined, &"CREDIT_TERRAN_CASEY", undefined );
    maps\_credits::_id_000C( &"CREDIT_DUSTIN_DAVIS", undefined, &"CREDIT_MARK_MCGREE", undefined, &"CREDIT_THEERAPOL_SRISUPHAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ED_HARMER", undefined, &"CREDIT_MARK_RUBIN", undefined, &"CREDIT_TIM_MCGRATH", undefined );
    maps\_credits::_id_000C( &"CREDIT_EDWARD_LEE", undefined, &"CREDIT_MARY_BENITEZ", undefined, &"CREDIT_TOM_DESMARAIS", undefined );
    maps\_credits::_id_000C( &"CREDIT_ERIC_FEINBERG", undefined, &"CREDIT_MATT_EVANS", undefined, &"CREDIT_TOM_FELKER", undefined );
    maps\_credits::_id_000C( &"CREDIT_ERIC_PAVEY", undefined, &"CREDIT_MATT_PROUDFOOT", undefined, &"CREDIT_TOM_WELLS", undefined );
    maps\_credits::_id_000C( &"CREDIT_ERIC_PIERCE", undefined, &"CREDIT_MATTHEW_ABBOTT", undefined, &"CREDIT_TOMMY_CINQUEGRANO", undefined );
    maps\_credits::_id_000C( &"CREDIT_ERIK_STRICKLAND", undefined, &"CREDIT_MATTHEW_BEIN", undefined, &"CREDIT_TOMMY_KEEGAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ERNESTO_GUAMAN", undefined, &"CREDIT_MATTHEW_HAUGEN", undefined, &"CREDIT_TONIE_MADRID", undefined );
    maps\_credits::_id_000C( &"CREDIT_GAURAV_SHELLIKERI", undefined, &"CREDIT_MATTHEW_VITALONE", undefined, &"CREDIT_TRAVELL_MCENTYRE", undefined );
    maps\_credits::_id_000C( &"CREDIT_GENNADY_BABICHENKO", undefined, &"CREDIT_MAZEN_ZAIYA", undefined, &"CREDIT_TRAVIS_NAAS", undefined );
    maps\_credits::_id_000C( &"CREDIT_GEOFFREY_HUDSON", undefined, &"CREDIT_MEGAN_MCDONALD", undefined, &"CREDIT_VELINDA_PELAYO", undefined );
    maps\_credits::_id_000C( &"CREDIT_GEOFFREY_NAHASHON", undefined, &"CREDIT_MICHAEL_BOON", undefined, &"CREDIT_WADE_BRAINERD", undefined );
    maps\_credits::_id_000C( &"CREDIT_GLEN_SCHOFIELD", undefined, &"CREDIT_MICHAEL_CONDREY", undefined, &"CREDIT_WILL_LANE", undefined );
    maps\_credits::_id_000C( &"CREDIT_GRANT_WHITTEN", undefined, &"CREDIT_MICHAEL_DIMEO", undefined, &"CREDIT_YARON_LEVI", undefined );
    maps\_credits::_id_000C( &"CREDIT_GREGORY_REISDORF", undefined, &"CREDIT_MICHAEL_GAUGY", undefined, &"CREDIT_YU_GU", undefined );
    maps\_credits::_id_000C( &"CREDIT_GRETA_GAVRISHEFF", undefined, &"CREDIT_MICHAEL_GEVORKIAN", undefined, &"CREDIT_ZACH_VOLKER", undefined );
    maps\_credits::_id_7456();
}

_id_002A()
{
    maps\_credits::_id_7455( &"CREDIT_ADDITIONAL_DEVELOPMENT_SUPPORT_F" );
    maps\_credits::_id_000C( undefined, undefined, undefined, undefined, undefined, undefined );
    maps\_credits::_id_7455( &"CREDIT_RAVEN_SOFTWARE__TREYARCH_AND_NEV" );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( &"CREDIT_AARON_SAN_FILIPPO", undefined, &"CREDIT_DWIGHT_LUETSCHER", undefined, &"CREDIT_KRISTIN_TODD", undefined );
    maps\_credits::_id_000C( &"CREDIT_ADAM_ROSAS", undefined, &"CREDIT_EMILY_SHERMAN", undefined, &"CREDIT_KRISTINA_ADELMEYER", undefined );
    maps\_credits::_id_000C( &"CREDIT_ADRIAN_SANDOVAL", undefined, &"CREDIT_EMMANUEL_APILADO", undefined, &"CREDIT_KURT_WILLIAMS", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALLEN_WU", undefined, &"CREDIT_ERAN_RICH", undefined, &"CREDIT_KYLE_STEPHENS", undefined );
    maps\_credits::_id_000C( &"CREDIT_AMIT_BHURA", undefined, &"CREDIT_ERIC_BIESSMAN", undefined, &"CREDIT_LINNEA_HARRISON", undefined );
    maps\_credits::_id_000C( &"CREDIT_AMOS_HODGE", undefined, &"CREDIT_ERIC_FELDMAN", undefined, &"CREDIT_LIZ_HUBLEY", undefined );
    maps\_credits::_id_000C( &"CREDIT_AMY_STEVENSON", undefined, &"CREDIT_ERIC_MCDANIEL", undefined, &"CREDIT_LUKA_ROMEL", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANDRE_BEARDSLEY_DUSETTE_", undefined, &"CREDIT_ERIC_MILOTA", undefined, &"CREDIT_MARIO_GIOMBI", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANDRE_TIRAN", undefined, &"CREDIT_ERIC_SCHLAUTMAN", undefined, &"CREDIT_MARK_KILBORN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANDREW_OLSON", undefined, &"CREDIT_ERIC_SCHMIDT", undefined, &"CREDIT_MARK_KORNKVEN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANDY_BAYLESS", undefined, &"CREDIT_ERIC_SPRAY", undefined, &"CREDIT_MARK_LAMIA", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANDY_WARWICK", undefined, &"CREDIT_ERIC_WIDNER", undefined, &"CREDIT_MARK_MAESTAS", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANET_HAMBARSUMIAN", undefined, &"CREDIT_GARETH_DAVIES", undefined, &"CREDIT_MARK_MANTO", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANTHONY_INTERRANTE", undefined, &"CREDIT_GAVIN_GOSLIN", undefined, &"CREDIT_MARKUS_PEEKNA", undefined );
    maps\_credits::_id_000C( &"CREDIT_ARNIE_SWEKEL", undefined, &"CREDIT_GAVIN_LOCKE", undefined, &"CREDIT_MARY_PRESCOTT", undefined );
    maps\_credits::_id_000C( &"CREDIT_BARRY_WHITNEY", undefined, &"CREDIT_GEOFF_D_HILL", undefined, &"CREDIT_MARYANN_KNOKE", undefined );
    maps\_credits::_id_000C( &"CREDIT_BENJAMIN_KOSAR", undefined, &"CREDIT_GIDEON_STOCEK", undefined, &"CREDIT_MATT_PINKSTON", undefined );
    maps\_credits::_id_000C( &"CREDIT_BENJAMIN_OBRIEN", undefined, &"CREDIT_GINA_LOHMAN", undefined, &"CREDIT_MEGAN_PARKER", undefined );
    maps\_credits::_id_000C( &"CREDIT_BLAIR_BITONTI_", undefined, &"CREDIT_GRADEN_MCCOOL", undefined, &"CREDIT_MICHAEL_BARNES", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRANDON_RIGGS", undefined, &"CREDIT_GREGORY_SHIVES", undefined, &"CREDIT_MICHAEL_C_GUMMELT", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRENT_TODA", undefined, &"CREDIT_GUY_SILLIMAN", undefined, &"CREDIT_MICHAEL_EKBERG", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_ANDERSON", undefined, &"CREDIT_IGOR_KRINITSKIY", undefined, &"CREDIT_MICHAEL_GILARDI", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_BARNES", undefined, &"CREDIT_ISAAC_OWENS", undefined, &"CREDIT_MICHAEL_STEWART", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_DOUGLAS", undefined, &"CREDIT_JAMES_BRADFORD", undefined, &"CREDIT_MICHAEL_WINTE", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_HACKBARTH", undefined, &"CREDIT_JAMES_DARGIE", undefined, &"CREDIT_MICHELLE_LAUMANN", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_JOYAL", undefined, &"CREDIT_JAMES_MONROE", undefined, &"CREDIT_MIKE_BUTTON", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_RAFFEL", undefined, &"CREDIT_JAMES_SINGER", undefined, &"CREDIT_MIKE_CURRAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_WHITE", undefined, &"CREDIT_JAMES_SNIDER", undefined, &"CREDIT_MIKE_MADDEN", undefined );
    maps\_credits::_id_000C( &"CREDIT_BROOKE_STAMPFLI", undefined, &"CREDIT_JAMES_WAGNER", undefined, &"CREDIT_MIKE_MAJERNIK", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRYCE_MERCADO", undefined, &"CREDIT_JARED_DICKINSON", undefined, &"CREDIT_MIKE_RENNER", undefined );
    maps\_credits::_id_000C( &"CREDIT_BUMJIN_LEE", undefined, &"CREDIT_JASON_BLUNDELL", undefined, &"CREDIT_MY_WU", undefined );
    maps\_credits::_id_000C( &"CREDIT_CALEB_TOMPLAIT", undefined, &"CREDIT_JASON_HOLT", undefined, &"CREDIT_NATHAN_RAUSCH", undefined );
    maps\_credits::_id_000C( &"CREDIT_CALEB_ZART", undefined, &"CREDIT_JASON_SCHOONOVER", undefined, &"CREDIT_NICHOLAS_STEVENSON", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHAD_R_GROTE", undefined, &"CREDIT_JEFF_DEGENHARDT", undefined, &"CREDIT_NICK_BENNETT", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHARLES_MORROW", undefined, &"CREDIT_JEFF_DISCHLER", undefined, &"CREDIT_NICK_PENWARDEN", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHARLES_WEISS", undefined, &"CREDIT_JEFF_SKUBAL", undefined, &"CREDIT_NICK_TRIFUNOVIC", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHARLIE_BERNSTEIN", undefined, &"CREDIT_JEFF_SWENTY", undefined, &"CREDIT_OMAR_AZIZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRIS_HARTMANN", undefined, &"CREDIT_JEFFREY_NEWQUIST", undefined, &"CREDIT_PAT_DWYER", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRIS_SELF", undefined, &"CREDIT_JEREMIAH_BYCHOWSKI", undefined, &"CREDIT_PATRICK_WILLIAMS", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTOPHER_BEESE", undefined, &"CREDIT_JEREMIAH_SYPULT", undefined, &"CREDIT_PHILLIP_SHEETS", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTOPHER_FOSTER", undefined, &"CREDIT_JEREMY_AGAMATA", undefined, &"CREDIT_RAE_CHEN", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTOPHER_J_LOGAN", undefined, &"CREDIT_JEREMY_BLUMEL", undefined, &"CREDIT_REX_CHAO", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTOPHER_OLSEN", undefined, &"CREDIT_JESS_FEIDT", undefined, &"CREDIT_REYMUNDO_SIERRA", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTOPHER_REED", undefined, &"CREDIT_JI_LI", undefined, &"CREDIT_ROBERT_LOVE", undefined );
    maps\_credits::_id_000C( &"CREDIT_CODY_MITCHELL", undefined, &"CREDIT_JIM_CHRISTOPHER", undefined, &"CREDIT_RONNIE_FAZIO", undefined );
    maps\_credits::_id_000C( &"CREDIT_COLIN_ALTEVEER", undefined, &"CREDIT_JIMMY_ZIELINSKI", undefined, &"CREDIT_ROSS_KAYLOR", undefined );
    maps\_credits::_id_000C( &"CREDIT_COLIN_WHITNEY", undefined, &"CREDIT_JOE_CHIANG", undefined, &"CREDIT_RYAN_BURNETT", undefined );
    maps\_credits::_id_000C( &"CREDIT_CORKY_LEHMKUHL", undefined, &"CREDIT_JOE_KOBERSTEIN", undefined, &"CREDIT_RYAN_BUTTS", undefined );
    maps\_credits::_id_000C( &"CREDIT_CORY_CARANI", undefined, &"CREDIT_JOE_SKUBAL", undefined, &"CREDIT_RYAN_DANZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_CRAIG_HOUSTON", undefined, &"CREDIT_JOEL_MCDONALD", undefined, &"CREDIT_RYAN_HUMMER", undefined );
    maps\_credits::_id_000C( &"CREDIT_DALE_MULCAHY", undefined, &"CREDIT_JOEL_WALSH", undefined, &"CREDIT_RYAN_RIES", undefined );
    maps\_credits::_id_000C( &"CREDIT_DALLAS_MIDDLETON", undefined, &"CREDIT_JOHN_DEHART", undefined, &"CREDIT_SARAH_WANAMAKER", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAMOUN_SHABESTARI", undefined, &"CREDIT_JOHN_SINCLAIR", undefined, &"CREDIT_SCARLETT_SUNG", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAN_BAKER", undefined, &"CREDIT_JON_HAUSE", undefined, &"CREDIT_SEAN_THURLER", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAN_KRAMER", undefined, &"CREDIT_JON_STOLL", undefined, &"CREDIT_SHANE_CALNAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAN_VONDRAK", undefined, &"CREDIT_JON_ZUK", undefined, &"CREDIT_SHAWN_PEEPLES", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANIEL_EDWARDS", undefined, &"CREDIT_JOSEPH_PEASE", undefined, &"CREDIT_SHAWN_WIEDERHOEFT", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANIEL_FETTER", undefined, &"CREDIT_JOSHUA_TERRY", undefined, &"CREDIT_SHORA_FARAHANI", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANIEL_ORZULAK", undefined, &"CREDIT_JUNE_PARK", undefined, &"CREDIT_SIDDHARTH_ACHREKAR", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANIEL_S_MENARD", undefined, &"CREDIT_JUSTIN_NEGRETE", undefined, &"CREDIT_SIMON_PARKINSON", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANNY_DONAHO", undefined, &"CREDIT_JUSTIN_SUPERTY", undefined, &"CREDIT_SPENCER_NIGL", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANNY_SHIN", undefined, &"CREDIT_KATHLEEN_MARTY", undefined, &"CREDIT_STE_CORK", undefined );
    maps\_credits::_id_000C( &"CREDIT_DARREN_BLONDIN", undefined, &"CREDIT_KATHY_BOCK", undefined, &"CREDIT_STEV_KALINOWSKI", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVE_ANTHONY", undefined, &"CREDIT_KEITH_MATEJKA", undefined, &"CREDIT_STEVE_RAFFEL", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVE_COWLING", undefined, &"CREDIT_KEITH_MORTON", undefined, &"CREDIT_STUART_WIEGERT", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVE_CURD", undefined, &"CREDIT_KELSON_RAFFEL", undefined, &"CREDIT_TAB_PATZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVE_KIM", undefined, &"CREDIT_KEVIN_BAIK", undefined, &"CREDIT_TED_THELEN", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_FIFIELD", undefined, &"CREDIT_KEVIN_DREW", undefined, &"CREDIT_TIFFANI_BURKETT", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_GULISANO", undefined, &"CREDIT_KEVIN_KRAEER", undefined, &"CREDIT_TIM_SMILOVITCH", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_HAUPTMAN", undefined, &"CREDIT_KEVIN_LONG", undefined, &"CREDIT_TIM_UTTECH", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_HERNANDEZ", undefined, &"CREDIT_KEVIN_REED", undefined, &"CREDIT_TRAVIS_RAMON", undefined );
    maps\_credits::_id_000C( &"CREDIT_DEAN_SERIO", undefined, &"CREDIT_KEVIN_WORREL", undefined, &"CREDIT_VADIM_NUNIYANTS", undefined );
    maps\_credits::_id_000C( &"CREDIT_DEREK_LARSON", undefined, &"CREDIT_KHALIN_MIKKELSEN", undefined, &"CREDIT_WILL_HUANG", undefined );
    maps\_credits::_id_000C( &"CREDIT_DOM_DROZDZ", undefined, &"CREDIT_KRISTEN_SYCH", undefined, &"CREDIT_WILLIAM_RYAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_DOUG_GUANLAO", undefined, &"CREDIT_KRISTIN_GALLAGHER", undefined, &"CREDIT_YANICK_LEBEL", undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_ORIGINAL_MUSIC_BY", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_BRIAN_TYLER", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_WRITTEN_BY", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_PAUL_HAGGIS", undefined, undefined, undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_WILL_STAPLES", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_VOICE_ACTORS", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( &"CREDIT_BILLY_MURRAY", undefined, &"CREDIT_IDRIS_ELBA", undefined, &"CREDIT_TIMOTHY_OLYPHANT", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRUCE_GREENWOOD", undefined, &"CREDIT_KEVIN_MCKIDD", undefined, &"CREDIT_WILLIAM_FICHTNER", undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_CRAIG_FAIRBRASS", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_ADDITIONAL_VOICE_ACTORS", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( &"CREDIT_ADE_MCCORMACK", undefined, &"CREDIT_EUGENE_LAZAREV", undefined, &"CREDIT_MATTHEW_MERCER", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANNA_GRAVES", undefined, &"CREDIT_GRAHAM_MCTAVISH", undefined, &"CREDIT_MICHAEL_CUDLITZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_AURELIAN_WIIK", undefined, &"CREDIT_HAKEEM_KAE_KAZIM", undefined, &"CREDIT_NIKOLAI_STOILOV", undefined );
    maps\_credits::_id_000C( &"CREDIT_BORIS_KIEVSKY", undefined, &"CREDIT_JAMES_PATRICK_STUART", undefined, &"CREDIT_PASCAL_PERTARDI", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_BLOOM", undefined, &"CREDIT_JB_BLANC", undefined, &"CREDIT_ROBIN_ATKIN_DOWNES", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAN_KASH", undefined, &"CREDIT_JEAN_MICHEL_RICHAUD", undefined, &"CREDIT_ROMAN_VARSHAVSKY", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANIEL_GAMBURG", undefined, &"CREDIT_JEFFREY_PIERCE", undefined, &"CREDIT_SIAKA_HARDING", undefined );
    maps\_credits::_id_000C( &"CREDIT_DARRYL_KURYLO", undefined, &"CREDIT_JOE_CAPPELLETTI", undefined, &"CREDIT_STELIO_SAVANTE", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_AGRANOV", undefined, &"CREDIT_JULIA_AREM", undefined, &"CREDIT_TIM_GRIFFIN", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_ANTHONY_PIZZUTO", undefined, &"CREDIT_JULIAN_STONE", undefined, &"CREDIT_TONY_CURRAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_DEPLANEAUX_WILLS", undefined, &"CREDIT_KAI_WULF", undefined, &"CREDIT_TROY_BAKER", undefined );
    maps\_credits::_id_000C( &"CREDIT_EDWARD_SHKOLNIKOV", undefined, &"CREDIT_LEX_QUARTERMAN", undefined, &"CREDIT_VALERIE_AREM", undefined );
    maps\_credits::_id_000C( &"CREDIT_EMERSON_BROOKS", undefined, &"CREDIT_LIAM_OBRIEN", undefined, &"CREDIT_YURI_LOWENTHAL", undefined );
    maps\_credits::_id_000C( &"CREDIT_EUGENE_ALPERS", undefined, &"CREDIT_MARK_IVANIR", undefined, &"CREDIT_ZACH_HANKS", undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_VOICE_TALENT_DIRECTION", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_KEITH_AREM_", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_PCB_PRODUCTIONS", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( &"CREDIT_AARON_GALLANT", undefined, &"CREDIT_MATT_LEMBERGER", undefined, &"CREDIT_VALERIE_AREM", undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_MOTION_CAPTURE_ACTORS", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( &"CREDIT_ALLEN_JO", undefined, &"CREDIT_LATEEF_CROWDER", undefined, &"CREDIT_SAM_LOOC", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANNY_HERNANDEZ", undefined, &"CREDIT_LIN_OEDING", undefined, &"CREDIT_YOSHIO_IZUKA", undefined );
    maps\_credits::_id_000C( &"CREDIT_DON_THEERATHADA", undefined, &"CREDIT_NICK_BENSEMAN", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_SPOV", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( &"CREDIT_ALLEN_LEITCH", undefined, &"CREDIT_JAMES_BROCKLEBANK", undefined, &"CREDIT_RACHEL_CHU", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANDREA_BRAGA", undefined, &"CREDIT_JANE_HARGREAVES", undefined, &"CREDIT_RHI_LEADBEATER", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRAD_COOMBER", undefined, &"CREDIT_JULIO_DEAN", undefined, &"CREDIT_RYAN_HAYS", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRIS_BOYLE", undefined, &"CREDIT_KUO_CHIEH_CHUNG", undefined, &"CREDIT_SAM_KERRIDGE", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAN_HIGGOTT", undefined, &"CREDIT_LUIS_RIBERO", undefined, &"CREDIT_SHAUN_YUE", undefined );
    maps\_credits::_id_000C( &"CREDIT_DYLAN_WYNNE", undefined, &"CREDIT_MATT_TSANG", undefined, &"CREDIT_SHAWN_SOBERS", undefined );
    maps\_credits::_id_000C( &"CREDIT_EVAN_BOEHM", undefined, &"CREDIT_MILES_CHRISTENSEN", undefined, &"CREDIT_VINCENT_KANE", undefined );
    maps\_credits::_id_000C( &"CREDIT_HAZEL_BAIRD", undefined, &"CREDIT_PAUL_HUNT", undefined, &"CREDIT_YUGEN_BLAKE", undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_MILITARY_CONSULTANTS", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( &"CREDIT_DALTON_FURY", undefined, &"CREDIT_EMILIO_CUESTA", undefined, &"CREDIT_KEVIN_COLLINS", undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_HANK_KEIRSEY", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_ADDITIONAL_SOUND_DESIGN___AUDIO_", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( &"CREDIT_ADAM_BOYD", undefined, &"CREDIT_EARBASH_AUDIO__INC", undefined, &"CREDIT_WABI_SABI_SOUND", undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_DEVELOPMENT_BABIES", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( &"CREDIT_ALEXANDER_EADY", undefined, &"CREDIT_EZRA_BLUMEL", undefined, &"CREDIT_MADELINE_MORTON", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANNA_MARTY", undefined, &"CREDIT_GRETA_SIDEY", undefined, &"CREDIT_MARISSA_OLSON", undefined );
    maps\_credits::_id_000C( &"CREDIT_ARIANA_SCHMIDT", undefined, &"CREDIT_ISAAC_MATEJKA", undefined, &"CREDIT_MICAH_DEBOLT", undefined );
    maps\_credits::_id_000C( &"CREDIT_ASHTON_CONDREY", undefined, &"CREDIT_ISABELLA_COUCOULES", undefined, &"CREDIT_MILES_RENNER", undefined );
    maps\_credits::_id_000C( &"CREDIT_CALEB_AND_ZACHARY_SILVERS", undefined, &"CREDIT_JIRAYUT_SRISUPHAN", undefined, &"CREDIT_MILO_KILBORN", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHASE_VOLKER", undefined, &"CREDIT_KAITLYN_RIES", undefined, &"CREDIT_NAIMA_MAI", undefined );
    maps\_credits::_id_000C( &"CREDIT_CONNOR_VUONG", undefined, &"CREDIT_LEILA_DENNY", undefined, &"CREDIT_NEVIN_KAR", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANIEL_WEST", undefined, &"CREDIT_LEVI_DAVIS", undefined, &"CREDIT_PENELOPE_BOWLING", undefined );
    maps\_credits::_id_000C( &"CREDIT_ELSIE_BOON", undefined, &"CREDIT_LIAM_DYE", undefined, undefined, undefined );
    maps\_credits::_id_7456();
}

_id_002B()
{
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_SPECIAL_THANKS", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( &"CREDIT_87ELEVEN", undefined, &"CREDIT_JAMES_MCDONALD", undefined, &"CREDIT_PHILIP_EARL", undefined );
    maps\_credits::_id_000C( &"CREDIT_ABBY_ALVARADO", undefined, &"CREDIT_JAMES_SPEIGHT", undefined, &"CREDIT_PMK_BNC", undefined );
    maps\_credits::_id_000C( &"CREDIT_ADVANCED_ARMAMENT_CORP", undefined, &"CREDIT_JASON_ADES", undefined, &"CREDIT_RACHEL_LEVINE", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANDREW_HOFFACKER", undefined, &"CREDIT_JASON_HARRIS", undefined, &"CREDIT_RACHEL_OVERTON", undefined );
    maps\_credits::_id_000C( &"CREDIT_ARCADIA_POLICE_DEPARTMENT", undefined, &"CREDIT_JASON_POSADA", undefined, &"CREDIT_REMINGTON", undefined );
    maps\_credits::_id_000C( &"CREDIT_BARBARA_SCHOFIELD", undefined, &"CREDIT_JEANE_WONG", undefined, &"CREDIT_RICARDO_ROMERO", undefined );
    maps\_credits::_id_000C( &"CREDIT_BARRETT", undefined, &"CREDIT_JEREMIAH_MAZA", undefined, &"CREDIT_ROB_TROY", undefined );
    maps\_credits::_id_000C( &"CREDIT_BARRETT_RIFLES", undefined, &"CREDIT_JOEL_JEWETT", undefined, &"CREDIT_RODRIGO_MORA", undefined );
    maps\_credits::_id_000C( &"CREDIT_BOBBY_KOTICK", undefined, &"CREDIT_JOEL_TAUBEL", undefined, &"CREDIT_SCOTT_BLAIR", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRAD_JAKEMAN", undefined, &"CREDIT_JOHN_PAUL_FASAL", undefined, &"CREDIT_SCOTT_CARSON", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRENT_MCDONALD", undefined, &"CREDIT_KATIE_PURCELL", undefined, &"CREDIT_SEA_SNIPERS", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_ABRAMS", undefined, &"CREDIT_KEVIN_SMITH", undefined, &"CREDIT_SHADOWS_IN_DARKNESS", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHETAN_DESAI", undefined, &"CREDIT_LARRY_ZANOFF", undefined, &"CREDIT_SIMON_DUQUET_GALARNEAU", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTINA_FEINBERG_", undefined, &"CREDIT_LEUPOLD___STEVENS__INC", undefined, &"CREDIT_STEFAN_LULUDES", undefined );
    maps\_credits::_id_000C( &"CREDIT_COLT_DEFENSE__LLC", undefined, &"CREDIT_LILIANA_CONDREY", undefined, &"CREDIT_STEP_3", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAKOTA_VOLKER", undefined, &"CREDIT_MAGNUM_RESEARCH_INC", undefined, &"CREDIT_STEVE_YOUNG", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAN_WINTERS", undefined, &"CREDIT_MAPMONKEYS_", undefined, &"CREDIT_SUZANNE_TODD", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANIEL_SUAREZ", undefined, &"CREDIT_MARC_WILLIAMS", undefined, &"CREDIT_TEAM_TODD", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVE_STOHL", undefined, &"CREDIT_MARIA_GONZALEZ", undefined, &"CREDIT_THE_ANT_FARM", undefined );
    maps\_credits::_id_000C( &"CREDIT_DEGROAT_TACTICAL_ARMAMENTS", undefined, &"CREDIT_MARYANNE_LATAIF", undefined, &"CREDIT_THOMAS_TIPPL", undefined );
    maps\_credits::_id_000C( &"CREDIT_DESERT_EAGLE", undefined, &"CREDIT_MICHAEL_SPORTOUCH", undefined, &"CREDIT_TIM_MCDONAGH", undefined );
    maps\_credits::_id_000C( &"CREDIT_ERIC_HIRSHBERG", undefined, &"CREDIT_NOAH_KIRCHER_ALLEN", undefined, &"CREDIT_TODD_MUELLER", undefined );
    maps\_credits::_id_000C( &"CREDIT_FACEBOOK", undefined, &"CREDIT_NURIA_ANDRES", undefined, &"CREDIT_TONY_HSU", undefined );
    maps\_credits::_id_000C( &"CREDIT_GRAHAM_HAGMAIER", undefined, &"CREDIT_OPS_CORE", undefined, &"CREDIT_VICTOR_LOPEZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_GREN_ATHERTON", undefined, &"CREDIT_PAUL_CALVERT", undefined, &"CREDIT_WES_THOMPSONS_RIFLE_RANGE", undefined );
    maps\_credits::_id_000C( &"CREDIT_INDEPENDENT_STUDIO_SERVICES", undefined, &"CREDIT_PETER_SANTHA", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_ON_BEHALF_OF_EVERYONE_INVOLVED_I", undefined, undefined, undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_THANK_OUR_FAMILIES_AND_LOVED_ONE", undefined, undefined, undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_YOU_GAVE_US_THE_STRENGTH_TO_REAC", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_7456();
}

_id_002C()
{
    maps\_credits::_id_7455( &"CREDIT_ACTIVISION_PUBLISHING" );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( &"CREDIT_PRODUCTION_MANAGEMENT_", "subtitle", &"CREDIT_BEACHHEAD_STUDIO", "subtitle", &"CREDIT_ACTIVISION_STUDIO_CENTRAL", "subtitle" );
    maps\_credits::_id_000C( &"CREDIT_ADRIENNE_ARRASMITH", undefined, &"CREDIT_CANDICE_CLARK", undefined, &"CREDIT_ADAM_FOSHKO", undefined );
    maps\_credits::_id_000C( &"CREDIT_BEN_BRINKMAN", undefined, &"CREDIT_CHACKO_SONNY", undefined, &"CREDIT_ALESSANDRO_TENTO", undefined );
    maps\_credits::_id_000C( &"CREDIT_DEREK_RACCA", undefined, &"CREDIT_CHRIS_CHERNOFF", undefined, &"CREDIT_ALEXANDRE_DEBROUSSE", undefined );
    maps\_credits::_id_000C( &"CREDIT_JAMES_LODATO", undefined, &"CREDIT_CHRIS_WILSON", undefined, &"CREDIT_ANDREW_LAU", undefined );
    maps\_credits::_id_000C( &"CREDIT_JOHN_BANAYAN", undefined, &"CREDIT_CHRISTINA_CHAN", undefined, &"CREDIT_ANIMATION_VERTIGO", undefined );
    maps\_credits::_id_000C( &"CREDIT_MARCUS_IREMONGER", undefined, &"CREDIT_DOUG_MUIR", undefined, &"CREDIT_BEN_WATSON", undefined );
    maps\_credits::_id_000C( &"CREDIT_MIKE_MEJIA", undefined, &"CREDIT_EARTH_WARREN", undefined, &"CREDIT_BERNARDO_ANTONIAZZI", undefined );
    maps\_credits::_id_000C( &"CREDIT_SHANNON_WAHL", undefined, &"CREDIT_ERIC_WU", undefined, &"CREDIT_BILL_PETRO", undefined );
    maps\_credits::_id_000C( &"CREDIT_VINCENT_FENNEL", undefined, &"CREDIT_ERIK_MELEN", undefined, &"CREDIT_BRENDAN_LUCHEN", undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_JENNIFER_PUNO", undefined, &"CREDIT_CARL_SCHNURR", undefined );
    maps\_credits::_id_000C( &"CREDIT_PRODUCT_MANAGEMENT___PR", "subtitle", &"CREDIT_KYLE_BLACKMAN", undefined, &"CREDIT_CHRIS_CHADA", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALAND_FAILDE", undefined, &"CREDIT_MUNIA_MORRIS", undefined, &"CREDIT_CHRIS_CHOWDHURY", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALEX_GOMEZ", undefined, &"CREDIT_NATHAN_OAKES", undefined, &"CREDIT_CHRIS_CODDING", undefined );
    maps\_credits::_id_000C( &"CREDIT_BIANCA_HARZBECKER", undefined, &"CREDIT_NOAH_HELLER", undefined, &"CREDIT_CHRIS_ELLIS", undefined );
    maps\_credits::_id_000C( &"CREDIT_BYRON_BEEDE", undefined, &"CREDIT_ROBERT_TAI", undefined, &"CREDIT_CHRISTINA_ACEVES", undefined );
    maps\_credits::_id_000C( &"CREDIT_JOHN_RAFACZ", undefined, &"CREDIT_SAM_FU", undefined, &"CREDIT_CORY_SANFORD", undefined );
    maps\_credits::_id_000C( &"CREDIT_JOSHUA_SELINGER", undefined, &"CREDIT_SHERBAN_DRULEA", undefined, &"CREDIT_DAVID_VILLATORO", undefined );
    maps\_credits::_id_000C( &"CREDIT_KYLE_WALKER", undefined, &"CREDIT_TED_ANGELILLI", undefined, &"CREDIT_EVAN_BUTTON", undefined );
    maps\_credits::_id_000C( &"CREDIT_MIKE_MANTARRO", undefined, &"CREDIT_TODD_GROTEN", undefined, &"CREDIT_HEATHER_POLUBINSKI", undefined );
    maps\_credits::_id_000C( &"CREDIT_MONICA_PONTRELLI", undefined, undefined, undefined, &"CREDIT_JEFFREY_CHEN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ROB_KOSTICH", undefined, &"CREDIT_ADDITIONAL_CALL_OF_DUTY_ELITE_DE", "subtitle", &"CREDIT_JENNIFER_VELAZQUEZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_ROBERT_TAYLOR", undefined, &"CREDIT_AARON_GIBSON", undefined, &"CREDIT_JEREMY_DUNN", undefined );
    maps\_credits::_id_000C( &"CREDIT_TYLER_MICHAUD", undefined, &"CREDIT_ALAN_FUNG", undefined, &"CREDIT_JOHAN_KOHLER", undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_ANTONIUS_LIN", undefined, &"CREDIT_LIM_HUR", undefined );
    maps\_credits::_id_000C( &"CREDIT_DEMONWARE", "subtitle", &"CREDIT_BILL_KELLER", undefined, &"CREDIT_MATT_KARNES", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALEX_COUTURE_BEIL", undefined, &"CREDIT_CHRISTI_NISHIYAMA", undefined, &"CREDIT_MICHAEL_JANTZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAMIEN_MARSHALL", undefined, &"CREDIT_DANN_PETTY", undefined, &"CREDIT_MICHAEL_RESTIFO", undefined );
    maps\_credits::_id_000C( &"CREDIT_TENDAYI_MAWUSHE", undefined, &"CREDIT_ELLIOT_KEMBER", undefined, &"CREDIT_MIKE_WARD", undefined );
    maps\_credits::_id_000C( &"CREDIT_ADRIAN_OLIVER", undefined, &"CREDIT_HECTOR_SIMPSON", undefined, &"CREDIT_MU_YONG_WALTER_KIM", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALEX_BOYD", undefined, &"CREDIT_JASON_GORDON", undefined, &"CREDIT_NICK_OTTO", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALLEN_KUMKA", undefined, &"CREDIT_JESPER_GARNEIJ", undefined, &"CREDIT_NOEL_VEGA", undefined );
    maps\_credits::_id_000C( &"CREDIT_AMY_SMITH", undefined, &"CREDIT_JOHN_CARROLL", undefined, &"CREDIT_PAUL_EDELSTEIN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ARTHUR_GREEN", undefined, &"CREDIT_MARKE_HALLOWELL", undefined, &"CREDIT_PHIL_KECK", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRENDAN_DILLON", undefined, &"CREDIT_NICOLA_MARZOLLA", undefined, &"CREDIT_RAY_KOWALEWSKI", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRENDAN_FIELDS", undefined, &"CREDIT_PIERRE_SCHIRO", undefined, &"CREDIT_RICCARD_LINDE", undefined );
    maps\_credits::_id_000C( &"CREDIT_CATHERINE_MCCARTHY", undefined, &"CREDIT_RYDER_ROSS", undefined, &"CREDIT_RYAN_FORD", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHARLIE_VON_METZRADT", undefined, &"CREDIT_SEAN_BERRY", undefined, &"CREDIT_SASHA_REBECCA_GROSS", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTOPHER_MCKNIGHT", undefined, &"CREDIT_STAN_LIN", undefined, &"CREDIT_SEAN_HEFFRON", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTOPHER_MUELLER", undefined, &"CREDIT_STUART_BROWN", undefined, &"CREDIT_SHAUN_PICCININO", undefined );
    maps\_credits::_id_000C( &"CREDIT_CONNOR_MAYER", undefined, &"CREDIT_YIQI_MENG", undefined, &"CREDIT_STEPHEN_WANG", undefined );
    maps\_credits::_id_000C( &"CREDIT_CRAIG_MCINNES", undefined, undefined, undefined, &"CREDIT_VINCENT_EDWARDS", undefined );
    maps\_credits::_id_000C( &"CREDIT_DARA_PRICE", undefined, &"CREDIT_TALENT__AUDIO_AND_MUSIC", "subtitle", undefined, undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_BRENNAN", undefined, &"CREDIT_BLAIR_BITONTI", undefined, &"CREDIT_OPERATIONS___STUDIO_PLANNING", "subtitle" );
    maps\_credits::_id_000C( &"CREDIT_DAVID_CAHILL", undefined, &"CREDIT_BRANDON_YOUNG", undefined, &"CREDIT_ANTHONY_TING", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_FALLOON", undefined, &"CREDIT_IVY_ISENBERG", undefined, &"CREDIT_BEN_SZETO", undefined );
    maps\_credits::_id_000C( &"CREDIT_EDWARD_BAKER", undefined, &"CREDIT_MARCHELE_HARDIN", undefined, &"CREDIT_BRANDON_SCHEBLER", undefined );
    maps\_credits::_id_000C( &"CREDIT_EOGHAN_GAFFNEY", undefined, &"CREDIT_NOAH_SARID", undefined, &"CREDIT_CHRISTOPHER_REINHART", undefined );
    maps\_credits::_id_000C( &"CREDIT_FRED_SHIH", undefined, &"CREDIT_SCOTT_MCDANIEL_", undefined, &"CREDIT_CLINTON_ALLEN", undefined );
    maps\_credits::_id_000C( &"CREDIT_GARY_QUAN", undefined, &"CREDIT_SERGIO_PIMENTEL", undefined, &"CREDIT_CODDY_JOHNSON", undefined );
    maps\_credits::_id_000C( &"CREDIT_GORDON_SCHNEIDER", undefined, &"CREDIT_STEFANI_JONES", undefined, &"CREDIT_DAVID_ASADOURIAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_GRAEME_HUMPHRIES", undefined, &"CREDIT_TIM_RILEY", undefined, &"CREDIT_DEREK_BROWN", undefined );
    maps\_credits::_id_000C( &"CREDIT_GRAHAM_CAMPBELL", undefined, &"CREDIT_TREVOR_BRESAW", undefined, &"CREDIT_EVAN_SROKA", undefined );
    maps\_credits::_id_000C( &"CREDIT_HUGH_NOWLAN", undefined, undefined, undefined, &"CREDIT_JASON_JORDAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_JAKE_XU", undefined, &"CREDIT_PRODUCTION_SERVICES___EUROPE", "subtitle", &"CREDIT_JENNIFER_HARE", undefined );
    maps\_credits::_id_000C( &"CREDIT_JASON_HAGAO_WEI", undefined, &"CREDIT_BARRY_KEHOE", undefined, &"CREDIT_JENNIFER_SULLIVAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_JOHN_HAMILL", undefined, &"CREDIT_BERNARD_COURTNEY", undefined, &"CREDIT_JOI_TANNER", undefined );
    maps\_credits::_id_000C( &"CREDIT_JOHN_KIRK", undefined, &"CREDIT_DIANA_XIFRE_DE_LA_PRADA", undefined, &"CREDIT_JON_LOMIBAO", undefined );
    maps\_credits::_id_000C( &"CREDIT_JONATHAN_FRAWLEY", undefined, &"CREDIT_EROS_CASTALDI", undefined, &"CREDIT_JOSH_MORRIS", undefined );
    maps\_credits::_id_000C( &"CREDIT_LANCE_LAURSEN", undefined, &"CREDIT_ESTHER_REIMANN", undefined, &"CREDIT_KEVIN_SANDLOW", undefined );
    maps\_credits::_id_000C( &"CREDIT_LEE_CASH", undefined, &"CREDIT_FERGUS_LINDSAY", undefined, &"CREDIT_MARCUS_SANFORD", undefined );
    maps\_credits::_id_000C( &"CREDIT_LUKE_BURDEN", undefined, &"CREDIT_FINTAN_HERLIHY", undefined, &"CREDIT_MELISSA_WESSELY", undefined );
    maps\_credits::_id_000C( &"CREDIT_MALCOLM_DOWSE", undefined, &"CREDIT_FIONA_EBBS", undefined, &"CREDIT_MIKE_HUNAU", undefined );
    maps\_credits::_id_000C( &"CREDIT_MARTIN_CLARKE", undefined, &"CREDIT_GABRIEL_MORISSEAU", undefined, &"CREDIT_ROB_LEBEAU", undefined );
    maps\_credits::_id_000C( &"CREDIT_MATTHEW_EDWARDS", undefined, &"CREDIT_GUILLAUME_JAZDONCZYK", undefined, &"CREDIT_SAMUEL_PETERSON", undefined );
    maps\_credits::_id_000C( &"CREDIT_MICHAEL_COLLINS", undefined, &"CREDIT_ILDEFONSO_RANCHAL", undefined, &"CREDIT_SHEILAH_BROOKS", undefined );
    maps\_credits::_id_000C( &"CREDIT_MIROSLAW_BARAN", undefined, &"CREDIT_IVAR_ROCHA_ARIAS", undefined, &"CREDIT_STUART_ROCH", undefined );
    maps\_credits::_id_000C( &"CREDIT_MORGAN_BRICKLEY", undefined, &"CREDIT_JACK_OHARA", undefined, &"CREDIT_TODD_PRUYN", undefined );
    maps\_credits::_id_000C( &"CREDIT_NADIA_ALRAMLI", undefined, &"CREDIT_JEREMY_LEVI", undefined, undefined, undefined );
    maps\_credits::_id_000C( &"CREDIT_NICOLA_COLLERAN", undefined, &"CREDIT_LAURA_COCCO", undefined, &"CREDIT_CUSTOMER_SUPPORT", "subtitle" );
    maps\_credits::_id_000C( &"CREDIT_PADRAIC_HALLINAN", undefined, &"CREDIT_LINDA_ZEMMLER", undefined, &"CREDIT_BERNARD_ABELLADA", undefined );
    maps\_credits::_id_000C( &"CREDIT_PAUL_FROESE", undefined, &"CREDIT_LUIS_HERNANDEZ_DALMAU", undefined, &"CREDIT_BRIAN_CARLSON", undefined );
    maps\_credits::_id_000C( &"CREDIT_RICK_BARZILLI", undefined, &"CREDIT_MARCO_FRANGELLA", undefined, &"CREDIT_CHRISTIANE_BRAND", undefined );
    maps\_credits::_id_000C( &"CREDIT_ROB_MCADOO", undefined, &"CREDIT_NURIA_SANCHEZ", undefined, &"CREDIT_DOV_CARSON", undefined );
    maps\_credits::_id_000C( &"CREDIT_ROMAN_LISAGOR", undefined, &"CREDIT_PAOLA_PALERMO", undefined, &"CREDIT_GUILLERMO_HERNANDEZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_RUAIDHR__POWER", undefined, &"CREDIT_PAULA_DEL_VALLE", undefined, &"CREDIT_JEFF_WALSH", undefined );
    maps\_credits::_id_000C( &"CREDIT_RUY_ASAN", undefined, &"CREDIT_RAFAEL_SANTOS", undefined, &"CREDIT_KIRK_MCNESBY", undefined );
    maps\_credits::_id_000C( &"CREDIT_SEAN_ODONNELL", undefined, &"CREDIT_SASCHA_WAGNER", undefined, &"CREDIT_KRIS_SNIDER_", undefined );
    maps\_credits::_id_000C( &"CREDIT_SEAN_OSULLIVAN", undefined, &"CREDIT_SHANE_MCNAMEE", undefined, &"CREDIT_MIKE_DANGERFIELD", undefined );
    maps\_credits::_id_000C( &"CREDIT_SINEAD_DEVEREAUX", undefined, &"CREDIT_SYLVAIN_VILLEDARY", undefined, &"CREDIT_PHILIP_CHUNG", undefined );
    maps\_credits::_id_000C( &"CREDIT_STEFAN_TJARKS", undefined, &"CREDIT_THOMAS_DORLEANS", undefined, &"CREDIT_RANDOLPH_DAMORE_", undefined );
    maps\_credits::_id_000C( &"CREDIT_STEFFEN_HIGEL", undefined, &"CREDIT_THOMAS_LOPEZ", undefined, &"CREDIT_RUSSELL_JOHNSON", undefined );
    maps\_credits::_id_000C( &"CREDIT_STEPHANIE_CATES", undefined, &"CREDIT_TODD_LAMBERT", undefined, &"CREDIT_SAM_AKIKI", undefined );
    maps\_credits::_id_000C( &"CREDIT_STEPHANIE_DEAN", undefined, &"CREDIT_VINCENZO_FERRARA", undefined, &"CREDIT_SJOERD_VAN_DEN_BERG", undefined );
    maps\_credits::_id_000C( &"CREDIT_TENG_SONG", undefined, undefined, undefined, &"CREDIT_TIM_RONDEAU", undefined );
    maps\_credits::_id_000C( &"CREDIT_TILMAN_SCHAEFER", undefined, &"CREDIT_MARKETING_COMMUNICATIONS", "subtitle", undefined, undefined );
    maps\_credits::_id_000C( &"CREDIT_TIM_CZERNIAK", undefined, &"CREDIT_CHRISTY_BUENA", undefined, &"CREDIT_BUSINESS___LEGAL_AFFAIRS", "subtitle" );
    maps\_credits::_id_000C( &"CREDIT_TONY_KELLY", undefined, &"CREDIT_JASON_TAYLOR", undefined, &"CREDIT_CHRIS_WALTHER", undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_JEFF_GOODWIN", undefined, &"CREDIT_KAP_KANG", undefined );
    maps\_credits::_id_000C( &"CREDIT_STUDIO___ACTIVISION_SHANGHAI", "subtitle", &"CREDIT_JILL_BARRY", undefined, &"CREDIT_KATE_OGOSTA", undefined );
    maps\_credits::_id_000C( &"CREDIT_AIMY_WENG_YANLIN", undefined, &"CREDIT_KAREN_STARR", undefined, &"CREDIT_KELLY_SCHWARM", undefined );
    maps\_credits::_id_000C( &"CREDIT_BAIRN_YU_YONGBO", undefined, &"CREDIT_MIKE_SWIONTKOWSKI", undefined, &"CREDIT_MARY_TUCK", undefined );
    maps\_credits::_id_000C( &"CREDIT_KIMI_XU_JIAN_JUN", undefined, &"CREDIT_ROCHELLE_WEBB", undefined, &"CREDIT_TRAVIS_STANSBURY", undefined );
    maps\_credits::_id_000C( &"CREDIT_KYLE_CHENG_HAO", undefined, &"CREDIT_ROSANNE_HONG", undefined, &"CREDIT_TERRI_DURHAM", undefined );
    maps\_credits::_id_000C( &"CREDIT_SABRINA_XIA_JINLEI", undefined, &"CREDIT_SUSAN_HALLOCK", undefined, &"CREDIT_PHIL_TERZIAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_VICKY_SUN_WEIYI", undefined, &"CREDIT_TODD_HARVEY", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_QUALITY_ASSURANCE", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( &"CREDIT_AARON_GARNER", undefined, &"CREDIT_GUILLAUME_MORIN", undefined, &"CREDIT_MATHEW_ABRAMS", undefined );
    maps\_credits::_id_000C( &"CREDIT_ABEL_DONTIGNY_PATRY", undefined, &"CREDIT_GUILLAUME_ROCHAT", undefined, &"CREDIT_MATHEW_CARPENTER", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALBERT_MILLSPAUGH", undefined, &"CREDIT_GUILLAUME_WEBBER", undefined, &"CREDIT_MATHIEU_BIBEAU_MORIN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALBERT_YAO", undefined, &"CREDIT_INDRA_YEE", undefined, &"CREDIT_MATHIEU_GOSSELIN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALEX_MERCIER", undefined, &"CREDIT_ISABELLE_BOUCHARD", undefined, &"CREDIT_MATT_MCCLURE", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALEXANDER_THORNE", undefined, &"CREDIT_ISMA_L_GENDREAU", undefined, &"CREDIT_MATT_WELLMAN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALEXANDRE_B_RUB_", undefined, &"CREDIT_JACK_MICHAEL_ROWE", undefined, &"CREDIT_MATTHEW_DAVIS", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALEXANDRE_GIROUARD", undefined, &"CREDIT_JACOB_DISSMORE", undefined, &"CREDIT_MAXIME_BOUCHER_ALLARD", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALEXIS_DROLET", undefined, &"CREDIT_JAN_NAVARRO", undefined, &"CREDIT_MAXIME_DE_VARENNES", undefined );
    maps\_credits::_id_000C( &"CREDIT_ALYSSA_DELHOTAL", undefined, &"CREDIT_JASON_BEAULIEU", undefined, &"CREDIT_MAXIME_DROUIN", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANDRE_GRACIAS", undefined, &"CREDIT_JASON_GAGN_", undefined, &"CREDIT_MAXIME_PICARD", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANGEL_PEREZ", undefined, &"CREDIT_JASON_GARZA", undefined, &"CREDIT_MAXIME_TRUDEL", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANTOINE_L_PINE", undefined, &"CREDIT_JASON_WONG", undefined, &"CREDIT_MICHAEL_CRUZ", undefined );
    maps\_credits::_id_000C( &"CREDIT_ANTOINE_LEROUX", undefined, &"CREDIT_JEAN_CHRISTOPHE_GOYETTE", undefined, &"CREDIT_MIGUEL_AREVALO", undefined );
    maps\_credits::_id_000C( &"CREDIT_ARI_EPSTEIN", undefined, &"CREDIT_JEAN_DAVID_PROULX_MARCOUX", undefined, &"CREDIT_MIKE_RAMEY", undefined );
    maps\_credits::_id_000C( &"CREDIT_AUDREY_LAGANI_RE", undefined, &"CREDIT_JEAN_FRAN_OIS_BOUTIN", undefined, &"CREDIT_MOSHE_MOADEB", undefined );
    maps\_credits::_id_000C( &"CREDIT_AXEL_AVILES", undefined, &"CREDIT_JEAN_FRAN_OIS_GIGU_RE", undefined, &"CREDIT_NICHOLAS_BLANCHARD", undefined );
    maps\_credits::_id_000C( &"CREDIT_AXEL_BELIVEAU", undefined, &"CREDIT_JEAN_FRAN_OIS_LE_HOUILLIER", undefined, &"CREDIT_NICOLAS_BOURGAULT", undefined );
    maps\_credits::_id_000C( &"CREDIT_BEN_JONES", undefined, &"CREDIT_JEAN_PHILIPE_BOURGOIN", undefined, &"CREDIT_NICOLAS_M_CAREAU", undefined );
    maps\_credits::_id_000C( &"CREDIT_BENJAMIN_SOLHEIM", undefined, &"CREDIT_JEAN_PHILIPPE_BUJOLD_BOUTIN", undefined, &"CREDIT_NICOLAS_MORIN", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRAD_SAAVEDRA", undefined, &"CREDIT_JEAN_PHILIPPE_SAUCIER", undefined, &"CREDIT_NICOLAS_VERRET", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_BENSI", undefined, &"CREDIT_JEFF_ROPER", undefined, &"CREDIT_NOBERT_DION_TRUDEL", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_CUTTS", undefined, &"CREDIT_JEFFREY_GOOD", undefined, &"CREDIT_PASCAL_THIBAULT_LAROUCHE", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRIAN_MARTIN", undefined, &"CREDIT_JEREMY_RICHARDS", undefined, &"CREDIT_PATRICK_LACHARIT_", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRITIAN_TAYLOR", undefined, &"CREDIT_JEREMY_SHORTELL", undefined, &"CREDIT_PAUL_TANIGUCHI", undefined );
    maps\_credits::_id_000C( &"CREDIT_BRYAN_CHICE", undefined, &"CREDIT_J_R_ME_LEMIEUX_TRUCHON", undefined, &"CREDIT_PEDRO_AGUILAR", undefined );
    maps\_credits::_id_000C( &"CREDIT_C_DRICK_LEMAY", undefined, &"CREDIT_JO_L_DENIS_SHEEHY", undefined, &"CREDIT_PETER_ELSLEY", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHAD_SCHMIDT", undefined, &"CREDIT_JOEL_ESPANA", undefined, &"CREDIT_PHILIPPE_MAYRAND", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTIAN_BAPTISTE", undefined, &"CREDIT_JOHN_ROSSER", undefined, &"CREDIT_PIER_LUC_MILHOMME", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTIAN_LIARD", undefined, &"CREDIT_JOHNNY_KIM", undefined, &"CREDIT_PIER_LUC_POULIN", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTIAN_M_NARD", undefined, &"CREDIT_JON_AN", undefined, &"CREDIT_PIERRE_MOREAU", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTIAN_TINCHER", undefined, &"CREDIT_JONATHAN_BUTCHER", undefined, &"CREDIT_PIERRE_LUC_BUHLER", undefined );
    maps\_credits::_id_000C( &"CREDIT_CHRISTOPHER_D_WILSON", undefined, &"CREDIT_JONATHAN_LAJOIE", undefined, &"CREDIT_PIERRE_LUC_VIENS_", undefined );
    maps\_credits::_id_000C( &"CREDIT_CLIFF_HOOPER", undefined, &"CREDIT_JONATHAN_PICH_", undefined, &"CREDIT_RICHARD_TOM", undefined );
    maps\_credits::_id_000C( &"CREDIT_COLIN_KAWAKAMI", undefined, &"CREDIT_JORDANE_GAGNON", undefined, &"CREDIT_RYAN_TRONDSEN", undefined );
    maps\_credits::_id_000C( &"CREDIT_COLIN_MCBAIN", undefined, &"CREDIT_JOSE_VEGA", undefined, &"CREDIT_SCOTT_BORAKOVE", undefined );
    maps\_credits::_id_000C( &"CREDIT_COREY_ROGERS", undefined, &"CREDIT_JOS_E_LABOISSONNI_RE", undefined, &"CREDIT_SCOTT_SMITH", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANIEL_L_NICHOLS", undefined, &"CREDIT_JOSEPH_UTLEY", undefined, &"CREDIT_S_BASTIEN_AUBUT", undefined );
    maps\_credits::_id_000C( &"CREDIT_DANY_PAQUET", undefined, &"CREDIT_JOSIANNE_PELLETIER", undefined, &"CREDIT_S_BASTIEN_DUSSEAULT", undefined );
    maps\_credits::_id_000C( &"CREDIT_DAVID_L_TOURNEAU_BROCHU", undefined, &"CREDIT_JULIAN_PONS", undefined, &"CREDIT_SHAWN_BELEW", undefined );
    maps\_credits::_id_000C( &"CREDIT_DEANDRE_HANDY", undefined, &"CREDIT_JUSTIN_NUNEZ", undefined, &"CREDIT_SIMON_BOUCHER", undefined );
    maps\_credits::_id_000C( &"CREDIT_DIEGO_CARRILLO", undefined, &"CREDIT_KAI_HSU_", undefined, &"CREDIT_SIMON_LEVESQUE", undefined );
    maps\_credits::_id_000C( &"CREDIT_DOMINIC_POIRIER", undefined, &"CREDIT_KARINE_WINDY_BOUDREAULT", undefined, &"CREDIT_SIMON_PIERRE_LEPAGE", undefined );
    maps\_credits::_id_000C( &"CREDIT_DUSTIN_CARTER", undefined, &"CREDIT_KELLY_HUFFINE", undefined, &"CREDIT_SKYLER_STANCIL", undefined );
    maps\_credits::_id_000C( &"CREDIT_EJ_ALCANTARA", undefined, &"CREDIT_KEVIN_VALL_E", undefined, &"CREDIT_SOLOMON_SMITH", undefined );
    maps\_credits::_id_000C( &"CREDIT_ELLIOTT_EHLIG", undefined, &"CREDIT_KIRT_SANCHEZ", undefined, &"CREDIT_ST_PHANE__LIE", undefined );
    maps\_credits::_id_000C( &"CREDIT__MILIE_VILLENEUVE", undefined, &"CREDIT_KURT_GOSCH", undefined, &"CREDIT_ST_PHANIE_LAMONTAGNE", undefined );
    maps\_credits::_id_000C( &"CREDIT_ERIC_KELLY", undefined, &"CREDIT_LAURENT_DUMONT_SAUCIER", undefined, &"CREDIT_STEPHEN_GLENN_SHEPPARD", undefined );
    maps\_credits::_id_000C( &"CREDIT_ERIC_STANZIONE_", undefined, &"CREDIT_LEONARD_RODRIGUEZ", undefined, &"CREDIT_SUNG_YOO", undefined );
    maps\_credits::_id_000C( &"CREDIT__TIENNE_DUB_", undefined, &"CREDIT_LOU_STUDDERT", undefined, &"CREDIT_SYLVAIN_DEVOST", undefined );
    maps\_credits::_id_000C( &"CREDIT_F_LIX_LEBLANC_BEAUREGARD", undefined, &"CREDIT_LUKA_L_B_LANGER", undefined, &"CREDIT_TEAK_HOLLEY", undefined );
    maps\_credits::_id_000C( &"CREDIT_FRANCIS_MALTAIS", undefined, &"CREDIT_MARC_ANDR__BARON", undefined, &"CREDIT_TEDDY_HWANG_", undefined );
    maps\_credits::_id_000C( &"CREDIT_FRANCK_MORISSEAU", undefined, &"CREDIT_MARC_ANDR__LALIBERT_", undefined, &"CREDIT_TOMMY_LAWLER", undefined );
    maps\_credits::_id_000C( &"CREDIT_FRAN_OIS_AUDETTE", undefined, &"CREDIT_MARC_ANDR__THIBEAULT", undefined, &"CREDIT_TOMY_CROUSSET", undefined );
    maps\_credits::_id_000C( &"CREDIT_GEORGE_BERGEN", undefined, &"CREDIT_MARC_ANDRE_VILLENEUVE", undefined, &"CREDIT_VICTOR_DURLING", undefined );
    maps\_credits::_id_000C( &"CREDIT_GERALD_ARTEAGA", undefined, &"CREDIT_MARC_ANTOINE_PELLETIER", undefined, &"CREDIT_WILLIAM_DAGGETT", undefined );
    maps\_credits::_id_000C( &"CREDIT_GLENN_ROBINSON", undefined, &"CREDIT_MARENKA_BISSON", undefined, &"CREDIT_WILLIAM_DZIAMBOR", undefined );
    maps\_credits::_id_000C( &"CREDIT_GLENN_VISTANTE", undefined, &"CREDIT_MARIE_CLAUDE_BLAIS", undefined, &"CREDIT_YOUNG_GUL_KIM", undefined );
    maps\_credits::_id_000C( &"CREDIT_GRANT_MARZETTE", undefined, &"CREDIT_MARIE_PIERRE_TREMBLAY", undefined, &"CREDIT_YOURI_GABBINO", undefined );
    maps\_credits::_id_000C( &"CREDIT_GREG_SANDS", undefined, &"CREDIT_MARVIN_SUPAN", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_LOCALISATION_TOOLS___SUPPORT", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_PROVIDED_BY_STEPHANIE_DEMING___X", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_PACKAGING_AND_MANUAL_DESIGN_BY", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_PETROL", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_FONTS_LICENSED_FROM", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_BITSTREAM", undefined, undefined, undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_MONOTYPE", undefined, undefined, undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_T26", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_FOOTAGE_AND_STILL_IMAGES_SUPPLIE", "subtitle", undefined, undefined );
    maps\_credits::_id_748B();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_GETTY_IMAGES", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_BOOMIN", undefined, undefined, undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_COMPOSED_BY_TODD_M_MICHILES_ASCA", undefined, undefined, undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_PUBLISHED_BY_WEST_ONE_APM_ASCAP", undefined, undefined, undefined );
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_COURTESY_OF_APM_MUSIC", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_JEEP__WRANGLER_AND_RUBICON__ARE_", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_IMAGE_METRICS__INC", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_PREDATOR_IS_A_US_REGISTERED_TRAD", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_USES_BINK_VIDEO_COPYRIGHT___1997", undefined, undefined, undefined );
    maps\_credits::_id_7456();
    maps\_credits::_id_000C( undefined, undefined, &"CREDIT_USES_MILES_SOUND_SYSTEM_COPYRIGH", undefined, undefined, undefined );
}

_id_745D()
{
    _id_7453();
    _id_002A();
    _id_002B();
    _id_002C();
}
