// IW5 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool

main()
{
    _id_5004();
    player();
    _id_4204();
    _id_47DE();
    _id_5B49();
    _id_5B48();
}
#using_animtree("generic_human");

_id_5004()
{
    level._id_11BB["hijack_plt_moscow"] = "hijack_plt_moscow";
    level._id_11BB["hijack_cmd_reportin"] = "hijack_cmd_reportin";
    level._id_11BB["hijack_fso1_presidentoffice"] = "hijack_fso1_presidentoffice";
    level._id_11BB["hijack_fso2_lowerdeckclear"] = "hijack_fso2_lowerdeckclear";
    level._id_11BB["hijack_fso3_fowardcabin"] = "hijack_fso3_fowardcabin";
    level._id_11BB["hijack_cmd_landinhamburg"] = "hijack_cmd_landinhamburg";
    level._id_11BB["hijack_cmd_remainwithpres"] = "hijack_cmd_remainwithpres";
    level._id_11BB["hijack_plt_message1"] = "hijack_plt_message1";
    level._id_11BB["hijack_plt_message2"] = "hijack_plt_message2";
    level._id_11BB["hijack_plt_message3"] = "hijack_plt_message3";
    level._id_11BB["hijack_cmd_staywithpres"] = "hijack_cmd_staywithpres";
    level._id_11BB["hijack_cmd_takeposition"] = "hijack_cmd_takeposition";
    level.scr_sound["president"]["hijack_prs_worldsafe"] = "hijack_prs_worldsafe";
    level.scr_sound["generic"]["hijack_fem1_scream"] = "hijack_fem1_scream";
    level.scr_sound["generic"]["hijack_fem2_scream"] = "hijack_fem2_scream";
    level.scr_sound["generic"]["hijack_fem3_scream"] = "hijack_fem3_scream";
    level.scr_sound["generic"]["hijack_fso1_pain"] = "hijack_fso1_pain";
    level.scr_sound["generic"]["hijack_fso2_pain"] = "hijack_fso2_pain";
    level.scr_sound["generic"]["hijack_fso1_gungun"] = "hijack_fso1_gungun";
    level.scr_sound["generic"]["hijack_fso2_lookout"] = "hijack_fso2_lookout";
    level.scr_sound["generic"]["hijack_hj1_placecharge"] = "hijack_hj1_placecharge";
    level.scr_sound["generic"]["hijack_hj2_standback"] = "hijack_hj2_standback";
    level.scr_sound["commander"]["hijack_cmd_onme"] = "hijack_cmd_onme";
    level.scr_sound["commander"]["hijack_cmd_safety"] = "hijack_cmd_safety";
    level.scr_sound["commander"]["hijack_cmd_statreport"] = "hijack_cmd_statreport";
    level._id_11BB["hijack_fso3_theyhave"] = "hijack_fso3_theyhave";
    level._id_11BB["hijack_fso2_resistance"] = "hijack_fso2_resistance";
    level._id_11BB["hijack_plt_losingcontrol"] = "hijack_plt_losingcontrol";
    level._id_11BB["hijack_plt_stalled"] = "hijack_plt_stalled";
    level._id_11BB["hijack_plt_inadive"] = "hijack_plt_inadive";
    level._id_11BB["hijack_plt_losingaltitude"] = "hijack_plt_losingaltitude";
    level._id_11BB["hijack_fso1_shotsfired"] = "hijack_fso1_shotsfired";
    level._id_11BB["hijack_fso2_altered"] = "hijack_fso2_altered";
    level._id_11BB["hijack_fso1_needbackup"] = "hijack_fso1_needbackup";
    level._id_11BB["hijack_fso2_gunshots"] = "hijack_fso2_gunshots";
    level._id_11BB["hijack_fso3_weaponsfree"] = "hijack_fso3_weaponsfree";
    level._id_11BB["hijack_fso1_sitrep"] = "hijack_fso1_sitrep";
    level._id_11BB["hijack_fso2_alert"] = "hijack_fso2_alert";
    level.scr_sound["commander"]["hijack_cmd_retakecockpit"] = "hijack_cmd_retakecockpit";
    level.scr_sound["commander"]["hijack_cmd_backuponway"] = "hijack_cmd_backuponway";
    level.scr_sound["generic"]["hijack_fso1_thiswaysir"] = "hijack_fso1_thiswaysir";
    level.scr_sound["generic"]["hijack_fso1_keepmoving"] = "hijack_fso1_keepmoving";
    level.scr_sound["generic"]["hijack_fso1_staywithgroup"] = "hijack_fso1_staywithgroup";
    level.scr_sound["generic"]["hijack_fso1_staytight"] = "hijack_fso1_staytight";
    level.scr_sound["generic"]["hijack_fso1_seperated"] = "hijack_fso1_seperated";
    level.scr_sound["generic"]["hijack_fso1_keepgoing"] = "hijack_fso1_keepgoing";
    level.scr_sound["commander"]["hijack_cmd_keeppushing"] = "hijack_cmd_keeppushing";
    level.scr_sound["commander"]["hijack_cmd_stayout"] = "hijack_cmd_stayout";
    level.scr_sound["commander"]["hijack_cmd_headdown"] = "hijack_cmd_headdown";
    level.scr_sound["commander"]["hijack_cmd_protectpres"] = "hijack_cmd_protectpres";
    level.scr_sound["commander"]["hijack_cmd_additionalhijack"] = "hijack_cmd_additionalhijack";
    level.scr_sound["commander"]["hijack_cmd_prestosaferoom"] = "hijack_cmd_prestosaferoom";
    level.scr_sound["commander"]["hijack_cmd_roomclear"] = "hijack_cmd_roomclear";
    level._id_11BB["hijack_fso2_resistance"] = "hijack_fso2_resistance";
    level._id_11BB["hijack_fso2_drivenback"] = "hijack_fso2_drivenback";
    level._id_11BB["hijack_fso2_jammedshut"] = "hijack_fso2_jammedshut";
    level._id_11BB["hijack_fso2_retake"] = "hijack_fso2_retake";
    level._id_11BB["hijack_fc1_descended"] = "hijack_fc1_descended";
    level._id_11BB["hijack_fc2_kgbandfso"] = "hijack_fc2_kgbandfso";
    level._id_11BB["hijack_fc1_squawking"] = "hijack_fc1_squawking";
    level._id_11BB["hijack_fc2_heading"] = "hijack_fc2_heading";
    level._id_11BB["hijack_fc1_scrambling"] = "hijack_fc1_scrambling";
    level._id_11BB["hijack_fc2_doyoucopy"] = "hijack_fc2_doyoucopy";
    level._id_11BB["hijack_fc1_notresponding"] = "hijack_fc1_notresponding";
    level._id_11BB["hijack_fc2_rapidrate"] = "hijack_fc2_rapidrate";
    level._id_11BB["hijack_fc1_slowdescent"] = "hijack_fc1_slowdescent";
    level._id_11BB["hijack_cmd_holdonhark"] = "hijack_cmd_holdonhark";
    level._id_11BB["hijack_plt_emergency"] = "hijack_plt_emergency";
    level._id_11BB["hijack_plt_brace"] = "hijack_plt_brace";
    level.scr_sound["generic"]["hijack_fso2_gonnahit"] = "hijack_fso2_gonnahit";
    level.scr_sound["generic"]["hijack_fso2_holdon"] = "hijack_fso2_holdon";
    level.scr_sound["generic"]["hijack_fso1_yell1"] = "hijack_fso1_yell1";
    level.scr_sound["generic"]["hijack_fso1_yell2"] = "hijack_fso1_yell2";
    level.scr_sound["generic"]["hijack_fso1_yell3"] = "hijack_fso1_yell3";
    level._id_11BB["hijack_rt1_stillinarea"] = "hijack_rt1_stillinarea";
    level._id_11BB["hijack_rt2_command"] = "hijack_rt2_command";
    level._id_11BB["hijack_rt3_scrambling"] = "hijack_rt3_scrambling";
    level._id_11BB["hijack_rt1_clearing"] = "hijack_rt1_clearing";
    level._id_11BB["hijack_rt2_neutralized"] = "hijack_rt2_neutralized";
    level._id_11BB["hijack_rt3_wounded"] = "hijack_rt3_wounded";
    level._id_11BB["hijack_rt1_verifylocation"] = "hijack_rt1_verifylocation";
    level._id_11BB["hijack_rt2_hamburg"] = "hijack_rt2_hamburg";
    level._id_11BB["hijack_fso1_flightpath"] = "hijack_fso1_flightpath";
    level.scr_sound["commander"]["hijack_cmd_perimeter"] = "hijack_cmd_perimeter";
    level.scr_sound["commander"]["hijack_cmd_findpresident2"] = "hijack_cmd_findpresident2";
    level.scr_sound["commander"]["hijack_cmd_keepmoving2"] = "hijack_cmd_keepmoving2";
    level.scr_sound["commander"]["hijack_cmd_comeon"] = "hijack_cmd_comeon";
    level.scr_sound["commander"]["hijack_cmd_letsgo"] = "hijack_cmd_letsgo";
    level._id_11BB["hijack_rt1_beacons"] = "hijack_rt1_beacons";
    level._id_11BB["hijack_rt2_channels"] = "hijack_rt2_channels";
    level._id_11BB["hijack_rt3_eta10mins"] = "hijack_rt3_eta10mins";
    level._id_11BB["hijack_rt3_eta10mins_b"] = "hijack_rt3_eta10mins_b";
    level.scr_sound["generic"]["hijack_fso1_injuredman"] = "hijack_fso1_injuredman";
    level.scr_sound["generic"]["hijack_fso3_helpme"] = "hijack_fso3_helpme";
    level.scr_sound["generic"]["hijack_fso1_agentdown"] = "hijack_fso1_agentdown";
    level.scr_sound["plane_exit_agent1"]["hijack_fso1_howdidthey"] = "hijack_fso1_howdidthey";
    level.scr_sound["plane_exit_agent2"]["hijack_fso2_theyknew2"] = "hijack_fso2_theyknew2";
    level.scr_sound["generic"]["hijack_fso1_myarm"] = "hijack_fso1_myarm";
    level.scr_sound["generic"]["hijack_fso2_medical"] = "hijack_fso2_medical";
    level.scr_sound["generic"]["hijack_fso1_surprise"] = "hijack_fso1_surprise";
    level.scr_sound["generic"]["hijack_fso2_surprise"] = "hijack_fso2_surprise";
    level.scr_sound["generic"]["hijack_fso1_cough"] = "hijack_fso1_cough";
    level.scr_sound["generic"]["hijack_fso1_cough2"] = "hijack_fso1_cough2";
    level.scr_sound["generic"]["hijack_fso1_moan"] = "hijack_fso1_moan";
    level.scr_sound["generic"]["hijack_fso1_moan2"] = "hijack_fso1_moan2";
    level.scr_sound["generic"]["hijack_fso1_yellofpain"] = "hijack_fso1_yellofpain";
    level.scr_sound["generic"]["hijack_fso1_yellofpain2"] = "hijack_fso1_yellofpain2";
    level.scr_sound["generic"]["hijack_fso1_longyell"] = "hijack_fso1_longyell";
    level.scr_sound["generic"]["hijack_fso2_cough"] = "hijack_fso2_cough";
    level.scr_sound["generic"]["hijack_fso2_cough2"] = "hijack_fso2_cough2";
    level.scr_sound["generic"]["hijack_fso2_moan"] = "hijack_fso2_moan";
    level.scr_sound["generic"]["hijack_fso2_moan2"] = "hijack_fso2_moan2";
    level.scr_sound["generic"]["hijack_fso2_yellofpain"] = "hijack_fso2_yellofpain";
    level.scr_sound["generic"]["hijack_fso2_yellofpain2"] = "hijack_fso2_yellofpain2";
    level.scr_sound["generic"]["hijack_fso2_longyell"] = "hijack_fso2_longyell";
    level.scr_sound["generic"]["hijack_fso3_cough"] = "hijack_fso3_cough";
    level.scr_sound["generic"]["hijack_fso3_cough2"] = "hijack_fso3_cough2";
    level.scr_sound["generic"]["hijack_fso3_moan"] = "hijack_fso3_moan";
    level.scr_sound["generic"]["hijack_fso3_moan2"] = "hijack_fso3_moan2";
    level.scr_sound["generic"]["hijack_fso3_yellofpain"] = "hijack_fso3_yellofpain";
    level.scr_sound["generic"]["hijack_fso3_yellofpain2"] = "hijack_fso3_yellofpain2";
    level.scr_sound["generic"]["hijack_fso3_longyell"] = "hijack_fso3_longyell";
    level._id_11BB["hijack_fso1_confirmation"] = "hijack_fso1_confirmation";
    level._id_11BB["hijack_rt1_onsceneinten"] = "hijack_rt1_onsceneinten";
    level._id_11BB["hijack_fso2_cordonoff"] = "hijack_fso2_cordonoff";
    level._id_11BB["hijack_fso3_leakingfuel"] = "hijack_fso3_leakingfuel";
    level._id_11BB["hijack_rt1_blackbox"] = "hijack_rt1_blackbox";
    level._id_11BB["hijack_fso3_blackbox"] = "hijack_fso3_blackbox";
    level._id_11BB["hijack_fso2_medical"] = "hijack_fso2_medical";
    level._id_11BB["hijack_fso1_satcom"] = "hijack_fso1_satcom";
    level._id_11BB["hijack_fso3_cockpit"] = "hijack_fso3_cockpit";
    level._id_11BB["hijack_fso2_tailsection"] = "hijack_fso2_tailsection";
    level.scr_sound["commander"]["hijack_cmd_evacontheway"] = "hijack_cmd_evacontheway";
    level.scr_sound["commander"]["hijack_cmd_team4report"] = "hijack_cmd_team4report";
    level._id_11BB["hijack_fso4_wounded"] = "hijack_fso4_wounded";
    level.scr_sound["commander"]["hijack_cmd_securearea"] = "hijack_cmd_securearea";
    level._id_11BB["hijack_fso4_sendingflare"] = "hijack_fso4_sendingflare";
    level.scr_sound["commander"]["hijack_cmd_theflare"] = "hijack_cmd_theflare";
    level.scr_sound["commander"]["hijack_cmd_onourway"] = "hijack_cmd_onourway";
    level.scr_sound["commander"]["hijack_cmd_evacchoppers"] = "hijack_cmd_evacchoppers";
    level._id_11BB["hijack_fso4_heavyfire"] = "hijack_fso4_heavyfire";
    level._id_11BB["hijack_fso4_notsecure"] = "hijack_fso4_notsecure";
    level.scr_sound["commander"]["hijack_cmd_getalenaout"] = "hijack_cmd_getalenaout";
    level.scr_sound["commander"]["hijack_cmd_wehavetomove"] = "hijack_cmd_wehavetomove";
    level._id_11BB["hijack_fso1_nearhangar"] = "hijack_fso1_nearhangar";
    level.scr_sound["commander"]["hijack_cmd_letsmoveit"] = "hijack_cmd_letsmoveit";
    level.scr_sound["commander"]["hijack_cmd_keeppushing2"] = "hijack_cmd_keeppushing2";
    level._id_11BB["hijack_fso2_multiplewounded"] = "hijack_fso2_multiplewounded";
    level.scr_sound["commander"]["hijack_cmd_moveupmoveup"] = "hijack_cmd_moveupmoveup";
    level._id_11BB["hijack_fso3_critical"] = "hijack_fso3_critical";
    level._id_11BB["hijack_fso3_codeblack"] = "hijack_fso3_codeblack";
    level.scr_sound["commander"]["hijack_cmd_takethemdown"] = "hijack_cmd_takethemdown";
    level.scr_sound["commander"]["hijack_cmd_holdyourfire"] = "hijack_cmd_holdyourfire";
    level.scr_sound["commander"]["hijack_cmd_thepresident"] = "hijack_cmd_thepresident";
    level.scr_sound["commander"]["hijack_cmd_getyouout"] = "hijack_cmd_getyouout";
    level.scr_sound["president"]["hijack_prs_wheresmy"] = "hijack_prs_wheresmy";
    level.scr_sound["commander"]["hijack_cmd_moveyounow"] = "hijack_cmd_moveyounow";
    level.scr_sound["commander"]["hijack_cmd_openthedoor2"] = "hijack_cmd_openthedoor2";
    level.scr_sound["makarov"]["hijack_mkv_yourattention"] = "hijack_mkv_yourattention";
    level._id_11BB["hijack_fso3_allteams"] = "hijack_fso3_allteams";
    level._id_0C59["generic"]["patrol_walk"] = %patrol_bored_patrolwalk;
    level._id_0C59["generic"]["patrol_stop"] = %patrol_bored_walk_2_bored;
    level._id_0C59["generic"]["patrol_start"] = %patrol_bored_2_walk;
    level._id_0C59["generic"]["patrol_turn180"] = %patrol_bored_2_walk_180turn;
    level._id_0C59["generic"]["stand_death_shoulder_spin"] = %stand_death_shoulder_spin;
    level._id_0C59["commander"]["cqb_stand_aim5"] = %cqb_stand_aim5;
    level._id_0C59["human"]["cowerstand_react_to_crouch"] = %unarmed_cowerstand_react_2_crouch;
    level._id_0C59["generic"]["hallway_dead_pose_agent"][0] = %hijack_hallway_dead_pose_agent;
    level._id_0C59["generic"]["hallway_dead_pose_terrorist"][0] = %hijack_hallway_dead_pose_terrorist;
    level._id_0C59["generic"]["hallway_dead_pose_assistant"][0] = %hijack_hallway_dead_pose_assistant;
    level._id_0C59["crawl_death_1"]["crawl"] = %dying_crawl;
    level._id_0C59["crawl_death_1"]["death"][0] = %dying_crawl_death_v3;
    level._id_0C59["president"]["intro_scene"] = %hijack_intro_cine_president;
    maps\_anim::_id_1264( "president", "notify_conf_room", maps\hijack_airplane::_id_5AAE, "intro_scene" );
    level._id_0C59["president"]["intro_cine_president_wait_loop"][0] = %hijack_intro_cine_president_wait_loop;
    level._id_0C59["daughter"]["intro_scene"] = %hijack_intro_cine_daughter;
    level._id_0C59["hero_agent"]["intro_scene"] = %hijack_intro_cine_hero_agent;
    level._id_0C59["hero_agent"]["intro_cine_hero_agent_loop"][0] = %hijack_intro_cine_hero_agent_loop;
    level._id_0C59["assistant"]["intro_scene"] = %hijack_intro_cine_assistant;
    maps\_anim::_id_1264( "assistant", "open_door2", maps\hijack_airplane::_id_5AAC, "intro_scene" );
    level._id_0C59["advisor"]["intro_cine_advisor"] = %hijack_intro_cine_advisor;
    level._id_0C59["advisor"]["intro_cine_advisor_wait_loop"][0] = %hijack_intro_cine_advisor_wait_loop;
    level._id_0C59["commander"]["intro_cine_commander"] = %hijack_intro_cine_commander;
    level._id_0C59["commander"]["intro_cine_commander_wait_loop"][0] = %hijack_intro_cine_commander_wait_loop;
    level._id_0C59["secretary"]["intro_cine_secretary"] = %hijack_intro_cine_secretary;
    level._id_0C59["secretary"]["intro_cine_secretary_wait_loop"][0] = %hijack_intro_cine_secretary_wait_loop;
    level._id_0C59["generic"]["intro_cine_agent"] = %hijack_intro_cine_agent;
    maps\_anim::_id_1264( "generic", "open_door3", maps\hijack_airplane::_id_5ABF, "intro_cine_agent" );
    level._id_0C59["generic"]["intro_cine_agent_loop"][0] = %hijack_intro_cine_agent_loop;
    level._id_0C59["generic"]["intro_cine_agent_close_door"] = %hijack_intro_cine_agent_close_door;
    maps\_anim::_id_1264( "generic", "close_door3", maps\hijack_airplane::_id_5AC0, "intro_cine_agent_close_door" );
    level._id_0C59["generic"]["intro_cine_agent_guard"] = %hijack_intro_cine_agent_guard;
    level._id_0C59["generic"]["intro_cine_agent_guard_loop"][0] = %hijack_intro_cine_agent_guard_loop;
    level._id_0C59["generic"]["intro_cine_agent2"] = %hijack_intro_cine_agent2;
    level._id_0C59["generic"]["intro_cine_agent2_loop"][0] = %hijack_intro_cine_agent2_loop;
    level._id_0C59["generic"]["intro_cine_agent3"] = %hijack_intro_cine_agent3;
    level._id_0C59["generic"]["intro_cine_agent3_loop"][0] = %hijack_intro_cine_agent3_loop;
    level._id_0C59["polit_1"]["intro_cine_politician1"] = %hijack_intro_cine_politician1;
    level._id_0C59["polit_1"]["intro_cine_politician1_loop"][0] = %hijack_intro_cine_politician1_loop;
    level._id_0C59["polit_2"]["intro_cine_politician2"] = %hijack_intro_cine_politician2;
    level._id_0C59["polit_2"]["intro_cine_politician2_loop"][0] = %hijack_intro_cine_politician2_loop;
    level._id_0C59["generic"]["intro_worker_checklist"] = %hijack_intro_worker_checklist;
    level._id_0C59["generic"]["intro_worker_checklist_loop"][0] = %hijack_intro_worker_checklist_loop;
    level._id_0C59["generic"]["intro_kitchenette_guy1"] = %hijack_intro_kitchenette_guy1;
    level._id_0C59["generic"]["intro_kitchenette_guy1_loop"][0] = %hijack_intro_kitchenette_guy1_loop;
    level._id_0C59["generic"]["intro_kitchenette_guy2"] = %hijack_intro_kitchenette_guy2;
    level._id_0C59["generic"]["intro_kitchenette_guy2_loop"][0] = %hijack_intro_kitchenette_guy2_loop;
    level._id_0C59["generic"]["intro_storage_guy"] = %hijack_intro_storage_guy;
    level._id_0C59["generic"]["intro_storage_guy_loop"][0] = %hijack_intro_storage_guy_loop;
    level._id_0C59["president"]["debate"] = %hijack_debate_cine_president;
    level._id_0C59["president"]["debate_cine_president_end_loop"][0] = %hijack_debate_cine_president_end_loop;
    level._id_0C59["advisor"]["debate"] = %hijack_debate_cine_advisor;
    level._id_0C59["advisor"]["debate_cine_advisor_end_loop"][0] = %hijack_debate_cine_advisor_end_loop;
    level._id_0C59["commander"]["debate"] = %hijack_debate_cine_commander;
    level._id_0C59["commander"]["debate_cine_commander_end_loop"][0] = %hijack_debate_cine_commander_end_loop;
    level._id_0C59["secretary"]["debate"] = %hijack_debate_cine_secretary;
    level._id_0C59["secretary"]["debate_cine_secretary_death"] = %hijack_debate_cine_secretary_death;
    level._id_0C59["generic"]["debate_cine_hijacker1_breach"] = %hijack_debate_cine_hijacker1_breach;
    level._id_0C59["generic"]["debate_cine_hijacker2_breach"] = %hijack_debate_cine_hijacker2_breach;
    level._id_0C59["generic"]["debate_cine_agent_rescue"] = %hijack_debate_cine_agent_rescue;
    maps\_anim::_id_1264( "generic", "open_door3", maps\hijack_airplane::_id_5ABE, "debate_cine_agent_rescue" );
    level._id_0C59["generic"]["debate_cine_agent_rescue_loop"][0] = %hijack_debate_cine_agent_rescue_loop;
    level._id_0C59["hero_agent"]["debate"] = %hijack_debate_cine_hero_agent;
    level._id_0C59["hero_agent"]["debate_cine_hero_agent_end_loop"][0] = %hijack_debate_cine_hero_agent_end_loop;
    level._id_0C59["generic"]["debate"] = %hijack_debate_cine_agent2;
    level._id_0C59["generic"]["debate_cine_agent2_end_loop"][0] = %hijack_debate_cine_agent2_end_loop;
    level._id_0C59["polit_1"]["debate"] = %hijack_debate_cine_politician1;
    level._id_0C59["polit_1"]["debate_cine_politician1_death_loop"][0] = %hijack_debate_cine_politician1_death_loop;
    level._id_0C59["polit_2"]["debate"] = %hijack_debate_cine_politician2;
    level._id_0C59["polit_2"]["debate_cine_politician2_death_loop"][0] = %hijack_debate_cine_politician2_death_loop;
    level._id_0C59["commander"]["hero_stumble"] = %hijack_pre_zero_g_hero_stumble;
    level._id_0C59["generic"]["hallway_slump_agent"] = %hijack_hallway_slump_agent;
    level._id_0C59["generic"]["hallway_slump_terrorist"] = %hijack_hallway_slump_terrorist;
    level._id_0C59["generic"]["hallway_slump_assistant"] = %hijack_hallway_slump_assistant;
    level._id_0C59["zerog_terrorist1"]["zerog_moment"] = %hijack_zerog_terrorist_01_alive;
    level._id_0C59["zerog_terrorist2"]["zerog_moment"] = %hijack_zerog_terrorist_02_alive;
    level._id_0C59["zerog_terrorist3"]["zerog_moment"] = %hijack_zerog_terrorist_03_alive;
    level._id_0C59["zerog_terrorist4"]["zerog_moment"] = %hijack_zerog_terrorist_04_alive;
    level._id_0C59["zerog_terrorist5"]["zerog_moment"] = %hijack_zerog_terrorist_05_alive;
    level._id_0C59["agent2"]["zerog_moment"] = %hijack_zerog_agent_01;
    level._id_0C59["agent1"]["zerog_moment"] = %hijack_zerog_agent_02;
    level._id_0C59["agent1"]["cockpit_door_bash_enter"] = %hijack_cockpit_door_bash_enter;
    level._id_0C59["agent1"]["cockpit_door_bash_loop"][0] = %hijack_cockpit_door_bash_loop;
    level._id_0C59["commander"]["zerog_hero_agent"] = %hijack_zerog_hero_agent;
    level._id_0C59["commander"]["zerog_commander_alt"] = %hijack_zerog_commander_alt;
    level._id_1245["zerog_terror1_track"] = #animtree;
    level._id_1F90["zerog_terror1_track"] = "generic_prop_raven";
    level._id_0C59["zerog_terror1_track"]["zerog_terrorist_01_align"] = %hijack_zerog_terrorist_01_align;
    level._id_1245["zerog_terror2_track"] = #animtree;
    level._id_1F90["zerog_terror2_track"] = "generic_prop_raven";
    level._id_0C59["zerog_terror2_track"]["zerog_terrorist_02_align"] = %hijack_zerog_terrorist_02_align;
    level._id_1245["zerog_terror3_track"] = #animtree;
    level._id_1F90["zerog_terror3_track"] = "generic_prop_raven";
    level._id_0C59["zerog_terror3_track"]["zerog_terrorist_03_align"] = %hijack_zerog_terrorist_03_align;
    level._id_1245["zerog_terror4_track"] = #animtree;
    level._id_1F90["zerog_terror4_track"] = "generic_prop_raven";
    level._id_0C59["zerog_terror4_track"]["zerog_terrorist_04_align"] = %hijack_zerog_terrorist_04_align;
    level._id_1245["zerog_terror5_track"] = #animtree;
    level._id_1F90["zerog_terror5_track"] = "generic_prop_raven";
    level._id_0C59["zerog_terror5_track"]["zerog_terrorist_05_align"] = %hijack_zerog_terrorist_05_align;
    level._id_0C59["generic"]["hijack_diningroom_bar_terrorist"] = %hijack_diningroom_bar_terrorist;
    level._id_0C59["generic"]["hijack_diningroom_door_terrorist"] = %hijack_diningroom_door_terrorist;
    level._id_0C59["generic"]["hijack_generic_stumble_crouch1"] = %hijack_generic_stumble_crouch1;
    level._id_0C59["generic"]["hijack_generic_stumble_crouch2"] = %hijack_generic_stumble_crouch2;
    level._id_0C59["generic"]["hijack_generic_stumble_stand1"] = %hijack_generic_stumble_stand1;
    level._id_0C59["generic"]["hijack_generic_stumble_stand2"] = %hijack_generic_stumble_stand2;
    level._id_0C59["daughter"]["pre_find_daughter"] = %hijack_pre_find_daughter_alena;
    level._id_0C59["generic"]["pre_find_daughter"] = %hijack_pre_find_daughter_enemy;
    level._id_0C59["daughter"]["pre_find_daughter_short"] = %hijack_pre_find_daughter_alena_short;
    level._id_0C59["generic"]["pre_find_daughter_short"] = %hijack_pre_find_daughter_enemy_short;
    level._id_0C59["generic"]["find_daughter_enter"] = %hijack_find_daughter_agent_enter;
    level._id_0C59["commander"]["find_daughter_enter"] = %hijack_find_daughter_commander_enter;
    level._id_0C59["commander"]["door1"] = %hijack_find_daughter_commander_door1;
    level._id_0C59["commander"]["find_daughter_commander_loop"][0] = %hijack_find_daughter_commander_loop;
    level._id_0C59["daughter"]["daughter_cry_loop"][0] = %hijack_find_daughter_cry_loop;
    level._id_0C59["daughter"]["find_daughter_enter"] = %hijack_find_daughter_elena_found;
    level._id_0C59["daughter"]["post_find_loop"][0] = %hijack_find_daughter_elena_loop2;
    level._id_0C59["president"]["find_daughter_enter"] = %hijack_find_daughter_president_enter;
    level._id_0C59["president"]["post_find_loop"][0] = %hijack_find_daughter_president_loop;
    level._id_0C59["commander"]["corner_standL_alert_twitch04"][0] = %corner_standl_alert_twitch04;
    level._id_0C59["generic"]["planecrash_enemy1"] = %hijack_plane_crash_enemy1;
    level._id_0C59["generic"]["planecrash_enemy2"] = %hijack_plane_crash_enemy2;
    level._id_0C59["generic"]["planecrash_enemy3"] = %hijack_plane_crash_enemy3;
    level._id_0C59["generic"]["planecrash_enemy4"] = %hijack_plane_crash_enemy4;
    level._id_0C59["generic"]["planecrash_enemy5"] = %hijack_plane_crash_enemy5;
    level._id_0C59["generic"]["planecrash_enemy6"] = %hijack_plane_crash_enemy6;
    maps\_anim::_id_1264( "generic", "fire", maps\hijack_crash_fx::_id_5983, "planecrash_enemy1" );
    maps\_anim::_id_1264( "generic", "fire", maps\hijack_crash_fx::_id_5983, "planecrash_enemy2" );
    maps\_anim::_id_1264( "generic", "fire", maps\hijack_crash_fx::_id_5983, "planecrash_enemy3" );
    maps\_anim::_id_1264( "generic", "fire", maps\hijack_crash_fx::_id_5983, "planecrash_enemy4" );
    maps\_anim::_id_1264( "generic", "fire", maps\hijack_crash_fx::_id_5983, "planecrash_enemy5" );
    maps\_anim::_id_1264( "generic", "fire", maps\hijack_crash_fx::_id_5983, "planecrash_enemy6" );
    level._id_0C59["generic"]["planecrash_agent1"] = %hijack_plane_crash_agent;
    level._id_0C59["commander"]["commander_blocks_door_right"] = %hijack_find_daughter_commander_door2r;
    level._id_0C59["commander"]["commander_blocks_door_left"] = %hijack_find_daughter_commander_door2l;
    level._id_0C59["commander"]["commander_planecrash_idle"][0] = %hijack_plane_crash_commander_loop;
    level._id_0C59["commander"]["help_player_up"] = %hijack_tarmac_agent_helps_agent;
    level._id_0C59["commander"]["exit_top_idle"][0] = %hijack_exit_plane_idle_top_commander;
    level._id_0C59["commander"]["exit_down_ramp"] = %hijack_exit_plane_commander;
    level._id_0C59["commander"]["exit_bottom_idle"][0] = %hijack_exit_plane_idle_commander;
    level._id_0C59["commander"]["secure_daughter"] = %hijack_secure_daughter_commander;
    level._id_0C59["plane_exit_agent1"]["secure_daughter"] = %hijack_secure_daughter_agent1;
    level._id_0C59["plane_exit_agent2"]["secure_daughter"] = %hijack_secure_daughter_agent2;
    level._id_0C59["daughter"]["secure_daughter"] = %hijack_secure_daughter_elena;
    level._id_0C59["plane_exit_agent1"]["secure_daughter_loop"][0] = %hijack_secure_daughter_end_loop_agent1;
    level._id_0C59["plane_exit_agent2"]["secure_daughter_loop"][0] = %hijack_secure_daughter_end_loop_agent2;
    level._id_0C59["daughter"]["secure_daughter_loop"][0] = %hijack_secure_daughter_end_loop_elena;
    level._id_0C59["generic"]["injured_hands_on_knees"][0] = %hijack_tarmac_injured_hands_on_knees;
    level._id_0C59["generic"]["injured_on_back"][0] = %hijack_tarmac_injured_on_back;
    level._id_0C59["generic"]["injured_leg_loop"][0] = %hijack_tarmac_injured_leg_loop;
    level._id_0C59["checkguy"]["checkdeadguy_start"] = %hijack_tarmac_checkdeadguy_start;
    level._id_0C59["checkguy"]["checkdeadguy_loop"][0] = %hijack_tarmac_checkdeadguy_loop;
    level._id_0C59["deadguy"]["checkdeadguy_start"] = %hijack_tarmac_deadguy_start;
    level._id_0C59["deadguy"]["checkdeadguy_loop"][0] = %hijack_tarmac_deadguy_loop;
    level._id_0C59["generic"]["scout_finds_buried_hijacker"] = %hijack_tarmac_scout;
    level._id_0C59["generic"]["buried_hijacker"] = %hijack_tarmac_burried_terrorist;
    level._id_0C59["generic"]["drag_from_engine_agent1"] = %hijack_tarmac_drag_from_engine_agent1;
    level._id_0C59["generic"]["drag_from_engine_agent1_loop"][0] = %hijack_tarmac_drag_from_engine_agent1_loop;
    level._id_0C59["generic"]["drag_from_engine_agent2"] = %hijack_tarmac_drag_from_engine_agent2;
    level._id_0C59["generic"]["drag_from_engine_agent2_loop"][0] = %hijack_tarmac_drag_from_engine_agent2_loop;
    level._id_0C59["generic"]["drag_from_engine_agent3"] = %hijack_tarmac_drag_from_engine_agent3;
    level._id_0C59["generic"]["drag_from_engine_agent3_loop"][0] = %hijack_tarmac_drag_from_engine_agent3_loop;
    level._id_0C59["generic"]["reach_to_explosion_agent1_loop_start"][0] = %hijack_tarmac_react_to_explosion_agent1_loop_start;
    level._id_0C59["generic"]["reach_to_explosion_agent1"] = %hijack_tarmac_react_to_explosion_agent1;
    level._id_0C59["generic"]["reach_to_explosion_agent1_loop_end"][0] = %hijack_tarmac_react_to_explosion_agent1_loop_end;
    level._id_0C59["generic"]["reach_to_explosion_agent2_loop_start"][0] = %hijack_tarmac_react_to_explosion_agent2_loop_start;
    level._id_0C59["generic"]["reach_to_explosion_agent2"] = %hijack_tarmac_react_to_explosion_agent2;
    level._id_0C59["generic"]["reach_to_explosion_agent2_loop_end"][0] = %hijack_tarmac_react_to_explosion_agent2_loop_end;
    level._id_0C59["generic"]["samaritan_start"] = %hijack_tarmac_samaritan_start;
    level._id_0C59["generic"]["samaritan_loop"][0] = %hijack_tarmac_samaritan_loop;
    level._id_0C59["generic"]["limping_agent_start"] = %hijack_tarmac_limping_agent_start;
    level._id_0C59["generic"]["limping_agent_loop"][0] = %hijack_tarmac_limping_agent_loop;
    level._id_0C59["generic"]["trapped_agent_start"] = %hijack_tarmac_trapped_agent_start;
    level._id_0C59["generic"]["trapped_agent_loop"][0] = %hijack_tarmac_trapped_agent_loop;
    level._id_0C59["commander"]["relaxed_idle"][0] = %hijack_tarmac_relaxed_idle_commander;
    level._id_0C59["commander"]["flare_reaction"] = %hijack_tarmac_flare_reaction_commander;
    level._id_0C59["commander"]["heli_wait"][0] = %hijack_tarmac_idle_heli_wait_commander;
    level._id_0C59["commander"]["heli_wave"] = %hijack_tarmac_heli_wave_commander;
    level._id_0C59["commander"]["engine_stumble"] = %hijack_tarmac_react_engine_commander;
    level._id_0C59["commander"]["injured_run"] = %hijack_tarmac_injured_run_commander;
    level._id_0C59["generic"]["tarmac_enter_combat_agent"] = %hijack_tarmac_enter_combat_agent;
    level._id_0C59["commander"]["tarmac_enter_combat_commander"] = %hijack_tarmac_enter_combat_commander;
    level._id_0C59["president"]["end_part1"][0] = %hijack_ending_cover_idle_president;
    level._id_0C59["end_agent"]["end_part1"][0] = %hijack_ending_cover_idle_agent01;
    level._id_0C59["advisor"]["end_part1"][0] = %hijack_ending_cover_idle_advisor;
    level._id_0C59["president"]["end_part2"] = %hijack_ending_walk_to_heli_presdient;
    level._id_0C59["end_agent"]["end_part2"] = %hijack_ending_walk_to_heli_agent01;
    level._id_0C59["advisor"]["end_part2"] = %hijack_ending_walk_to_heli_advisor;
    level._id_0C59["commander"]["end_part2"] = %hijack_ending_walk_to_heli_commander;
    level._id_0C59["president"]["end_part3"][0] = %hijack_ending_waiting_open_door_president;
    level._id_0C59["end_agent"]["end_part3"][0] = %hijack_ending_waiting_open_door_agent01;
    level._id_0C59["advisor"]["end_part3"][0] = %hijack_ending_waiting_open_door_advisor;
    level._id_0C59["commander"]["end_part3"][0] = %hijack_ending_waiting_open_door_commander;
    level._id_0C59["president"]["end_part4"] = %hijack_ending_reveal_president;
    level._id_0C59["end_agent"]["end_part4"] = %hijack_ending_reveal_agent01;
    level._id_0C59["advisor"]["end_part4"] = %hijack_ending_reveal_advisor;
    level._id_0C59["commander"]["end_part4"] = %hijack_ending_reveal_commander;
    level._id_0C59["makarov"]["end_part4"] = %hijack_ending_reveal_makarov;
    level._id_0C59["henchman1"]["end_part4"] = %hijack_ending_reveal_henchman01;
    level._id_0C59["henchman2"]["end_part4"] = %hijack_ending_reveal_henchman02;
}

_id_5B48()
{
    level._id_1245["test_body"] = #animtree;
    level._id_1F90["test_body"] = "viewhands_player_fso";
    level._id_0C59["test_body"]["zero_g_player"] = %hijack_zero_g_player;
    maps\_anim::_id_1264( "test_body", "people_lurch_left", maps\hijack_airplane::_id_5B0E, "zero_g_player" );
    maps\_anim::_id_1264( "test_body", "plane_dive_down", maps\hijack_airplane::_id_5B10, "zero_g_player" );
    maps\_anim::_id_1264( "test_body", "people_fly_up", maps\hijack_airplane::_id_5B0F, "zero_g_player" );
    maps\_anim::_id_1264( "test_body", "screen_shake_1", maps\hijack_airplane::_id_5B11, "zero_g_player" );
    maps\_anim::_id_1264( "test_body", "plane_roll_right", maps\hijack_airplane::_id_5B12, "zero_g_player" );
    maps\_anim::_id_1264( "test_body", "screen_shake_2", maps\hijack_airplane::_id_5B13, "zero_g_player" );
    maps\_anim::_id_1264( "test_body", "plane_roll_left", maps\hijack_airplane::_id_5B14, "zero_g_player" );
    maps\_anim::_id_1264( "test_body", "screen_shake_3", maps\hijack_airplane::_id_5B15, "zero_g_player" );
    maps\_anim::_id_1264( "test_body", "plane_level_out", maps\hijack_airplane::_id_5B16, "zero_g_player" );
}
#using_animtree("player");

player()
{
    level._id_1245["player_rig"] = #animtree;
    level._id_1F90["player_rig"] = "viewhands_player_fso";
    level._id_0C59["player_rig"]["debate_react_player"] = %hijack_debate_react_player;
    level._id_0C59["player_rig"]["crash_fall_out"] = %hijack_plane_crash_fall_out_player;
    level._id_0C59["player_rig"]["help_player_up"] = %hijack_tarmac_agent_helps_player;
    level._id_0C59["player_rig"]["end_part4"] = %hijack_ending_open_door_player;
}
#using_animtree("animated_props");

_id_4204()
{
    level._id_1245["turbines"] = #animtree;
    level._id_1F90["turbines"] = "generic_prop_raven";
    level._id_0C59["turbines"]["engine_turbine_spin"] = %hijack_engine_turbine_spin_loop;
    level._id_0C59["turbines"]["engine_turbine_spin_loop"][0] = %hijack_engine_turbine_spin_loop;
    level._id_1245["binder"] = #animtree;
    level._id_1F90["binder"] = "generic_prop_raven";
    level._id_0C59["binder"]["intro_cine_pres_binder"] = %hijack_intro_cine_pres_binder;
    level._id_1245["clipboard"] = #animtree;
    level._id_1F90["clipboard"] = "generic_prop_raven";
    level._id_0C59["clipboard"]["intro_worker_clipboard"] = %hijack_intro_worker_clipboard;
    level._id_0C59["clipboard"]["intro_worker_clipboard_loop"][0] = %hijack_intro_worker_clipboard_loop;
    level._id_1245["food_cart"] = #animtree;
    level._id_1F90["food_cart"] = "generic_prop_raven";
    level._id_0C59["food_cart"]["intro_storage_cart"] = %hijack_intro_storage_cart;
    level._id_0C59["food_cart"]["intro_storage_candy"] = %hijack_intro_storage_candy_loop;
    level._id_0C59["food_cart"]["intro_storage_candy_loop"][0] = %hijack_intro_storage_candy_loop;
    level._id_0C59["food_cart"]["intro_storage_candy2"] = %hijack_intro_storage_candy2_loop;
    level._id_0C59["food_cart"]["intro_storage_candy2_loop"][0] = %hijack_intro_storage_candy2_loop;
    level._id_0C59["food_cart"]["intro_storage_peanuts"] = %hijack_intro_storage_peanuts_loop;
    level._id_0C59["food_cart"]["intro_storage_peanuts_loop"][0] = %hijack_intro_storage_peanuts_loop;
    level._id_1245["door"] = #animtree;
    level._id_1F90["door"] = "generic_prop_raven";
    level._id_0C59["door"]["intro_cine_presdoor_open"] = %hijack_intro_cine_presdoor_open;
    level._id_0C59["door"]["intro_door_open"] = %hijack_intro_begin_room_door_open;
    level._id_0C59["door"]["intro_door2_worker_open"] = %hijack_intro_cine_door2_worker_open;
    level._id_0C59["door"]["intro_door2_assistant_open"] = %hijack_intro_cine_door2_assistant_open;
    level._id_0C59["door"]["intro_door3_agent_open"] = %hijack_intro_cine_door3_agent_open;
    level._id_0C59["door"]["intro_door3_agent_close"] = %hijack_intro_cine_door3_agent_close;
    level._id_0C59["door"]["debate_cine_door4_blown_off"] = %hijack_debate_cine_door4_blown_off;
    level._id_0C59["door"]["debate_cine_door3_agent_open"] = %hijack_debate_cine_door3_agent_open;
    level._id_1245["conf_chair"] = #animtree;
    level._id_0C59["conf_chair"]["intro_chair1"] = %hijack_intro_cine_chair1_swivel;
    level._id_0C59["conf_chair"]["intro_chair2"] = %hijack_intro_cine_chair2_swivel;
    level._id_0C59["conf_chair"]["intro_chair3"] = %hijack_intro_cine_chair3_swivel;
    level._id_0C59["conf_chair"]["intro_chair4"] = %hijack_intro_cine_chair4_swivel;
    level._id_0C59["conf_chair"]["intro_chair5"] = %hijack_intro_cine_chair5_swivel;
    level._id_0C59["conf_chair"]["intro_chair6"] = %hijack_intro_cine_chair6_swivel;
    level._id_0C59["conf_chair"]["debate_chair1"] = %hijack_debate_cine_chair1_swivel;
    level._id_0C59["conf_chair"]["debate_chair2"] = %hijack_debate_cine_chair2_swivel;
    level._id_0C59["conf_chair"]["debate_chair3"] = %hijack_debate_cine_chair3_swivel;
    level._id_0C59["conf_chair"]["debate_chair4"] = %hijack_debate_cine_chair4_swivel;
    level._id_0C59["conf_chair"]["debate_chair5"] = %hijack_debate_cine_chair5_swivel;
    level._id_0C59["conf_chair"]["debate_chair6"] = %hijack_debate_cine_chair6_swivel;
    level._id_0C59["conf_chair"]["debate_chair8"] = %hijack_debate_cine_chair8_swivel;
    level._id_1245["conf_roller"] = #animtree;
    level._id_1F90["conf_roller"] = "generic_prop_raven";
    level._id_0C59["conf_roller"]["debate_cine_lurchcam"] = %hijack_debate_cine_lurchcam;
    level._id_1245["phone"] = #animtree;
    level._id_0C59["phone"]["debate_phone"] = %hijack_intro_cine_phone_advisor;
    level._id_0C59["phone"]["debate_phone1_lurch"] = %hijack_debate_phone1_lurch;
    level._id_0C59["phone"]["debate_phone2_lurch"] = %hijack_debate_phone2_lurch;
    level._id_1245["debate_laptop"] = #animtree;
    level._id_0C59["debate_laptop"]["debate_laptop_lurch"] = %hijack_debate_laptop_lurch;
    level._id_1245["debate_prop"] = #animtree;
    level._id_1F90["debate_prop"] = "generic_prop_raven";
    level._id_0C59["debate_prop"]["debate_props_bck_lurch"] = %hijack_debate_props_bck_lurch;
    level._id_0C59["debate_prop"]["debate_props_frnt_lurch"] = %hijack_debate_props_frnt_lurch;
    level._id_1245["pitcher"] = #animtree;
    level._id_1F90["pitcher"] = "generic_prop_raven";
    level._id_0C59["pitcher"]["intro_cine_pitcher"] = %hijack_intro_cine_pitcher;
    level._id_0C59["pitcher"]["intro_cine_pitcher_loop"][0] = %hijack_intro_cine_pitcher_loop;
    level._id_1245["destroy_chair"] = #animtree;
    level._id_1F90["destroy_chair"] = "generic_prop_raven";
    level._id_0C59["destroy_chair"]["debate_cine_end_chair"] = %hijack_debate_cine_end_chair;
    level._id_1245["upperhall_roller"] = #animtree;
    level._id_1F90["upperhall_roller"] = "generic_prop_raven";
    level._id_0C59["upperhall_roller"]["hallway_lurchcam"] = %hijack_hallway_lurchcam;
    level._id_0C59["upperhall_roller"]["hallway_lurchcam_loop"][0] = %hijack_hallway_lurchcam_loop;
    level._id_0C59["upperhall_roller"]["hallway_godraycam"] = %hijack_hallway_godraycam;
    level._id_1245["upperhall_cabinet"] = #animtree;
    level._id_1F90["upperhall_cabinet"] = "generic_prop_raven";
    level._id_0C59["upperhall_cabinet"]["hallway_cabinet_open"] = %hijack_hallway_cabinet_open;
    level._id_0C59["upperhall_cabinet"]["hallway_cabinet_loop"][0] = %hijack_hallway_cabinet_loop;
    level._id_0C59["upperhall_cabinet"]["hallway_picture_fall"] = %hijack_hallway_picture_fall;
    level._id_1245["zerog_prop"] = #animtree;
    level._id_1F90["zerog_prop"] = "generic_prop_raven";
    level._id_0C59["zerog_prop"]["zerog_hero_prop"] = %hijack_zerog_hero_prop;
    level._id_0C59["zerog_prop"]["zerog_suitcase1"] = %hijack_zerog_suitcase1;
    level._id_0C59["zerog_prop"]["zerog_suitcase2"] = %hijack_zerog_suitcase2;
    level._id_0C59["zerog_prop"]["zerog_suitcase3"] = %hijack_zerog_suitcase3;
    level._id_0C59["zerog_prop"]["zerog_suitcase4"] = %hijack_zerog_suitcase4;
    level._id_0C59["zerog_prop"]["zerog_suitcase5"] = %hijack_zerog_suitcase5;
    level._id_0C59["zerog_prop"]["zerog_suitcase6"] = %hijack_zerog_suitcase6;
    level._id_0C59["zerog_prop"]["zerog_suitcase7"] = %hijack_zerog_suitcase7;
    level._id_0C59["zerog_prop"]["zerog_suitcase8"] = %hijack_zerog_suitcase8;
    level._id_0C59["zerog_prop"]["zerog_squarebox"] = %hijack_zerog_squarebox;
    level._id_0C59["zerog_prop"]["zerog_rectanglebox"] = %hijack_zerog_rectanglebox;
    level._id_0C59["zerog_prop"]["zerog_overhead_door_r"] = %hijack_zerog_overhead_door_r;
    level._id_0C59["zerog_prop"]["zerog_overhead_door_l"] = %hijack_zerog_overhead_door_l;
    level._id_0C59["zerog_prop"]["zerog_mealcart"] = %hijack_zerog_mealcart;
    level._id_0C59["zerog_prop"]["fire_extinguisher_enter"] = %hijack_zerog_fire_extinguisher_enter;
    level._id_0C59["zerog_prop"]["fire_extinguisher_loop"][0] = %hijack_zerog_fire_extinguisher_loop;
    level._id_1245["zerog_laptop"] = #animtree;
    level._id_0C59["zerog_laptop"]["zerog_laptop"] = %hijack_zerog_laptop;
    level._id_1245["zerog_o2_module"] = #animtree;
    level._id_0C59["zerog_o2_module"]["zerog_o2_module_r"] = %hijack_zerog_o2_module_r;
    level._id_0C59["zerog_o2_module"]["zerog_o2_module_l"] = %hijack_zerog_o2_module_l;
    level._id_1245["hanging_phone"] = #animtree;
    level._id_0C59["hanging_phone"]["phone_swaying"][0] = %hijack_phone_swaying;
    level._id_1245["cargo"] = #animtree;
    level._id_1F90["cargo"] = "generic_prop_raven";
    level._id_0C59["cargo"]["prop_bag_shift"] = %hijack_find_daughter_prop_bag_shift;
    level._id_0C59["cargo"]["prop_bag_loop"][0] = %hijack_find_daughter_prop_bag_loop;
    level._id_0C59["cargo"]["prop_ladder_shift"] = %hijack_find_daughter_prop_ladder_shift;
    level._id_0C59["cargo"]["prop_ladder_loop"][0] = %hijack_find_daughter_prop_ladder_loop;
    level._id_0C59["cargo"]["prop_box1_shift"] = %hijack_find_daughter_prop_box1_shift;
    level._id_0C59["cargo"]["prop_box1_loop"][0] = %hijack_find_daughter_prop_box1_loop;
    level._id_0C59["cargo"]["prop_box2_3_shift"] = %hijack_find_daughter_prop_box2_3_shift;
    level._id_0C59["cargo"]["prop_box2_3_loop"][0] = %hijack_find_daughter_prop_box2_3_loop;
    level._id_0C59["cargo"]["prop_sm_box2_shift"] = %hijack_find_daughter_prop_sm_box2_shift;
    level._id_0C59["cargo"]["prop_sm_box2_loop"][0] = %hijack_find_daughter_prop_sm_box2_loop;
    level._id_0C59["cargo"]["prop_sm_box1_shift"] = %hijack_find_daughter_prop_sm_box1_shift;
    level._id_0C59["cargo"]["prop_sm_box1_loop"][0] = %hijack_find_daughter_prop_sm_box1_loop;
    level._id_0C59["cargo"]["prop_propane1_shift"] = %hijack_find_daughter_prop_propane1_shift;
    level._id_0C59["cargo"]["prop_propane2_3_shift"] = %hijack_find_daughter_prop_propane2_3_shift;
    level._id_0C59["cargo"]["prop_propane2_3_loop"][0] = %hijack_find_daughter_prop_propane2_3_loop;
    level._id_0C59["cargo"]["prop_propane4_shift"] = %hijack_find_daughter_prop_propane4_shift;
    level._id_0C59["cargo"]["prop_propane4_loop"][0] = %hijack_find_daughter_prop_propane4_loop;
    level._id_0C59["cargo"]["prop_toolbox_shift"] = %hijack_find_daughter_prop_toolbox_shift;
    level._id_0C59["cargo"]["prop_toolbox_loop"][0] = %hijack_find_daughter_prop_toolbox_loop;
    level._id_0C59["cargo"]["prop_smbox3_lg6_shift"] = %hijack_find_daughter_prop_smbox3_lg6_shift;
    level._id_0C59["cargo"]["prop_smbox3_lg6_loop"][0] = %hijack_find_daughter_prop_smbox3_lg6_loop;
    level._id_0C59["generic"]["hijack_plane_crash_anim"] = %hijack_plane_crash_plane;
    level._id_0C59["generic"]["hijack_pre_plane_crash_door"] = %hijack_pre_plane_crash_door;
    level._id_0C59["generic"]["hijack_pre_plane_crash_door_close"] = %hijack_pre_plane_crash_door_close;
    level._id_0C59["generic"]["hijack_pre_plane_crash_compartments"][0] = %hijack_pre_plane_crash_compartments_loop;
    level._id_1245["pine_tree_lg"] = #animtree;
    level._id_1F90["pine_tree_lg"] = "hjk_tree_pine_lg";
    level._id_0C59["pine_tree_lg"]["crash_tree_1"] = %hijack_plane_crash_tree1;
    level._id_0C59["pine_tree_lg"]["crash_tree_2"] = %hijack_plane_crash_tree2;
    level._id_1245["pine_tree_sm"] = #animtree;
    level._id_1F90["pine_tree_sm"] = "hjk_tree_pine_sm";
    level._id_0C59["pine_tree_sm"]["crash_tree_3"] = %hijack_plane_crash_tree3;
    level._id_0C59["pine_tree_sm"]["crash_tree_4"] = %hijack_plane_crash_tree4;
    level._id_0C59["pine_tree_lg"]["crash_tree_5"] = %hijack_plane_crash_tree5;
    level._id_0C59["pine_tree_sm"]["crash_tree_6"] = %hijack_plane_crash_tree6;
    level._id_1245["crash_tower"] = #animtree;
    level._id_1F90["crash_tower"] = "hjk_control_tower";
    level._id_0C59["crash_tower"]["hijack_plane_crash_anim"] = %hijack_plane_crash_tower;
    level._id_1245["crash_tower_lights"] = #animtree;
    level._id_1F90["crash_tower_lights"] = "hjk_control_tower_lit_windows";
    level._id_0C59["crash_tower_lights"]["hijack_plane_crash_anim"] = %hijack_plane_crash_tower;
    level._id_1245["crash_engine_1"] = #animtree;
    level._id_1F90["crash_engine_1"] = "hijack_plane_crash_engine_clean";
    level._id_0C59["crash_engine_1"]["hijack_plane_crash_anim"] = %hijack_plane_crash_plane;
    level._id_1245["crash_engine_2"] = #animtree;
    level._id_1F90["crash_engine_2"] = "hijack_plane_crash_engine_damaged";
    level._id_0C59["crash_engine_2"]["hijack_plane_crash_anim"] = %hijack_plane_crash_plane;
    level._id_1245["post_crash_telephone"] = #animtree;
    level._id_0C59["post_crash_telephone"]["telephone_swing"] = %hijack_tarmac_telephone_swing;
    level._id_1F90["plane_crash_lights_on_front"] = "hijack_plane_crash_front_interior";
    level._id_1F90["plane_crash_lights_off_front"] = "hijack_plane_crash_front_interior_lightsoff";
    level._id_1F90["plane_crash_lights_on_rear"] = "hijack_plane_crash_rear_interior";
    level._id_1F90["plane_crash_lights_off_rear"] = "hijack_plane_crash_rear_interior_lightsoff";
    level._id_1245["post_crash_prop"] = #animtree;
    level._id_1F90["post_crash_prop"] = "generic_prop_raven";
    level._id_0C59["post_crash_prop"]["post_crash_locker1"] = %hijack_post_crash_locker1;
    level._id_0C59["post_crash_prop"]["post_crash_locker2"] = %hijack_post_crash_locker2;
    level._id_0C59["post_crash_prop"]["post_crash_locker3"] = %hijack_post_crash_locker3;
    level._id_0C59["post_crash_prop"]["post_crash_locker4"] = %hijack_post_crash_locker4;
    level._id_0C59["post_crash_prop"]["post_crash_locker5"] = %hijack_post_crash_locker5;
    level._id_0C59["post_crash_prop"]["post_crash_locker6"] = %hijack_post_crash_locker6;
    level._id_0C59["post_crash_prop"]["post_crash_locker7"] = %hijack_post_crash_locker7;
    level._id_0C59["post_crash_prop"]["post_crash_locker8"] = %hijack_post_crash_locker8;
    level._id_0C59["post_crash_prop"]["post_crash_locker9"] = %hijack_post_crash_locker9;
    level._id_0C59["post_crash_prop"]["post_crash_locker10"] = %hijack_post_crash_locker10;
    level._id_0C59["post_crash_prop"]["post_crash_locker11"] = %hijack_post_crash_locker11;
    level._id_0C59["post_crash_prop"]["post_crash_locker12"] = %hijack_post_crash_locker12;
    level._id_0C59["post_crash_prop"]["post_crash_locker13"] = %hijack_post_crash_locker13;
    level._id_0C59["post_crash_prop"]["post_crash_locker14"] = %hijack_post_crash_locker14;
    level._id_0C59["post_crash_prop"]["post_crash_locker15"] = %hijack_post_crash_locker15;
    level._id_0C59["post_crash_prop"]["post_crash_locker16"] = %hijack_post_crash_locker16;
    level._id_0C59["post_crash_prop"]["post_crash_locker17"] = %hijack_post_crash_locker17;
    level._id_0C59["post_crash_prop"]["post_crash_locker18"] = %hijack_post_crash_locker18;
    level._id_0C59["post_crash_prop"]["post_crash_locker19"] = %hijack_post_crash_locker19;
    level._id_0C59["post_crash_prop"]["post_crash_locker20"] = %hijack_post_crash_locker20;
    level._id_0C59["post_crash_prop"]["post_crash_locker21"] = %hijack_post_crash_locker21;
    level._id_0C59["post_crash_prop"]["post_crash_drawer1"] = %hijack_post_crash_drawer1;
    level._id_0C59["post_crash_prop"]["post_crash_drawer2"] = %hijack_post_crash_drawer2;
    level._id_0C59["post_crash_prop"]["post_crash_ladder"] = %hijack_post_crash_ladder;
    level._id_0C59["post_crash_prop"]["post_crash_tire"] = %hijack_post_crash_tire;
    level._id_0C59["post_crash_prop"]["post_crash_crate"] = %hijack_post_crash_crate;
    level._id_0C59["post_crash_prop"]["post_crash_pipe_small"] = %hijack_post_crash_pipe_small;
    level._id_0C59["post_crash_prop"]["post_crash_pipe_large"] = %hijack_post_crash_pipe_large;
    level._id_1245["engine"] = #animtree;
    level._id_0C59["engine"]["engine_spin"] = %hijack_tarmac_turbine_spin;
    level._id_0C59["engine"]["engine_spin_slow"] = %hijack_tarmac_turbine_spin_slow;
    level._id_1245["daughter_blanket"] = #animtree;
    level._id_1F90["daughter_blanket"] = "hjk_blanket_anim";
    level._id_0C59["daughter_blanket"]["secure_daughter"] = %hijack_secure_daughter_blanket;
    level._id_0C59["daughter_blanket"]["secure_daughter_loop"][0] = %hijack_secure_daughter_blanket_end_loop;
    level._id_1245["tail_prop"] = #animtree;
    level._id_1F90["tail_prop"] = "generic_prop_raven";
    level._id_0C59["tail_prop"]["plane_tail_collapse"] = %hijack_tarmac_plane_tail_collapse;
    level._id_1245["plane_seats"] = #animtree;
    level._id_1F90["plane_seats"] = "generic_prop_raven";
    level._id_0C59["plane_seats"]["buried_prop"] = %hijack_tarmac_buried_prop;
    level._id_1245["metal_beam"] = #animtree;
    level._id_1F90["metal_beam"] = "generic_prop_raven";
    level._id_0C59["metal_beam"]["trapped_prop"] = %hijack_tarmac_trapped_prop;
    level._id_1245["makarov_heli_door"] = #animtree;
    level._id_0C59["makarov_heli_door"]["end_part4"] = %hijack_ending_reveal_heli;
}
#using_animtree("vehicles");

_id_47DE()
{
    level._id_1245["makarov_heli"] = #animtree;
    level._id_0C59["makarov_heli"]["end_part4"] = %hijack_ending_reveal_heli;
}
#using_animtree("generic_human");

_id_5B49()
{
    var_0 = [];
    var_0[0] = 2;
    var_0[1] = 1;
    var_0[2] = 1;
    var_0[3] = 1;
    var_1 = [];
    var_1[0] = 7;
    var_1[1] = 3;
    var_2 = common_scripts\utility::get_cumulative_weights( var_1 );
    level._id_0C59["president"]["civilian_stand_idle"][0] = %hijack_president_idle_panic;
    level._id_0C59["president"]["run_noncombat"][0] = %hijack_president_run_panic;
    level._id_0C59["president"]["run_noncombat"][1] = %hijack_president_run_panic;
    level._id_0C59["president"]["run_weights"] = var_2;
    level._id_0C59["president"]["turn_left_45"] = %hijack_president_run_panic_turnl45;
    level._id_0C59["president"]["turn_right_45"] = %hijack_president_run_panic_turnr45;
    level._id_0C59["president"]["turn_left_90"] = %hijack_president_run_panic_turnl90;
    level._id_0C59["president"]["turn_right_90"] = %hijack_president_run_panic_turnr90;
    level._id_0C59["president"]["idle_noncombat"][0] = %hijack_president_idle_panic;
    level._id_0C59["president"]["idle_combat"][0] = %hijack_president_idle_panic;
    level._id_0C59["president"]["run_combat"][0] = %hijack_president_run_panic;
}

_id_5A83()
{
    self._id_0C89 = [];
    self._id_0C89["stand"] = %hijack_president_idle_panic;
}

_id_5A84( var_0 )
{
    var_1 = undefined;

    if ( var_0 < -22.5 && var_0 >= -70 )
        var_1 = level._id_0C59[self._id_1032]["turn_left_45"];

    if ( var_0 < -70 && var_0 > -120 )
        var_1 = level._id_0C59[self._id_1032]["turn_left_90"];

    if ( var_0 > 22.5 && var_0 <= 70 )
        var_1 = level._id_0C59[self._id_1032]["turn_right_45"];

    if ( var_0 > 70 && var_0 < 120 )
        var_1 = level._id_0C59[self._id_1032]["turn_right_90"];

    if ( isdefined( var_1 ) && animscripts\move::_id_10C4( var_1 ) )
        return var_1;
    else
        return undefined;
}

_id_5B4A()
{
    self._id_0C89 = [];
    self._id_0C89["stand"] = %hijack_tarmac_relaxed_idle_commander;
}
