// IW5 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool

main()
{
    _id_4069();
    _id_6838();
    _id_6839();
    _id_683A();
    _id_683E();
}
#using_animtree("generic_human");

_id_4069()
{
    level.scr_sound["soap"]["payback_mct_targetsite"] = "payback_mct_targetsite";
    level.scr_sound["price"]["payback_pri_throughgate"] = "payback_pri_throughgate";
    level.scr_sound["price"]["payback_pri_softenhim"] = "payback_pri_softenhim";
    level._id_11BB["payback_nik_misslesaway"] = "payback_nik_misslesaway";
    level.scr_sound["price"]["payback_pri_targetsahead"] = "payback_pri_targetsahead";
    level._id_11BB["payback_mrc3_mortarteams"] = "payback_mrc3_mortarteams";
    level._id_11BB["payback_mrc3_destroy"] = "payback_mrc3_destroy";
    level._id_11BB["payback_mrc3_mainhouse"] = "payback_mrc3_mainhouse";
    level._id_11BB["payback_mrc3_gunemplacements"] = "payback_mrc3_gunemplacements";
    level._id_11BB["payback_mrc3_reinforcements"] = "payback_mrc3_reinforcements";
    level._id_11BB["payback_mrc1_alltroops"] = "payback_mrc1_alltroops";
    level._id_11BB["payback_pri_staywithteam"] = "payback_pri_staywithteam";
    level.scr_sound["soap"]["payback_mct_takedown_r"] = "payback_mct_takeemdown";
    level.scr_sound["soap"]["payback_mct_tagetusmorters_r"] = "payback_mct_usingmortars";
    level.scr_sound["price"]["payback_pri_weneedair_r"] = "payback_pri_needsupport";
    level._id_11BB["payback_nik_movinginto_r"] = "payback_nik_intoposition";
    level.scr_sound["price"]["payback_pri_yougotcontrol_r"] = "payback_pri_gotcontrol";
    level._id_11BB["payback_nik_additonalhostiles_r"] = "payback_nik_hostilesnorth";
    level.scr_sound["price"]["payback_pri_sweepunder"] = "payback_pri_sweepunder";
    level.scr_sound["price"]["payback_pri_laydowncovering"] = "payback_pri_laydowncovering";
    level.scr_sound["price"]["payback_pri_techincalscoming_r"] = "payback_pri_technicals";
    level._id_11BB["payback_nik_morehostiles_r"] = "payback_nik_outofbuildings";
    level._id_11BB["payback_nik_enemytroops_r"] = "payback_nik_crossingroad";
    level._id_11BB["payback_nik_additonalforces_r"] = "payback_nik_closingin";
    level.scr_sound["price"]["payback_pri_advancetotarget"] = "payback_pri_advancetotarget";
    level.scr_sound["price"]["payback_pri_pinneddown"] = "payback_pri_pinneddown";
    level.scr_sound["price"]["payback_pri_getwaraabe"] = "payback_pri_getwaraabe";
    level.scr_sound["soap"]["payback_mct_targetbuilding"] = "payback_mct_targetbuilding";
    level.scr_sound["soap"]["payback_mct_findwaraabe"] = "payback_mct_findwaraabe";
    level.scr_sound["price"]["payback_pri_cmonletsget"] = "payback_pri_cmonletsget";
    level.scr_sound["price"]["payback_pri_yurimoveit"] = "payback_pri_yurimoveit";
    level.scr_sound["price"]["payback_pri_letsgocmon"] = "payback_pri_letsgocmon";
    level._id_11BB["payback_nik_inposition"] = "payback_nik_inposition";
    level._id_11BB["payback_nik_ready"] = "payback_nik_ready";
    level._id_11BB["payback_nik_gunrun"] = "payback_nik_gunrun";
    level._id_11BB["payback_nik_gunonline"] = "payback_nik_gunonline";
    level._id_11BB["payback_nik_useremotegun"] = "payback_nik_useremotegun";
    level._id_11BB["payback_nik_imready"] = "payback_nik_imready";
    level._id_11BB["payback_nik_activategun"] = "payback_nik_activategun";
    level._id_11BB["payback_nik_maneuvering"] = "payback_nik_maneuvering";
    level._id_11BB["payback_nik_circling"] = "payback_nik_circling";
    level._id_11BB["payback_nik_anotherstrafing"] = "payback_nik_anotherstrafing";
    level._id_11BB["payback_nik_flyback"] = "payback_nik_flyback";
    level._id_11BB["payback_nik_comingback"] = "payback_nik_comingback";
    level._id_11BB["payback_nik_swingaround"] = "payback_nik_swingaround";
    level._id_11BB["payback_nik_anotherpass"] = "payback_nik_anotherpass";
    level._id_11BB["payback_pri_killsconfirmed"] = "payback_pri_killsconfirmed";
    level._id_11BB["payback_pri_confirmedkill"] = "payback_pri_confirmedkill";
    level._id_11BB["payback_pri_vehicledestroyed"] = "payback_pri_vehicledestroyed";
    level._id_11BB["payback_pri_welldoneyuri"] = "payback_pri_welldoneyuri";
    level._id_11BB["payback_pri_multipleconfirmed"] = "payback_pri_multipleconfirmed";
    level._id_11BB["payback_pri_roundsdown"] = "payback_pri_roundsdown";
    level._id_11BB["payback_nik_goodkills"] = "payback_nik_goodkills";
    level._id_11BB["payback_nik_targetsdown"] = "payback_nik_targetsdown";
    level._id_11BB["payback_nik_niceshooting"] = "payback_nik_niceshooting";
    level._id_11BB["payback_nik_multiplekills"] = "payback_nik_multiplekills";
    level._id_11BB["payback_pri_atleastthree"] = "payback_pri_atleastthree";
    level._id_11BB["payback_pri_fivedown"] = "payback_pri_fivedown";
    level._id_11BB["payback_pri_sixmorekills"] = "payback_pri_sixmorekills";
    level._id_11BB["payback_pri_eightpluskills"] = "payback_pri_eightpluskills";
    level._id_11BB["payback_nik_thatwasclose"] = "payback_nik_thatwasclose";
    level._id_11BB["payback_nik_aimisbetter"] = "payback_nik_aimisbetter";
    level._id_11BB["payback_nik_almosthit"] = "payback_nik_almosthit";
    level._id_11BB["payback_nik_luckholds"] = "payback_nik_luckholds";
    level.scr_sound["soap"]["payback_mct_tearingus"] = "payback_mct_tearingus";
    level.scr_sound["price"]["payback_pri_yuriremotegun"] = "payback_pri_yuriremotegun";
    level.scr_sound["price"]["payback_pri_bravoteamsecure_r"] = "payback_pri_secureperimeter";
    level.scr_sound["price"]["payback_pri_baseplatetarget"] = "payback_pri_baseplatetarget";
    level._id_11BB["payback_eol_prepforexfil"] = "payback_eol_prepforexfil";
    level.scr_sound["price"]["payback_pri_clearleft1_r"] = "payback_pri_clearleft2";
    level.scr_sound["soap"]["payback_mct_clearright1_r"] = "payback_mct_clearright2";
    level.scr_sound["price"]["payback_pri_wahtthecorners_r"] = "payback_pri_watchthosecorners";
    level.scr_sound["price"]["payback_pri_firstfloorclear"] = "payback_pri_firstfloorclear";
    level._id_11BB["payback_eol_proceedtosecond"] = "payback_eol_proceedtosecond";
    level.scr_sound["price"]["payback_pri_watchyourcorners"] = "payback_pri_watchyourcorners";
    level.scr_sound["price"]["payback_pri_contactfront"] = "payback_pri_contactfront";
    level._id_11BB["payback_nik_2ndflrbalcony"] = "payback_nik_2ndflrbalcony";
    level._id_11BB["payback_eol_2ndfloor"] = "payback_eol_2ndfloor";
    level.scr_sound["price"]["payback_pri_bravooneposition"] = "payback_pri_bravooneposition";
    level._id_11BB["payback_brvl_flankingtoback"] = "payback_brvl_flankingtoback";
    level.scr_sound["price"]["payback_pri_office"] = "payback_pri_office";
    level.scr_sound["price"]["payback_pri_doortooffice"] = "payback_pri_doortooffice";
    level.scr_sound["price"]["payback_pri_needhimalive2"] = "payback_pri_needhimalive2";
    level.scr_sound["waraabe"]["payback_wrb_mycar"] = "payback_wrb_mycar";
    level.scr_sound["waraabe"]["payback_mrc1_driver"] = "payback_mrc1_driver";
    level.scr_sound["waraabe"]["payback_wrb_fiveminutes"] = "payback_wrb_fiveminutes";
    level.scr_sound["waraabe"]["payback_mrc1_dontknow"] = "payback_mrc1_dontknow";
    level.scr_sound["waraabe"]["payback_wrb_leavenow"] = "payback_wrb_leavenow";
    level.scr_sound["waraabe"]["payback_mrc1_heresoon"] = "payback_mrc1_heresoon";
    level.scr_sound["waraabe"]["payback_wrb_trapped"] = "payback_wrb_trapped";
    level.scr_sound["price"]["payback_pri_krugerbroke"] = "payback_pri_krugerbroke";
    level._id_11BB["payback_nik_lzlooksclear"] = "payback_nik_lzlooksclear";
    level.scr_sound["price"]["payback_pri_20seconds"] = "payback_pri_20seconds";
    level.scr_sound["soap"]["payback_mct_massive"] = "payback_mct_massive";
    level.scr_sound["price"]["payback_pri_nightmare"] = "payback_pri_nightmare";
    level.scr_sound["soap"]["payback_mct_tellingtruth"] = "payback_mct_tellingtruth";
    level.scr_sound["price"]["payback_pri_tellingtruth"] = "payback_pri_tellingtruth";
    level.scr_sound["price"]["payback_pri_makingplans"] = "payback_pri_makingplans";
    level.scr_sound["price"]["payback_pri_checkleft"] = "payback_pri_checkleft";
    level.scr_sound["soap"]["payback_mct_clear2"] = "payback_mct_clear2";
    level.scr_sound["price"]["payback_pri_watchrooftops"] = "payback_pri_watchrooftops";
    level.scr_sound["price"]["payback_pri_gottamove"] = "payback_pri_gottamove";
    level.scr_sound["soap"]["payback_mct_sniper"] = "payback_mct_sniper";
    level.scr_sound["price"]["payback_pri_takecover"] = "payback_pri_takecover";
    level.scr_sound["soap"]["payback_mct_ambush"] = "payback_mct_ambush";
    level.scr_sound["soap"]["payback_mct_spreadout"] = "payback_mct_spreadout";
    level.scr_sound["price"]["payback_pri_outtatheopen"] = "payback_pri_outtatheopen";
    level.scr_sound["soap"]["payback_mct_movemove"] = "payback_mct_movemove";
    level.scr_sound["price"]["payback_pri_outofhere"] = "payback_pri_outofhere";
    level.scr_sound["price"]["payback_pri_contactright"] = "payback_pri_contactright";
    level.scr_sound["soap"]["payback_mct_rooftops"] = "payback_mct_rooftops";
    level.scr_sound["price"]["payback_pri_nikolaisecondary"] = "payback_pri_nikolaisecondary";
    level._id_11BB["payback_nik_sandstormcoming"] = "payback_nik_sandstormcoming";
    level.scr_sound["price"]["payback_pri_justbethere"] = "payback_pri_justbethere";
    level.scr_sound["price"]["payback_pri_beforethestorm"] = "payback_pri_beforethestorm";
    level.scr_sound["price"]["payback_pri_crossstreets"] = "payback_pri_crossstreets";
    level._id_11BB["payback_nik_enemiesclosing"] = "payback_nik_enemiesclosing";
    level.scr_sound["price"]["payback_pri_moreonroof"] = "payback_pri_moreonroof";
    level.scr_sound["price"]["payback_pri_keeppushing"] = "payback_pri_keeppushing";
    level.scr_sound["price"]["payback_pri_lzisclose"] = "payback_pri_lzisclose";
    level.scr_sound["price"]["payback_pri_alloverus"] = "payback_pri_alloverus";
    level._id_11BB["payback_nik_winds"] = "payback_nik_winds";
    level.scr_sound["price"]["payback_pri_ontheway"] = "payback_pri_ontheway";
    level.scr_sound["soap"]["payback_mct_contactfront"] = "payback_mct_contactfront";
    level.scr_sound["price"]["payback_pri_lzinsight"] = "payback_pri_lzinsight";
    level._id_11BB["payback_nik_movefast"] = "payback_nik_movefast";
    level.scr_sound["price"]["payback_pri_thewall"] = "payback_pri_thewall";
    level.scr_sound["price"]["payback_pri_topfloor"] = "payback_pri_topfloor";
    level.scr_sound["price"]["payback_pri_1stfloorclear2"] = "payback_pri_1stfloorclear2";
    level.scr_sound["price"]["payback_pri_watchit"] = "payback_pri_watchit";
    level._id_11BB["payback_nik_startingmyapproach"] = "payback_nik_startingmyapproach";
    level.scr_sound["price"]["payback_pri_meetyouattop"] = "payback_pri_meetyouattop";
    level.scr_sound["price"]["payback_pri_2ndfloorclear"] = "payback_pri_2ndfloorclear";
    level.scr_sound["price"]["payback_pri_whereareyou"] = "payback_pri_whereareyou";
    level._id_11BB["payback_nik_almostthere"] = "payback_nik_almostthere";
    level._id_11BB["payback_nik_sitetoohot"] = "payback_nik_sitetoohot";
    level.scr_sound["price"]["payback_pri_turret"] = "payback_pri_turret";
    level._id_11BB["payback_nik_imhit"] = "payback_nik_imhit";
    level.scr_sound["price"]["payback_pri_outofcontrol"] = "payback_pri_outofcontrol";
    level.scr_sound["price"]["payback_pri_getoffroof"] = "payback_pri_getoffroof";
    level.scr_sound["price"]["payback_pri_useropes"] = "payback_pri_useropes";
    level.scr_sound["soap"]["payback_mct_jumpforit"] = "payback_mct_jumpforit";
    level.scr_sound["soap"]["payback_mct_jump"] = "payback_mct_jump";
    level._id_11BB["payback_nik_goingdown"] = "payback_nik_goingdown";
    level.scr_sound["price"]["payback_pri_cmonlads"] = "payback_pri_cmonlads";
    level._id_11BB["payback_pri_vehiclecoming_r"] = "payback_pri_vehiclecoming";
    level._id_11BB["payback_mct_cantsee_r"] = "payback_mct_cantsee";
    level.scr_sound["price"]["payback_pri_holdup"] = "payback_pri_holdup";
    level.scr_sound["price"]["payback_pri_takeemout"] = "payback_pri_takeemout";
    level.scr_sound["price"]["payback_pri_echoteam2"] = "payback_pri_echoteam2";
    level._id_11BB["payback_eol_locatedchopper"] = "payback_eol_locatedchopper";
    level.scr_sound["price"]["payback_pri_meetatcrash"] = "payback_pri_meetatcrash";
    level._id_11BB["payback_eol_rogerthat2"] = "payback_eol_rogerthat2";
    level._id_11BB["payback_afr_thisway"] = "payback_mrc1_foundchopper";
    level._id_11BB["payback_pri_getdown_r"] = "payback_pri_getdown";
    level._id_11BB["payback_afm_keepsearching"] = "payback_afm_keepsearching";
    level._id_11BB["payback_pri_foundnikolai_r"] = "payback_pri_foundnikolai";
    level._id_11BB["payback_tm2_reachednikolai"] = "payback_tm2_reachednikolai";
    level.scr_sound["price"]["payback_pri_hangon"] = "payback_pri_hangon";
    level._id_11BB["payback_afm_hurry"] = "payback_afm_hurry";
    level.scr_sound["price"]["payback_mct_headingfornik"] = "payback_mct_headingfornik";
    level.scr_sound["price"]["payback_pri_dropem"] = "payback_pri_dropem";
    level.scr_sound["soap"]["payback_mct_theresnikschopper"] = "payback_mct_theresnikschopper";
    level.scr_sound["price"]["payback_pri_echoteampinned"] = "payback_pri_echoteampinned";
    level.scr_sound["price"]["payback_pri_fromnorthwest"] = "payback_pri_fromnorthwest";
    level._id_11BB["payback_eol_copythat"] = "payback_eol_copythat";
    level.scr_sound["price"]["payback_pri_goodtoseeyou"] = "payback_pri_goodtoseeyou";
    level.scr_sound["rescue_echo_1"]["payback_eol_twovehicles"] = "payback_eol_twovehicles";
    level.scr_sound["price"]["payback_pri_suppress"] = "payback_pri_suppress";
    level.scr_sound["price"]["payback_pri_getnikolai"] = "payback_pri_getnikolai";
    level.scr_sound["price"]["payback_pri_grabnikolai"] = "payback_pri_grabnikolai";
    level.scr_sound["price"]["payback_pri_waitingfor"] = "payback_pri_waitingfor";
    level._id_11BB["payback_pri_wheregoing"] = "payback_pri_wheregoing";
    level._id_11BB["payback_pri_getbackhere2"] = "payback_pri_getbackhere2";
    level.scr_sound["price"]["payback_pri_moveout4"] = "payback_pri_moveout4";
    level.scr_sound["price"]["payback_pri_headingtoexfil"] = "payback_pri_headingtoexfil";
    level.scr_sound["price"]["payback_pri_gettoexfil"] = "payback_pri_gettoexfil";
    level.scr_sound["soap"]["payback_mct_followme"] = "payback_mct_followme";
    level.scr_sound["price"]["payback_pri_comeonyuri"] = "payback_pri_comeonyuri";
    level.scr_sound["soap"]["payback_mct_iseethem"] = "payback_mct_iseethem";
    level.scr_sound["price"]["payback_pri_yurithisway"] = "payback_pri_yurithisway";
    level.scr_sound["soap"]["payback_mct_keepmoving2"] = "payback_mct_keepmoving2";
    level.scr_sound["rescue_echo_1"]["payback_eol_approachingexfil"] = "payback_eol_approachingexfil";
    level.scr_sound["rescue_echo_1"]["payback_eol_letsgo"] = "payback_eol_letsgo";
    level._id_6837["rescue_echo_1"]["payback_eol_marker"] = "payback_eol_marker";
    level.scr_sound["price"]["payback_pri_letsgoyuri"] = "payback_pri_letsgoyuri";
    level.scr_sound["escape_jeep_1_driver"]["payback_eol_glad"] = "payback_eol_glad";
    level._id_11BB["payback_mct_inparis"] = "payback_mct_inparis";
    level.scr_sound["price"]["payback_pri_iknowwho"] = "payback_pri_iknowwho";
    level._id_11BB["payback_pri_moveout_r"] = "payback_pri_moveout3";
    level._id_11BB["payback_mct_deadahead_r"] = "payback_mct_hostiledeadahead";
    level._id_11BB["payback_mct_thatwaseasy_r"] = "payback_mct_thatwaseasy2";
    level._id_11BB["payback_mct_wereclear_r"] = "payback_mct_wereclear2";
    level._id_11BB["payback_mct_theyknow_r"] = "payback_mct_theyknow";
    level._id_11BB["payback_pri_deadahead_r"] = "payback_pri_deadahead";
    level._id_0C59["soap"]["soap_shoots_from_hummer"] = %payback_gatecrasher_intro_soap;
    maps\_anim::_id_1264( "soap", "gun_2_right", maps\payback_1_script_a::_id_6825 );
    maps\_anim::_id_1264( "soap", "gun_2_left", maps\payback_1_script_a::_id_6826 );
    level._id_0C59["soap"]["intro_soap"] = %payback_intro_soap;
    level._id_0C59["soap"]["intro_soap_stand"] = %payback_gatecrasher_intro_soap;
    level._id_0C59["soap"]["intro_soap_stand_idle"] = %payback_gatecrasher_intro_soap_idle;
    level._id_0C59["soap"]["intro_soap_stand_end"] = %payback_gatecrasher_intro_soap_exit;
    level._id_0C59["price"]["intro_price"] = %payback_intro_price;
    level._id_0C59["price"]["intro_price_shift_up"] = %payback_intro_shift_up;
    level._id_0C59["price"]["intro_price_shift_down"] = %payback_intro_shift_down;
    level._id_0C59["price"]["intro_price_getout"] = %payback_intro_dismount_price;
    level._id_0C59["generic"]["intro_civilian_A_run"] = %freerunnera_loop;
    level._id_0C59["generic"]["intro_civilian_B_run"] = %freerunnera_loop;
    level._id_0C59["price"]["intro_jump_react"] = %payback_intro_turn_driver;
    level._id_0C59["soap"]["intro_jump_react"] = %payback_intro_turn_passenger;
    level._id_0C59["Hannibal"]["intro_jump_react"] = %payback_intro_turn_driver;
    level._id_0C59["Murdock"]["intro_jump_react"] = %payback_intro_turn_passenger;
    level._id_0C59["price_killguy_1"]["intro_price_shoots_guys"] = %payback_gatecrash_enemy_death_1;
    level._id_0C59["price_killguy_2"]["intro_price_shoots_guys"] = %payback_gatecrash_enemy_death_2;
    level._id_0C59["Murdock"]["bravo_intro_signal"] = %payback_intro_bravo_thumbs_up;
    level._id_0C59["Barracus"]["bravo_intro_stand"] = %payback_intro_bravo_standup;
    level._id_0C59["Barracus"]["bravo_intro_stand_idle"] = %payback_intro_bravo_standup_idle;
    level._id_0C59["Barracus"]["bravo_intro_stand_turn"] = %payback_intro_bravo_turn_back;
    level._id_0C59["Barracus"]["bravo_intro_stand_idle_2"] = %payback_intro_bravo_standup_idle_2;
    level._id_0C59["Barracus"]["bravo_intro_stand_gatecrash"] = %payback_intro_bravo_gatecrash_back;
    level._id_0C59["gate_guy_left"]["gate_close"] = %payback_gatecrash_closegate_l;
    level._id_0C59["gate_guy_right"]["gate_close"] = %payback_gatecrash_closegate_r;
    level._id_0C59["gate_guy_left"]["gate_close_dive"] = %payback_gatecrash_dive_l;
    level._id_0C59["gate_guy_right"]["gate_close_dive"] = %payback_gatecrash_dive_r;
    level._id_0C59["generic"]["gate_guy_anim"][0] = %exposed_idle_twitch_v2;
    level._id_0C59["generic"]["london_kickout_window_kick_reaction"] = %london_kickout_window_kick_reaction;
    level._id_0C59["generic"]["payback_docks_table_enemy1"] = %payback_docks_table_enemy1;
    level._id_0C59["generic"]["payback_docks_table_enemy2"] = %payback_docks_table_enemy2;
    level._id_0C59["generic"]["payback_docks_get_rpg_enemy"] = %payback_docks_get_rpg_enemy;
    level._id_0C59["generic"]["payback_docks_drag_body1"] = %payback_docks_drag_body1;
    level._id_0C59["generic"]["payback_docks_drag_body2"] = %payback_docks_drag_body2;
    level._id_0C59["generic"]["payback_comp_balcony_kick_enemy"] = %payback_comp_balcony_kick_enemy;
    level._id_0C59["soap"]["payback_comp_balcony_kick_soap"] = %payback_comp_balcony_kick_soap;
    level._id_0C59["generic"]["doorkick_2_stand"] = %doorkick_2_stand;
    level._id_0C59["price"]["payback_coverstand_trans_IN_R"] = %coverstand_trans_in_r;
    level._id_0C59["price"]["payback_coverstand_look_moveup"] = %coverstand_look_moveup;
    level._id_0C59["price"]["payback_coverstand_look_idle"][0] = %coverstand_look_idle;
    level._id_0C59["soap"]["payback_corner_standL_trans_IN_2"] = %corner_standl_trans_in_2;
    level._id_0C59["soap"]["payback_corner_standl_alert_idle"][0] = %corner_standl_alert_idle;
    level._id_0C59["price"]["waraabe_interrogation"] = %payback_interrogation_price_new;
    maps\_anim::_id_1264( "price", "unhide_mask_1", maps\payback_1_script_e::_id_667F, "waraabe_interrogation" );
    maps\_anim::_id_1264( "price", "unhide_mask_3", maps\payback_1_script_e::_id_6681, "waraabe_interrogation" );
    maps\_anim::_id_1264( "price", "activate_gas_can", maps\payback_1_script_e::_id_6683, "waraabe_interrogation" );
    maps\_anim::_id_1264( "price", "hide_mask_1", maps\payback_1_script_e::_id_6688, "waraabe_interrogation" );
    maps\_anim::_id_1264( "price", "price_holster_mg", maps\payback_1_script_e::_id_668A, "waraabe_interrogation" );
    maps\_anim::_id_1264( "price", "price_unholster_pistol", maps\payback_1_script_e::_id_668C, "waraabe_interrogation" );
    maps\_anim::_id_1264( "price", "price_shoot_pistol", maps\payback_1_script_e::_id_668E, "waraabe_interrogation" );
    maps\_anim::_id_1264( "price", "price_holster_pistol", maps\payback_1_script_e::_id_668F, "waraabe_interrogation" );
    maps\_anim::_id_1264( "price", "price_unholster_mg", maps\payback_1_script_e::_id_6690, "waraabe_interrogation" );
    maps\_anim::_id_1264( "price", "swap_model", maps\payback_1_script_e::_id_6666, "waraabe_interrogation" );
    level._id_0C59["kruger"]["waraabe_breach"] = %payback_breach_warrabe;
    maps\_anim::_id_1264( "kruger", "shot_in_leg", maps\payback_1_script_e::_id_6668, "waraabe_breach" );
    level._id_0C59["kruger"]["waraabe_breach_injured_loop"][0] = %payback_breach_warrabe_loop;
    level._id_0C59["kruger"]["payback_interrogation_warrabe"] = %payback_interrogation_warrabe;
    maps\_anim::_id_1264( "kruger", "wound_stomp", maps\payback_1_script_e::_id_666A, "payback_interrogation_warrabe" );
    level._id_0C59["kruger"]["payback_interrogation_warrabe_death_loop"][0] = %payback_interrogation_warrabe_death_loop;
    level._id_0C59["kruger"]["waraabe_death_ground"] = %payback_interrogation_death_on_ground_warrabe;
    level._id_0C59["kruger"]["waraabe_death_crate"] = %payback_interrogation_death_on_crates_warrabe;
    level._id_0C59["generic"]["payback_breach_gunrack_guy"] = %payback_breach_gunrack_guy;
    level._id_0C59["generic"]["payback_breach_crateguy"] = %payback_breach_crateguy;
    level._id_0C59["generic"]["payback_breach_doorguy"] = %payback_breach_doorguy;
    level._id_0C59["generic"]["payback_breach_react_soldier_4"] = %payback_breach_react_soldier_4;
    level._id_0C59["generic"]["payback_breach_pushedguy"] = %payback_breach_pushedguy;
    level._id_0C59["generic"]["generic_death"] = %exposed_death_falltoknees_02;
    level._id_0C59["generic"]["generic_death_2"] = %exposed_death_blowback;
    level._id_0C59["soap"]["waraabe_interrogation"] = %payback_interrogation_soap_new;
    maps\_anim::_id_1264( "soap", "unhide_mask_2", maps\payback_1_script_e::_id_6680, "waraabe_interrogation" );
    maps\_anim::_id_1264( "soap", "unhide_gas_can", maps\payback_1_script_e::_id_6682, "waraabe_interrogation" );
    maps\_anim::_id_1264( "soap", "hide_mask_2", maps\payback_1_script_e::_id_6689, "waraabe_interrogation" );
    maps\_anim::_id_1264( "soap", "open_door_2", maps\payback_1_script_e::_id_668B, "waraabe_interrogation" );
    level._id_0C59["generic"]["arcadia_ending_sceneA_enemy2_death_pose"] = %arcadia_ending_scenea_enemy2_death_pose;
    level._id_0C59["generic"]["ch_pragueb_civ_escalator_12_a_death_pose"] = %ch_pragueb_civ_escalator_12_a_death_pose;
    level._id_0C59["generic"]["ch_pragueb_civ_escalator_12_b_death_pose"] = %ch_pragueb_civ_escalator_12_b_death_pose;
    level._id_0C59["generic"]["ch_pragueb_civ_escalator_12_c_death_pose"] = %ch_pragueb_civ_escalator_12_c_death_pose;
    level._id_0C59["generic"]["wall_fall_a"] = %payback_const_wall_fall_reaction_a;
    level._id_0C59["generic"]["wall_fall_b"] = %payback_const_wall_fall_reaction_b;
    level._id_0C59["generic"]["stand_exposed_extendedpain_hip_2_crouch"] = %stand_exposed_extendedpain_hip_2_crouch;
    level._id_0C59["generic"]["chopper_dive"] = %exposed_dive_grenade_b;
    level._id_0C59["price"]["exposed_crouch_turn_90_right"] = %exposed_crouch_turn_90_right;
    level._id_0C59["price"]["exposed_crouch_turn_180_right"] = %exposed_crouch_turn_180_right;
    level._id_0C59["soap"]["exposed_crouch_turn_90_left"] = %exposed_crouch_turn_90_left;
    level._id_0C59["soap"]["exposed_crouch_turn_180_left"] = %exposed_crouch_turn_180_left;
    level._id_0C59["price"]["const_top"] = %payback_const_top_price;
    level._id_0C59["generic"]["death_run_forward_crumple"] = %death_run_forward_crumple;
    level._id_0C59["generic"]["death_stand_dropinplace"] = %death_stand_dropinplace;
    level._id_0C59["generic"]["death_explosion_stand_R_v1"] = %death_explosion_stand_r_v1;
    level._id_0C59["generic"]["death_explosion_right13"] = %death_explosion_right13;
    level._id_0C59["generic"]["nikolai_in_heli_loop"][0] = %helicopter_pilot1_idle;
    level._id_0C59["generic"]["payback_city_pushcar_left"] = %payback_city_truck_push_a;
    level._id_0C59["generic"]["payback_city_pushcar_right"] = %payback_city_truck_push_b;
    level._id_0C59["soap"]["payback_const_rappel_soap_wave"] = %payback_escape_forward_wave_right_price;
    level._id_0C59["soap"]["const_rappel_soap"] = %payback_const_rappel_soap;
    maps\_anim::_id_1264( "soap", "fire", maps\payback_streets_const::_id_658C, "const_rappel_soap" );
    level._id_0C59["price"]["const_rappel_price"] = %payback_const_rappel_price;
    maps\_anim::_id_1264( "price", "gun_2_hand", maps\payback_streets_const::_id_6748, "const_rappel_price" );
    level._id_0C59["price"]["const_rappel_end_price"] = %payback_const_rappel_end_price;
    level._id_0C59["generic"]["corner_standR_trans_A_2_B"] = %corner_standr_trans_a_2_b;
    level._id_0C59["generic"]["deploy_flare"] = %payback_sstorm_flare;
    level._id_0C59["generic"]["payback_sstorm_reaction_guard1"] = %payback_sstorm_reaction_guard1;
    level._id_0C59["generic"]["active_patrolwalk_v5"] = %active_patrolwalk_v5;
    level._id_0C59["generic"]["active_patrolwalk_pause"] = %active_patrolwalk_pause;
    level._id_0C59["generic"]["active_patrolwalk_turn_180"] = %active_patrolwalk_turn_180;
    level._id_0C59["generic"]["payback_pmc_sandstorm_stumble_1"] = %payback_pmc_sandstorm_stumble_1;
    level._id_0C59["generic"]["payback_pmc_sandstorm_stumble_2"] = %payback_pmc_sandstorm_stumble_2;
    level._id_0C59["generic"]["payback_pmc_sandstorm_stumble_3"] = %payback_pmc_sandstorm_stumble_3;
    level._id_0C59["generic"]["payback_sstorm_guard_wave_1"] = %payback_sstorm_guard_wave_1;
    level._id_0C59["generic"]["payback_sstorm_guard_wave_2"] = %payback_sstorm_guard_wave_2;
    level._id_0C59["generic"]["signal_enemy_coverR"] = %cornerstndr_alert_signal_enemy_spotted;
    level._id_0C59["generic"]["balcony_death"] = [];
    level._id_0C59["generic"]["balcony_death"][0] = %death_rooftop_a;
    level._id_0C59["generic"]["balcony_death"][1] = %death_rooftop_b;
    level._id_0C59["generic"]["balcony_death"][2] = %death_rooftop_c;
    level._id_0C59["generic"]["balcony_death"][3] = %death_rooftop_d;
    level._id_0C59["rescue_echo_3"]["payback_sstorm_chopper_rescue_echo_pullout"] = %payback_sstorm_chopper_rescue_echo_pullout;
    level._id_0C59["nikolai"]["payback_sstorm_chopper_rescue_nikolai_pullout"] = %payback_sstorm_chopper_rescue_nikolai_pullout;
    level._id_0C59["generic"]["echo_stumble_forward_death"] = %stand_death_stumbleforward;
    level._id_0C59["price"]["payback_escape_start_backpedal_price"] = %payback_escape_start_backpedal_price;
    level._id_0C59["price"]["escape_debris_dodge"] = %payback_escape_dodge_debris_price;
    level._id_0C59["price"]["payback_escape_rpg_react_price"] = %payback_escape_rpg_react_price;
    level._id_0C59["price"]["payback_escape_forward_wave_right_price"] = %payback_escape_forward_wave_right_price;
    level._id_0C59["soap"]["payback_escape_start_wave_soap"] = %payback_escape_start_wave_soap;
    level._id_0C59["soap"]["payback_escape_turn_shoot_wave_soap"] = %payback_escape_turn_shoot_wave_soap;
    level._id_0C59["soap"]["payback_escape_hood_slide_soap"] = %payback_escape_hood_slide_soap;
    level._id_0C59["soap"]["payback_escape_forward_wave_left_soap"] = %payback_escape_forward_wave_left_soap;
    level._id_0C59["nikolai"]["rescue_nikolai_idle"][0] = %payback_sstorm_chopper_rescue_nikolai_hit_idle;
    level._id_0C59["nikolai"]["rescue_nikolai"] = %payback_sstorm_chopper_rescue_nikolai_getup;
    level._id_0C59["nikolai"]["rescue_nikolai_death"] = %payback_sstorm_chopper_rescue_nikolai_killed;
    level._id_0C59["price"]["exfil_slide_price"] = %payback_exfil_slide_price;
    level._id_0C59["price"]["payback_exfil_slide_loop_price"][0] = %payback_exfil_slide_loop_price;
    level._id_0C59["price"]["payback_exfil_slide_end_price"] = %payback_exfil_slide_end_price;
    maps\_anim::_id_1264( "price", "slide_fx_on", maps\payback_rescue::_id_657B, "exfil_slide_price" );
    maps\_anim::_id_1264( "price", "slide_fx_off", maps\payback_rescue::_id_657C, "exfil_slide_price" );
    level._id_0C59["price"]["price_enter_jeep"] = %rubicon_mount_backr;
    level._id_0C59["soap"]["exfil_slide_soap"] = %payback_exfil_slide_soap;
    maps\_anim::_id_1264( "soap", "slide_fx_on", maps\payback_rescue::_id_657B, "exfil_slide_soap" );
    maps\_anim::_id_1264( "soap", "slide_fx_off", maps\payback_rescue::_id_657C, "exfil_slide_soap" );
    level._id_0C59["soap"]["soap_enter_jeep"] = %payback_exfil_enter_jeep_soap;
    level._id_0C59["rescue_echo_2"]["exfil_slide_echo_2"] = %payback_exfil_slide_soap;
    maps\_anim::_id_1264( "rescue_echo_2", "slide_fx_on", maps\payback_rescue::_id_657B, "exfil_slide_echo_2" );
    maps\_anim::_id_1264( "rescue_echo_2", "slide_fx_off", maps\payback_rescue::_id_657C, "exfil_slide_echo_2" );
    level._id_0C59["nikolai_jeep_escape"]["exfil_slide_nikolai"] = %payback_exfil_slide_nikolai;
    maps\_anim::_id_1264( "nikolai_jeep_escape", "slide_fx_on", maps\payback_rescue::_id_657B, "exfil_slide_nikolai" );
    maps\_anim::_id_1264( "nikolai_jeep_escape", "slide_fx_off", maps\payback_rescue::_id_657C, "exfil_slide_nikolai" );
    level._id_0C59["rescue_echo_1"]["enter_jeep_rescue_echo_1"] = %payback_exfil_slide_echo_a;
    level._id_0C59["price"]["jeep_slide_escape"] = %payback_end_slide_price;
    maps\_anim::_id_1264( "price", "slide_fx_on", maps\payback_rescue::_id_657B, "jeep_slide_escape" );
    maps\_anim::_id_1264( "price", "slide_fx_off", maps\payback_rescue::_id_657C, "jeep_slide_escape" );
    level._id_0C59["price"]["price_jeep_shoot_loop"][0] = %payback_end_fire_price;
    level._id_0C59["price"]["price_jeep_sit_down"] = %payback_end_to_idle_price;
    level._id_0C59["price"]["price_back_jeep_loop"][0] = %rubicon_idle_backl;
    level._id_0C59["nikolai_jeep_escape"]["jeep_slide_escape"] = %payback_end_slide_nikolai;
    maps\_anim::_id_1264( "nikolai_jeep_escape", "slide_fx_on", maps\payback_rescue::_id_657B, "jeep_slide_escape" );
    maps\_anim::_id_1264( "nikolai_jeep_escape", "slide_fx_off", maps\payback_rescue::_id_657C, "jeep_slide_escape" );
    level._id_0C59["nikolai_jeep_escape"]["nikolai_passenger_loop"][0] = %payback_end_idle_nikolai;
    level._id_0C59["escape_jeep_1_gunner"]["escape_jeep_1_gunner_shoot_loop"][0] = %payback_end_fire_passenger;
    level._id_0C59["escape_jeep_1_gunner"]["escape_jeep_1_gunner_sit_down"] = %payback_end_to_idle_passenger;
    level._id_0C59["escape_jeep_1_gunner"]["escape_jeep_1_gunner_passenger_loop"][0] = %rubicon_idle_passenger;
    level._id_0C59["escape_jeep_2_gunner"]["escape_jeep_2_gunner_shoot_loop"][0] = %payback_end_fire_back_l;
    level._id_0C59["escape_jeep_2_gunner"]["escape_jeep_2_gunner_sit_down"] = %payback_end_to_idle_back_l;
    level._id_0C59["escape_jeep_2_gunner"]["escape_jeep_2_gunner_rear_loop"][0] = %rubicon_idle_backl;
    level._id_0C59["soap"]["jeep_slide_escape"] = %payback_end_slide_soap;
    maps\_anim::_id_1264( "soap", "slide_fx_on", maps\payback_rescue::_id_657B, "jeep_slide_escape" );
    maps\_anim::_id_1264( "soap", "slide_fx_off", maps\payback_rescue::_id_657C, "jeep_slide_escape" );
    level._id_0C59["soap"]["soap_jeep_shoot_loop"][0] = %payback_end_fire_soap;
    level._id_0C59["soap"]["soap_jeep_shoot_loop_2"][0] = %payback_end_fire_soap_2;
    level._id_0C59["soap"]["soap_jeep_sit_down"] = %payback_end_to_idle_soap;
    level._id_0C59["soap"]["soap_back_jeep_loop"][0] = %rubicon_idle_backr;
    level._id_0C59["rescue_echo_1"]["rescue_echo_1_slide"] = %payback_end_slide_bravo_1;
    maps\_anim::_id_1264( "rescue_echo_1", "slide_fx_on", maps\payback_rescue::_id_657B, "rescue_echo_1_slide" );
    maps\_anim::_id_1264( "rescue_echo_1", "slide_fx_off", maps\payback_rescue::_id_657C, "rescue_echo_1_slide" );
    level._id_0C59["rescue_echo_2"]["rescue_echo_2_slide"] = %payback_end_slide_bravo_2;
    maps\_anim::_id_1264( "rescue_echo_2", "slide_fx_on", maps\payback_rescue::_id_657B, "rescue_echo_2_slide" );
    maps\_anim::_id_1264( "rescue_echo_2", "slide_fx_off", maps\payback_rescue::_id_657C, "rescue_echo_2_slide" );
    level._id_0C59["escape_jeep_1_driver"]["escape_jeep_1_driver_loop"][0] = %rubicon_idle_driver;
    level._id_0C59["escape_jeep_2_driver"]["escape_jeep_2_driver_loop"][0] = %rubicon_idle_driver;
}
#using_animtree("animated_props");

_id_6838()
{
    level._id_1245["umbrella"] = #animtree;
    level._id_0C59["umbrella"]["heli_wind_near"][0] = %payback_tableumbrella_broken_wind_1;
    level._id_0C59["umbrella"]["heli_wind_far"][0] = %payback_tableumbrella_broken_wind_2;
    level._id_0C59["umbrella"]["wind_idle_1"][0] = %payback_tableumbrella_broken_wind_1_idle;
    level._id_0C59["umbrella"]["wind_idle_2"][0] = %payback_tableumbrella_broken_wind_2_idle;
    level._id_1245["construction_lamp"] = #animtree;
    level._id_0C59["construction_lamp"]["wind_medium"][0] = %payback_const_hanging_light;
    level._id_1245["moroccan_lamp"] = #animtree;
    level._id_0C59["moroccan_lamp"]["wind_heavy"][0] = %payback_sstorm_moroccan_lamp_wind_heavy;
    level._id_1245["foliage_tree_palm_med_1"] = #animtree;
    level._id_0C59["foliage_tree_palm_med_1"]["light_sway"][0] = %palmtree_med1_sway;
    level._id_0C59["foliage_tree_palm_med_1"]["strong_sway"][0] = %payback_sstorm_palm_med_windy;
    level._id_1245["foliage_tree_palm_bushy_3"] = #animtree;
    level._id_0C59["foliage_tree_palm_bushy_3"]["med_sway"][0] = %payback_sstorm_palm_bushy_windy_med;
    level._id_0C59["foliage_tree_palm_bushy_3"]["strong_sway"][0] = %payback_sstorm_palm_bushy_windy;
    level._id_1245["foliage_tree_jungle"] = #animtree;
    level._id_0C59["foliage_tree_jungle"]["wind_med_1"][0] = %payback_sstorm_tree_jungle_wind_med;
    level._id_0C59["foliage_tree_jungle"]["wind_med_2"][0] = %payback_sstorm_tree_jungle_wind_med_02;
    level._id_0C59["foliage_tree_jungle"]["wind_heavy_1"][0] = %payback_sstorm_tree_jungle_wind_heavy;
    level._id_0C59["foliage_tree_jungle"]["wind_heavy_2"][0] = %payback_sstorm_tree_jungle_wind_heavy_02;
    level._id_1245["foliage_tree_pine"] = #animtree;
    level._id_0C59["foliage_tree_pine"]["wind_light_1"][0] = %payback_sstorm_pine_wind_light_1;
    level._id_0C59["foliage_tree_pine"]["wind_light_2"][0] = %payback_sstorm_pine_wind_light_2;
    level._id_0C59["foliage_tree_pine"]["wind_med_1"][0] = %payback_sstorm_pine_wind_med_1;
    level._id_0C59["foliage_tree_pine"]["wind_med_2"][0] = %payback_sstorm_pine_wind_med_2;
    level._id_0C59["foliage_tree_pine"]["wind_heavy_1"][0] = %payback_sstorm_pine_wind_heavy_1;
    level._id_0C59["foliage_tree_pine"]["wind_heavy_2"][0] = %payback_sstorm_pine_wind_heavy_2;
    level._id_1245["dwarf_palm"] = #animtree;
    level._id_0C59["dwarf_palm"]["wind_light"][0] = %payback_sstorm_dwarf_palm_light;
    level._id_0C59["dwarf_palm"]["wind_med"][0] = %payback_sstorm_dwarf_palm_med;
    level._id_1245["rpg_crate"] = #animtree;
    level._id_0C59["rpg_crate"]["payback_docks_get_rpg_crate"] = %payback_docks_get_rpg_crate;
    level._id_1245["hanging_sheet"] = #animtree;
    level._id_0C59["hanging_sheet"]["wind_medium"][0] = %hanging_clothes_sheet_wind_medium;
    level._id_1245["hanging_short_sleeve"] = #animtree;
    level._id_0C59["hanging_short_sleeve"]["wind_medium"][0] = %hanging_clothes_short_sleeve_wind_medium;
    level._id_1245["hanging_long_sleeve"] = #animtree;
    level._id_0C59["hanging_long_sleeve"]["wind_medium"][0] = %hanging_clothes_long_sleeve_wind_medium;
    level._id_1245["hanging_apron"] = #animtree;
    level._id_0C59["hanging_apron"]["wind_medium"][0] = %hanging_clothes_apron_wind_medium;
    level._id_1245["city_rollcar"] = #animtree;
    level._id_0C59["city_rollcar"]["payback_city_rollcar"] = %payback_city_truck_push_car;
    maps\_anim::_id_1267( "city_rollcar", "explosion", "city_rollcar_switchmodel", "payback_city_rollcar" );
    level._id_1245["car_barrels"] = #animtree;
    level._id_1F90["car_barrels"] = "generic_prop_raven";
    level._id_0C59["car_barrels"]["payback_city_truck_push_barrels"] = %payback_city_truck_push_barrels;
    level._id_1245["sstorm_antenna"] = #animtree;
    level._id_0C59["sstorm_antenna"]["light_sway"][0] = %payback_sstorm_antenna_wind_1;
    level._id_0C59["sstorm_antenna"]["strong_sway"][0] = %payback_sstorm_antenna_wind_2;
    level._id_1245["highrise_fencetarp_01"] = #animtree;
    level._id_0C59["highrise_fencetarp_01"]["light_sway"][0] = %highrise_fencetarp_01_wind;
    level._id_0C59["highrise_fencetarp_01"]["strong_sway_initial_loop"][0] = %payback_sstorm_tarp_01_wind_1;
    level._id_0C59["highrise_fencetarp_01"]["strong_sway_tear"] = %payback_sstorm_tarp_01_tear;
    level._id_0C59["highrise_fencetarp_01"]["strong_sway_final_loop"][0] = %payback_sstorm_tarp_01_wind_2;
    level._id_1245["highrise_fencetarp_03"] = #animtree;
    level._id_0C59["highrise_fencetarp_03"]["light_sway"][0] = %highrise_fencetarp_03_wind;
    level._id_0C59["highrise_fencetarp_03"]["strong_sway_1"][0] = %payback_sstorm_tarp_03_wind_1;
    level._id_0C59["highrise_fencetarp_03"]["strong_sway_2"][0] = %payback_sstorm_tarp_03_wind_2;
    level._id_1245["highrise_fencetarp_08"] = #animtree;
    level._id_0C59["highrise_fencetarp_08"]["strong_sway"][0] = %highrise_fencetarp_08_wind;
    level._id_1245["tarp_crate"] = #animtree;
    level._id_0C59["tarp_crate"]["payback_tarp_crate_light_wind"][0] = %payback_tarp_crate_light_wind;
    level._id_0C59["tarp_crate"]["payback_tarp_crate_heavy_wind"][0] = %payback_tarp_crate_heavy_wind;
    level._id_1245["payback_sstorm_grass"] = #animtree;
    level._id_0C59["payback_sstorm_grass"]["strong_sway_1"][0] = %payback_sstorm_grass_wind_1;
    level._id_0C59["payback_sstorm_grass"]["strong_sway_2"][0] = %payback_sstorm_grass_wind_2;
    level._id_0C59["payback_sstorm_grass"]["strong_sway_3"][0] = %payback_sstorm_grass_wind_3;
    level._id_0C59["payback_sstorm_grass"]["light_sway"][0] = %payback_sstorm_grass_wind_light;
    level._id_1245["payback_foliage_bush01"] = #animtree;
    level._id_0C59["payback_foliage_bush01"]["strong_sway_1"][0] = %payback_sstorm_bush_wind_1;
    level._id_0C59["payback_foliage_bush01"]["strong_sway_2"][0] = %payback_sstorm_bush_wind_2;
    level._id_0C59["payback_foliage_bush01"]["light_sway"][0] = %payback_sstorm_bush_low_wind_1;
    level._id_1245["payback_wires_single"] = #animtree;
    level._id_0C59["payback_wires_single"]["strong_sway"][0] = %payback_sstorm_stwires_wind_1;
    level._id_1245["payback_wires_long"] = #animtree;
    level._id_0C59["payback_wires_long"]["wind_light_1"][0] = %payback_wires_long_wind_light_1;
    level._id_0C59["payback_wires_long"]["wind_light_2"][0] = %payback_wires_long_wind_light_2;
    level._id_0C59["payback_wires_long"]["wind_medium_1"][0] = %payback_wires_long_wind_medium_1;
    level._id_0C59["payback_wires_long"]["wind_medium_2"][0] = %payback_wires_long_wind_medium_2;
    level._id_0C59["payback_wires_long"]["wind_heavy_1"][0] = %payback_wires_long_wind_heavy_1;
    level._id_0C59["payback_wires_long"]["wind_heavy_2"][0] = %payback_wires_long_wind_heavy_2;
    level._id_0C59["payback_wires_long"]["wind_extreme_1"][0] = %payback_wires_long_wind_heavy_1;
    level._id_0C59["payback_wires_long"]["wind_extreme_2"][0] = %payback_wires_long_wind_heavy_2;
    level._id_0C59["payback_wires_long"]["wind_rescue_1"][0] = %payback_wires_long_wind_medium_1;
    level._id_0C59["payback_wires_long"]["wind_rescue_2"][0] = %payback_wires_long_wind_medium_2;
    level._id_1245["payback_wires_short"] = #animtree;
    level._id_0C59["payback_wires_short"]["wind_light_1"][0] = %payback_wires_short_wind_light_1;
    level._id_0C59["payback_wires_short"]["wind_light_2"][0] = %payback_wires_short_wind_light_2;
    level._id_0C59["payback_wires_short"]["wind_medium_1"][0] = %payback_wires_short_wind_medium_1;
    level._id_0C59["payback_wires_short"]["wind_medium_2"][0] = %payback_wires_short_wind_medium_2;
    level._id_0C59["payback_wires_short"]["wind_heavy_1"][0] = %payback_wires_short_wind_heavy_1;
    level._id_0C59["payback_wires_short"]["wind_heavy_2"][0] = %payback_wires_short_wind_heavy_2;
    level._id_0C59["payback_wires_short"]["wind_extreme_1"][0] = %payback_wires_short_wind_heavy_1;
    level._id_0C59["payback_wires_short"]["wind_extreme_2"][0] = %payback_wires_short_wind_heavy_2;
    level._id_0C59["payback_wires_short"]["wind_rescue_1"][0] = %payback_wires_short_wind_medium_1;
    level._id_0C59["payback_wires_short"]["wind_rescue_2"][0] = %payback_wires_short_wind_medium_2;
    level._id_1245["payback_sstorm_fence_chainlink"] = #animtree;
    level._id_0C59["payback_sstorm_fence_chainlink"]["strong_sway_1"][0] = %payback_sstorm_fence_wind_1;
    level._id_0C59["payback_sstorm_fence_chainlink"]["strong_sway_2"][0] = %payback_sstorm_fence_wind_2;
    level._id_1245["payback_sstorm_sign_metal"] = #animtree;
    level._id_0C59["payback_sstorm_sign_metal"]["strong_sway_l"][0] = %payback_sstorm_sign_metal_wind_l;
    level._id_0C59["payback_sstorm_sign_metal"]["strong_sway_r"][0] = %payback_sstorm_sign_metal_wind_r;
    level._id_1245["payback_sstorm_sign_chain"] = #animtree;
    level._id_0C59["payback_sstorm_sign_chain"]["strong_sway_l"][0] = %payback_sstorm_sign_chain_l;
    level._id_0C59["payback_sstorm_sign_chain"]["strong_sway_r"][0] = %payback_sstorm_sign_chain_r;
    level._id_1245["payback_scaffolding_collapse"] = #animtree;
    level._id_0C59["payback_scaffolding_collapse"]["payback_scaffolding_collapse"] = %payback_scaffolding_collapse;
    level._id_1245["const_wall_frame"] = #animtree;
    level._id_0C59["const_wall_frame"]["fall"] = %payback_const_frame_break;
    level._id_1245["const_wall_scaffold"] = #animtree;
    level._id_0C59["const_wall_scaffold"]["fall"] = %payback_const_scaff_fall;
    level._id_1245["const_wall_wall"] = #animtree;
    level._id_0C59["const_wall_wall"]["fall"] = %payback_const_wall_fall;
    maps\_anim::_id_1267( "const_wall_wall", "screen_shake", "const_wallfall_screen_shake", "fall" );
    level._id_1245["const_wall_side_wall"] = #animtree;
    level._id_0C59["const_wall_side_wall"]["fall"] = %payback_const_side_wall_break;
    level._id_1245["const_wall_final_debris"] = #animtree;
    level._id_0C59["const_wall_final_debris"]["fall"] = %payback_const_final_break;
    level._id_1245["payback_studwall_collapse"] = #animtree;
    level._id_0C59["payback_studwall_collapse"]["payback_studwall_collapse_loop"][0] = %payback_studwall_collapse_loop;
    level._id_0C59["payback_studwall_collapse"]["payback_studwall_collapse"] = %payback_studwall_collapse;
    level._id_1245["sstorm_bush"] = #animtree;
    level._id_0C59["sstorm_bush"]["roll_loop"][0] = %payback_sstorm_bush_roll;
    level._id_0C59["sstorm_bush"]["roll_stop_loop"][0] = %payback_sstorm_bush_stop_loop;
    level._id_1245["sstorm_bucket"] = #animtree;
    level._id_0C59["sstorm_bucket"]["roll_loop"][0] = %payback_sstorm_bucket_roll;
    level._id_0C59["sstorm_bucket"]["roll_stop_loop"][0] = %payback_sstorm_bucket_stop_loop;
    level._id_1245["sstorm_barrel"] = #animtree;
    level._id_0C59["sstorm_barrel"]["roll_loop"][0] = %payback_sstorm_barrel_roll;
    level._id_1245["sstorm_chicken_coop"] = #animtree;
    level._id_0C59["sstorm_chicken_coop"]["roll_loop"] = %payback_sstorm_cage_roll;
    level._id_1245["sstorm_chicken"] = #animtree;
    level._id_0C59["sstorm_chicken"]["chicken_loop_01"] = %chicken_cage_loop_01;
    level._id_0C59["sstorm_chicken"]["chicken_loop_02"] = %chicken_cage_loop_02;
    level._id_1245["intro_gate"] = #animtree;
    level._id_0C59["intro_gate"]["gate_close"] = %payback_gatecrash_closegate_gate;
    level._id_0C59["intro_gate"]["gate_crash"] = %payback_gate_gatecrasher_intro;
    level._id_1245["tinroof"] = #animtree;
    level._id_0C59["tinroof"]["payback_sstorm_tinroof_enter_idle"] = %payback_sstorm_tinroof_enter_idle;
    level._id_0C59["tinroof"]["payback_sstorm_tinroof_tear"] = %payback_sstorm_tinroof_tear;
    level._id_0C59["tinroof"]["payback_sstorm_tinroof_exit_idle"] = %payback_sstorm_tinroof_exit_idle;
    level._id_1245["sstorm_gate"] = #animtree;
    level._id_0C59["sstorm_gate"]["gate_loop"][0] = %payback_sstorm_gate_windy;
    level._id_0C59["sstorm_gate"]["gate_loop_single"] = %payback_sstorm_gate_windy;
    level._id_0C59["sstorm_gate"]["gate_loop_2"][0] = %payback_sstorm_gate_windy_2;
    level._id_0C59["sstorm_gate"]["gate_loop_2_single"] = %payback_sstorm_gate_windy_2;
    level._id_0C59["sstorm_gate"]["gate_loop_closed"][0] = %payback_sstorm_gate_windy_loop_closed;
    level._id_0C59["sstorm_gate"]["gate_loop_closed_single"] = %payback_sstorm_gate_windy_loop_closed;
    level._id_0C59["sstorm_gate"]["gate_windy_open"] = %payback_sstorm_gate_windy_open;
    level._id_1245["sstorm_gate_chain"] = #animtree;
    level._id_0C59["sstorm_gate_chain"]["chain_windy_loop_closed"][0] = %payback_sstorm_chain_windy_loop_closed;
    level._id_0C59["sstorm_gate_chain"]["chain_windy_loop_closed_single"] = %payback_sstorm_chain_windy_loop_closed;
    level._id_0C59["sstorm_gate_chain"]["chain_windy_open"] = %payback_sstorm_chain_windy_open;
    level._id_1245["sstorm_gate_chain"] = #animtree;
    level._id_0C59["sstorm_gate_chain"]["chain_windy_2_loop"][0] = %payback_sstorm_chain_windy_2;
    level._id_0C59["sstorm_gate_chain"]["chain_windy_2_single"] = %payback_sstorm_chain_windy_2;
    level._id_1245["marketstall"] = #animtree;
    level._id_0C59["marketstall"]["payback_sstorm_market_stall_loop"][0] = %payback_sstorm_market_stall_loop;
    level._id_0C59["marketstall"]["payback_sstorm_market_stall_tear"] = %payback_sstorm_market_stall_tear;
    level._id_0C59["marketstall"]["payback_sstorm_market_stall_exit"] = %payback_sstorm_market_stall_exit;
    level._id_1245["watertower"] = #animtree;
    level._id_0C59["watertower"]["payback_sstorm_water_tower_idle"][0] = %payback_sstorm_water_tower_idle;
    level._id_0C59["watertower"]["payback_sstorm_water_tower_fall"] = %payback_sstorm_water_tower_fall;
    level._id_1245["price_hat"] = #animtree;
    level._id_1F90["price_hat"] = "hat_price_africa";
    level._id_0C59["price_hat"]["price_hat_interrogation"] = %payback_interrogation_price_hat;
    level._id_1245["dummy_prop_1"] = #animtree;
    level._id_1F90["dummy_prop_1"] = "generic_prop_raven";
    level._id_0C59["dummy_prop_1"]["waraabe_breach"] = %payback_breach_frontcrates;
    level._id_0C59["dummy_prop_1"]["waraabe_interrogation"] = %payback_interrogation_frontcrates;
    level._id_1245["dummy_prop_2"] = #animtree;
    level._id_1F90["dummy_prop_2"] = "generic_prop_raven";
    level._id_0C59["dummy_prop_2"]["waraabe_interrogation"] = %payback_interrogation_warrabe_gasmask;
    level._id_1245["dummy_prop_7"] = #animtree;
    level._id_1F90["dummy_prop_7"] = "generic_prop_raven";
    level._id_0C59["dummy_prop_7"]["waraabe_interrogation"] = %payback_interrogation_gascanister;
    maps\_anim::_id_1264( "dummy_prop_7", "fx_big_spew", maps\payback_1_script_e::_id_6687, "waraabe_interrogation" );
    maps\_anim::_id_1264( "dummy_prop_7", "fx_sparks", maps\payback_1_script_e::_id_6684, "waraabe_interrogation" );
    maps\_anim::_id_1264( "dummy_prop_7", "fx_initial_spew", maps\payback_1_script_e::_id_6685, "waraabe_interrogation" );
    maps\_anim::_id_1264( "dummy_prop_7", "fx_big_spew", maps\payback_1_script_e::_id_6686, "waraabe_interrogation" );
    level._id_1245["price_new_gas_mask"] = #animtree;
    level._id_1F90["price_new_gas_mask"] = "pb_gas_mask_prop";
    level._id_0C59["price_new_gas_mask"]["waraabe_interrogation"] = %payback_interrogation_mask_price;
    level._id_1245["soap_new_gas_mask"] = #animtree;
    level._id_1F90["soap_new_gas_mask"] = "pb_gas_mask_prop";
    level._id_0C59["soap_new_gas_mask"]["waraabe_interrogation"] = %payback_interrogation_mask_soap;
    level._id_1245["extra_new_gas_mask"] = #animtree;
    level._id_1F90["extra_new_gas_mask"] = "pb_gas_mask_prop";
    level._id_0C59["extra_new_gas_mask"]["waraabe_interrogation"] = %payback_interrogation_mask_waraabe;
    level._id_1245["dummy_prop_4"] = #animtree;
    level._id_1F90["dummy_prop_4"] = "generic_prop_raven";
    level._id_0C59["dummy_prop_4"]["waraabe_breach"] = %payback_breach_backcrates;
    level._id_0C59["dummy_prop_4"]["waraabe_interrogation"] = %payback_interrogation_backcrates;
    level._id_1245["dummy_prop_5"] = #animtree;
    level._id_1F90["dummy_prop_5"] = "generic_prop_raven";
    level._id_0C59["dummy_prop_5"]["waraabe_breach"] = %payback_breach_clipboardphone;
    level._id_1245["dummy_prop_6"] = #animtree;
    level._id_1F90["dummy_prop_6"] = "generic_prop_raven";
    level._id_0C59["dummy_prop_6"]["waraabe_interrogation"] = %payback_interrogation_door;
    level._id_1245["waraabe_laptop"] = #animtree;
    level._id_1F90["waraabe_laptop"] = "hjk_laptop_animated";
    level._id_0C59["waraabe_laptop"]["waraabe_breach"] = %payback_breach_laptop;
    level._id_1245["interrogation_room_shutters"] = #animtree;
    level._id_1F90["interrogation_room_shutters"] = "generic_prop_raven";
    level._id_0C59["interrogation_room_shutters"]["shutters_01"][0] = %payback_interrogation_shutters1;
    level._id_0C59["interrogation_room_shutters"]["shutters_02"][0] = %payback_interrogation_shutters2;
    level._id_0C59["interrogation_room_shutters"]["shutters_03"][0] = %payback_interrogation_shutters3;
    level._id_0C59["interrogation_room_shutters"]["shutters_04"][0] = %payback_interrogation_shutters4;
    level._id_0C59["interrogation_room_shutters"]["shutters_05"][0] = %payback_interrogation_shutters5;
    level._id_0C59["interrogation_room_shutters"]["shutters_06"][0] = %payback_interrogation_shutters6;
    level._id_1245["interrogation_room_curtains"] = #animtree;
    level._id_0C59["interrogation_room_curtains"]["curtains_01"][0] = %payback_interrogation_curtain1;
    level._id_0C59["interrogation_room_curtains"]["curtains_02"][0] = %payback_interrogation_curtain2;
    level._id_0C59["interrogation_room_curtains"]["curtains_04"][0] = %payback_interrogation_curtain4;
    level._id_0C59["interrogation_room_curtains"]["curtains_05"][0] = %payback_interrogation_curtain5;
    level._id_0C59["interrogation_room_curtains"]["curtains_06"][0] = %payback_interrogation_curtain6;
    level._id_1245["compound_curtains"] = #animtree;
    level._id_0C59["compound_curtains"]["lower_curtains_01"][0] = %payback_lower_curtains1;
    level._id_0C59["compound_curtains"]["lower_curtains_02"][0] = %payback_lower_curtains2;
    level._id_1245["payback_const_crates"] = #animtree;
    level._id_0C59["payback_const_crates"]["debris_fall"] = %payback_const_crates;
    level._id_1245["payback_heli_crash"] = #animtree;
    level._id_0C59["payback_heli_crash"]["heli_crash"] = %payback_heli_crash_new;
    level._id_0C59["payback_heli_crash"]["heli_crash_rappel"] = %payback_heli_crash_rappel;
    level._id_0C59["payback_heli_crash"]["heli_crash_rpg"] = %payback_heli_crash_rpg;
    level._id_0C59["payback_heli_crash"]["heli_crash_roof_debris"] = %payback_heli_crash_debris;
    level._id_0C59["payback_heli_crash"]["heli_crash_rappel_debris"] = %payback_heli_crash_rappel_debris;
    level._id_1245["player_rope"] = #animtree;
    level._id_1F90["player_rope"] = "payback_const_rappel_rope";
    level._id_0C59["player_rope"]["payback_const_rappel_rope_idle_1"][0] = %payback_const_rappel_rope_idle_1;
    level._id_0C59["player_rope"]["const_rappel_player"] = %payback_const_rappel_rope_player;
    level._id_0C59["player_rope"]["const_rappel_price"] = %payback_const_rappel_rope_price;
    level._id_1245["soap_rope"] = #animtree;
    level._id_1F90["soap_rope"] = "payback_const_rappel_rope";
    level._id_0C59["soap_rope"]["payback_const_rappel_rope_idle_2"][0] = %payback_const_rappel_rope_idle_2;
    level._id_0C59["soap_rope"]["const_rappel_soap"] = %payback_const_rappel_rope_soap;
    level._id_1245["rope_glow"] = #animtree;
    level._id_1F90["rope_glow"] = "payback_const_rappel_rope_obj";
    level._id_0C59["rope_glow"]["payback_const_rappel_rope_idle_1"][0] = %payback_const_rappel_rope_idle_1;
    level._id_1245["chopper_prop"] = #animtree;
    level._id_1F90["chopper_prop"] = "pb_sstorm_chopper_rescue_propeller";
    level._id_0C59["chopper_prop"]["payback_sstorm_chopper_rescue_propeller"][0] = %payback_sstorm_chopper_rescue_propeller;
    level._id_1245["chopper_tail"] = #animtree;
    level._id_1F90["chopper_tail"] = "pb_sstorm_chopper_rescue_tail_anim";
    level._id_0C59["chopper_tail"]["payback_sstorm_chopper_rescue_tail_rotor"][0] = %payback_sstorm_chopper_rescue_tail_rotor;
    level._id_1245["escape_debris"] = #animtree;
    level._id_1F90["escape_debris"] = "payback_escape_debris";
    level._id_0C59["escape_debris"]["escape_debris_dodge"] = %payback_escape_price_debris;
}
#using_animtree("script_model");

_id_6839()
{
    level._id_1245["com_square_flag"] = #animtree;
    level._id_0C59["com_square_flag"]["strong_sway"][0] = %cliffhanger_square_flag_high_wind;
    level._id_0C59["breach_door_charge_payback"]["breach"] = %breach_player_frame_charge;
    level._id_1245["breach_door_charge_payback"] = #animtree;
    level._id_1F90["breach_door_charge_payback"] = "weapon_frame_charge_iw5_water";
    level._id_0C59["breach_door_model_payback"]["breach"] = %breach_player_door_v2;
    level._id_1245["breach_door_model_payback"] = #animtree;
    level._id_1F90["breach_door_model_payback"] = "pb_door_breach_anim";
    level._id_0C59["breach_door_hinge_payback"]["breach"] = %breach_player_door_hinge_v1;
    level._id_1245["breach_door_hinge_payback"] = #animtree;
    level._id_1F90["breach_door_hinge_payback"] = "pb_door_breach_hinge_anim";
}
#using_animtree("vehicles");

_id_683A()
{
    level._id_1245["escape_jeep_1"] = #animtree;
    level._id_1F90["escape_jeep_1"] = "vehicle_jeep_rubicon";
    level._id_0C59["escape_jeep_1"]["jeep_slide_escape"] = %payback_end_turnaround_jeep;
    level._id_1245["escape_jeep_2"] = #animtree;
    level._id_1F90["escape_jeep_2"] = "vehicle_jeep_rubicon";
    level._id_0C59["escape_jeep_2"]["jeep_slide_escape"] = %payback_end_jeep_2;
    level._id_1245["swerve_technical"] = #animtree;
    level._id_1F90["swerve_technical"] = "vehicle_pickup_technical_pb_rusted";
    level._id_0C59["swerve_technical"]["jeep_slide_escape"] = %payback_end_technical_2;
    level._id_1245["smash_technical"] = #animtree;
    level._id_1F90["smash_technical"] = "vehicle_pickup_technical_pb_rusted";
    level._id_0C59["smash_technical"]["jeep_slide_escape"] = %payback_end_technical_1;
    level._id_1245["alpha_hummer"] = #animtree;
    level._id_0C59["alpha_hummer"]["shift_up"] = %payback_intro_shift_up_jeep;
    level._id_0C59["alpha_hummer"]["wheel_turn"] = %payback_intro_turn_rubicon;
}

_id_683B()
{
    level._id_29F9 = "humvee";
    level._id_29FF = "vehicle_hummer_open_top_noturret";
    level._id_29F4 = "script_vehicle_hummer_opentop_payback";
    maps\_vehicle::_id_2ACA( ::_id_683C, _id_55BA::_id_3A9C );
}
#using_animtree("generic_human");

_id_683C()
{
    var_0 = _id_55BA::_id_3A9D();
    var_0[1]._id_683D = %payback_gatecrasher_intro_soap;
    return var_0;
}
#using_animtree("player");

_id_683E()
{
    level._id_1245["const_player_jeep_rig_1"] = #animtree;
    level._id_1F90["const_player_jeep_rig_1"] = "viewhands_player_yuri";
    level._id_0C59["const_player_jeep_rig_1"]["intro_jeep_stand_player"] = %payback_intro_getup_player;
    level._id_0C59["const_player_jeep_rig_1"]["intro_jeep_jump_player"] = %payback_intro_turn_player;
    level._id_0C59["const_player_jeep_rig_1"]["intro_jeep_exit_player"] = %payback_gatecrash_dismount_player;
    level._id_1245["const_player_rig_1"] = #animtree;
    level._id_1F90["const_player_rig_1"] = "viewhands_player_yuri";
    level._id_0C59["const_player_rig_1"]["const_rappel_player"] = %payback_const_rappel_player_intro;
    level._id_1245["const_player_rig_2"] = #animtree;
    level._id_1F90["const_player_rig_2"] = "viewhands_player_yuri";
    level._id_0C59["const_player_rig_2"]["const_rappel_player"] = %payback_const_rappel_player_intro02;
    level._id_1245["const_player_rig_ledge_1"] = #animtree;
    level._id_1F90["const_player_rig_ledge_1"] = "viewhands_player_yuri";
    level._id_0C59["const_player_rig_ledge_1"]["const_rappel_player"] = %payback_const_rappel_player_intro;
    level._id_1245["const_player_rig_ledge_2"] = #animtree;
    level._id_1F90["const_player_rig_ledge_2"] = "viewhands_player_yuri";
    level._id_0C59["const_player_rig_ledge_2"]["const_rappel_player"] = %payback_const_rappel_player_intro02;
    level._id_1245["rescue_nikolai_player_rig"] = #animtree;
    level._id_1F90["rescue_nikolai_player_rig"] = "viewhands_player_yuri";
    level._id_0C59["rescue_nikolai_player_rig"]["rescue_nikolai"] = %payback_sstorm_chopper_rescue_player_getup;
    level._id_1245["player_slide_rig"] = #animtree;
    level._id_1F90["player_slide_rig"] = "viewhands_player_yuri";
    level._id_0C59["player_slide_rig"]["exfil_slide_player"] = %payback_exfil_slide_player;
    level._id_1245["player_slide_legs"] = #animtree;
    level._id_1F90["player_slide_legs"] = "viewlegs_generic";
    level._id_0C59["player_slide_legs"]["jeep_slide_escape"] = %payback_end_slide_player_legs;
    maps\_anim::_id_1264( "player_slide_legs", "slide_fx_on", maps\payback_rescue::_id_657B, "jeep_slide_escape" );
    maps\_anim::_id_1264( "player_slide_legs", "slide_fx_off", maps\payback_rescue::_id_657C, "jeep_slide_escape" );
    level._id_1245["player_jeep_enter_rig"] = #animtree;
    level._id_1F90["player_jeep_enter_rig"] = "viewhands_player_yuri";
    level._id_0C59["player_jeep_enter_rig"]["exfil_enter_jeep_player"] = %payback_exfil_enter_jeep_player;
    level._id_1245["player_slide_arms"] = #animtree;
    level._id_1F90["player_slide_arms"] = "viewhands_player_yuri";
    level._id_0C59["player_slide_arms"]["jeep_slide_escape"] = %payback_end_slide_player;
    level._id_1245["player_jeep_arms"] = #animtree;
    level._id_1F90["player_jeep_arms"] = "viewhands_player_yuri";
    level._id_0C59["player_jeep_arms"]["end_mount"] = %payback_end_mount_player;
}
