// IW5 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool

main()
{
    _id_043C();
    _id_56D9();
    _id_47D9();
    _id_47DE();
    _id_4CAC();
    _id_6838();
    _id_7D58();
}
#using_animtree("chicken");

_id_043C()
{
    level._id_1245["pigeon"] = #animtree;
    level._id_0C59["pigeon"]["idle"][0] = %pigeon_idle;
    level._id_0C59["pigeon"]["idleweight"][0] = 1;
    level._id_0C59["pigeon"]["idle"][1] = %pigeon_idle_twitch_1;
    level._id_0C59["pigeon"]["idleweight"][1] = 0.3;
    level._id_0C59["pigeon"]["flying"] = %pigeon_flying_cycle;
}
#using_animtree("generic_human");

_id_56D9()
{
    level._id_1245["generic_human"] = #animtree;
    level._id_0C59["soap"]["belltower_intro_idle"][0] = %ch_pragueb_1_1_idle_soap;
    level._id_0C59["soap"]["belltower_intro"] = %ch_pragueb_1_1_intro_soap;
    maps\_anim::_id_1264( "soap", "dialog_01", maps\prague_escape_sniper::_id_7AEA, "belltower_intro" );
    maps\_anim::_id_1267( "soap", "dialog_02", "belltower_intro_dialogue_02", "belltower_intro" );
    level._id_0C59["convoy_guard_1"]["convoy_arrives_idle"][0] = %ch_pragueb_1_2_convoy_arrives_idle_grd_01;
    level._id_0C59["convoy_guard_2"]["convoy_arrives_idle"][0] = %ch_pragueb_1_2_convoy_arrives_idle_grd_02;
    level._id_0C59["convoy_guard_3"]["convoy_arrives_idle"][0] = %ch_pragueb_1_2_convoy_arrives_idle_grd_03;
    level._id_0C59["convoy_guard_1"]["convoy_setup"] = %ch_pragueb_1_2_convoy_arrives_setup_grd_01;
    level._id_0C59["convoy_guard_2"]["convoy_setup"] = %ch_pragueb_1_2_convoy_arrives_setup_grd_02;
    level._id_0C59["convoy_guard_3"]["convoy_setup"] = %ch_pragueb_1_2_convoy_arrives_setup_grd_03;
    level._id_0C59["convoy_guard_1"]["convoy_arrives_wait"][0] = %ch_pragueb_1_2_convoy_arrives_wait_grd_01;
    level._id_0C59["convoy_guard_2"]["convoy_arrives_wait"][0] = %ch_pragueb_1_2_convoy_arrives_wait_grd_02;
    level._id_0C59["convoy_guard_3"]["convoy_arrives_wait"][0] = %ch_pragueb_1_2_convoy_arrives_wait_grd_03;
    level._id_0C59["convoy_guard_1"]["convoy_arrives"] = %ch_pragueb_1_2_convoy_arrives_grd_01;
    maps\_anim::_id_1267( "convoy_guard_1", "open_door", "door_guards_start", "convoy_arrives" );
    maps\_anim::_id_1267( "convoy_guard_1", "start_makarov", "convoy_arrives_start_makarov", "convoy_arrives" );
    maps\_anim::_id_1267( "convoy_guard_1", "close_door", "door_guards_close_door", "convoy_arrives" );
    level._id_0C59["convoy_guard_2"]["convoy_arrives"] = %ch_pragueb_1_2_convoy_arrives_grd_02;
    level._id_0C59["convoy_guard_3"]["convoy_arrives"] = %ch_pragueb_1_2_convoy_arrives_grd_03;
    level._id_0C59["makarov"]["convoy_arrives_idle"][0] = %ch_pragueb_1_2_makarov_idle_maka;
    level._id_0C59["makarov"]["convoy_arrives_signals"] = %ch_pragueb_1_2_makarov_signals_maka;
    level._id_0C59["door_guard_1"]["hotel_door_close"] = %ch_pragueb_1_2_door_guards_close_grd_01;
    level._id_0C59["door_guard_2"]["hotel_door_close"] = %ch_pragueb_1_2_door_guards_close_grd_02;
    level._id_0C59["door_guard_1"]["hotel_door_enter"] = %ch_pragueb_1_2_door_guards_enter_grd_01;
    level._id_0C59["door_guard_2"]["hotel_door_enter"] = %ch_pragueb_1_2_door_guards_enter_grd_02;
    level._id_0C59["door_guard_1"]["hotel_door_open"] = %ch_pragueb_1_2_door_guards_open_grd_01;
    level._id_0C59["door_guard_2"]["hotel_door_open"] = %ch_pragueb_1_2_door_guards_open_grd_02;
    level._id_0C59["door_guard_1"]["hotel_door_open_wait"][0] = %ch_pragueb_1_2_door_guards_open_wait_grd_01;
    level._id_0C59["door_guard_2"]["hotel_door_open_wait"][0] = %ch_pragueb_1_2_door_guards_open_wait_grd_02;
    level._id_0C59["door_guard_1"]["hotel_door_wait"][0] = %ch_pragueb_1_2_door_guards_wait_grd_01;
    level._id_0C59["door_guard_2"]["hotel_door_wait"][0] = %ch_pragueb_1_2_door_guards_wait_grd_02;
    level._id_0C59["price"]["rappel_hook_up_reveal"] = %ch_pragueb_1_3_hook_up_reveal_price;
    level._id_0C59["price"]["rappel_hook_up_idle"][0] = %ch_pragueb_1_3_hook_up_idle_price;
    level._id_0C59["price"]["rappel_hook_up"] = %ch_pragueb_1_3_hook_up_price;
    maps\_anim::_id_125D( "price", "dialogue03", "rappel_hook_up", "presc_mct_sentrysbalcony" );
    level._id_0C59["price"]["rappel_mid_idle"][0] = %ch_pragueb_1_3_idle_price;
    level._id_0C59["price"]["price_window_breach"] = %ch_pragueb_1_4_window_breach_price;
    maps\_anim::_id_1264( "price", "ambush_guards", maps\prague_escape_sniper::_id_7AE8, "price_window_breach" );
    maps\_anim::_id_125D( "price", "dialogue01", "price_window_breach", "presc_pri_breachingnow" );
    level._id_0C59["window_breach_grd_1"]["window_breach"] = %ch_pragueb_1_4_window_breach_grd_01;
    level._id_0C59["window_breach_grd_2"]["window_breach"] = %ch_pragueb_1_4_window_breach_grd_02;
    level._id_0C59["window_breach_grd_3"]["window_breach"] = %ch_pragueb_1_4_window_breach_grd_03;
    level._id_0C59["window_breach_grd_4"]["window_breach"] = %ch_pragueb_1_4_window_breach_grd_04;
    level._id_0C59["price"]["price_discover_kamarov"] = %ch_pragueb_1_4_discover_kamarov_price;
    maps\_anim::_id_1264( "price", "dialogue06", maps\prague_escape_sniper::_id_7AEB, "price_discover_kamarov" );
    level._id_0C59["kamarov"]["kamarov_dead"][0] = %ch_pragueb_1_4_kamarov_dead_kama;
    level._id_0C59["balcony_guard_1"]["balcony_enter"] = %ch_pragueb_1_3_patrol_grd_01;
    level._id_0C59["balcony_guard_2"]["balcony_enter"] = %ch_pragueb_1_3_patrol_grd_02;
    level._id_0C59["balcony_guard_3"]["balcony_enter"] = %ch_pragueb_1_3_patrol_grd_03;
    level._id_0C59["balcony_guard_4"]["balcony_enter"] = %ch_pragueb_1_3_patrol_grd_04;
    level._id_0C59["soap"]["scaffolding_fall"] = %ch_pragueb_2_2_scaffolding_fall_soap;
    maps\_anim::_id_1264( "soap", "dialogue02", maps\prague_escape_scaffold::_id_7B4E, "scaffolding_fall" );
    maps\_anim::_id_1264( "soap", "soap_hit_board_1", maps\prague_escape_scaffold::_id_7B54, "scaffolding_fall" );
    maps\_anim::_id_1267( "soap", "dialogue03", "scaffolding_fall_dialogue_3", "scaffolding_fall" );
    level._id_0C59["soap"]["fade_in_a"] = %ch_pragueb_2_3_fade_in_a_soap;
    level._id_0C59["soap"]["fade_in_b"] = %ch_pragueb_2_3_fade_in_b_soap;
    level._id_0C59["soap"]["scaffold_soap_injured"] = %ch_pragueb_2_3_soap_injured_soap;
    level._id_0C59["price"]["limp_a"] = %ch_pragueb_2_3_limp_a_price;
    level._id_0C59["price"]["limp_b"] = %ch_pragueb_2_3_limp_b_price;
    level._id_0C59["price"]["scaffold_soap_injured"] = %ch_pragueb_2_3_soap_injured_price;
    maps\_anim::_id_1264( "price", "dialogue01", maps\prague_escape_scaffold::_id_7B50, "scaffold_soap_injured" );
    maps\_anim::_id_1264( "price", "fire_grenade", maps\prague_escape_scaffold::_id_7B53, "scaffold_soap_injured" );
    maps\_anim::_id_1264( "price", "explosion", maps\prague_escape_scaffold::_id_7B52, "scaffold_soap_injured" );
    maps\_anim::_id_1267( "price", "dialogue02", "soap_injured_dialogue_2", "scaffold_soap_injured" );
    maps\_anim::_id_1267( "price", "dialogue03", "soap_injured_dialogue_3", "scaffold_soap_injured" );
    maps\_anim::_id_1264( "price", "rumble", maps\prague_escape_code::_id_7A56, "scaffold_soap_injured" );
    maps\_anim::_id_1267( "price", "dialogue04", "soap_injured_dialogue_4", "scaffold_soap_injured" );
    level._id_0C59["soap"]["soap_carry_prone_soap"][0] = %ch_pragueb_3_1_prone_soap;
    level._id_0C59["soap"]["soap_carry_pickup"] = %ch_pragueb_3_1_pickup_soap;
    level._id_0C59["soap"]["soap_carry_idle"][0] = %ch_pragueb_3_1_idle_soap;
    level._id_0C59["soap"]["soap_carry_run"][0] = %ch_pragueb_3_1_run_soap;
    level._id_0C59["price"]["grenade_fire_a"] = %ch_pragueb_3_1_grenade_fire_a_price;
    level._id_0C59["price"]["grenade_fire_b"] = %ch_pragueb_3_1_grenade_fire_b_price;
    maps\_anim::_id_1264( "price", "fire_grenade", maps\prague_escape_soap_carry::_id_7B2E, "grenade_fire_a" );
    maps\_anim::_id_1264( "price", "fire_grenade", maps\prague_escape_soap_carry::_id_7B2F, "grenade_fire_b" );
    maps\_anim::_id_1264( "price", "dialogue01", maps\prague_escape_soap_carry::_id_7B31, "grenade_fire_b" );
    level._id_0C59["soap"]["soap_carry_cough"] = %ch_pragueb_3_2_cough_soap;
    level._id_0C59["price"]["soap_carry_cough_stop"] = %ch_pragueb_3_2_throw_smoke_price;
    maps\_anim::_id_1267( "price", "pull_pin", "soap_carry_cough_throw_smoke", "soap_carry_cough_stop" );
    maps\_anim::_id_1264( "price", "dialogue02", maps\prague_escape_soap_carry::_id_7B36, "soap_carry_cough_stop" );
    maps\_anim::_id_1267( "price", "dialogue03", "soap_carry_cough_stop_dialogue_3", "soap_carry_cough_stop" );
    maps\_anim::_id_1267( "price", "dialogue04", "soap_carry_cough_stop_dialogue_4", "soap_carry_cough_stop" );
    level._id_0C59["soap"]["soap_carry_cough_stop"] = %ch_pragueb_3_1_cough_stop_soap;
    maps\_anim::_id_1264( "soap", "dialogue01", maps\prague_escape_soap_carry::_id_7B35, "soap_carry_cough_stop" );
    level._id_0C59["price"]["clear_path_in"] = %ch_pragueb_3_3_clear_path_in_price;
    level._id_0C59["price"]["clear_path_loop"][0] = %ch_pragueb_3_3_clear_path_loop_price;
    level._id_0C59["price"]["clear_path_out"] = %ch_pragueb_3_3_clear_path_out_price;
    maps\_anim::_id_1264( "price", "fire_grenade", maps\prague_escape_soap_carry::_id_7B30, "clear_path_out" );
    maps\_anim::_id_1264( "price", "dialogue01", maps\prague_escape_soap_carry::_id_7B32, "clear_path_in" );
    maps\_anim::_id_1267( "price", "dialogue02", "clear_path_dialogue_2", "clear_path_out" );
    level._id_0C59["price"]["toss_gun_idle"][0] = %ch_pragueb_3_5_toss_m203_idle_price;
    level._id_0C59["price"]["toss_gun_in"] = %ch_pragueb_3_5_toss_m203_in_price;
    level._id_0C59["price"]["toss_gun"] = %ch_pragueb_3_5_toss_m203_price;
    maps\_anim::_id_1264( "price", "handoff_rumble", maps\prague_escape_code::_id_7A56, "toss_gun" );
    level._id_0C59["soap"]["toss_gun"] = %ch_pragueb_3_5_toss_m203_soap;
    level._id_0C59["price"]["soap_lift_dumpster"] = %ch_pragueb_4_1_priceliftsoap_price;
    level._id_0C59["soap"]["soap_lift_dumpster"] = %ch_pragueb_4_1_priceliftsoap_soap;
    level._id_0C59["price"]["kickdoor_dumpster"] = %ch_pragueb_4_2_kickdoor_price;
    level._id_0C59["soap"]["kickdoor_dumpster"] = %ch_pragueb_4_2_kickdoor_soap;
    level._id_0C59["price"]["idle_roomclear"][0] = %ch_pragueb_4_3_idle_price;
    level._id_0C59["soap"]["idle_roomclear"][0] = %ch_pragueb_4_3_idle_soap;
    level._id_0C59["price"]["reachroom"] = %ch_pragueb_4_3_reachroom_price;
    level._id_0C59["soap"]["reachroom"] = %ch_pragueb_4_3_reachroom_soap;
    level._id_0C59["price"]["reachdoor"] = %ch_pragueb_4_4_reachdoor_price;
    maps\_anim::_id_1264( "price", "bang", maps\prague_escape_dumpster::_id_7B75, "reachdoor" );
    level._id_0C59["soap"]["reachdoor"] = %ch_pragueb_4_4_reachdoor_soap;
    level._id_0C59["price"]["clearroom"][0] = %ch_pragueb_4_4_clearroom_price;
    maps\_anim::_id_1264( "price", "bang", maps\prague_escape_dumpster::_id_7B75, "clearroom" );
    level._id_0C59["soap"]["clearroom"][0] = %ch_pragueb_4_4_clearroom_soap;
    maps\_anim::_id_1264( "soap", "bang", maps\prague_escape_dumpster::_id_7B75, "clearroom" );
    level._id_0C59["price"]["idle_clearroom"][0] = %ch_pragueb_4_4_clearroomidle_price;
    level._id_0C59["soap"]["idle_clearroom"][0] = %ch_pragueb_4_4_clearroomidle_soap;
    level._id_0C59["price"]["doorbreach"] = %ch_pragueb_4_4_doorbreach_price;
    level._id_0C59["soap"]["doorbreach"] = %ch_pragueb_4_4_doorbreach_soap;
    maps\_anim::_id_1264( "soap", "magic_shot", maps\prague_escape_dumpster::_id_7B76, "doorbreach" );
    level._id_1245["dead_guy"] = #animtree;
    level._id_0C59["dead_guy"]["resist_death01"] = %dying_crawl_death_v1;
    level._id_0C59["dead_guy"]["resist_death02"] = %dying_back_death_v1;
    level._id_0C59["dead_guy"]["resist_death03"] = %crawl_death_front;
    level._id_0C59["price"]["to_courtyard"] = %ch_pragueb_5_1_courtyard_price;
    level._id_0C59["soap"]["to_courtyard"] = %ch_pragueb_5_1_courtyard_soap;
    level._id_0C59["soap"]["idle_statue"][0] = %ch_pragueb_5_2_statue_idleloop_soap;
    level._id_0C59["price"]["statue"] = %ch_pragueb_5_2_statue_price;
    maps\_anim::_id_1264( "price", "fire", maps\prague_escape_store::_id_7BA1, "statue" );
    level._id_0C59["soap"]["statue"] = %ch_pragueb_5_2_statue_soap;
    level._id_0C59["price"]["statue_leave"] = %ch_pragueb_5_2_statueleave_price;
    maps\_anim::_id_1264( "price", "drop_gunground", maps\prague_escape_store::_id_7BA3, "statue_leave" );
    maps\_anim::_id_1264( "price", "attach_pistol", maps\prague_escape_store::_id_7BA4, "statue_leave" );
    level._id_0C59["soap"]["statue_leave"] = %ch_pragueb_5_2_statueleave_soap;
    level._id_0C59["price"]["thru_building"] = %ch_pragueb_6_1_throughbuilding_price;
    maps\_anim::_id_1264( "price", "kick_door", maps\prague_escape_store::_id_7BB4, "thru_building" );
    level._id_0C59["soap"]["thru_building"] = %ch_pragueb_6_1_throughbuilding_soap;
    level._id_0C59["price"]["advance_building"] = %ch_pragueb_6_1_throughbuilding_advance_price;
    level._id_0C59["soap"]["advance_building"] = %ch_pragueb_6_1_throughbuilding_advance_soap;
    level._id_0C59["price"]["take_cover"] = %ch_pragueb_6_1_throughbuilding_takecover_price;
    level._id_0C59["soap"]["take_cover"] = %ch_pragueb_6_1_throughbuilding_takecover_soap;
    level._id_0C59["price"]["idle_building"][0] = %ch_pragueb_6_1_throughbuilding_loop_price;
    level._id_0C59["soap"]["idle_building"][0] = %ch_pragueb_6_1_throughbuilding_loop_soap;
    level._id_0C59["price"]["cover_exit"] = %ch_pragueb_6_1_throughbuilding_takecover_exit_price;
    level._id_0C59["soap"]["cover_exit"] = %ch_pragueb_6_1_throughbuilding_takecover_exit_soap;
    level._id_0C59["price"]["to_street"] = %ch_pragueb_6_2_street_price;
    level._id_0C59["soap"]["to_street"] = %ch_pragueb_6_2_street_soap;
    level._id_0C59["price"]["idle_street"][0] = %ch_pragueb_6_2_street_idleloop_price;
    level._id_0C59["soap"]["idle_street"][0] = %ch_pragueb_6_2_street_idleloop_soap;
    level._id_0C59["price"]["to_tunnel"] = %ch_pragueb_7_1_alleytunnel_price;
    level._id_0C59["soap"]["to_tunnel"] = %ch_pragueb_7_1_alleytunnel_soap;
    level._id_0C59["price"]["bank_divert"] = %ch_pragueb_7_2_enemyarrive_price;
    maps\_anim::_id_1264( "price", "fire", maps\prague_escape_bank::_id_7BC1, "bank_divert" );
    level._id_0C59["soap"]["bank_divert"] = %ch_pragueb_7_2_enemyarrive_soap;
    level._id_0C59["price"]["enter_bank"] = %ch_pragueb_7_3_enterbank_price;
    maps\_anim::_id_1264( "price", "fire", maps\prague_escape_bank::_id_7BC1, "enter_bank" );
    level._id_0C59["soap"]["enter_bank"] = %ch_pragueb_7_3_enterbank_soap;
    level._id_0C59["price"]["idle_bank_battle"][0] = %ch_pragueb_7_4_bankbattle_loop__price;
    maps\_anim::_id_1264( "price", "fire", maps\prague_escape_bank::_id_7BBF, "idle_bank_battle" );
    level._id_0C59["soap"]["idle_bank_battle"][0] = %ch_pragueb_7_4_bankbattle_loop__soap;
    maps\_anim::_id_1264( "soap", "fire", maps\prague_escape_bank::_id_7BC0, "idle_bank_battle" );
    level._id_0C59["price"]["exit_bank"] = %ch_pragueb_7_4_bankexit_price;
    level._id_0C59["soap"]["exit_bank"] = %ch_pragueb_7_4_bankexit_soap;
    level._id_0C59["price"]["crosscourt"] = %ch_pragueb_7_5_crosscourt_price;
    maps\_anim::_id_1264( "price", "hide_gun", maps\prague_escape_defend::_id_7C7B, "crosscourt" );
    maps\_anim::_id_1264( "price", "bang", maps\prague_escape_defend::_id_7C7A, "crosscourt" );
    level._id_0C59["soap"]["crosscourt"] = %ch_pragueb_7_5_crosscourt_soap;
    level._id_0C59["price"]["crossplaza"] = %ch_pragueb_7_5_crossplaza_price;
    maps\_anim::_id_1264( "price", "show_m16", maps\prague_escape_defend::_id_7C7C, "crossplaza" );
    level._id_0C59["soap"]["crossplaza"] = %ch_pragueb_7_5_crossplaza_soap;
    level._id_0C59["soap"]["idle_fire_soap"][0] = %ch_pragueb_8_1_plazadefend_fire_soap;
    level._id_0C59["soap"]["idle_soap"][0] = %ch_pragueb_8_1_plazadefend_idle_soap;
    level._id_0C59["resistance1"]["resistancearrive2"] = %ch_pragueb_9_1_resistancearrive_guy01;
    level._id_0C59["resistance2"]["resistancearrive2"] = %ch_pragueb_9_1_resistancearrive_guy02;
    level._id_0C59["resistance3"]["resistancearrive2"] = %ch_pragueb_9_1_resistancearrive_guy03;
    level._id_0C59["resistance4"]["resistancearrive1"] = %ch_pragueb_9_1_resistancearrive_guy04;
    level._id_0C59["resistance_leader"]["resistancearrive1"] = %ch_pragueb_9_1_resistancearrive_leader;
    level._id_0C59["price"]["resistancearrive1"] = %ch_pragueb_9_1_resistancearrive_price;
    level._id_0C59["soap"]["resistancearrive1"] = %ch_pragueb_9_1_resistancearrive_soap;
    level._id_0C59["resistance4"]["idle_carry"][0] = %ch_pragueb_9_2_resistancecarry_loop_guy04;
    level._id_0C59["resistance_leader"]["idle_carry"][0] = %ch_pragueb_9_2_resistancecarry_loop_leader;
    level._id_0C59["price"]["idle_carry"][0] = %ch_pragueb_9_2_resistancecarry_loop_price;
    level._id_0C59["soap"]["idle_carry"][0] = %ch_pragueb_9_2_resistancecarry_loop_soap;
    level._id_0C59["resistance4"]["resistancecarry"] = %ch_pragueb_9_2_resistancecarry_guy04;
    level._id_0C59["resistance_leader"]["resistancecarry"] = %ch_pragueb_9_2_resistancecarry_leader;
    level._id_0C59["price"]["resistancecarry"] = %ch_pragueb_9_2_resistancecarry_price;
    level._id_0C59["soap"]["resistancecarry"] = %ch_pragueb_9_2_resistancecarry_soap;
    level._id_0C59["resistance4"]["idle_table"][0] = %ch_pragueb_9_2_resistancecarry_tableloop_guy04;
    level._id_0C59["resistance_leader"]["idle_table"][0] = %ch_pragueb_9_2_resistancecarry_tableloop_leader;
    level._id_0C59["price"]["idle_table"][0] = %ch_pragueb_9_2_resistancecarry_tableloop_price;
    level._id_0C59["soap"]["idle_table"][0] = %ch_pragueb_9_2_resistancecarry_tableloop_soap;
    level._id_0C59["resistance_leader"]["idle_clear_table"][0] = %ch_pragueb_10_1_clear_table_idle_guy1;
    level._id_0C59["resistance_leader"]["clear_table"] = %ch_pragueb_10_1_clear_table_guy1;
    level._id_0C59["enemy"]["balcony_death"] = %ch_pragueb_5_2_statue_balconydeath01;
    level._id_0C59["enemy"]["idle_balcony_death"][0] = %ch_pragueb_5_2_statue_balconydeath01_loop;
    level._id_0C59["enemy"]["bank_entry_dive"] = %ch_pragueb_7_4_bankbattle_enemyentry_diveover;
    maps\_anim::_id_1264( "enemy", "window_break", maps\prague_escape_bank::_id_7BDE, "bank_entry_dive" );
    level._id_0C59["enemy"]["bank_entry_jump"] = %ch_pragueb_7_4_bankbattle_enemyentry_jumpover;
    maps\_anim::_id_1264( "enemy", "window_break", maps\prague_escape_bank::_id_7BDD, "bank_entry_jump" );
    level._id_0C59["enemy"]["bank_entry_left"] = %ch_pragueb_7_4_bankbattle_enemyentry_windowleft;
    level._id_0C59["enemy"]["bank_entry_right"] = %ch_pragueb_7_4_bankbattle_enemyentry_windowright;
    level._id_0C59["enemy"]["bank_entry_door1"] = %ch_pragueb_7_4_bankbattle_enemyentry_guycover01;
    level._id_0C59["enemy"]["bank_entry_door2"] = %ch_pragueb_7_4_bankbattle_enemyentry_guycover02;
    level._id_0C59["enemy"]["court_mantle_A"] = %ch_pragueb_7_5_crosscourt_aimantle_a;
    level._id_0C59["enemy"]["court_mantle_B"] = %ch_pragueb_7_5_crosscourt_aimantle_b;
    level._id_0C59["enemy"]["court_mantle_C"] = %ch_pragueb_7_5_crosscourt_aimantle_c;
    level._id_0C59["enemy"]["court_mantle_D"] = %ch_pragueb_7_5_crosscourt_aimantle_d;
    level._id_0C59["enemy"]["court_mantle_E"] = %ch_pragueb_7_5_crosscourt_aimantle_e;
    level._id_0C59["enemy"]["court_mantle_F"] = %ch_pragueb_7_5_crosscourt_aimantle_f;
    level._id_0C59["enemy"]["court_mantle_G"] = %ch_pragueb_7_5_crosscourt_aimantle_g;
    level._id_0C59["enemy"]["court_jumpdown_A"] = %ch_pragueb_7_5_crosscourt_aitmantle_off_a;
    level._id_0C59["enemy"]["court_jumpdown_B"] = %ch_pragueb_7_5_crosscourt_aitmantle_off_b;
    level._id_0C59["enemy"]["court_jumpdown_C"] = %ch_pragueb_7_5_crosscourt_aitmantle_off_c;
    level._id_0C59["enemy"]["sprint"] = %sprint1_loop;
    level._id_0C59["enemy"]["box_traverse_A"] = %ch_pragueb_8_1_plazadefend_boxtraversea;
    level._id_0C59["enemy"]["box_traverse_B"] = %ch_pragueb_8_1_plazadefend_boxtraverseb;
    level._id_0C59["enemy"]["box_traverse_C"] = %ch_pragueb_8_1_plazadefend_boxtraversec;
    level._id_0C59["enemy"]["box_traverse_D"] = %ch_pragueb_8_1_plazadefend_boxtraversed;
    level._id_0C59["enemy"]["fence_traverse"] = %ch_pragueb_8_1_plazadefend_fencetraverse;
    level._id_0C59["door_breacher"]["doorbreach"] = %ch_pragueb_4_4_doorbreach_doorkicker;
    level._id_0C59["btr_victim"]["death_window"] = %ch_pragueb_9_1_resistancewindow_death;
    maps\_anim::_id_1264( "btr_victim", "start_ragdoll", maps\prague_escape_defend::_id_7C62, "death_window" );
    level._id_0C59["generic"]["death_forward"] = %stand_death_stumbleforward;
    level._id_0C59["price"]["gesture"] = %ch_pragueb_10_1_savingsoap_callingplayer_price;
    maps\_anim::_id_1264( "price", "dialogue01", maps\prague_escape_medic::_id_7C10, "gesture" );
    level._id_0C59["price"]["no_pressure"][0] = %ch_pragueb_10_1_savingsoap_nopressure_price;
    maps\_anim::_id_1267( "price", "dialogue02", "price_put_pressure_dialogue02", "no_pressure" );
    level._id_0C59["soap"]["no_pressure"][0] = %ch_pragueb_10_1_savingsoap_nopressure_soap;
    level._id_0C59["resistance_guy1"]["no_pressure"][0] = %ch_pragueb_10_1_savingsoap_nopressure_soldier1;
    level._id_0C59["resistance_guy2"]["no_pressure"][0] = %ch_pragueb_10_1_savingsoap_nopressure_soldier2;
    level._id_0C59["price"]["slow_death"] = %ch_pragueb_10_1_savingsoap_slowdeath_price;
    maps\_anim::_id_1264( "price", "presc_pri_donttrytospeak", maps\prague_escape_medic::_id_7C0E, "slow_death" );
    maps\_anim::_id_1267( "price", "presc_pri_tellmelater", "price_slowdeath_tellmelater", "slow_death" );
    maps\_anim::_id_1267( "price", "presc_pri_soap2", "price_slowdeath_soap2", "slow_death" );
    level._id_0C59["soap"]["slow_death"] = %ch_pragueb_10_1_savingsoap_slowdeath_soap;
    maps\_anim::_id_1264( "soap", "presc_mct_price2", maps\prague_escape_medic::_id_7C0F, "slow_death" );
    maps\_anim::_id_1267( "soap", "presc_mct_needtoknow", "soap_slowdeath_needtoknow", "slow_death" );
    maps\_anim::_id_1267( "soap", "presc_mct_knowsyuri", "soap_slowdeath_knowsyuri", "slow_death" );
    level._id_0C59["resistance_guy1"]["slow_death"] = %ch_pragueb_10_1_savingsoap_slowdeath_soldier1;
    level._id_0C59["resistance_guy2"]["slow_death"] = %ch_pragueb_10_1_savingsoap_slowdeath_soldier2;
    level._id_0C59["price"]["soap_death"] = %prague_escape_soap_death_price;
    level._id_0C59["price"]["soap_death_idle"][0] = %prague_escape_soap_death_price_idle;
    level._id_0C59["soap"]["soap_death"] = %prague_escape_soap_death_soap;
    level._id_0C59["soap"]["soap_dead"][0] = %prague_escape_soap_death_soap_idle_noloop;
    level._id_0C59["soap"]["soap_death_idle"][0] = %prague_escape_soap_death_soap_idle;
    level._id_0C59["resistance_leader"]["soap_death"] = %prague_escape_soap_death_resistance;
    level._id_0C59["resistance_leader"]["soap_death_idle"][0] = %prague_escape_soap_death_resistance_idle;
    level._id_0C59["resistance_leader"]["soap_death_window_run"] = %prague_escape_soap_death_resistance_runtowindow;
    maps\_anim::_id_1264( "price", "attach_pistol", maps\prague_escape_medic::_id_7BEA, "soap_death" );
    maps\_anim::_id_1264( "price", "detach_pistol", maps\prague_escape_medic::_id_7BEB, "soap_death" );
    maps\_anim::_id_1264( "price", "attach_journal", maps\prague_escape_medic::_id_7BEC, "soap_death" );
    maps\_anim::_id_1264( "price", "detach_journal", maps\prague_escape_medic::_id_7BED, "soap_death" );
    level._id_0C59["price"]["escape_loop"][0] = %ch_pragueb_11_1_escape_price_loop;
    level._id_0C59["price"]["escape"] = %ch_pragueb_11_1_escape_price;
    level._id_0C59["soap"]["escape_loop"][0] = %ch_pragueb_11_1_escape_soap_loop;
    level._id_0C59["resistance_guy1"]["escape_loop"][0] = %ch_pragueb_11_1_escape_res_guy_1_loop;
    level._id_0C59["resistance_guy1"]["escape"] = %ch_pragueb_11_1_escape_res_guy_1;
    level._id_0C59["resistance_guy2"]["escape_loop"][0] = %ch_pragueb_11_1_escape_res_guy_2_loop;
    level._id_0C59["resistance_guy2"]["escape"] = %ch_pragueb_11_1_escape_res_guy_2;
    maps\_anim::_id_1267( "resistance_guy1", "blood_fx", "start_blood_fx", "escape" );
    maps\_anim::_id_1264( "resistance_guy1", "start_ragdoll", maps\prague_escape_medic::_id_7BF4, "escape" );
    maps\_anim::_id_1264( "resistance_guy2", "kill_me", maps\prague_escape_medic::_id_7BF4, "escape" );
    level._id_0C59["resistance_leader"]["escape"] = %ch_pragueb_11_1_escape_res_leader;
    maps\_anim::_id_1264( "resistance_leader", "dialogue01", maps\prague_escape_to_cellar::_id_7CC6, "escape" );
    maps\_anim::_id_1267( "resistance_leader", "dialogue02", "leader_escape_dialogue02", "escape" );
    maps\_anim::_id_1267( "resistance_leader", "dialogue03", "leader_escape_dialogue03", "escape" );
    level._id_0C59["resistance_leader"]["escape_loop"][0] = %ch_pragueb_11_1_escape_res_leader_loop;
    level._id_0C59["resistance_leader"]["escape_shoot_loop"][0] = %ch_pragueb_11_1_escape_res_leader_wave_loop;
    level._id_0C59["resistance_leader"]["escape_wave"] = %ch_pragueb_11_1_escape_res_leader_wave;
    maps\_anim::_id_1267( "resistance_leader", "leader_wave_start", "leader_wave_set", "escape_shoot_loop" );
    maps\_anim::_id_1268( "resistance_leader", "leader_wave_clear", "leader_wave_set", "escape_shoot_loop" );
    level._id_0C59["price"]["price_punch_loop"][0] = %ch_pragueb_12_1_punch_price_loop;
    level._id_0C59["price"]["price_punch"] = %ch_pragueb_11_1_punch_price;
    maps\_anim::_id_1264( "price", "dialog_01", maps\prague_escape_to_cellar::_id_7CC8, "price_punch" );
    maps\_anim::_id_1267( "price", "dialog_02", "price_punch_dialog_02", "price_punch" );
    maps\_anim::_id_1267( "price", "dialog_03", "price_punch_dialog_03", "price_punch" );
    maps\_anim::_id_1264( "price", "open_door", maps\prague_escape_code::_id_7A56, "price_punch" );
    level._id_0C59["makarov"]["no_time"] = %ch_pragueb_13_1_no_time_maka;
    level._id_0C59["guard_1"]["bullet_strikes"] = %ch_pragueb_13_3_bullet_strikes_grd_01;
    level._id_0C59["guard_2"]["bullet_strikes"] = %ch_pragueb_13_3_bullet_strikes_grd_02;
    level._id_0C59["makarov"]["bullet_strikes"] = %ch_pragueb_13_3_bullet_strikes_maka;
    maps\_anim::_id_1267( "makarov", "dialogue06", "makarov_bullet_strike_dialogue03", "bullet_strikes" );
    level._id_0C59["zakhaev"]["bullet_strikes"] = %ch_pragueb_13_3_bullet_strikes_zakh;
    maps\_anim::_id_1267( "zakhaev", "dialogue07", "zakhaev_bullet_strike_dialogue04", "bullet_strikes" );
    level._id_0C59["generic"]["cqb_stop"] = %cqb_stop_2_signal;
    level._id_0C59["generic"]["exchange_surprise_0"] = %exposed_idle_reacta;
    level._id_0C59["generic"]["exchange_surprise_1"] = %exposed_idle_reactb;
    level._id_0C59["generic"]["exchange_surprise_2"] = %exposed_idle_twitch;
    level._id_0C59["generic"]["exchange_surprise_3"] = %exposed_idle_twitch_v4;
    level._id_7AD1 = 4;
    level._id_0C59["zakhaev"]["exchange_short"] = %ch_pragueb_13_1_meeting_zakhaev;
    maps\_anim::_id_1264( "zakhaev", "presc_zkv_whatdoyou", maps\prague_escape_flashback_sniper::_id_7CC0, "exchange_short" );
    maps\_anim::_id_1267( "zakhaev", "presc_zkv_hadadeal", "zakhaev_exchange_hadadeal", "exchange_short" );
    maps\_anim::_id_1267( "zakhaev", "presc_zkv_argueover", "zakhaev_exchange_argueover", "exchange_short" );
    maps\_anim::_id_1267( "zakhaev", "presc_zkv_knownbetter", "zakhaev_exchange_knownbetter", "exchange_short" );
    maps\_anim::_id_1267( "zakhaev", "flag_drop_1", "drop_the_flag", "exchange_short" );
    level._id_0C59["guard"]["exchange_short"] = %ch_pragueb_13_1_meeting_guard;
    level._id_0C59["dealer"]["exchange_short"] = %ch_pragueb_13_1_meeting_dealer;
    level._id_1245["zakhaev"] = #animtree;
    level._id_1F90["zakhaev"] = "body_complete_onearm_sp_zakhaev";
    level._id_0C59["zakhaev"]["zak_pain"] = %sniper_escape_meeting_zakhaev_hit_front;
    level._id_0C59["generic"]["stealth_jog"] = %patrol_jog;
    level._id_0C59["generic"]["stealth_walk"] = %patrol_bored_patrolwalk;
    level._id_0C59["generic"]["combat_jog"] = %combat_jog;
    level._id_0C59["generic"]["bored_cell_loop"][0] = %patrol_bored_idle_cellphone;
    level._id_0C59["generic"]["smoking_lean_idle"][0] = %parabolic_leaning_guy_smoking_idle;
    level._id_0C59["generic"]["smoking_lean_twitch"][0] = %parabolic_leaning_guy_smoking_twitch;
    level._id_0C59["generic"]["smoking_lean_react"] = %parabolic_leaning_guy_react;
    level._id_0C59["generic"]["bored_idle"][0] = %patrol_bored_idle;
    level._id_0C59["generic"]["bored_idle"][1] = %patrol_bored_twitch_bug;
    level._id_0C59["generic"]["bored_idle"][2] = %patrol_bored_twitch_stretch;
    level._id_0C59["generic"]["smoke_idle"][0] = %patrol_bored_idle_smoke;
    level._id_1245["makarov"] = #animtree;
    level._id_0C59["makarov"]["shock_and_awe"] = %ch_pragueb_14_1_shockandawe_makarov;
    level._id_0C59["makarov"]["phonecall"] = %ch_pragueb_14_1_shockandawe_makarov_phonecall;
    maps\_anim::_id_1267( "makarov", "take_phone", "FLAG_nuke_makarov_take_phone", "phonecall" );
    level._id_0C59["makarov"]["blast"] = %ch_pragueb_14_1_shockandawe_makarov_blast;
    level._id_0C59["makarov"]["idle"][0] = %ch_pragueb_14_1_shockandawe_makarov_idle;
    level._id_0C59["poor_bastard"]["crewchief_sucked_out"] = %airlift_crewchief_sucked_out;
    level._id_0C59["kiril"]["betray_me"] = %ch_pragueb_15_1_betray_me_guy_1;
    level._id_0C59["lev"]["betray_me"] = %ch_pragueb_15_1_betray_me_guy_2;
    level._id_0C59["makarov"]["betray_me"] = %ch_pragueb_15_1_betray_me_makarov;
    maps\_anim::_id_1267( "makarov", "fire", "makarov_shoots_yuri", "betray_me" );
    level._id_1245["hurt_officer_1"] = #animtree;
    level._id_1F90["hurt_officer_1"] = "body_secret_service_assault_a";
    level._id_0C59["hurt_officer_1"]["wounded_civ"] = %ch_pragueb_15_6_wounded_civ_01;
    level._id_0C59["hurt_officer_1"]["wounded_civ_loop"][0] = %ch_pragueb_15_6_wounded_civ_01_loop;
    level._id_1245["hurt_officer_2"] = #animtree;
    level._id_1F90["hurt_officer_2"] = "body_secret_service_assault_a";
    level._id_0C59["hurt_officer_2"]["wounded_civ"] = %ch_pragueb_15_6_wounded_civ_02;
    level._id_0C59["hurt_officer_2"]["wounded_civ_loop"][0] = %ch_pragueb_15_6_wounded_civ_02_loop;
    level._id_1245["wounded_officer"] = #animtree;
    level._id_1F90["wounded_officer"] = "body_secret_service_assault_a";
    level._id_0C59["wounded_officer"]["wounded_officer"] = %ch_pragueb_15_6_wounded_officer;
    level._id_0C59["wounded_officer"]["wounded_officer_loop"][0] = %ch_pragueb_15_6_wounded_officer_loop;
    level._id_1245["neck_wound_civ"] = #animtree;
    level._id_0C59["neck_wound_civ"]["wounded_civ"] = %ch_pragueb_15_6_wounded_civ_03;
    level._id_0C59["neck_wound_civ"]["death"] = %civilian_leaning_death;
    level._id_1F90["neck_wound_civ"] = "body_urban_civ_male_ba";
    level._id_1245["crying_civ"] = #animtree;
    level._id_0C59["crying_civ"]["wounded_civ"] = %ch_pragueb_15_6_wounded_civ_04;
    level._id_0C59["crying_civ"]["death"] = %civilian_leaning_death_shot;
    level._id_1F90["crying_civ"] = "body_slum_civ_female_ba";
    level._id_1245["wounded_shoulder"] = #animtree;
    level._id_0C59["wounded_shoulder"]["wounded_civ"] = %ch_pragueb_15_6_wounded_civ_05;
    level._id_1F90["wounded_shoulder"] = "body_complete_civilian_suit_male_1";
    level._id_1245["headwound_civ"] = #animtree;
    level._id_0C59["headwound_civ"]["wounded_civ"] = %ch_pragueb_15_6_wounded_civ_06;
    level._id_1F90["headwound_civ"] = "body_slum_civ_female_ba";
    level._id_1245["falling_civ"] = #animtree;
    level._id_1F90["falling_civ"] = "body_slum_civ_female_ba";
    level._id_0C59["falling_civ"]["death"] = %airport_civ_dying_groupa_kneel_death;
    level._id_1245["crawling_civ"] = #animtree;
    level._id_1F90["crawling_civ"] = "body_urban_civ_male_bc";
    level._id_0C59["crawling_civ"]["crawl"] = %civilian_crawl_2;
    level._id_0C59["crawling_civ"]["death"] = %civilian_crawl_2_death_a;
    level._id_1245["male_red_stripes"] = #animtree;
    level._id_1F90["male_red_stripes"] = "body_urban_civ_male_ba";
    level._id_0C59["male_red_stripes"]["lobby_death_pose_12a"][0] = %ch_pragueb_civ_in_line_12_a_death_pose;
    level._id_1245["security"] = #animtree;
    level._id_1F90["security"] = "body_secret_service_assault_a";
    level._id_0C59["security"]["lobby_death_pose_13i"][0] = %ch_pragueb_civ_in_line_13_i_death_pose;
    level._id_0C59["security"]["lobby_death_pose_9c"][0] = %ch_pragueb_civ_in_line_9_c_death_pose;
    level._id_1245["male_green_blue"] = #animtree;
    level._id_1F90["male_green_blue"] = "body_urban_civ_male_bb";
    level._id_0C59["male_green_blue"]["lobby_death_pose_12b"][0] = %ch_pragueb_civ_in_line_12_b_death_pose;
    level._id_0C59["male_green_blue"]["lobby_death_pose_13h"][0] = %ch_pragueb_civ_in_line_13_h_death_pose;
    level._id_1245["male_blue_khaki"] = #animtree;
    level._id_1F90["male_blue_khaki"] = "body_urban_civ_male_aa";
    level._id_0C59["male_blue_khaki"]["lobby_death_pose_12c"][0] = %ch_pragueb_civ_in_line_12_c_death_pose;
    level._id_0C59["male_blue_khaki"]["lobby_death_pose_13c"][0] = %ch_pragueb_civ_in_line_13_c_death_pose;
    level._id_0C59["male_blue_khaki"]["lobby_death_pose_15c"][0] = %ch_pragueb_civ_in_line_15_c_death_pose;
    level._id_0C59["male_blue_khaki"]["lobby_death_pose_13d"][0] = %ch_pragueb_civ_in_line_13_d_death_pose;
    level._id_0C59["male_blue_khaki"]["lobby_death_pose_10a"][0] = %ch_pragueb_civ_in_line_10_a_death_pose;
    level._id_1245["male_red_blue"] = #animtree;
    level._id_1F90["male_red_blue"] = "body_urban_civ_male_bc";
    level._id_0C59["male_red_blue"]["lobby_death_pose_15a"][0] = %ch_pragueb_civ_in_line_15_a_death_pose;
    level._id_0C59["male_red_blue"]["lobby_death_pose_10c"][0] = %ch_pragueb_civ_in_line_10_c_death_pose;
    level._id_0C59["male_red_blue"]["lobby_death_pose_13j"][0] = %ch_pragueb_civ_in_line_13_j_death_pose;
    level._id_1245["airport_male_suit"] = #animtree;
    level._id_1F90["airport_male_suit"] = "body_complete_civilian_suit_male_1";
    level._id_0C59["airport_male_suit"]["lobby_death_pose_6a"][0] = %ch_pragueb_civ_in_line_6_a_death_pose;
    level._id_0C59["airport_male_suit"]["lobby_death_pose_6b"][0] = %ch_pragueb_civ_in_line_6_b_death_pose;
    level._id_0C59["airport_male_suit"]["lobby_death_pose_9a"][0] = %ch_pragueb_civ_in_line_9_a_death_pose;
    level._id_0C59["airport_male_suit"]["lobby_death_pose_13e"][0] = %ch_pragueb_civ_in_line_13_e_death_pose;
    level._id_0C59["airport_male_suit"]["lobby_death_pose_13g"][0] = %ch_pragueb_civ_in_line_13_g_death_pose;
    level._id_1245["escalator_male_suit"] = #animtree;
    level._id_1F90["escalator_male_suit"] = "body_complete_civilian_suit_male_1";
    level._id_0C59["escalator_male_suit"]["lobby_death_pose_12b"][0] = %ch_pragueb_civ_escalator_12_b_death_pose;
    level._id_0C59["escalator_male_suit"]["lobby_death_pose_12c"][0] = %ch_pragueb_civ_escalator_12_c_death_pose;
    level._id_0C59["escalator_male_suit"]["lobby_death_pose_12h"][0] = %ch_pragueb_civ_escalator_12_h_death_pose;
    level._id_1245["escalator_female_green"] = #animtree;
    level._id_1F90["escalator_female_green"] = "body_slum_civ_female_ba";
    level._id_0C59["escalator_female_green"]["lobby_death_pose_12d"][0] = %ch_pragueb_civ_escalator_12_d_death_pose;
    level._id_1245["escalator_male_red"] = #animtree;
    level._id_1F90["escalator_male_red"] = "body_urban_civ_male_bc";
    level._id_0C59["escalator_male_red"]["lobby_death_pose_12f"][0] = %ch_pragueb_civ_escalator_12_f_death_pose;
    level._id_0C59["escalator_male_red"]["lobby_death_pose_12g"][0] = %ch_pragueb_civ_escalator_12_g_death_pose;
    level._id_1245["escalator_male_blue"] = #animtree;
    level._id_1F90["escalator_male_blue"] = "body_urban_civ_male_aa";
    level._id_0C59["escalator_male_blue"]["lobby_death_pose_12e"][0] = %ch_pragueb_civ_escalator_12_e_death_pose;
    level._id_1245["female_gray_blue"] = #animtree;
    level._id_1F90["female_gray_blue"] = "body_slum_civ_female_ba";
    level._id_0C59["female_gray_blue"]["lobby_death_pose_10b"][0] = %ch_pragueb_civ_in_line_10_b_death_pose;
    level._id_0C59["female_gray_blue"]["lobby_death_pose_9b"][0] = %ch_pragueb_civ_in_line_9_b_death_pose;
    level._id_0C59["female_gray_blue"]["lobby_death_pose_13a"][0] = %ch_pragueb_civ_in_line_13_a_death_pose;
    level._id_0C59["female_gray_blue"]["lobby_death_pose_13f"][0] = %ch_pragueb_civ_in_line_13_f_death_pose;
    level._id_0C59["female_gray_blue"]["lobby_death_pose_13k"][0] = %ch_pragueb_civ_in_line_13_k_death_pose;
    level._id_1245["price_stream_model"] = #animtree;
    level._id_1F90["price_stream_model"] = "body_tf141_assault_a";
    level._id_0C59["price_stream_model"]["lobby_death_pose_12e"][0] = %ch_pragueb_civ_escalator_12_e_death_pose;
    level._id_1245["emt"] = #animtree;
    level._id_1F90["emt"] = "body_secret_service_assault_a";
    level._id_0C59["emt"]["emt_assist"] = %ch_pragueb_16_1_emt_assist_guy_01;
    level._id_0C59["price"]["gun_to_head"] = %ch_pragueb_16_1_gun_to_head_price;
    maps\_anim::_id_125D( "price", "sfx", "gun_to_head", "scn_prague_price_last_lines_foley" );
    level._id_1245["generic"] = #animtree;
    level._id_0C59["generic"]["patrol_walk"] = %patrol_bored_patrolwalk;
    level._id_0C59["generic"]["patrol_walk_twitch"] = %patrol_bored_patrolwalk_twitch;
    level._id_0C59["generic"]["patrol_stop"] = %patrol_bored_walk_2_bored;
    level._id_0C59["generic"]["patrol_start"] = %patrol_bored_2_walk;
    level._id_0C59["generic"]["patrol_turn180"] = %patrol_bored_2_walk_180turn;
    level._id_0C59["generic"]["patrol_idle_1"] = %patrol_bored_idle;
    level._id_0C59["generic"]["patrol_idle_2"] = %patrol_bored_idle_smoke;
    level._id_0C59["generic"]["patrol_idle_3"] = %patrol_bored_idle_cellphone;
    level._id_0C59["generic"]["patrol_idle_4"] = %patrol_bored_twitch_bug;
    level._id_0C59["generic"]["patrol_idle_5"] = %patrol_bored_twitch_checkphone;
    level._id_0C59["generic"]["patrol_idle_6"] = %patrol_bored_twitch_stretch;
    level._id_0C59["generic"]["patrol_idle_smoke"] = %patrol_bored_idle_smoke;
    level._id_0C59["generic"]["patrol_idle_checkphone"] = %patrol_bored_twitch_checkphone;
    level._id_0C59["generic"]["patrol_idle_stretch"] = %patrol_bored_twitch_stretch;
    level._id_0C59["generic"]["patrol_idle_phone"] = %patrol_bored_idle_cellphone;
}
#using_animtree("player");

_id_47D9()
{
    level._id_1245["player_rig"] = #animtree;
    level._id_1F90["player_rig"] = level._id_1F5D;
    level._id_1245["player_rig_oneshot"] = #animtree;
    level._id_1F90["player_rig_oneshot"] = "viewhands_player_russian_c";
    level._id_1245["player_rig_nuke"] = #animtree;
    level._id_1F90["player_rig_nuke"] = "viewhands_player_russian_b";
    level._id_1245["player_rig_airport"] = #animtree;
    level._id_1F90["player_rig_airport"] = "viewhands_player_yuri_airport";
    level._id_1245["player_rig_airport_alt"] = #animtree;
    level._id_1F90["player_rig_airport_alt"] = "viewhands_player_yuri_airport";
    level._id_0C59["player_rig"]["belltower_intro_idle"][0] = %p_pragueb_1_1_idle_player;
    maps\_anim::_id_1264( "player_rig", "rumble_01", maps\prague_escape_code::_id_7A56, "belltower_intro" );
    level._id_0C59["player_rig"]["belltower_intro"] = %p_pragueb_1_1_setup_player;
    level._id_0C59["player_rifle"]["belltower_intro"] = %p_pragueb_1_1_setup_player_gun;
    level._id_1245["player_rifle"] = #animtree;
    level._id_1F90["player_rifle"] = "viewmodel_rsass_sp_iw5";
    maps\_anim::_id_1264( "player_rig", "dof_change_01", maps\prague_escape_code::_id_00C3, "belltower_intro" );
    maps\_anim::_id_1264( "player_rig", "dof_change_02", maps\prague_escape_code::_id_00C3, "belltower_intro" );
    maps\_anim::_id_1264( "player_rig", "dof_change_03", maps\prague_escape_code::_id_00C3, "belltower_intro" );
    maps\_anim::_id_1264( "player_rig", "dof_change_04", maps\prague_escape_code::_id_00C3, "belltower_intro" );
    maps\_anim::_id_1264( "player_rig", "rumble_02", maps\prague_escape_code::_id_7A56, "belltower_intro" );
    maps\_anim::_id_1264( "player_rig", "rumble_03", maps\prague_escape_code::_id_7A56, "belltower_intro" );
    maps\_anim::_id_1264( "player_rig", "rumble_04", maps\prague_escape_code::_id_7A56, "belltower_intro" );
    maps\_anim::_id_1267( "player_rig", "fade_out", "belltower_intro_fade_out", "belltower_intro" );
    level._id_0C59["player_rig"]["belltower_intro_setup"] = %p_pragueb_1_1_setup_player;
    level._id_0C59["player_rig"]["scaffolding_fall"] = %p_pragueb_2_2_scaffolding_fall_player;
    maps\_anim::_id_1264( "player_rig", "hide_tower", maps\prague_escape_scaffold::_id_7B4B, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "explosion_1", maps\prague_escape_scaffold::_id_7B49, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "explosion_1", maps\prague_escape_scaffold::_id_7B4C, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "player_hit_by_soap", maps\prague_escape_scaffold::_id_7B4A, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "start_scaffolding_anim", maps\prague_escape_scaffold::_id_7B4D, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "player_hit_by_soap", maps\prague_escape_code::_id_7A55, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "player_hit_by_soap", maps\prague_escape_scaffold::_id_7B5A, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "rumble", maps\prague_escape_code::_id_7A55, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "player_hit_board_1", maps\prague_escape_code::_id_7A53, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "player_hit_board_2", maps\prague_escape_scaffold::_id_7B55, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "player_hit_board_3", maps\prague_escape_code::_id_7A53, "scaffolding_fall" );
    maps\_anim::_id_1264( "player_rig", "player_hit_floor", maps\prague_escape_scaffold::_id_7B56, "scaffolding_fall" );
    level._id_0C59["player_rig"]["fade_in_a"] = %p_pragueb_2_3_fade_in_a_player;
    level._id_0C59["player_rig"]["fade_in_b"] = %p_pragueb_2_3_fade_in_b_player;
    level._id_0C59["player_rig"]["scaffold_soap_injured"] = %p_pragueb_2_3_soap_injured_player;
    level._id_0C59["player_rig"]["soap_carry_pickup"] = %p_pragueb_3_1_pickup_player;
    level._id_0C59["player_rig"]["soap_carry_idle"][0] = %p_pragueb_3_1_idle_player;
    level._id_0C59["player_rig"]["soap_carry_run"][0] = %p_pragueb_3_1_run_player;
    level._id_0C59["player_rig"]["soap_carry_cough_stop"] = %p_pragueb_3_1_cough_stop_player;
    maps\_anim::_id_1264( "player_rig", "start_price", maps\prague_escape_soap_carry::_id_7B34, "soap_carry_cough_stop" );
    level._id_0C59["player_rig"]["soap_carry_cough"] = %p_pragueb_3_2_cough_player;
    level._id_0C59["player_rig"]["toss_gun"] = %p_pragueb_3_5_toss_m203_player;
    level._id_0C59["player_rig"]["no_pressure"][0] = %p_pragueb_10_1_savingsoap_nopressure_player;
    level._id_0C59["player_rig"]["no_pressure_single"] = %p_pragueb_10_1_savingsoap_nopressure_player;
    level._id_0C59["player_rig"]["soap_death"] = %prague_escape_soap_death_player;
    level._id_0C59["player_rig"]["escape"] = %p_pragueb_11_1_escape_player;
    maps\_anim::_id_1264( "player_rig", "slowmo_intro", maps\prague_escape_medic::_id_7C03, "escape" );
    maps\_anim::_id_1267( "player_rig", "slowmo_gun", "stop_pistol_slowmo", "escape" );
    level._id_0C59["player_rig"]["price_punch"] = %p_pragueb_12_1_punch_player;
    maps\_anim::_id_1264( "player_rig", "punch_rumble", maps\prague_escape_to_cellar::_id_7CCC, "price_punch" );
    maps\_anim::_id_1264( "player_rig", "flip_rumble", maps\prague_escape_code::_id_7A54, "price_punch" );
    maps\_anim::_id_1264( "player_rig", "stairs_rumble_start", maps\prague_escape_to_cellar::_id_7CCD, "price_punch" );
    maps\_anim::_id_1267( "player_rig", "stairs_rumble_stop", "stop_stair_rumble", "price_punch" );
    maps\_anim::_id_1264( "player_rig", "floor_hit", maps\prague_escape_code::_id_7A54, "price_punch" );
    maps\_anim::_id_1267( "player_rig", "floor_hit", "give_punch_headlook", "price_punch" );
    level._id_0C59["player_rig"]["no_time"] = %p_pragueb_13_1_no_time_player;
    level._id_0C59["player_rig"]["bullet_strikes"] = %p_pragueb_13_3_bullet_strikes_player;
    maps\_anim::_id_1264( "player_rig", "headlook", maps\prague_escape_flashback_sniper::_id_7CAB, "bullet_strikes" );
    maps\_anim::_id_1264( "player_rig", "glass_shatter", maps\prague_escape_flashback_sniper::_id_7C86, "bullet_strikes" );
    maps\_anim::_id_1264( "player_rig", "rumble_lt", maps\prague_escape_code::_id_7A56, "bullet_strikes" );
    maps\_anim::_id_1264( "player_rig", "rumble_hv", maps\prague_escape_code::_id_7A54, "bullet_strikes" );
    maps\_anim::_id_1264( "player_rig", "hit_1", maps\prague_escape_flashback_sniper::_id_7CA9, "bullet_strikes" );
    maps\_anim::_id_1264( "player_rig", "hit_2", maps\prague_escape_flashback_sniper::_id_7CAA, "bullet_strikes" );
    maps\_anim::_id_1264( "player_rig", "start_rumble", maps\prague_escape_code::_id_7A57, "bullet_strikes" );
    maps\_anim::_id_1267( "player_rig", "hit_2", "stop_uaz_rumble", "bullet_strikes" );
    maps\_anim::_id_1267( "player_rig", "start_zakhaev", "spawn_onearm_zakhaev", "bullet_strikes" );
    maps\_anim::_id_1267( "player_rig", "poor_bastards", "spawn_escape_victims", "bullet_strikes" );
    level._id_0C59["player_rig"]["shock_and_awe"] = %p_pragueb_14_1_shockandawe_player_relative;
    maps\_anim::_id_1267( "player_rig", "helicopter_1", "spawn_helicopter_1", "shock_and_awe" );
    maps\_anim::_id_1267( "player_rig", "explosion", "nuke_explosion_start", "shock_and_awe" );
    level._id_0C59["player_rig"]["betray_me"] = %p_pragueb_15_1_betray_me_player;
    maps\_anim::_id_1264( "player_rig", "rumble_01", maps\prague_escape_code::_id_7A56, "betray_me" );
    maps\_anim::_id_1264( "player_rig", "rumble_02", maps\prague_escape_code::_id_7A56, "betray_me" );
    maps\_anim::_id_1264( "player_rig", "rumble_03", maps\prague_escape_code::_id_7A56, "betray_me" );
    maps\_anim::_id_1264( "player_rig", "rumble_04", maps\prague_escape_code::_id_7A56, "betray_me" );
    maps\_anim::_id_1264( "player_rig", "rumble_05", maps\prague_escape_code::_id_7A56, "betray_me" );
    maps\_anim::_id_1264( "player_rig", "rumble_06", maps\prague_escape_code::_id_7A56, "betray_me" );
    maps\_anim::_id_1264( "player_rig", "rumble_07", maps\prague_escape_code::_id_7A56, "betray_me" );
    maps\_anim::_id_1264( "player_rig", "rumble_08", maps\prague_escape_code::_id_7A56, "betray_me" );
    maps\_anim::_id_1264( "player_rig", "rumble_06", maps\prague_escape_flashback_airport::_id_7D13, "betray_me" );
    maps\_anim::_id_1264( "player_rig", "rumble_07", maps\prague_escape_flashback_airport::_id_7D13, "betray_me" );
    maps\_anim::_id_1267( "player_rig", "hit_ground", "start_gunshot_blackout", "betray_me" );
    level._id_0C59["player_rig"]["elevator_hand"] = %p_pragueb_15_4_elevator_crawl_in_hand_player;
    level._id_0C59["player_rig"]["elevator_idle"][0] = %p_pragueb_15_4_elevator_crawl_in_idle_player;
    level._id_0C59["player_rig"]["elevator_crawl_in"] = %p_pragueb_15_4_elevator_crawl_in_player;
    level._id_0C59["player_rig"]["elevator_crawl_out"] = %p_pragueb_15_4_elevator_crawl_out_player;
    level._id_0C59["player_rig"]["gun_crawl_00"] = %player_afchase_ending_gun_crawl_00;
    level._id_0C59["player_rig"]["gun_crawl_01"] = %player_afchase_ending_gun_crawl_01;
    level._id_0C59["player_rig"]["gun_crawl_02"] = %player_afchase_ending_gun_crawl_02;
    level._id_0C59["player_rig"]["gun_crawl_03"] = %player_afchase_ending_gun_crawl_03;
    level._id_0C59["player_rig"]["gun_crawl_04"] = %player_afchase_ending_gun_crawl_04;
    level._id_0C59["player_rig"]["gun_crawl_05"] = %player_afchase_ending_gun_crawl_05;
    level._id_0C59["player_rig"]["gun_crawl_06"] = %player_afchase_ending_gun_crawl_06;
    level._id_0C59["player_rig"]["gun_crawl_00_idle"][0] = %player_afchase_ending_gun_crawl_idle_00;
    level._id_0C59["player_rig"]["gun_crawl_01_idle"][0] = %player_afchase_ending_gun_crawl_idle_01;
    level._id_0C59["player_rig"]["gun_crawl_02_idle"][0] = %player_afchase_ending_gun_crawl_idle_02;
    level._id_0C59["player_rig"]["gun_crawl_03_idle"][0] = %player_afchase_ending_gun_crawl_idle_03;
    level._id_0C59["player_rig"]["gun_crawl_04_idle"][0] = %player_afchase_ending_gun_crawl_idle_04;
    level._id_0C59["player_rig"]["gun_crawl_05_idle"][0] = %player_afchase_ending_gun_crawl_idle_05;
    level._id_0C59["player_rig"]["gun_crawl_06_idle"][0] = %player_afchase_ending_gun_crawl_idle_06;
    level._id_0C59["player_rig"]["wakeup"] = %player_afchase_ending_wakeup_no_node;
    maps\_anim::_id_1267( "player_rig", "hit_button", "player_hits_button", "elevator_crawl_in" );
    maps\_anim::_id_1267( "player_rig", "player_fallback", "close_elevator_doors", "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "button_slam_rumble", maps\prague_escape_code::_id_7A54, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "button_slam_rumble", maps\prague_escape_code::_id_7A59, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "right_hand_blood", maps\prague_escape_code::_id_7A59, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "left_hand_blood", maps\prague_escape_code::_id_7A59, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "button_rumble", maps\prague_escape_code::_id_7A54, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "railing_grab", maps\prague_escape_code::_id_7A54, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "door_lean", maps\prague_escape_code::_id_7A56, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "player_fallout", maps\prague_escape_code::_id_7A59, "elevator_crawl_out" );
    maps\_anim::_id_1264( "player_rig", "pistol_grab", maps\prague_escape_code::_id_7A56, "elevator_crawl_out" );
    maps\_anim::_id_1264( "player_rig", "crawl_rumble_1", maps\prague_escape_code::_id_7A56, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "crawl_rumble_2", maps\prague_escape_code::_id_7A56, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "crawl_rumble_3", maps\prague_escape_code::_id_7A56, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "wall_grab_rumble_1", maps\prague_escape_code::_id_7A56, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "wall_grab_rumble_2", maps\prague_escape_code::_id_7A56, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "blink", maps\prague_escape_flashback_airport::_id_7D18, "elevator_crawl_in" );
    maps\_anim::_id_1264( "player_rig", "player_fallout", maps\prague_escape_flashback_airport::_id_7D17, "elevator_crawl_out" );
    level._id_0C59["player_rig"]["player_force_blackout"] = %p_pragueb_15_6_dying_inplace_player;
    maps\_anim::_id_1264( "player_rig", "rumble_02", maps\prague_escape_code::_id_7A56, "player_force_blackout" );
    maps\_anim::_id_1264( "player_rig", "rumble_03", maps\prague_escape_code::_id_7A56, "player_force_blackout" );
    level._id_0C59["player_rig"]["left_detector_passout"] = %p_pragueb_15_6_dying_detector_l_player;
    maps\_anim::_id_1264( "player_rig", "blood_smear_left", maps\prague_escape_code::_id_7A5A, "left_detector_passout" );
    maps\_anim::_id_1267( "player_rig", "blood_smear_left", "play_left_hand_blood", "left_detector_passout" );
    maps\_anim::_id_1268( "player_rig", "blood_smear_left_stop", "play_left_hand_blood", "left_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "rumble_01", maps\prague_escape_code::_id_7A56, "left_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "rumble_02", maps\prague_escape_code::_id_7A56, "left_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "rumble_03", maps\prague_escape_code::_id_7A56, "left_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "rumble_04", maps\prague_escape_code::_id_7A56, "left_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "rumble_05", maps\prague_escape_code::_id_7A52, "left_detector_passout" );
    level._id_0C59["player_rig"]["right_detector_passout"] = %p_pragueb_15_6_dying_detector_r_player;
    maps\_anim::_id_1264( "player_rig", "drop_gun", maps\prague_escape_code::_id_7A56, "right_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "blood_smear_right", maps\prague_escape_code::_id_7A5B, "right_detector_passout" );
    maps\_anim::_id_1268( "player_rig", "blood_smear_right_stop", "play_right_hand_blood", "right_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "rumble_01", maps\prague_escape_code::_id_7A56, "right_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "rumble_02", maps\prague_escape_code::_id_7A56, "right_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "rumble_03", maps\prague_escape_code::_id_7A56, "right_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "rumble_04", maps\prague_escape_code::_id_7A56, "right_detector_passout" );
    maps\_anim::_id_1264( "player_rig", "rumble_05", maps\prague_escape_code::_id_7A52, "right_detector_passout" );
    level._id_0C59["player_rig"]["emt_assist"] = %p_pragueb_16_1_emt_assist_player;
    level._id_0C59["player_rig"]["gun_to_head"] = %p_pragueb_16_1_gun_to_head_player;
    maps\_anim::_id_1264( "player_rig", "rumble_01", maps\prague_escape_code::_id_7A56, "gun_to_head" );
    maps\_anim::_id_1264( "player_rig", "rumble_02", maps\prague_escape_code::_id_7A56, "gun_to_head" );
    maps\_anim::_id_1264( "player_rig", "wall_rumble", maps\prague_escape_code::_id_7A54, "gun_to_head" );
}
#using_animtree("vehicles");

_id_47DE()
{
    level._id_1245["convoy_vehicle"] = #animtree;
    level._id_0C59["soap_carry_suv"]["suv_flip"] = %v_pragueb_3_1_suburban_flip_suburban;
    level._id_1245["player_uaz"] = #animtree;
    level._id_1F90["player_uaz"] = "vehicle_uaz_covered_destructible";
    level._id_0C59["player_uaz"]["no_time"] = %v_pragueb_13_1_no_time_uaz;
    level._id_0C59["player_uaz"]["bullet_strikes"] = %v_pragueb_13_3_bullet_strikes_uaz;
}
#using_animtree("script_model");

_id_4CAC()
{
    level._id_1245["script_model"] = #animtree;
    level._id_0C59["hotel_door_1"]["close_door"] = %o_pragueb_1_2_door_guards_close_door_01;
    level._id_0C59["hotel_door_2"]["close_door"] = %o_pragueb_1_2_door_guards_close_door_02;
    level._id_0C59["hotel_door_1"]["enter_door"] = %o_pragueb_1_2_door_guards_enter_door_01;
    level._id_0C59["hotel_door_2"]["enter_door"] = %o_pragueb_1_2_door_guards_enter_door_02;
    level._id_0C59["rpg_wall"]["rpg_wall_explode"] = %fxanim_prague2_rpg_wall_anim;
    level._id_0C59["exit_wall"]["exit_wall_explode"] = %fxanim_prague2_exit_wall_anim;
    level._id_0C59["curtain"]["window_breach_curtain_fall"] = %fxanim_prague2_curtain_fall_anim;
    level._id_0C59["curtain"]["curtain_idle"][0] = %fxanim_prague2_curtain_win_long_anim;
    level._id_0C59["hotel_columns"]["hotel_explode"] = %fxanim_prague2_hotel_anim;
    level._id_0C59["bell_tower"]["bell_tower_explode"] = %fxanim_prague2_bell_tower_anim;
    level._id_0C59["scaffold"]["scaffold_break"] = %fxanim_prague2_bell_tower_scaf_anim;
    maps\_anim::_id_1264( "scaffold", "bell_impact_ground", maps\prague_escape_scaffold::_id_7B51, "scaffold_break" );
    level._id_1245["debris01"] = #animtree;
    level._id_1F90["debris01"] = "tag_origin_animate";
    level._id_0C59["debris01"]["scaffolding_fall"] = %o_pragueb_2_2_scaffolding_fall_debris1;
    level._id_0C59["debris01"]["scaffold_soap_injured"] = %o_pragueb_2_3_soap_injured_debris01;
    maps\_anim::_id_1264( "debris01", "debris_lift", maps\prague_escape_scaffold::_id_7B57, "scaffold_soap_injured" );
    maps\_anim::_id_1264( "debris01", "debris_fall", maps\prague_escape_scaffold::_id_7B58, "scaffold_soap_injured" );
    level._id_1245["debris02"] = #animtree;
    level._id_1F90["debris02"] = "tag_origin_animate";
    level._id_0C59["debris02"]["scaffolding_fall"] = %o_pragueb_2_2_scaffolding_fall_debris2;
    level._id_0C59["debris02"]["scaffold_soap_injured"] = %o_pragueb_2_3_soap_injured_debris02;
    level._id_1245["debris03"] = #animtree;
    level._id_1F90["debris03"] = "tag_origin_animate";
    level._id_0C59["debris03"]["scaffolding_fall"] = %o_pragueb_2_2_scaffolding_fall_debris3;
    level._id_0C59["debris03"]["scaffold_soap_injured"] = %o_pragueb_2_3_soap_injured_debris03;
    level._id_1245["debris04"] = #animtree;
    level._id_1F90["debris04"] = "tag_origin_animate";
    level._id_0C59["debris04"]["scaffolding_fall"] = %o_pragueb_2_2_scaffolding_fall_debris4;
    level._id_0C59["debris04"]["scaffold_soap_injured"] = %o_pragueb_2_3_soap_injured_debris04;
    level._id_1245["debris05"] = #animtree;
    level._id_1F90["debris05"] = "tag_origin_animate";
    level._id_0C59["debris05"]["scaffolding_fall"] = %o_pragueb_2_2_scaffolding_fall_debris5;
    level._id_0C59["debris05"]["scaffold_soap_injured"] = %o_pragueb_2_3_soap_injured_debris05;
    level._id_1245["lamp"] = #animtree;
    level._id_1F90["lamp"] = "tag_origin_animate";
    level._id_0C59["lamp"]["take_cover"] = %o_pragueb_6_1_throughbuilding_lamp;
    level._id_0C59["lamp"]["idle_cover"][0] = %o_pragueb_6_1_throughbuilding_lamp_loop;
    level._id_1245["table"] = #animtree;
    level._id_1F90["table"] = "tag_origin_animate";
    level._id_0C59["table"]["take_cover"] = %o_pragueb_6_1_throughbuilding_table;
    level._id_0C59["table"]["idle_cover"][0] = %o_pragueb_6_1_throughbuilding_table_loop;
    level._id_1245["box1"] = #animtree;
    level._id_1F90["box1"] = "tag_origin_animate";
    level._id_0C59["box1"]["reachroom"] = %o_pragueb_4_3_reachroom_box01;
    level._id_0C59["box1"]["idle_room"][0] = %o_pragueb_4_3_reachroom_idle_box01;
    level._id_1245["box2"] = #animtree;
    level._id_1F90["box2"] = "tag_origin_animate";
    level._id_0C59["box2"]["reachroom"] = %o_pragueb_4_3_reachroom_box02;
    level._id_0C59["box2"]["idle_room"][0] = %o_pragueb_4_3_reachroom_idle_box02;
    level._id_1245["box3"] = #animtree;
    level._id_1F90["box3"] = "tag_origin_animate";
    level._id_0C59["box3"]["reachroom"] = %o_pragueb_4_3_reachroom_box03;
    level._id_0C59["box3"]["idle_room"][0] = %o_pragueb_4_3_reachroom_idle_box03;
    level._id_1245["box4"] = #animtree;
    level._id_1F90["box4"] = "tag_origin_animate";
    level._id_0C59["box4"]["reachroom"] = %o_pragueb_4_3_reachroom_box04;
    level._id_0C59["box4"]["idle_room"][0] = %o_pragueb_4_3_reachroom_idle_box04;
    level._id_1245["box5"] = #animtree;
    level._id_1F90["box5"] = "tag_origin_animate";
    level._id_0C59["box5"]["reachroom"] = %o_pragueb_4_3_reachroom_box05;
    level._id_0C59["box5"]["idle_room"][0] = %o_pragueb_4_3_reachroom_idle_box05;
    level._id_1245["box6"] = #animtree;
    level._id_1F90["box6"] = "tag_origin_animate";
    level._id_0C59["box6"]["reachroom"] = %o_pragueb_4_3_reachroom_box06;
    level._id_0C59["box6"]["idle_room"][0] = %o_pragueb_4_3_reachroom_idle_box06;
    level._id_1245["resistance_door"] = #animtree;
    level._id_1F90["resistance_door"] = "tag_origin_animate";
    level._id_0C59["resistance_door"]["resistancearrive2"] = %o_pragueb_9_1_resistancecarry_door;
    level._id_0C59["resistance_door"]["resistancecarry_idle"][0] = %o_pragueb_9_1_resistancecarry_door_loop;
    level._id_1245["resistance_gate"] = #animtree;
    level._id_1F90["resistance_gate"] = "tag_origin_animate";
    level._id_0C59["resistance_gate"]["resistancearrive2"] = %o_pragueb_9_1_resistancecarry_gate;
    level._id_0C59["resistance_gate"]["resistancecarry_idle"][0] = %o_pragueb_9_1_resistancecarry_gate_loop;
    level._id_1245["script_model"] = #animtree;
    level._id_0C59["btr_fence"]["btr_entrance"] = %fxanim_prague2_basketball_court_anim;
    level._id_1245["script_model"] = #animtree;
    level._id_0C59["lion"]["lion_statue_destroy"] = %fxanim_prague2_lion_statue_anim;
    level._id_1245["beer1"] = #animtree;
    level._id_1F90["beer1"] = "tag_origin_animate";
    level._id_0C59["beer1"]["clear_table"] = %o_pragueb_10_1_clear_table_beer1;
    level._id_1245["beer2"] = #animtree;
    level._id_1F90["beer2"] = "tag_origin_animate";
    level._id_0C59["beer2"]["clear_table"] = %o_pragueb_10_1_clear_table_beer2;
    level._id_1245["beer3"] = #animtree;
    level._id_1F90["beer3"] = "tag_origin_animate";
    level._id_0C59["beer3"]["clear_table"] = %o_pragueb_10_1_clear_table_beer3;
    level._id_1245["beer4"] = #animtree;
    level._id_1F90["beer4"] = "tag_origin_animate";
    level._id_0C59["beer4"]["clear_table"] = %o_pragueb_10_1_clear_table_beer4;
    level._id_1245["cup1"] = #animtree;
    level._id_1F90["cup1"] = "tag_origin_animate";
    level._id_0C59["cup1"]["clear_table"] = %o_pragueb_10_1_clear_table_cup1;
    level._id_1245["cup2"] = #animtree;
    level._id_1F90["cup2"] = "tag_origin_animate";
    level._id_0C59["cup2"]["clear_table"] = %o_pragueb_10_1_clear_table_cup2;
    level._id_1245["cup3"] = #animtree;
    level._id_1F90["cup3"] = "tag_origin_animate";
    level._id_0C59["cup3"]["clear_table"] = %o_pragueb_10_1_clear_table_cup3;
    level._id_1245["wine"] = #animtree;
    level._id_1F90["wine"] = "tag_origin_animate";
    level._id_0C59["wine"]["clear_table"] = %o_pragueb_10_1_clear_table_wine;
    level._id_1245["price_journal"] = #animtree;
    level._id_1F90["price_journal"] = "tag_origin_animate";
    level._id_0C59["price_journal"]["escape"] = %o_pragueb_11_1_escape_journal;
    level._id_1245["soap_table"] = #animtree;
    level._id_1F90["soap_table"] = "tag_origin_animate";
    level._id_0C59["soap_table"]["escape"][0] = %o_pragueb_11_1_escape_table;
    level._id_1245["punch_door"] = #animtree;
    level._id_1F90["punch_door"] = "tag_origin_animate";
    level._id_0C59["punch_door"]["price_punch"] = %o_pragueb_12_1_punch_door;
    level._id_0C59["blind_01"]["cellar_blinds"] = %fxanim_prague2_blind01_anim;
    maps\_anim::_id_1264( "blind_01", "blind1_chunks", ::_id_7D56, "cellar_blinds" );
    level._id_0C59["blind_02"]["cellar_blinds"] = %fxanim_prague2_blind02_anim;
    maps\_anim::_id_1264( "blind_02", "blind2_chunks", ::_id_7D56, "cellar_blinds" );
    level._id_0C59["blind_03"]["cellar_blinds"] = %fxanim_prague2_blind03_anim;
    maps\_anim::_id_1264( "blind_03", "blind3_chunks", ::_id_7D56, "cellar_blinds" );
    level._id_0C59["blind_01"]["cellar_blinds_idle"][0] = %fxanim_prague2_blind01_idle_anim;
    maps\_anim::_id_1264( "blind_01", "blind1_chunks", ::_id_7D56, "cellar_blinds_idle" );
    maps\_anim::_id_1264( "blind_01", "blind1_impact", ::_id_7D57, "cellar_blinds_idle" );
    level._id_0C59["blind_02"]["cellar_blinds_idle"][0] = %fxanim_prague2_blind02_idle_anim;
    maps\_anim::_id_1264( "blind_02", "blind2_chunks", ::_id_7D56, "cellar_blinds_idle" );
    maps\_anim::_id_1264( "blind_02", "blind2_impact", ::_id_7D57, "cellar_blinds_idle" );
    level._id_0C59["blind_03"]["cellar_blinds_idle"][0] = %fxanim_prague2_blind03_idle_anim;
    maps\_anim::_id_1264( "blind_03", "blind3_chunks", ::_id_7D56, "cellar_blinds_idle" );
    maps\_anim::_id_1264( "blind_03", "blind3_impact", ::_id_7D57, "cellar_blinds_idle" );
    level._id_1245["zak_left_arm"] = #animtree;
    level._id_1F90["zak_left_arm"] = "zakhaev_left_arm";
    level._id_0C59["zak_left_arm"]["zak_pain"] = %sniper_escape_meeting_zakhaev_hit_arm_front;
    level._id_1245["flag"] = #animtree;
    level._id_0C59["flag"]["up"] = %sniper_escape_flag_wave_up;
    level._id_0C59["flag"]["down"] = %sniper_escape_flag_wave_down;
    level._id_1F90["flag"] = "prop_car_flag";
    level._id_1245["briefcase"] = #animtree;
    level._id_0C59["briefcase"]["exchange_short"] = %o_pragueb_13_1_meeting_briefcase;
    level._id_1F90["briefcase"] = "com_gold_brick_case";
    level._id_1245["cell_phone"] = #animtree;
    level._id_0C59["cell_phone"]["shock_and_awe"] = %o_pragueb_14_1_shockandawe_phone;
    level._id_1F90["cell_phone"] = "hjk_cell_phone_on";
    level._id_1245["oxygen_mask"] = #animtree;
    level._id_0C59["oxygen_mask"]["emt_assist"] = %o_pragueb_16_1_emt_assist_mask;
    level._id_1F90["oxygen_mask"] = "prague_oxygen_mask_animated";
    level._id_0C59["falling_tiles"]["airport_tiles"] = %fxanim_prague2_airport_tiles_anim;
    level._id_1245["slow_grass"] = #animtree;
    level._id_0C59["slow_grass"]["slow_anim_grass"][0] = %fxanim_prague2_grass_lrg_slow_anim;
    level._id_1245["fast_grass"] = #animtree;
    level._id_0C59["fast_grass"]["fast_anim_grass"][0] = %fxanim_prague2_grass_lrg_fast_anim;
    level._id_1245["fast_grass"] = #animtree;
    level._id_0C59["fast_grass"]["fast_anim_grass"][0] = %fxanim_prague2_grass_lrg_fast_anim;
    level._id_1245["tall_palm_tree"] = #animtree;
    level._id_0C59["tall_palm_tree"]["tall_palm_tree_sway"] = %fxanim_gp_tree_palm_tall_nuke_anim;
    level._id_1245["bushy_palm_tree"] = #animtree;
    level._id_0C59["bushy_palm_tree"]["bushy_palm_tree_sway"] = %fxanim_gp_tree_palm_bushy_nuke_anim;
    level._id_0C59["swinging_light"]["airport_light"] = %fxanim_prague2_airport_light_anim;
}

_id_7D56( var_0 )
{
    if ( var_0._id_1032 == "blind_01" )
    {
        common_scripts\utility::exploder( 1101 );
        common_scripts\utility::exploder( 1121 );
    }
    else if ( var_0._id_1032 == "blind_02" )
    {
        common_scripts\utility::exploder( 1102 );
        common_scripts\utility::exploder( 1122 );
    }
    else
    {
        common_scripts\utility::exploder( 1103 );
        common_scripts\utility::exploder( 1123 );
    }
}

_id_7D57( var_0 )
{
    if ( var_0._id_1032 == "blind_01" )
    {
        common_scripts\utility::exploder( 1111 );
        common_scripts\utility::exploder( 1121 );
    }
    else if ( var_0._id_1032 == "blind_02" )
    {
        common_scripts\utility::exploder( 1112 );
        common_scripts\utility::exploder( 1122 );
    }
    else
    {
        common_scripts\utility::exploder( 1113 );
        common_scripts\utility::exploder( 1123 );
    }
}
#using_animtree("animated_props");

_id_6838()
{
    level._id_1245["prague_bullet_animated"] = #animtree;
    level._id_1F90["prague_bullet_animated"] = "prague_bullet_animated";
    level._id_0C59["prague_bullet_animated"]["prague_bullet"] = %o_pragueb_1_1_bullet;
    level._id_1245["prague_rsass_clip_animated"] = #animtree;
    level._id_1F90["prague_rsass_clip_animated"] = "prague_rsass_clip_animated";
    level._id_0C59["prague_rsass_clip_animated"]["prague_mag"] = %o_pragueb_1_1_mag;
    level._id_1245["prague_rappel_rope"] = #animtree;
    level._id_1F90["prague_rappel_rope"] = "prague_rope_rappel_building_animated";
    level._id_0C59["prague_rappel_rope"]["rappel_hook_up"] = %o_pragueb_1_3_hook_up_rope;
    level._id_0C59["prague_rappel_rope"]["rappel_mid_idle"][0] = %o_pragueb_1_3_idle_rope;
    level._id_0C59["prague_rappel_rope"]["price_window_breach"] = %o_pragueb_1_4_window_breach_rope;
}

_id_7D58()
{
    level.scr_sound["soap"]["presc_mct_almosttime"] = "presc_mct_almosttime";
    level.scr_sound["soap"]["presc_mct_makarovconvoy"] = "presc_mct_makarovconvoy";
    level.scr_sound["soap"]["presc_mct_getinposition"] = "presc_mct_getinposition";
    level.scr_sound["price"]["presc_mct_almosttime"] = "presc_mct_almosttime";
    level.scr_sound["soap"]["presc_mct_ready"] = "presc_mct_ready";
    level.scr_sound["price"]["presc_pri_eyesonconvoy"] = "presc_pri_eyesonconvoy";
    level.scr_sound["soap"]["presc_mct_iseeit"] = "presc_mct_iseeit";
    level.scr_sound["price"]["presc_pri_alrightkamarov"] = "presc_pri_alrightkamarov";
    level.scr_sound["price"]["presc_pri_doyouread"] = "presc_pri_doyouread";
    level.scr_sound["soap"]["presc_mct_switchiton"] = "presc_mct_switchiton";
    level.scr_sound["price"]["presc_pri_doesntmatter"] = "presc_pri_doesntmatter";
    level.scr_sound["price"]["presc_pri_inposition"] = "presc_pri_inposition";
    level.scr_sound["price"]["presc_pri_sittight"] = "presc_pri_sittight";
    level.scr_sound["soap"]["presc_mct_stoppinghotel"] = "presc_mct_stoppinghotel";
    level.scr_sound["price"]["presc_pri_doyouseetarget"] = "presc_pri_doyouseetarget";
    level.scr_sound["soap"]["presc_mct_makarovcar"] = "presc_mct_makarovcar";
    level.scr_sound["soap"]["presc_mct_rightatusprice"] = "presc_mct_rightatusprice";
    level.scr_sound["price"]["presc_pri_dontgetskiddish"] = "presc_pri_dontgetskiddish";
    level.scr_sound["soap"]["presc_mct_frontdoorhotelnow"] = "presc_mct_frontdoorhotelnow";
    level.scr_sound["soap"]["presc_mct_wegotyou"] = "presc_mct_wegotyou";
    level.scr_sound["price"]["presc_pri_makarovsmeeting"] = "presc_pri_makarovsmeeting";
    level.scr_sound["price"]["presc_pri_preparingtobreach"] = "presc_pri_preparingtobreach";
    level.scr_sound["soap"]["presc_mct_sentrysbalcony"] = "presc_mct_sentrysbalcony";
    level.scr_sound["soap"]["presc_mct_fourtargets"] = "presc_mct_fourtargets";
    level._id_11BB["presc_mct_fourtargets"] = "presc_mct_fourtargets";
    level.scr_sound["soap"]["presc_mct_takethemout"] = "presc_mct_takethemout";
    level._id_11BB["presc_mct_takethemout"] = "presc_mct_takethemout";
    level.scr_sound["price"]["presc_pri_atleastweknow"] = "presc_pri_atleastweknow";
    level.scr_sound["price"]["presc_pri_breachingnow"] = "presc_pri_breachingnow";
    level.scr_sound["soap"]["presc_mct_zoominyuri"] = "presc_mct_zoominyuri";
    level.scr_sound["price"]["presc_pri_allclear"] = "presc_pri_allclear";
    level.scr_sound["kamarov"]["presc_mct_makarov"] = "presc_mct_makarov";
    level.scr_sound["price"]["presc_pri_nosign"] = "presc_pri_nosign";
    level.scr_sound["kamarov"]["presc_mct_price"] = "presc_mct_price";
    level.scr_sound["price"]["presc_pri_damnit"] = "presc_pri_damnit";
    level.scr_sound["makarov"]["presc_mkv_welcometohell"] = "presc_mkv_welcometohell";
    level.scr_sound["price"]["presc_pri_itsasetup"] = "presc_pri_itsasetup";
    level.scr_sound["soap"]["presc_mct_getouttathere"] = "presc_mct_getouttathere";
    level.scr_sound["price"]["presc_mkv_yurimyfriend"] = "presc_mkv_yurimyfriend";
    level.scr_sound["soap"]["presc_mct_hellshetalkinabout"] = "presc_mct_hellshetalkinabout";
    level.scr_sound["soap"]["presc_mct_useyourscope"] = "presc_mct_useyourscope";
    level.scr_sound["soap"]["presc_mct_keepwatch"] = "presc_mct_keepwatch";
    level.scr_sound["soap"]["presc_mct_ok"] = "presc_mct_ok";
    level.scr_sound["soap"]["presc_mct_iseeit"] = "presc_mct_iseeit";
    level.scr_sound["soap"]["presc_mct_escortonfoot"] = "presc_mct_escortonfoot";
    level.scr_sound["soap"]["presc_mct_upalittle"] = "presc_mct_upalittle";
    level.scr_sound["soap"]["presc_mct_downabit"] = "presc_mct_downabit";
    level.scr_sound["soap"]["presc_mct_pullitmore"] = "presc_mct_pullitmore";
    level.scr_sound["soap"]["presc_mct_totheleft"] = "presc_mct_totheleft";
    level.scr_sound["soap"]["presc_mct_upandleft"] = "presc_mct_upandleft";
    level.scr_sound["soap"]["presc_mct_upandright"] = "presc_mct_upandright";
    level.scr_sound["soap"]["presc_mct_lowerleft"] = "presc_mct_lowerleft";
    level.scr_sound["soap"]["presc_mct_downandright"] = "presc_mct_downandright";
    level.scr_sound["soap"]["presc_mct_eyesonconvoy"] = "presc_mct_eyesonconvoy";
    level.scr_sound["soap"]["presc_mct_outofyoursights"] = "presc_mct_outofyoursights";
    level.scr_sound["soap"]["presc_mct_focus"] = "presc_mct_focus";
    level.scr_sound["soap"]["presc_pri_doyouseemak"] = "presc_pri_doyouseemak";
    level.scr_sound["soap"]["presc_pri_confirmtarget"] = "presc_pri_confirmtarget";
    level.scr_sound["price"]["presc_pri_doyouseetarget"] = "presc_pri_doyouseetarget";
    level.scr_sound["soap"]["presc_mct_looksedgy"] = "presc_mct_looksedgy";
    level.scr_sound["soap"]["presc_mct_findprice"] = "presc_mct_findprice";
    level.scr_sound["soap"]["presc_mct_ontopofhotel"] = "presc_mct_ontopofhotel";
    level.scr_sound["soap"]["presc_pri_whatstaking"] = "presc_pri_whatstaking";
    level.scr_sound["price"]["presc_mct_sentrysbalcony"] = "presc_mct_sentrysbalcony";
    level.scr_sound["soap"]["presc_mct_hesdown"] = "presc_mct_hesdown";
    level.scr_sound["soap"]["presc_mct_thatsakill"] = "presc_mct_thatsakill";
    level.scr_sound["soap"]["presc_mct_thatsamiss"] = "presc_mct_thatsamiss";
    level.scr_sound["soap"]["presc_mct_shite"] = "presc_mct_shite";
    level.scr_sound["price"]["presc_pri_soap"] = "presc_pri_soap";
    level.scr_sound["price"]["presc_pri_igotyouson"] = "presc_pri_igotyouson";
    level.scr_sound["price"]["presc_pri_yuri"] = "presc_pri_yuri";
    level.scr_sound["price"]["presc_pri_grabsoap"] = "presc_pri_grabsoap";
    level.scr_sound["price"]["presc_pri_keepmoving"] = "presc_pri_keepmoving";
    level.scr_sound["soap"]["presc_mct_coughing"] = "presc_mct_coughing";
    level.scr_sound["price"]["presc_pri_clearthestore"] = "presc_pri_clearthestore";
    level.scr_sound["price"]["presc_pri_cmonnow"] = "presc_pri_cmonnow";
    level.scr_sound["price"]["presc_pri_wehavetogetoff"] = "presc_pri_wehavetogetoff";
    level.scr_sound["price"]["presc_pri_thisway"] = "presc_pri_thisway";
    level.scr_sound["soap"]["presc_mct_putmedown"] = "presc_mct_putmedown";
    level.scr_sound["soap"]["presc_mct_givemearifle"] = "presc_mct_givemearifle";
    level.scr_sound["price"]["presc_pri_dontyoudare"] = "presc_pri_dontyoudare";
    level.scr_sound["price"]["presc_pri_cmonsoap"] = "presc_pri_cmonsoap";
    level.scr_sound["soap"]["presc_mct_makarovsaid"] = "presc_mct_makarovsaid";
    level.scr_sound["soap"]["presc_mct_fallpains"] = "presc_mct_fallpains";
    level.scr_sound["price"]["presc_pri_chopperscircling"] = "presc_pri_chopperscircling";
    level.scr_sound["price"]["presc_pri_getoffroad"] = "presc_pri_getoffroad";
    level.scr_sound["price"]["presc_pri_yurimove"] = "presc_pri_yurimove";
    level.scr_sound["price"]["presc_pri_letsgoletsgo"] = "presc_pri_letsgoletsgo";
    level.scr_sound["price"]["presc_pri_pickupthepace"] = "presc_pri_pickupthepace";
    level.scr_sound["price"]["presc_pri_yurimoveyour"] = "presc_pri_yurimoveyour";
    level.scr_sound["soap"]["presc_mct_needto"] = "presc_mct_needto";
    level.scr_sound["price"]["presc_pri_pickhimup"] = "presc_pri_pickhimup";
    level.scr_sound["price"]["presc_pri_cmonson"] = "presc_pri_cmonson";
    level.scr_sound["price"]["presc_pri_takepoint"] = "presc_pri_takepoint";
    level.scr_sound["price"]["presc_pri_theyrehere"] = "presc_pri_theyrehere";
    level.scr_sound["price"]["presc_pri_niceone"] = "presc_pri_niceone";
    level.scr_sound["soap"]["presc_mct_teachyou"] = "presc_mct_teachyou";
    level.scr_sound["price"]["presc_pri_getbehindstatue"] = "presc_pri_getbehindstatue";
    level.scr_sound["price"]["presc_pri_stayonemyuri"] = "presc_pri_stayonemyuri";
    level.scr_sound["soap"]["presc_pri_ontheroof"] = "presc_pri_ontheroof";
    level.scr_sound["price"]["presc_pri_reinforcementsright"] = "presc_pri_reinforcementsright";
    level.scr_sound["soap"]["presc_mct_damnright"] = "presc_mct_damnright";
    level.scr_sound["price"]["presc_pri_findsomewhere"] = "presc_pri_findsomewhere";
    level.scr_sound["price"]["presc_pri_cmonyuri"] = "presc_pri_cmonyuri";
    level.scr_sound["price"]["presc_pri_cantwait"] = "presc_pri_cantwait";
    level.scr_sound["price"]["presc_pri_keepup"] = "presc_pri_keepup";
    level.scr_sound["price"]["presc_pri_keepmoving3"] = "presc_pri_keepmoving3";
    level.scr_sound["price"]["presc_pri_dontslowdown"] = "presc_pri_dontslowdown";
    level.scr_sound["price"]["presc_pri_alrightson"] = "presc_pri_alrightson";
    level.scr_sound["soap"]["presc_pri_enemyvehicleahead"] = "presc_pri_enemyvehicleahead";
    level.scr_sound["soap"]["presc_mct_justleaveme"] = "presc_mct_justleaveme";
    level.scr_sound["price"]["presc_pri_gettingyouout"] = "presc_pri_gettingyouout";
    level.scr_sound["price"]["presc_pri_therestoomany"] = "presc_pri_therestoomany";
    level.scr_sound["price"]["presc_pri_thisway2"] = "presc_pri_thisway2";
    level.scr_sound["price"]["presc_pri_moreontheway"] = "presc_pri_moreontheway";
    level.scr_sound["price"]["presc_pri_headforthat"] = "presc_pri_headforthat";
    level.scr_sound["price"]["presc_pri_behindus"] = "presc_pri_behindus";
    level.scr_sound["price"]["presc_pri_coveroursix"] = "presc_pri_coveroursix";
    level.scr_sound["price"]["presc_pri_keeponem2"] = "presc_pri_keeponem2";
    level.scr_sound["price"]["presc_pri_holdemback"] = "presc_pri_holdemback";
    level.scr_sound["price"]["presc_pri_uazreinforce"] = "presc_pri_uazreinforce";
    level.scr_sound["price"]["presc_pri_dontletthem"] = "presc_pri_dontletthem";
    level.scr_sound["price"]["presc_pri_morereinforcements"] = "presc_pri_morereinforcements";
    level.scr_sound["price"]["presc_pri_tryingtorush"] = "presc_pri_tryingtorush";
    level.scr_sound["price"]["presc_pri_illcoverleft"] = "presc_pri_illcoverleft";
    level.scr_sound["price"]["presc_pri_rightflank"] = "presc_pri_rightflank";
    level.scr_sound["price"]["presc_pri_coverleft"] = "presc_pri_coverleft";
    level.scr_sound["price"]["presc_pri_leftflank"] = "presc_pri_leftflank";
    level.scr_sound["price"]["presc_pri_damnit"] = "presc_pri_damnit";
    level.scr_sound["price"]["presc_pri_allaroundus"] = "presc_pri_allaroundus";
    level.scr_sound["price"]["presc_pri_yurigetbackhere"] = "presc_pri_yurigetbackhere";
    level.scr_sound["price"]["presc_pri_whereareyougoing"] = "presc_pri_whereareyougoing";
    level.scr_sound["soap"]["presc_mct_bringingbtr"] = "presc_mct_bringingbtr";
    level.scr_sound["soap"]["presc_mct_damnit"] = "presc_mct_damnit";
    level.scr_sound["soap"]["presc_mct_leaveme"] = "presc_mct_leaveme";
    level.scr_sound["price"]["presc_pri_notanoption"] = "presc_pri_notanoption";
    level.scr_sound["price"]["presc_pri_holdemback"] = "presc_pri_holdemback";
    level.scr_sound["price"]["presc_pri_movesoap"] = "presc_pri_movesoap";
    level.scr_sound["price"]["presc_pri_yurigetoverhere2"] = "presc_pri_yurigetoverhere2";
    level.scr_sound["price"]["presc_pri_itstheresistance2"] = "presc_pri_itstheresistance2";
    level.scr_sound["price"]["presc_pri_helphim"] = "presc_pri_helphim";
    level.scr_sound["price"]["presc_pri_wereleaving"] = "presc_pri_wereleaving";
    level.scr_sound["price"]["presc_pri_gethimontable"] = "presc_pri_gethimontable";
    level.scr_sound["price"]["presc_pri_soapsoap"] = "presc_pri_soapsoap";
    level.scr_sound["price"]["presc_pri_havetostabalize"] = "presc_pri_havetostabalize";
    level.scr_sound["price"]["presc_pri_givemeroom"] = "presc_pri_givemeroom";
    level.scr_sound["price"]["presc_pri_yurigetoverhere"] = "presc_pri_yurigetoverhere";
    level.scr_sound["price"]["presc_pri_putpressure"] = "presc_pri_putpressure";
    level.scr_sound["soap"]["presc_mct_needtoknow"] = "presc_mct_needtoknow";
    level.scr_sound["price"]["presc_pri_donttrytospeak"] = "presc_pri_donttrytospeak";
    level.scr_sound["price"]["presc_pri_tellmelater"] = "presc_pri_tellmelater";
    level.scr_sound["soap"]["presc_mct_knowsyuri"] = "presc_mct_knowsyuri";
    level.scr_sound["price"]["presc_pri_overherenow"] = "presc_pri_overherenow";
    level.scr_sound["price"]["presc_pri_needyourhelp"] = "presc_pri_needyourhelp";
    level.scr_sound["soap"]["presc_mct_youneedtoknow"] = "presc_mct_youneedtoknow";
    level.scr_sound["soap"]["presc_mct_price2"] = "presc_mct_price2";
    level.scr_sound["price"]["presc_pri_helpdamnit"] = "presc_pri_helpdamnit";
    level.scr_sound["price"]["presc_pri_waitingfor"] = "presc_pri_waitingfor";
    level.scr_sound["price"]["presc_pri_rusianbastard"] = "presc_pri_rusianbastard";
    level.scr_sound["price"]["presc_pri_soap2"] = "presc_pri_soap2";
    level.scr_sound["resistance_leader"]["presc_rl_price"] = "presc_rl_price";
    level.scr_sound["resistance_leader"]["presc_rl_havetogo"] = "presc_rl_havetogo";
    level.scr_sound["resistance_leader"]["presc_rl_thisway"] = "presc_rl_thisway";
    level.scr_sound["price"]["presc_pri_yuriopenit"] = "presc_pri_yuriopenit";
    level.scr_sound["resistance_leader"]["presc_rl_getout"] = "presc_rl_getout";
    level.scr_sound["resistance_leader"]["presc_rl_now"] = "presc_rl_havetogo";
    level.scr_sound["price"]["presc_pri_soaptrustedyou"] = "presc_pri_soaptrustedyou";
    level.scr_sound["price"]["presc_pri_thoughticouldtoo"] = "presc_pri_thoughticouldtoo";
    level.scr_sound["price"]["presc_pri_makarovknowyou"] = "presc_pri_makarovknowyou";
    level.scr_sound["makarov"]["presc_mkv_yuriwakeup"] = "presc_mkv_yuriwakeup";
    level.scr_sound["makarov"]["presc_mkv_wearelucky"] = "presc_mkv_wearelucky";
    level.scr_sound["makarov"]["presc_mkv_tensofmillions"] = "presc_mkv_tensofmillions";
    level.scr_sound["makarov"]["presc_mkv_roadtothefuture"] = "presc_mkv_roadtothefuture";
    level.scr_sound["zakhaev"]["presc_zkv_whatdoyou"] = "presc_zkv_whatdoyou";
    level.scr_sound["zakhaev"]["presc_zkv_hadadeal"] = "presc_zkv_hadadeal";
    level.scr_sound["zakhaev"]["presc_zkv_argueover"] = "presc_zkv_argueover";
    level.scr_sound["zakhaev"]["presc_zkv_knownbetter"] = "presc_zkv_knownbetter";
    level.scr_sound["makarov"]["presc_mkv_itsanattack"] = "presc_mkv_itsanattack";
    level.scr_sound["zakhaev"]["presc_rl_getusout"] = "presc_rl_getusout";
    level.scr_sound["makarov"]["presc_mkv_moneycan"] = "presc_mkv_moneycan";
    level.scr_sound["makarov"]["presc_mkv_telephone"] = "presc_mkv_telephone";
    level.scr_sound["makarov"]["presc_mkv_everythingready"] = "presc_mkv_everythingready";
    level.scr_sound["makarov"]["presc_mkv_doit"] = "presc_mkv_doit";
    level.scr_sound["makarov"]["presc_mkv_americanslearn"] = "presc_mkv_americanslearn";
    level.scr_sound["makarov"]["presc_mkv_onlybeginning"] = "presc_mkv_onlybeginning";
    level.scr_sound["makarov"]["presc_mkv_iknowwhat"] = "presc_mkv_iknowwhat";
    level.scr_sound["makarov"]["presc_mkv_myfriend"] = "presc_mkv_myfriend";
    level.scr_sound["makarov"]["presc_mkv_changeforever"] = "presc_mkv_changeforever";
    level.scr_sound["makarov"]["presc_mkv_nothingcanstop"] = "presc_mkv_nothingcanstop";
    level.scr_sound["makarov"]["presc_mkv_notevenyou"] = "presc_mkv_notevenyou";
    level.scr_sound["emt"]["presc_med_liveone"] = "presc_med_liveone";
    level.scr_sound["price"]["presc_pri_okyuri"] = "presc_pri_okyuri";
    level.scr_sound["price"]["presc_pri_boughtyourself"] = "presc_pri_boughtyourself";
    level.scr_sound["price"]["presc_pri_watchingyou"] = "presc_pri_watchingyou";
    level.scr_sound["rebel"]["presc_reb1_gettogether"] = "presc_reb1_gettogether";
    level.scr_sound["rebel"]["presc_reb1_myleg"] = "presc_reb1_myleg";
    level.scr_sound["rebel"]["presc_reb1_makarovcan"] = "presc_reb1_makarovcan";
    level.scr_sound["rebel"]["presc_reb1_mother"] = "presc_reb1_mother";
    level.scr_sound["rebel"]["presc_reb1_helpme"] = "presc_reb1_helpme";
    level.scr_sound["rebel"]["presc_reb1_forpresc"] = "presc_reb1_forpresc";
    level.scr_sound["rebel"]["presc_reb1_nevergiveup"] = "presc_reb1_nevergiveup";
    level.scr_sound["rebel"]["presc_reb1_quick"] = "presc_reb1_quick";
    level.scr_sound["rebel"]["presc_reb1_stopmakarov"] = "presc_reb1_stopmakarov";
    level.scr_sound["rebel"]["presc_reb1_whothe"] = "presc_reb1_whothe";
    level.scr_sound["rebel"]["presc_reb1_voicesdown"] = "presc_reb1_voicesdown";
    level.scr_sound["rebel"]["presc_reb1_doanything"] = "presc_reb1_doanything";
    level.scr_sound["rebel"]["presc_reb1_howold"] = "presc_reb1_howold";
    level.scr_sound["rebel"]["presc_reb1_drunk"] = "presc_reb1_drunk";
    level.scr_sound["rebel"]["presc_reb2_killallofthem"] = "presc_reb2_killallofthem";
    level.scr_sound["rebel"]["presc_reb2_wellfixyou"] = "presc_reb2_wellfixyou";
    level.scr_sound["rebel"]["presc_reb2_cantkillme"] = "presc_reb2_cantkillme";
    level.scr_sound["rebel"]["presc_reb2_treatwounded"] = "presc_reb2_treatwounded";
    level.scr_sound["rebel"]["presc_reb2_hopeless"] = "presc_reb2_hopeless";
    level.scr_sound["rebel"]["presc_reb2_destroy"] = "presc_reb2_destroy";
    level.scr_sound["rebel"]["presc_reb2_mustbehere"] = "presc_reb2_mustbehere";
    level.scr_sound["rebel"]["presc_reb2_ihope"] = "presc_reb2_ihope";
    level.scr_sound["rebel"]["presc_reb2_helpuswin"] = "presc_reb2_helpuswin";
    level.scr_sound["rebel"]["presc_reb2_theyjustwatched"] = "presc_reb2_theyjustwatched";
    level.scr_sound["rebel"]["presc_reb2_didyouknow"] = "presc_reb2_didyouknow";
    level.scr_sound["rebel"]["presc_reb2_four"] = "presc_reb2_four";
    level.scr_sound["rebel"]["presc_reb3_getanrpg"] = "presc_reb3_getanrpg";
    level.scr_sound["rebel"]["presc_reb3_givethemhell"] = "presc_reb3_givethemhell";
    level.scr_sound["rebel"]["presc_reb3_ineedamedic"] = "presc_reb3_ineedamedic";
    level.scr_sound["rebel"]["presc_reb3_cantfindson"] = "presc_reb3_cantfindson";
    level.scr_sound["rebel"]["presc_reb3_shutup"] = "presc_reb3_shutup";
    level.scr_sound["rebel"]["presc_reb3_forgreat"] = "presc_reb3_forgreat";
    level.scr_sound["rebel"]["presc_reb3_whoarethesemen"] = "presc_reb3_whoarethesemen";
    level.scr_sound["rebel"]["presc_reb3_quiet"] = "presc_reb3_quiet";
    level.scr_sound["rebel"]["presc_reb3_dontlooktough"] = "presc_reb3_dontlooktough";
    level.scr_sound["rebel"]["presc_reb3_nothing"] = "presc_reb3_nothing";
    level.scr_sound["rebel"]["presc_reb3_whatthe"] = "presc_reb3_whatthe";
    level.scr_sound["russian_chopper_pilot"]["presc_rcp_intruder"] = "presc_rcp_intruder";
    level.scr_sound["russian_chopper_pilot"]["presc_rcp_dropweapon"] = "presc_rcp_dropweapon";
    level.scr_sound["russian_chopper_pilot"]["presc_rcp_handsup"] = "presc_rcp_handsup";
}
