// IW5 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool

main()
{
    level._effect["ground_dust_paris_ac130"] = loadfx( "dust/ground_dust_paris_ac130" );
    level._effect["ambient_bombing"] = loadfx( "explosions/clusterbomb_ac130_paris" );
    level._effect["smoke_grenade"] = loadfx( "smoke/smoke_screen_ac_prs_bridge_a" );
    level._effect["eiffel_explosion"] = loadfx( "impacts/ac_prs_fx_eiffel_tower_debris_a" );
    level._effect["no_effect"] = loadfx( "misc/no_effect" );
    level._effect["slamzoom_clouds"] = loadfx( "weather/cloud_speed_player_ac130" );
    level._effect["ac130_105mm_IR_impact_paris"] = loadfx( "impacts/ac130_105mm_color_impact_paris" );
    level._effect["ac130_40mm_IR_impact_paris"] = loadfx( "impacts/ac130_40mm_color_impact_paris" );
    level._effect["FX_mi17_explosion"] = loadfx( "explosions/helicopter_explosion_mi17_woodland_ac130" );
    level._effect["FX_mi17_air_explosion"] = loadfx( "explosions/aerial_explosion_mi17_woodland" );
    level._effect["FX_mi17_air_explosion_LA"] = loadfx( "explosions/aerial_explosion_ac130" );
    level._effect["FX_apache_hydra_rocket_flash"] = loadfx( "muzzleflashes/ac130_hydra_rocket_flash_wv" );
    level._effect["FX_s300v_a"] = loadfx( "explosions/vehicle_explosion_sam" );
    level._effect["FX_s300v_a_missile_startup"] = loadfx( "muzzleflashes/missile_flash_wv_cheap" );
    level._effect["FX_s300v_a_missile_trail"] = loadfx( "smoke/ac130_smoke_geotrail_missile_large" );
    level._effect["FX_mig_missile_trail"] = loadfx( "smoke/ac130_smoke_geotrail_missile_large" );
    level._effect["FX_gaz_on_fire"] = loadfx( "fire/fire_ac130_linger_med" );
    level._effect["FX_gaz_hurt_explosion"] = loadfx( "explosions/small_vehicle_explosion_ac130" );
    level._effect["FX_gaz_death_explosion"] = loadfx( "explosions/vehicle_explosion_technical_ac130" );
    level._effect["FX_gaz_dust_slide"] = loadfx( "impacts/tankfall_dust_large" );
    level._effect["FX_bm21_on_fire"] = loadfx( "fire/fire_ac130_linger_med" );
    level._effect["FX_bm21_hurt_explosion"] = loadfx( "explosions/small_vehicle_explosion_ac130" );
    level._effect["FX_bm21_death_explosion"] = loadfx( "explosions/vehicle_explosion_bm21_ac130" );
    level._effect["FX_bm21_dust_slide"] = loadfx( "impacts/tankfall_dust_large" );
    level._effect["FX_hummer_mg_ricochet"] = loadfx( "impacts/ac130_25mm_IR_impact_paris" );
    level._effect["FX_hummer_dust_slide"] = loadfx( "impacts/tankfall_dust_large" );
    level._effect["FX_hind_air_explosion"] = loadfx( "explosions/aerial_explosion_hind_chernobyl" );
    level._effect["FX_c130_paratroop_aircaft"] = loadfx( "misc/c130_paratroop_aircraft" );
    level._effect["FX_b52_bomber_squadron_a"] = loadfx( "misc/b52_bomber_squadron_a" );
    level._effect["FX_osprey_air_explosion"] = loadfx( "explosions/helicopter_explosion_osprey_air" );
    level._effect["FX_osprey_engine_explosion"] = loadfx( "explosions/heli_engine_osprey_explosion" );
    level._effect["FX_osprey_engine_explosion_sm"] = loadfx( "explosions/heli_engine_osprey_explosion_small" );
    level._effect["FX_osprey_engine_fire"] = loadfx( "fire/heli_engine_fire" );
    level._effect["FX_osprey_engine_fire_small"] = loadfx( "fire/heli_engine_fire_small" );
    level._effect["FX_osprey_jet_engine_fire"] = loadfx( "fire/jet_engine_fire_osprey_crash" );
    level._effect["FX_osprey_engine_smoke"] = loadfx( "smoke/heli_engine_smoke" );
    level._effect["FX_osprey_ground_explosion"] = loadfx( "explosions/helicopter_explosion_osprey_ground" );
    level._effect["FX_osprey_dust"] = loadfx( "treadfx/heli_dust_large" );
    level._effect["FX_osprey_rpg_impact"] = loadfx( "misc/heli_rotor_impact_dirt" );
    level._effect["FX_osprey_crash_ground_engine"] = loadfx( "misc/crash_heli_dirt_kickup_high" );
    level._effect["FX_osprey_crash_ground"] = loadfx( "misc/crash_heli_dirt_kickup_high" );
    level._effect["FX_osprey_blade_1_hit"] = loadfx( "misc/crash_heli_dirt_kickup_rotor_small" );
    level._effect["FX_osprey_blade_2_hit"] = loadfx( "misc/crash_heli_dirt_kickup_rotor_small" );
    level._effect["FX_osprey_blade_3_hit"] = loadfx( "misc/crash_heli_dirt_kickup_rotor_small" );
    level._effect["FX_osprey_side_skid"] = loadfx( "misc/crash_heli_dirt_kickup_body_loop" );
    level._effect["FX_osprey_nose_skid"] = loadfx( "misc/crash_heli_dirt_kickup_nose_loop" );
    level._effect["FX_osprey_engine_skid"] = loadfx( "misc/crash_heli_dirt_kickup_engine_loop" );
    level._effect["FX_osprey_car_crash"] = loadfx( "misc/crash_heli_car_dirt_kickup" );
    level._effect["FX_osprey_car_crash_small"] = loadfx( "misc/crash_heli_car_dirt_kickup_small" );
    level._effect["FX_osprey_dirt_kickup_settle"] = loadfx( "misc/crash_heli_dirt_kickup_settle" );
    level._effect["FX_osprey_dirt_kickup_settle_small"] = loadfx( "misc/crash_heli_dirt_kickup_settle_small" );
    level._effect["crash_heli_dirt_kickup_settle_small"] = loadfx( "misc/crash_heli_dirt_kickup_settle_small" );
    level._effect["crash_heli_dustwave"] = loadfx( "misc/crash_heli_dustwave" );
    level._effect["FX_osprey_sparks_scrape_line_short"] = loadfx( "misc/crash_heli_sparks_scrape_line_short" );
    level._effect["FX_angel_flare_geotrail"] = loadfx( "smoke/angel_flare_geotrail_ac130" );
    level._effect["FX_angel_flare_explosion"] = loadfx( "explosions/aa_flak_single_close_paris_ac130" );
    level._effect["FX_c130_contrail"] = loadfx( "smoke/jet_contrail" );
    level._effect["FX_c130_water_crash"] = loadfx( "impacts/105mm_water_impact_fast" );
    level._effect["FX_jet_afterburner_ignite"] = loadfx( "fire/jet_afterburner_ignite" );
    level._effect["FX_jet_smoke_trail"] = loadfx( "smoke/smoke_trail_black_jet" );
    level._effect["FX_jet_smoke_trail_quick"] = loadfx( "smoke/smoke_trail_black_jet_quick" );
    level._effect["FX_jet_20mm_tracer"] = loadfx( "misc/f15_20mm_tracer" );
    level._effect["FX_jet_20mm_tracer_ac130"] = loadfx( "misc/f15_20mm_tracer_ac130" );
    level._effect["FX_jet_20mm_tracer_close_ac130"] = loadfx( "misc/f15_20mm_tracer_close_ac130" );
    level._effect["FX_mig29_air_explosion"] = loadfx( "explosions/aerial_explosion_mig29" );
    level._effect["FX_mig29_on_fire"] = loadfx( "fire/jet_on_fire" );
    level._effect["FX_m1a1_explosion"] = loadfx( "explosions/mortarexp_ac130_mud" );
    level._effect["FX_t72_explosion"] = loadfx( "explosions/mortarexp_ac130_concrete" );
    level._effect["FX_t72_shell_hitting_building"] = loadfx( "impacts/t72_125mm_building_impact" );
    level._effect["FX_t72_shell_hitting_road"] = loadfx( "explosions/mortarexp_ac130_concrete" );
    level._effect["FX_t72_death_explosion"] = loadfx( "explosions/vehicle_explosion_t72_ac130" );
    level._effect["FX_t72_death_debris"] = loadfx( "explosions/ac_prs_fx_flir_debris_explosion_a" );
    level._effect["FX_t72_damaged_smoke"] = loadfx( "smoke/damaged_vehicle_smoke_ac130" );
    level._effect["shell"] = loadfx( "shellejects/20mm_cargoship" );
    level._effect["huge_explosion2"] = loadfx( "explosions/fuel_storage_no_plume" );
    level._effect["courtyard_fire"] = loadfx( "fire/window_fire_large_short_smoke_ac130_cheap" );
    level._effect["courtyard_fire_cheap"] = loadfx( "fire/window_fire_large_short_smoke_ac130_cheap" );
    level._effect["courtyard_fire_cheap_nofire"] = loadfx( "fire/window_fire_large_short_smoke_ac130_cheap_nofire" );
    level._effect["turret_smoke"] = loadfx( "fire/firelp_small_cheap_mp" );
    level._effect["intro_building_explosion"] = loadfx( "explosions/building_explosion_paris_ac130_intro" );
    level._effect["FX_barge_a_explosion"] = loadfx( "impacts/105mm_water_impact_fast" );
    level._effect["FX_barrels_a_1"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_barrels_a_2"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_cargo_crate_a_1"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_con_digger_a"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_con_dump_truck_a"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_crates_a_1"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_crates_a_2"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_crates_b_1"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_crates_b_2"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_fuel_tank_a"] = loadfx( "explosions/fuel_storage" );
    level._effect["FX_fuel_tank_a_fire_trail"] = loadfx( "explosions/large_vehicle_explosion_IR" );
    level._effect["FX_maz_a"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_mi26_halo_a"] = loadfx( "explosions/helicopter_explosion_mi26_halo" );
    level._effect["FX_missile_boat_a_explosion"] = loadfx( "impacts/105mm_water_impact_fast" );
    level._effect["FX_mobile_crane_a"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_mstas_a"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_radar_maz_a"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_speed_boat_a"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_storage_bld_a_1"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_storage_bld_a_2"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_storage_bld_b"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_tent_a"] = loadfx( "explosions/tent_collapse" );
    level._effect["FX_tent_a_smoke"] = loadfx( "explosions/tent_collapse" );
    level._effect["FX_tent_b"] = loadfx( "explosions/tent_collapse" );
    level._effect["FX_tent_b_smoke"] = loadfx( "explosions/tent_collapse" );
    level._effect["FX_tent_c"] = loadfx( "explosions/tent_collapse" );
    level._effect["FX_tent_c_smoke"] = loadfx( "explosions/tent_collapse" );
    level._effect["FX_truck_a"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_truck_a_fire_trail"] = loadfx( "explosions/large_vehicle_explosion_IR" );
    level._effect["FX_watch_tower_a"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_satellite_dish_explosion"] = loadfx( "explosions/ac_prs_fx_satellite_dish_explosion_a" );
    level._effect["FX_flir_debris_explosion_a"] = loadfx( "explosions/ac_prs_fx_flir_debris_explosion_a" );
    level._effect["FX_flir_debris_explosion_max_a"] = loadfx( "explosions/ac_prs_fx_flir_debris_explosion_max_a" );
    level._effect["FX_enm_crates_a_explosion_1"] = loadfx( "explosions/ac_prs_fx_enm_crates_a_explosion_1" );
    level._effect["FX_enm_crates_b_explosion_1"] = loadfx( "explosions/ac_prs_fx_enm_crates_b_explosion_1" );
    level._effect["FX_debris_explosion_fire_a"] = loadfx( "explosions/ac_prs_fx_debris_explosion_fire_a" );
    level._effect["FX_40mm_metal_impact_a"] = loadfx( "impacts/ac_prs_fx_40mm_metal_impact_a" );
    level._effect["FX_40mm_wood_impact_a"] = loadfx( "impacts/ac_prs_fx_40mm_wood_impact_a" );
    level._effect["FX_eiffel_tower_debris_a"] = loadfx( "impacts/ac_prs_fx_eiffel_tower_debris_a" );
    level._effect["FX_eiffel_tower_debris_b"] = loadfx( "impacts/ac_prs_fx_eiffel_tower_debris_b" );
    level._effect["FX_eiffel_tower_stress"] = loadfx( "impacts/ac_prs_fx_eiffel_tower_stress" );
    level._effect["FX_eiffel_tower_debris_loop_a"] = loadfx( "misc/eiffel_tower_debris_loop_a" );
    level._effect["FX_eiffel_tower_debris_loop_a_main"] = loadfx( "misc/eiffel_tower_debris_loop_a_main" );
    level._effect["FX_eiffel_tower_debris_loop_a_meteor"] = loadfx( "misc/eiffel_tower_debris_loop_a_meteor" );
    level._effect["FX_eiffel_tower_debris_loop_b"] = loadfx( "misc/eiffel_tower_debris_loop_b" );
    level._effect["FX_eiffel_tower_debris_loop_b_meteor"] = loadfx( "misc/eiffel_tower_debris_loop_b_meteor" );
    level._effect["FX_eiffel_tower_debris_burst_a"] = loadfx( "misc/eiffel_tower_debris_burst_a" );
    level._effect["FX_eiffel_tower_debris_burst_b"] = loadfx( "misc/eiffel_tower_debris_burst_b" );
    level._effect["FX_eiffel_tower_debris_fall_a_wide"] = loadfx( "misc/eiffel_tower_debris_fall_a_wide" );
    level._effect["FX_eiffel_tower_flash_burst_a"] = loadfx( "misc/eiffel_tower_flash_burst_a" );
    level._effect["FX_eiffel_tower_spark_burst_a"] = loadfx( "misc/eiffel_tower_spark_burst_a" );
    level._effect["FX_eiffel_tower_spark_burst_b"] = loadfx( "misc/eiffel_tower_spark_burst_b" );
    level._effect["FX_fire_ac130_linger_lrg_glow_short"] = loadfx( "fire/fire_ac130_linger_lrg_glow_short" );
    level._effect["FX_fire_ac130_simple_lrg_glow_ranged_a"] = loadfx( "fire/fire_ac130_simple_lrg_glow_ranged_a" );
    level._effect["FX_ac_prs_fx_dust_explosion_a"] = loadfx( "explosions/ac_prs_fx_dust_explosion_a" );
    level._effect["FX_ac_prs_extc_balc_a_explosion_1"] = loadfx( "explosions/ac_prs_fps_extc_balcony_a_explosion_1" );
    level._effect["FX_ac_prs_extc_balc_b_explosion_1"] = loadfx( "explosions/ac_prs_fps_extc_balcony_b_explosion_1" );
    level._effect["FX_ac_prs_extc_balc_c_explosion_1"] = loadfx( "explosions/ac_prs_fps_extc_balcony_c_explosion_1" );
    level._effect["FX_ac_prs_extc_balc_c_explosion_2"] = loadfx( "explosions/ac_prs_fps_extc_balcony_c_explosion_2" );
    level._effect["FX_firelight"] = loadfx( "lights/firelight" );
    level._effect["FX_lights_firelight_small"] = loadfx( "lights/lights_firelight_small" );
    level._effect["FX_ac_prs_smoke_amb_1"] = loadfx( "smoke/ac_prs_fx_smoke_amb_1" );
    level._effect["FX_grand_palais_roof"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_open_area_ambient_explosion"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_osprey_explosion"] = loadfx( "explosions/large_vehicle_explosion" );
    level._effect["FX_tank_explosion"] = loadfx( "explosions/vehicle_explosion_btr80" );
    level._effect["FX_bombing_run_large_explosion"] = loadfx( "explosions/bomb_explosion_large_ac130" );
    level._effect["FX_bombing_run_small_explosion"] = loadfx( "explosions/bomb_explosion_ac130_runner" );
    level._effect["FX_bombing_run_small_explosion_med"] = loadfx( "explosions/bomb_explosion_ac130" );
    level._effect["FX_bombing_run_small_explosion_small"] = loadfx( "explosions/bomb_explosion_ac130_small" );
    level._effect["FX_bombing_run_small_explosion_large"] = loadfx( "explosions/bomb_explosion_ac130_large" );
    level._effect["FX_bombing_run_tiny_explosion"] = loadfx( "explosions/building_explosion_paris_ac130" );
    level._effect["FX_bomb_explosion_ac130_bombing_run_runner"] = loadfx( "explosions/bomb_explosion_ac130_bombing_run_runner" );
    level._effect["FX_bomb_explosion_ac130_bombing_run_small"] = loadfx( "explosions/bomb_explosion_ac130_bombing_run_small" );
    level._effect["FX_bomb_explosion_ac130_bombing_run_medium"] = loadfx( "explosions/bomb_explosion_ac130_bombing_run_medium" );
    level._effect["FX_bomb_explosion_ac130_bombing_run_large"] = loadfx( "explosions/bomb_explosion_ac130_bombing_run_large" );
    level._effect["FX_bomb_explosion_ac130_bombing_run_mega"] = loadfx( "explosions/bomb_explosion_ac130_bombing_run_mega" );
    level._effect["FX_bomb_explosion_ac130_bombing_run_dist_runner"] = loadfx( "explosions/bomb_explosion_ac130_bombing_run_dist_runner" );
    level._effect["FX_bomb_explosion_ac130_bombing_run_dist_small"] = loadfx( "explosions/bomb_explosion_ac130_bombing_run_dist_small" );
    level._effect["FX_bomb_explosion_ac130_bombing_run_dist_medium"] = loadfx( "explosions/bomb_explosion_ac130_bombing_run_dist_medium" );
    level._effect["FX_bomb_explosion_ac130_bombing_run_dist_large"] = loadfx( "explosions/bomb_explosion_ac130_bombing_run_dist_large" );
    level._effect["FX_bomb_explosion_ac130_bombing_run_dist_mega"] = loadfx( "explosions/bomb_explosion_ac130_bombing_run_dist_mega" );
    level._effect["car_explosion_ac130_car1"] = loadfx( "explosions/small_vehicle_explosion_ac130_car1" );
    level._effect["car_explosion_ac130_car2"] = loadfx( "explosions/small_vehicle_explosion_ac130_car2" );
    level._effect["car_explosion_ac130_car3"] = loadfx( "explosions/small_vehicle_explosion_ac130_car3" );
    level._effect["car_explosion_ac130_car4_debris"] = loadfx( "explosions/small_vehicle_explosion_ac130_car4_debris" );
    level._effect["car_explosion_ac130_car5_meteor"] = loadfx( "explosions/small_vehicle_explosion_ac130_car5_meteor" );
    level._effect["car_explosion_ac130_car6_dirtrain"] = loadfx( "explosions/small_vehicle_explosion_ac130_car6_dirtrain" );
    level._effect["FX_flak_tracers"] = loadfx( "misc/antiair_single_tracer_flak" );
    level._effect["FX_flak"] = loadfx( "explosions/aa_flak_single_paris_ac130" );
    level._effect["FX_flak_large"] = loadfx( "explosions/aa_flak_single_paris_ac130_large" );
    level._effect["FX_aa_fire_1"] = loadfx( "misc/antiair_single_tracer01_day_flak_no_sfx" );
    level._effect["FX_aa_fire_2"] = loadfx( "misc/antiair_single_tracer02_day_flak_no_sfx" );
    level._effect["FX_aa_fire_3"] = loadfx( "misc/antiair_single_tracer03_day_flak_no_sfx" );
    level._effect["FX_aa_fire_short_1"] = loadfx( "misc/antiair_single_tracer01_cloudy_short_no_sfx" );
    level._effect["FX_aa_fire_short_2"] = loadfx( "misc/antiair_single_tracer02_cloudy_short_no_sfx" );
    level._effect["FX_aa_fire_short_3"] = loadfx( "misc/antiair_single_tracer03_cloudy_short_no_sfx" );
    level._effect["FX_aa_fire_short_4"] = loadfx( "misc/antiair_single_tracer04_cloudy_short_no_sfx" );
    level._effect["FX_aa_fire_tracer_1"] = loadfx( "misc/antiair_single_tracer01_no_sfx" );
    level._effect["FX_aa_fire_tracer_2"] = loadfx( "misc/antiair_single_tracer02_no_sfx" );
    level._effect["FX_aa_fire_tracer_3"] = loadfx( "misc/antiair_single_tracer03_no_sfx" );
    level._effect["FX_aa_fire_tracer_4"] = loadfx( "misc/antiair_single_tracer04_no_sfx" );
    level._effect["FX_aa_fire_flash"] = loadfx( "explosions/aa_explosion_super_cloudonly" );
    level._effect["cloud_bank_paris_ac130"] = loadfx( "weather/cloud_bank_paris_ac130" );
    level._effect["cloud_bank_paris_ac130_background"] = loadfx( "weather/cloud_bank_paris_ac130_background" );
    level._effect["cloud_bank_paris_ac130_start"] = loadfx( "weather/cloud_bank_paris_ac130_start" );
    level._effect["FX_cloud_bank_paris_ac130_slamzoom_out"] = loadfx( "weather/cloud_bank_paris_ac130_slamzoom_out" );
    level._effect["FX_cloud_single"] = loadfx( "weather/cloud_single_paris_ac130" );
    level._effect["FX_rpg_building_collapsing"] = loadfx( "impacts/ac130_105mm_IR_impact_paris_cheap" );
    level._effect["FX_hind_rocket_hitting_building"] = loadfx( "impacts/ac130_105mm_IR_impact_paris_cheap" );
    level._effect["FX_smoke_signal_osprey"] = loadfx( "smoke/signal_smoke_green_paris_ac130_start" );
    level._effect["FX_smoke_signal_osprey_blowing"] = loadfx( "smoke/signal_smoke_green_paris_ac130_blowing" );
    level._effect["FX_smoke_signal_osprey_penetrated"] = loadfx( "smoke/signal_smoke_green_paris_ac130_penetrated" );
    level._effect["FX_smoke_signal_osprey_sequence"] = loadfx( "smoke/signal_smoke_green_paris_ac130_sequence" );
    level._effect["FX_smoke_signal_osprey_start"] = loadfx( "smoke/signal_smoke_green_paris_ac130_start" );
    level._effect["FX_mortar_explosion_mud"] = loadfx( "explosions/mortarexp_ac130_mud" );
    level._effect["FX_mortar_explosion_concrete"] = loadfx( "explosions/mortarexp_ac130_concrete" );
    level._effect["FX_signal_ac130"] = loadfx( "smoke/signal_smoke_purple_2min_ac130" );
    level._effect["FX_signal_evac_hot"] = loadfx( "smoke/signal_smoke_red_2min_ac130" );
    level._effect["FX_horizon_flash_runner_harbor"] = loadfx( "weather/horizon_flash_runner_harbor" );
    level._effect["FX_ambient_explosion_paris"] = loadfx( "maps/paris/ambient_explosion_paris" );
    level._effect["FX_drone_ak47_muzzle_flash"] = loadfx( "muzzleflashes/ac130_ak47_flash_wv" );
    level._effect["FX_drone_m16_muzzle_flash"] = loadfx( "muzzleflashes/ac130_ak47_flash_wv" );
    level._effect["crawling_death_blood_smear"] = loadfx( "impacts/blood_smear_decal" );
    level._effect["blood_drip"] = loadfx( "impacts/blood_drip" );
    level._effect["test_effect"] = loadfx( "misc/moth_runner" );
    level._effect["105_impact"] = loadfx( "impacts/ac130_105mm_impact_slamzoom" );
    level._effect["debris_explosion"] = loadfx( "explosions/generic_explosion_debris" );
    level._effect["debris_fall_big"] = loadfx( "misc/building_debris_falling_ny" );
    level._effect["debris_fall_small"] = loadfx( "misc/falling_debris_small" );
    level._effect["wood_impact"] = loadfx( "impacts/expround_big_default" );
    level._effect["big_muzzle"] = loadfx( "muzzleflashes/bmp_flash_wv" );
    level._effect["water_stop"] = loadfx( "misc/parabolic_water_stand" );
    level._effect["water_movement"] = loadfx( "misc/parabolic_water_movement" );
    level._effect["sand_wall"] = loadfx( "sand/sand_wall_payback" );
    level._effect["debris_explosion_intro"] = loadfx( "explosions/generic_explosion_debris_paris_ac130_intro" );
    level._effect["tower_ash"] = loadfx( "dust/building_collapse_street_dust_ash_eiffel_tower" );
    level._effect["tower_cloud"] = loadfx( "dust/building_collapse_eiffel_tower" );
    level._effect["huge_explosion"] = loadfx( "explosions/100ton_bomb_eifel_tower" );
    level._effect["jet_crash"] = loadfx( "explosions/jet_crash_paris_ac130" );
    level._effect["dirt_kickup_eiffel_tower"] = loadfx( "misc/dirt_kickup_eiffel_tower" );
    level._effect["dirt_kickup_eiffel_tower_mid"] = loadfx( "misc/dirt_kickup_eiffel_tower_mid" );
    level._effect["dirt_kickup_eiffel_tower_rear"] = loadfx( "misc/dirt_kickup_eiffel_tower_rear" );
    level._effect["fence_blowout_eiffel_tower"] = loadfx( "misc/fence_blowout_eiffel_tower" );
    level._effect["gust_debris"] = loadfx( "misc/gust_debris" );
    level._effect["water_splash_large_eiffel_tower"] = loadfx( "water/water_splash_large_eiffel_tower" );
    level._effect["water_splash_large_eiffel_tower_bigger"] = loadfx( "water/water_splash_large_eiffel_tower_bigger" );
    level._effect["water_splash_large_eiffel_tower_ripple"] = loadfx( "water/water_splash_large_eiffel_tower_ripple" );
    level._effect["metal_eject"] = loadfx( "misc/metal_eject" );
    level._effect["metal_eject_far"] = loadfx( "misc/metal_eject_far" );
    level._effect["jet_crash_water_impact_ac130"] = loadfx( "impacts/jet_crash_water_impact_ac130" );
    level._effect["leaves_spiral_runner"] = loadfx( "misc/leaves_spiral_runner" );
    level._effect["room_smoke_200"] = loadfx( "smoke/room_smoke_200" );
    level._effect["fire_falling_runner_point"] = loadfx( "fire/fire_falling_runner_point" );
    level._effect["fire_falling_runner_point_nocull"] = loadfx( "fire/fire_falling_runner_point_nocull" );
    level._effect["fire_falling_runner_point_infrequent"] = loadfx( "fire/fire_falling_runner_point_infrequent" );
    level._effect["falling_dirt_frequent_runner_ac130"] = loadfx( "dust/falling_dirt_frequent_runner_ac130" );
    level._effect["firelp_med_pm_cheap_nolight"] = loadfx( "fire/firelp_med_pm_cheap_nolight" );
    level._effect["firelp_med_pm_cheap_nolight_nocull"] = loadfx( "fire/firelp_med_pm_cheap_nolight_nocull" );
    level._effect["firelp_small_pm_a_nolight"] = loadfx( "fire/firelp_small_pm_a_nolight" );
    level._effect["firelp_cheap_mp"] = loadfx( "fire/firelp_cheap_mp" );
    level._effect["firelp_small_cheap_mp"] = loadfx( "fire/firelp_small_cheap_mp" );
    level._effect["car_fire_mp"] = loadfx( "fire/car_fire_mp" );
    level._effect["car_fire_mp_far"] = loadfx( "fire/car_fire_mp_far" );
    level._effect["firelp_med_cheap_dist_mp"] = loadfx( "fire/firelp_med_cheap_dist_mp" );
    level._effect["firelp_small_cheap_dist_mp"] = loadfx( "fire/firelp_small_cheap_dist_mp" );
    level._effect["leaves_fall_gentlewind"] = loadfx( "misc/leaves_fall_gentlewind" );
    level._effect["leaves_ground_gentlewind"] = loadfx( "misc/leaves_ground_gentlewind" );
    level._effect["battlefield_smokebank_S_warm"] = loadfx( "smoke/battlefield_smokebank_S_warm" );
    level._effect["battlefield_smokebank_S_warm_thick"] = loadfx( "smoke/battlefield_smokebank_S_warm_thick" );
    level._effect["insect_trail_runner_icbm"] = loadfx( "misc/insect_trail_runner_icbm" );
    level._effect["insects_light_invasion"] = loadfx( "misc/insects_light_invasion" );
    loadfx( "treadfx/tread_concrete_ac130" );
    loadfx( "treadfx/tread_water_ac130" );
    _id_56D3();

    if ( !getdvarint( "r_reflectionProbeGenerate" ) )
        _id_6372::main();
}

_id_56D3()
{
    animscripts\utility::_id_24BB( "default", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BB( "asphalt", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BB( "brick", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BB( "carpet", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BB( "cloth", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BB( "concrete", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BB( "cushion", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BB( "dirt", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BB( "foliage", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BB( "grass", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BB( "gravel", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BB( "mud", loadfx( "impacts/footstep_mud" ) );
    animscripts\utility::_id_24BB( "rock", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BB( "sand", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BB( "water", loadfx( "impacts/footstep_water" ) );
    animscripts\utility::_id_24BB( "wood", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BC( "default", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BC( "asphalt", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BC( "brick", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BC( "carpet", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BC( "cloth", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BC( "concrete", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BC( "cushion", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BC( "dirt", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BC( "foliage", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BC( "grass", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BC( "gravel", loadfx( "impacts/footstep_dust_subtle" ) );
    animscripts\utility::_id_24BC( "mud", loadfx( "impacts/footstep_mud" ) );
    animscripts\utility::_id_24BC( "rock", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BC( "sand", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BC( "water", loadfx( "impacts/footstep_water" ) );
    animscripts\utility::_id_24BC( "wood", loadfx( "misc/dirt_kickup_feet_skid" ) );
    animscripts\utility::_id_24BD( "bodyfall small", "J_SpineLower", "dirt", loadfx( "impacts/bodyfall_dust_small_runner" ), "bodyfall_", "_small" );
    animscripts\utility::_id_24BD( "bodyfall small", "J_SpineLower", "concrete", loadfx( "impacts/bodyfall_default_small_runner" ), "bodyfall_", "_small" );
    animscripts\utility::_id_24BD( "bodyfall small", "J_SpineLower", "asphalt", loadfx( "impacts/bodyfall_default_small_runner" ), "bodyfall_", "_small" );
    animscripts\utility::_id_24BD( "bodyfall small", "J_SpineLower", "rock", loadfx( "impacts/bodyfall_default_small_runner" ), "bodyfall_", "_small" );
    animscripts\utility::_id_24BD( "bodyfall large", "J_SpineLower", "dirt", loadfx( "impacts/bodyfall_dust_large_runner" ), "bodyfall_", "_large" );
    animscripts\utility::_id_24BD( "bodyfall large", "J_SpineLower", "concrete", loadfx( "impacts/bodyfall_default_large_runner" ), "bodyfall_", "_large" );
    animscripts\utility::_id_24BD( "bodyfall large", "J_SpineLower", "asphalt", loadfx( "impacts/bodyfall_default_large_runner" ), "bodyfall_", "_large" );
    animscripts\utility::_id_24BD( "bodyfall large", "J_SpineLower", "rock", loadfx( "impacts/bodyfall_default_large_runner" ), "bodyfall_", "_large" );
    animscripts\utility::_id_24BD( "knee fx left", "J_Knee_LE", "dirt", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BD( "knee fx left", "J_Knee_LE", "concrete", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BD( "knee fx left", "J_Knee_LE", "asphalt", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BD( "knee fx left", "J_Knee_LE", "rock", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BD( "knee fx left", "J_Knee_LE", "mud", loadfx( "impacts/footstep_mud" ) );
    animscripts\utility::_id_24BD( "knee fx right", "J_Knee_RI", "dirt", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BD( "knee fx right", "J_Knee_RI", "concrete", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BD( "knee fx right", "J_Knee_RI", "asphalt", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BD( "knee fx right", "J_Knee_RI", "rock", loadfx( "impacts/footstep_dust" ) );
    animscripts\utility::_id_24BD( "knee fx right", "J_Knee_RI", "mud", loadfx( "impacts/footstep_mud" ) );
}
